### ISSUE TITLE
Live Update Not Working

### ISSUE THREAD

**Issue by civAnimal** [mypaint/mypaint#1046]
#### Description of the problem

In Brush Editor:
Live Update is not working anymore.

#### Basic system details
Windows 8
mypaint w64 2.0.0 beta git 97372

**Comment by odysseywestra** [comment]
Could you read https://github.com/mypaint/mypaint/wiki/Reporting-Bugs and edit your issue ticket accordingly? Thanks.

**Comment by odysseywestra** [comment]
This error pops up when hitting the live update button in the Brush Editor while MyPaint is in Debug Mode: 

```python
Mypaint version: 2.0.0-beta.0+git.0bc97372
System information: Windows-10-10.0.17134-SP0
Using: Python 3.8.0, GTK 3.24.13, GdkPixbuf 2.40.0, Cairo 1.16.0, GLib 2.62.1
Traceback (most recent call last):
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint\gui\brusheditor.py", line 1069, _live_update_idle_cb(self=<brusheditor.BrushEditorWindow object at 0x00000...heditor+BrushEditorWindow at 0x000000002080c800)>)
            doc = self.app.doc.model
            doc.redo_last_stroke_with_different_brush(self._brush)
            self._live_update_idle_cb_id = None
  variables: {'doc.redo_last_stroke_with_different_brush': ('local', <bound method Document.redo_last_stroke_with_different_brush of <Document nlayers=1 bbox=Rect(384, 64, 256, 512) paintonly=False>>), 'self._brush': ('local', <lib.brush.BrushInfo object at 0x000000001f68a190>)}
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint\lib\document.py", line 1013, redo_last_stroke_with_different_brush(self=<Document nlayers=1 bbox=Rect(384, 64, 256, 512) paintonly=False>, brushinfo=<lib.brush.BrushInfo object>)
                return
            cmd.update(brushinfo=brushinfo)
  variables: {'cmd.update': ('local', <bound method Brushwork.update of <Brushwork 0x217ef5b0 1.562s None>>), 'brushinfo': ('local', <lib.brush.BrushInfo object at 0x000000001f68a190>)}
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint\lib\command.py", line 381, update(self=<Brushwork 0x217ef5b0 1.562s None>, brushinfo=<lib.brush.BrushInfo object>)
            stroke = self._stroke_seq.copy_using_different_brush(brushinfo)
            layer.render_stroke(stroke)
            self._stroke_seq = stroke
  variables: {'layer.render_stroke': ('local', <bound method StrokemappedPaintingLayer.render_stroke of <PaintingLayer 'Layer'>>), 'stroke': ('local', <lib.stroke.Stroke object at 0x00000000228a4d00>)}
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint\lib\layer\data.py", line 1535, render_stroke(self=<PaintingLayer 'Layer'>, stroke=<lib.stroke.Stroke object>)
            """
            stroke.render(self._surface)
            self.autosave_dirty = True
  variables: {'stroke.render': ('local', <bound method Stroke.render of <lib.stroke.Stroke object at 0x00000000228a4d00>>), 'self._surface': ('local', <lib.tiledsurface.MyPaintSurface object at 0x000000002057ecd0>)}
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint\lib\stroke.py", line 89, render(self=<lib.stroke.Stroke object>, surface=<lib.tiledsurface.MyPaintSurface object>)
            version, data = self.stroke_data[0], self.stroke_data[1:]
            assert version == b'2'
            data = np.fromstring(data, dtype='float64')
  variables: {'version': ('local', 50)}
AssertionError: 
```
