### ISSUE TITLE
MyPaint can not open any file.

### ISSUE THREAD

**Issue by macktab** [mypaint/mypaint#1048]
#### Description

MyPaint can not open any file.

#### Steps to reproduce

Just run mypaint and open any file.

#### Traceback

```python
Mypaint version: 2.0.0-alpha+unknown
System information: Linux-5.5.0-0.rc2.git3.1.fc32.x86_64-x86_64-with-glibc2.2.5
Using: Python 3.8.1, GTK 3.24.13, GdkPixbuf 2.40.0, Cairo 1.16.0, GLib 2.62.0
Traceback (most recent call last):
  File "/usr/lib64/mypaint/gui/application.py", line 434, _at_application_start(self=<gui.application.Application object>, filenames=['/run/media/maktub/maktub2TB/oppa/aws/aws-dev-pro-exam (copy)/01.png'], fullscreen=None)
                else:
                    self.filehandler.open_file(fn)
  variables: {'self.filehandler.open_file': ('local', <bound method FileHandler.open_file of <gui.filehandling.FileHandler object at 0x7f658a7cb2b0>>), 'fn': ('local', '/run/media/maktub/maktub2TB/oppa/aws/aws-dev-pro-exam (copy)/01.png')}
  File "/usr/lib64/mypaint/gui/filehandling.py", line 815, open_file(self=<gui.filehandling.FileHandler object>, filename='/run/media/maktub/maktub2TB/oppa/aws/aws-dev-pro-exam (copy)/01.png')
            """Load a file, replacing the current working document."""
            if not self._call_doc_load_method(self.doc.model.load, filename,
                                              False):
  variables: {'self._call_doc_load_method': ('local', <bound method FileHandler._call_doc_load_method of <gui.filehandling.FileHandler object at 0x7f658a7cb2b0>>), 'self.doc.model.load': ('local', <bound method Document.load of <Document nlayers=1 bbox=Rect(0, 0, 0, 0) paintonly=False>>), 'filename': ('local', '/run/media/maktub/maktub2TB/oppa/aws/aws-dev-pro-exam (copy)/01.png')}
  File "/usr/lib64/mypaint/gui/filehandling.py", line 859, _call_doc_load_method(self=<gui.filehandling.FileHandler object>, method=<bound method Document.load of <Document nlayers=1 bbox=Rect(0, 0, 0, 0) paintonly=False>>, arg='/run/media/maktub/maktub2TB/oppa/aws/aws-dev-pro-exam (copy)/01.png', is_import=False)
            ioui = _IOProgressUI(self.app, op_type, files_summary)
            ioui.call(
                method, arg,
  variables: {'ioui.call': ('local', <bound method _IOProgressUI.call of <gui.filehandling._IOProgressUI object at 0x7f6588e1c520>>), 'method': ('local', <bound method Document.load of <Document nlayers=1 bbox=Rect(0, 0, 0, 0) paintonly=False>>), 'arg': ('local', '/run/media/maktub/maktub2TB/oppa/aws/aws-dev-pro-exam (copy)/01.png'), 'convert_to_srgb': (None, []), 'display_colorspace_setting': ('local', 'srgb')}
  File "/usr/lib64/mypaint/gui/widgets.py", line 182, wrapper(self=<gui.filehandling._IOProgressUI object>, *args=(<bound method Document.load of <Document nlayers=1 bbox=Rect(0, 0, 0, 0) paintonly=False>>, '/run/media/maktub/maktub2TB/oppa/aws/aws-dev-pro-exam (copy)/01.png'), **kwargs={'convert_to_srgb': True})
            try:
                return func(self, *args, **kwargs)
                # gtk main loop may be called in here...
  variables: {'func': ('local', <function _IOProgressUI.call at 0x7f658aa6ed30>), 'self': ('local', <gui.filehandling._IOProgressUI object at 0x7f6588e1c520>), 'args': ('local', (<bound method Document.load of <Document nlayers=1 bbox=Rect(0, 0, 0, 0) paintonly=False>>, '/run/media/maktub/maktub2TB/oppa/aws/aws-dev-pro-exam (copy)/01.png')), 'kwargs': ('local', {'convert_to_srgb': True})}
  File "/usr/lib64/mypaint/gui/filehandling.py", line 312, call(self=<gui.filehandling._IOProgressUI object>, func=<bound method Document.load of <Document nlayers=1 bbox=Rect(0, 0, 0, 0) paintonly=False>>, *args=('/run/media/maktub/maktub2TB/oppa/aws/aws-dev-pro-exam (copy)/01.png',), **kwargs={'convert_to_srgb': True, 'progress': <Progress 0.0/None>})
            self._start_time = time.clock()
            self._last_pulse = None
  variables: {'self._start_time': ('local', <gui.filehandling._IOProgressUI object at 0x7f6588e1c520>)}
AttributeError: module 'time' has no attribute 'clock'
```

**Comment by jplloyd** [comment]
Thank you, looks like another Python 3.8 deprecation. It'll be fixed within the day (CET).

**Comment by jplloyd** [comment]
Nvm, this is the same one that was fixed 5 weeks ago.
You can get a newer build here: https://github.com/mypaint/mypaint-appimage/releases/continuous
or download the beta: https://github.com/mypaint/mypaint/releases/tag/v2.0.0-beta.0
