### ISSUE TITLE
not run appimage. alfa 2.1-1-gc066c2a-2020-02-17_21.05

### ISSUE THREAD

**Issue by rus30vv** [mypaint/mypaint#1057]
#### Basic system details

MyPaint version: [2.1-alpha-1-gc066c2a-2020-02-17_21.05, appimage,]
Operating system: [ Ubuntu 18.04.4 LTS x86_64 …]
Desktop environment: [ unity ]

#### Steps to reproduce

1. Start MyPaint

#### error messages

```
./MyPaint-v2.1.0-alpha-1-gc066c2a-2020-02-17_21.05.AppImage 
DIR: /tmp/.mount_MyPainfq20U4
AILIBDIR=/tmp/tmp.Qj2TG0oocT
deleting /tmp/tmp.Qj2TG0oocT/libxcb-dri3.so*
System stdc++ library: "/usr/lib/x86_64-linux-gnu/libstdc++.so.6"
System stdc++ library version: "3.4.25"
Bundled stdc++ library version: "3.4.19"
Newest stdc++ library version: "3.4.25"
Using system stdc++ library
atomiclib: /usr/lib/x86_64-linux-gnu/libatomic.so.1
Checking versions of library "libfontconfig"
  system library: "/usr/lib/x86_64-linux-gnu/libfontconfig.so.1.10.1" (libfontconfig.so.1.10.1)
  system library version: 1.10.1
  ailib: "/tmp/.mount_MyPainfq20U4/usr/lib/libfontconfig.so.1.11.1"
  bundled library: "/tmp/.mount_MyPainfq20U4/usr/lib/libfontconfig.so.1.11.1" (libfontconfig.so.1.11.1)
  bundled library version: 1.11.1
  newest library version: "1.11.1"
Checking versions of library "libfreetype"
  system library: "/usr/lib/x86_64-linux-gnu/libfreetype.so.6.15.0" (libfreetype.so.6.15.0)
  system library version: 6.15.0
  ailib: "/tmp/.mount_MyPainfq20U4/usr/lib/libfreetype.so.6.14.0"
  bundled library: "/tmp/.mount_MyPainfq20U4/usr/lib/libfreetype.so.6.14.0" (libfreetype.so.6.14.0)
  bundled library version: 6.14.0
  newest library version: "6.15.0"
Removing bundled "libfreetype"
 deleted '/tmp/tmp.Qj2TG0oocT/libfreetype.so.6'
deleted '/tmp/tmp.Qj2TG0oocT/libfreetype.so.6.14.0' 
GTK_IM_MODULE_FILE=/tmp/.mount_MyPainfq20U4/usr/lib/gtk-2.0:/tmp/.mount_MyPainfq20U4/usr/lib/gtk-2.0
PANGO_LIBDIR=/tmp/.mount_MyPainfq20U4/usr/lib
/tmp/.mount_MyPainfq20U4/apprun-helper.sh: строка 130: /tmp/.mount_MyPainfq20U4/startup_scripts/*.sh: "non file or directory"Нет такого файла или каталога
No explicit user theme set
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/tmp/.mount_MyPainfq20U4/usr'
INFO: mypaint: Using brushdir path relative to installation-prefix
Traceback (most recent call last):
  File "/tmp/.mount_MyPainfq20U4/usr/bin/mypaint", line 294, in <module>
    = get_paths()
  File "/tmp/.mount_MyPainfq20U4/usr/bin/mypaint", line 241, in get_paths
    from lib import fileutils
  File "/tmp/.mount_MyPainfq20U4/usr/lib/mypaint/lib/fileutils.py", line 2, in <module>
    import os,os.path,sys,functools,logging,shutil,unicodedata,lib.gichecks,lib.helpers
  File "/tmp/.mount_MyPainfq20U4/usr/lib/mypaint/lib/helpers.py", line 7, in <module>
    from .  import mypaintlib
  File "/tmp/.mount_MyPainfq20U4/usr/lib/mypaint/lib/mypaintlib.py", line 7, in <module>
    _mypaintlib=swig_import_helper();del swig_import_helper
  File "/tmp/.mount_MyPainfq20U4/usr/lib/mypaint/lib/mypaintlib.py", line 6, in swig_import_helper
    except ImportError:return A.import_module('_mypaintlib')
  File "/tmp/.mount_MyPainfq20U4/usr/lib64/python2.7/importlib/__init__.py", line 19, in import_module
    __import__(A);return sys.modules[A]
ImportError: No module named _mypaintlib
```

**Comment by jplloyd** [comment]
Apparently I have culled bundled libraries a bit too aggressively. I see that the appimage doesn't work out of the box on 18.04 (speaking of which, you should specify the version of Ubuntu you are using).

> [✍ Paste any error messages here between the ``` lines.]

I have edited your message, but please follow the instruction above literally next time. In this case it didn't matter, but when the error contains hash signs it can create tons of unwanted references to other issues in the repo.

**Comment by jplloyd** [comment]
@rus30vv Do you get the same error with this build:
https://github.com/mypaint/mypaint-appimage/releases/download/continuous/MyPaint-v2.1.0-alpha-2-g937ed67-2020-02-18_19.21-no-translations.AppImage
?

**Comment by rus30vv** [comment]
> @rus30vv Do you get the same error with this build:
> https://github.com/mypaint/mypaint-appimage/releases/download/continuous/MyPaint-v2.1.0-alpha-2-g937ed67-2020-02-18_19.21-no-translations.AppImage
> ?

there is no such error. it works) and the brush sets were brought there. thanks
Ubuntu 18.04.4 LTS x86_64

**Comment by jplloyd** [comment]
Alright, nice!
