### ISSUE TITLE
Can't open up file or drawing 

### ISSUE THREAD

**Issue by bromosky** [mypaint/mypaint#1068]
#### Description of the problem

Can't open any data from the programm or with file programm. It just pops up an error. Everything works fine after this, except the file won't open up.

#### Basic system details

MyPaint version: 2.0.0+git.af5225a
Operating system: Fedora 31 
Desktop environment: Gnome

#### Steps to reproduce
1. Start MyPaint
2. Trying to open drawing or any data.
3. Error window pops up. Everything except opening data works fine after this.

#### Backtraces or error messages

```
```python
Mypaint version: 2.0.0+git.af5225a
System information: Linux-5.5.8-200.fc31.x86_64-x86_64-with-fedora-31-Thirty_One
Using: Python 2.7.5, GTK 3.22.30, GdkPixbuf 2.36.12, Cairo 1.15.12, GLib 2.56.1
Traceback (most recent call last):
  File "/tmp/.mount_MyPainVrCI2A/usr/lib/mypaint/gui/filehandling.py", line 203, open_cb(B=<gui.filehandling.FileHandler object>, action=<Gtk.Action object at 0x7f241c3d7870 (GtkAction at 0x267e870)>)
        try:
          if A.run()==Gtk.ResponseType.OK:A.hide();D=A.get_filename();D=filename_to_unicode(D);B.open_file(D,compat_handler=C.compat_function)
        finally:A.destroy()
  variables: {'B.open_file': ('local', <bound method FileHandler.open_file of <gui.filehandling.FileHandler object at 0x7f241c3de3d0>>), 'A.get_filename': ('local', gi.FunctionInfo(get_filename)), 'D': ('local', u'/home/max/Downloads/Max2.ora'), 'filename_to_unicode': ('global', <function filename_to_unicode at 0x7f241d0ca9b0>), 'A.run': ('local', gi.FunctionInfo(run)), 'C.compat_function': ('local', <gui.compatibility.CompatSelector instance at 0x7f2419e3acb0>), 'Gtk.ResponseType.OK': ('global', <enum GTK_RESPONSE_OK of type Gtk.ResponseType>), 'A.hide': ('local', gi.FunctionInfo(hide)), 'compat_handler': (None, [])}
  File "/tmp/.mount_MyPainVrCI2A/usr/lib/mypaint/gui/filehandling.py", line 151, open_file(A=<gui.filehandling.FileHandler object>, filename=u'/home/max/Downloads/Max2.ora', **F={'compat_handler': None})
        D=filename
        if not A._call_doc_load_method(A.doc.model.load,D,False,**F):A.filename=None;A.app.reset_compat_mode();A.doc.model.clear();return
        A.filename=os.path.abspath(D)
  variables: {'A._call_doc_load_method': ('local', <bound method FileHandler._call_doc_load_method of <gui.filehandling.FileHandler object at 0x7f241c3de3d0>>), 'None': ('builtin', None), 'False': ('builtin', False), 'D': ('local', u'/home/max/Downloads/Max2.ora'), 'F': ('local', {'compat_handler': None}), 'A.filename': ('local', <gui.filehandling.FileHandler object at 0x7f241c3de3d0>), 'A.app.reset_compat_mode': ('local', <bound method Application.reset_compat_mode of <gui.application.Application object at 0x7f241dea5c90>>), 'A.doc.model.clear': ('local', <bound method Document.clear of <Document nlayers=1 bbox=Rect(0, 0, 0, 0) paintonly=False>>), 'A.doc.model.load': ('local', <bound method Document.load of <Document nlayers=1 bbox=Rect(0, 0, 0, 0) paintonly=False>>)}
  File "/tmp/.mount_MyPainVrCI2A/usr/lib/mypaint/gui/filehandling.py", line 167, _call_doc_load_method(A=<gui.filehandling.FileHandler object>, method=<bound method Document.load of <Document nlayers=1 bbox=Rect(0, 0, 0, 0) paintonly=False>>, arg=u'/home/max/Downloads/Max2.ora', is_import=False, compat_handler=None)
        if not B:B=compat.ora_compat_handler(A.app)
        D=A.app.preferences;E=D['display.colorspace'];F=is_import and'import'or'load';G=_IOProgressUI.format_files_summary(arg);C=_IOProgressUI(A.app,F,G);H=C.call(method,arg,convert_to_srgb=E=='srgb',compat_handler=B,incompatible_ora_cb=compat.incompatible_ora_cb(A.app));return H is not False and C.success
      def open_scratchpad(A,filename):
  variables: {'compat.incompatible_ora_cb': ('global', <function incompatible_ora_cb at 0x7f241d077320>), '_IOProgressUI': ('global', <class gui.filehandling._IOProgressUI at 0x7f241c726598>), 'C': (None, []), 'A.app.preferences': ('local', ObservableDict({'frame.color_rgba': [0.12, 0.12, 0.12, 0.92], 'ui.feedback.scale': False, u'colors.palette': {'name': u'MyPaint Default', 'columns': 7, 'entries': [('#000000', u'Black'), ('#262626', u'Gray 15'), ('#4d4d4d', u'Grey 30'), ('#808080', u'Grey 50'), ('#ababab', u'Grey 67'), ('#d9d9d9', u'Grey 85'), ('#ffffff', u'White'), ('#800000', u'Maroon'), ('#d10000', u'English-red'), ('#ff3622', u'Tomato'), ('#fc3c03', u'Orange-red'), ('#ff8c69', u'Salmon'), ('#fce820', u'Cadium-yellow'), ('#f3fd25', u'Lemon yellow'), ('#790523', u'Dark crimson'), ('#a9203e', u'Deep carmine'), ('#ff8c00', u'Orange'), ('#ffa812', u'Dark tangerine'), ('#d99058', u'Persian orange'), ('#c2b280', u'Sand'), ('#ffe5b4', u'Peach'), ('#64362e', u'Bole'), ('#6c2934', u'Dark cordovan'), ('#a3412c', u'Chestnut'), ('#e48864', u'Dark salmon'), ('#ffc38f', u'Apricot'), ('#ffdbbc', u'Unbleached silk'), ('#f2e3c6', u'Straw'), ('#35130d', u'Bistre'), ('#542a0e', u'Dark chocolate'), ('#66332b', u'Burnt sienna'), ('#b84200', u'Sienna'), ('#d8990c', u'Yellow ochre'), ('#d2b48c', u'Tan'), ('#e8cc90', u'Dark wheat'), ('#003153', u'Prussian blue'), ('#304577', u'Dark grey blue'), ('#0047ab', u'Cobalt blue'), ('#1f75fe', u'Blue'), ('#78b4ff', u'Bright french blue'), ('#abc8ff', u'Bright steel blue'), ('#d0e7ff', u'Ice blue'), ('#1e333a', u'Medium jungle green'), ('#2f4f4f', u'Dark slate grey'), ('#4a685d', u'Dark grullo green'), ('#008080', u'Teal'), ('#43aab0', u'Turquoise'), ('#6daec7', u'Cerulean frost'), ('#add9ba', u'Tiffany green'), ('#16221d', u'Gray-asparagus'), ('#24302d', u'Medium dark teal'), ('#4a685d', u'Xanadu'), ('#77c679', u'Mint'), ('#afcdb6', u'Timberwolf'), ('#b9f5f6', u'Celeste'), ('#c1ffea', u'Aquamarine'), ('#1d3423', u'Cal Poly Pomona'), ('#014421', u'Forest green'), ('#2a8000', u'Napier green'), ('#808000', u'Olive'), ('#419c69', u'Sea green'), ('#bdf61d', u'Green-yellow'), ('#e7f486', u'Bright chartreuse'), ('#8a1789', u'Purple'), ('#4e278a', u'Violet'), ('#c14b6e', u'Dark thulian pink'), ('#de3163', u'Cerise'), ('#ff1493', u'Deep pink'), ('#ff66cc', u'Rose pink'), ('#ffcbdb', u'Pink'), ('#ffffff', u'White'), ('#e51101', u'RGB Red'), ('#00ff00', u'RGB Green'), ('#0000ff', u'RGB Blue'), ('#00ffff', u'CMYK Cyan'), ('#ff00ff', u'CMYK Magenta'), ('#ffff00', u'CMYK Yellow')]}, 'ui.feedback.last_pos': False, u'colors.current': '#2e2d2d', u'ui.blink_layers': True, 'view.default_zoom': 1.0, 'brushmanager.selected_groups': [], 'ui.toolbar_items': {u'toolbar1_file': True, u'toolbar1_view_modes': True, u'toolbar1_edit': True, u'toolbar1_blendmodes': False, u'toolbar1_view_manips': False, u'toolbar1_view_resets': True, u'toolbar1_scrap': False, u'toolbar1_linemodes': True}, 'default_compatibility_mode': '2.x', u'brush_chooser.default.window_size': [256, 256], 'input.button_mapping': {'<Primary>Button2': u'ZoomViewMode', '<Primary><Shift>Button2': u'FrameEditMode', '<Shift>Button2': u'RotateViewMode', 'Button3': u'ShowPopupMenu', 'Button2': u'PanViewMode', '<Shift><Alt>Button2': u'FrameEditMode', '<Alt>Button2': u'ZoomViewMode'}, 'ui.hide_toolbar_in_fullscreen': True, 'ui.dark_theme_variant': True, 'misc.context_restores_color': True, 'ui.parts': {u'main_toolbar': True, u'menubar': True}, 'ui.toolbar_icon_size': u'large', 'document.autosave_backups': True, 'display.colorspace': u'srgb', 'input.barrel_rotation_offset': 0.5, 'ui.rendered_tile_cache_size': 16384, 'ui.hide_subwindows_in_fullscreen': True, u'ui.file_compat_warning_mild': True, 'display.colorspace_EOTF': 2.2, 'input.use_barrel_rotation': True, u'colors.history': ['#272727', '#565757', '#007f6a', '#3e3d3e', '#2e2d2d'], 'saving.scrap_prefix': u'~/MyPaint/scrap', 'ui.hide_menubar_in_fullscreen': True, u'ui.file_compat_warning_severe': True, 'input.barrel_rotation_subtract_ascension': True, 'input.global_pressure_mapping': [[0.0, 1.0], [1.0, 0.0]], 'workspace.layout': {u'fullscreen': False, u'right_sidebar': {u'h': 898, u'groups': [{u'h': 412, u'tools': [[u'MyPaintLayersTool']], u'w': 331, u'active_page': 0}, {u'h': 474, u'tools': [[u'MyPaintBrushGroupTool', u'Classic']], u'w': 331, u'active_page': 0}, {u'tools': [], u'active_page': -1}], u'w': 331}, u'autohide': True, u'maximized': True, u'position': {}, u'floating': [], u'left_sidebar': {u'h': 898, u'groups': [{u'h': 237, u'tools': [[u'MyPaintHCYWheelTool']], u'w': 222, u'active_page': 0}, {u'tools': [], u'active_page': -1}], u'w': 222}}, 'compat_behavior_when_unknown': u'unless-pigment-layer-1.x', 'saving.default_format': u'openraster', 'brushmanager.selected_brush': u'classic/blur', u'ui.support_smooth_scrolling': True, u'input.devices': {u'Virtual core XTEST pointer:mouse:2': {}, u'xwayland-touch:16:touchscreen:2': {}, u'xwayland-relative-pointer:16:mouse:2': {}, u'xwayland-pointer:16:mouse:4': {}, u'xwayland-eraser:16:eraser:6': {}, u'xwayland-cursor:16:cursor:6': {}, u'xwayland-stylus:16:touchscreen:6': {}}, 'view.real_alpha_checks': True, 'input.device_mode': u'screen', 'document.autosave_interval': 10, 'scratchpad.last_opened_scratchpad': u'/home/max/.local/share/mypaint/scratchpads/autosave.ora', 'compability_settings': {u'2.x': {u'pigment_on_by_default': True, u'pigment_layer_is_default': True}, u'1.x': {u'pigment_on_by_default': False, u'pigment_layer_is_default': False}}})), 'E': ('local', u'srgb'), 'D': ('local', ObservableDict({'frame.color_rgba': [0.12, 0.12, 0.12, 0.92], 'ui.feedback.scale': False, u'colors.palette': {'name': u'MyPaint Default', 'columns': 7, 'entries': [('#000000', u'Black'), ('#262626', u'Gray 15'), ('#4d4d4d', u'Grey 30'), ('#808080', u'Grey 50'), ('#ababab', u'Grey 67'), ('#d9d9d9', u'Grey 85'), ('#ffffff', u'White'), ('#800000', u'Maroon'), ('#d10000', u'English-red'), ('#ff3622', u'Tomato'), ('#fc3c03', u'Orange-red'), ('#ff8c69', u'Salmon'), ('#fce820', u'Cadium-yellow'), ('#f3fd25', u'Lemon yellow'), ('#790523', u'Dark crimson'), ('#a9203e', u'Deep carmine'), ('#ff8c00', u'Orange'), ('#ffa812', u'Dark tangerine'), ('#d99058', u'Persian orange'), ('#c2b280', u'Sand'), ('#ffe5b4', u'Peach'), ('#64362e', u'Bole'), ('#6c2934', u'Dark cordovan'), ('#a3412c', u'Chestnut'), ('#e48864', u'Dark salmon'), ('#ffc38f', u'Apricot'), ('#ffdbbc', u'Unbleached silk'), ('#f2e3c6', u'Straw'), ('#35130d', u'Bistre'), ('#542a0e', u'Dark chocolate'), ('#66332b', u'Burnt sienna'), ('#b84200', u'Sienna'), ('#d8990c', u'Yellow ochre'), ('#d2b48c', u'Tan'), ('#e8cc90', u'Dark wheat'), ('#003153', u'Prussian blue'), ('#304577', u'Dark grey blue'), ('#0047ab', u'Cobalt blue'), ('#1f75fe', u'Blue'), ('#78b4ff', u'Bright french blue'), ('#abc8ff', u'Bright steel blue'), ('#d0e7ff', u'Ice blue'), ('#1e333a', u'Medium jungle green'), ('#2f4f4f', u'Dark slate grey'), ('#4a685d', u'Dark grullo green'), ('#008080', u'Teal'), ('#43aab0', u'Turquoise'), ('#6daec7', u'Cerulean frost'), ('#add9ba', u'Tiffany green'), ('#16221d', u'Gray-asparagus'), ('#24302d', u'Medium dark teal'), ('#4a685d', u'Xanadu'), ('#77c679', u'Mint'), ('#afcdb6', u'Timberwolf'), ('#b9f5f6', u'Celeste'), ('#c1ffea', u'Aquamarine'), ('#1d3423', u'Cal Poly Pomona'), ('#014421', u'Forest green'), ('#2a8000', u'Napier green'), ('#808000', u'Olive'), ('#419c69', u'Sea green'), ('#bdf61d', u'Green-yellow'), ('#e7f486', u'Bright chartreuse'), ('#8a1789', u'Purple'), ('#4e278a', u'Violet'), ('#c14b6e', u'Dark thulian pink'), ('#de3163', u'Cerise'), ('#ff1493', u'Deep pink'), ('#ff66cc', u'Rose pink'), ('#ffcbdb', u'Pink'), ('#ffffff', u'White'), ('#e51101', u'RGB Red'), ('#00ff00', u'RGB Green'), ('#0000ff', u'RGB Blue'), ('#00ffff', u'CMYK Cyan'), ('#ff00ff', u'CMYK Magenta'), ('#ffff00', u'CMYK Yellow')]}, 'ui.feedback.last_pos': False, u'colors.current': '#2e2d2d', u'ui.blink_layers': True, 'view.default_zoom': 1.0, 'brushmanager.selected_groups': [], 'ui.toolbar_items': {u'toolbar1_file': True, u'toolbar1_view_modes': True, u'toolbar1_edit': True, u'toolbar1_blendmodes': False, u'toolbar1_view_manips': False, u'toolbar1_view_resets': True, u'toolbar1_scrap': False, u'toolbar1_linemodes': True}, 'default_compatibility_mode': '2.x', u'brush_chooser.default.window_size': [256, 256], 'input.button_mapping': {'<Primary>Button2': u'ZoomViewMode', '<Primary><Shift>Button2': u'FrameEditMode', '<Shift>Button2': u'RotateViewMode', 'Button3': u'ShowPopupMenu', 'Button2': u'PanViewMode', '<Shift><Alt>Button2': u'FrameEditMode', '<Alt>Button2': u'ZoomViewMode'}, 'ui.hide_toolbar_in_fullscreen': True, 'ui.dark_theme_variant': True, 'misc.context_restores_color': True, 'ui.parts': {u'main_toolbar': True, u'menubar': True}, 'ui.toolbar_icon_size': u'large', 'document.autosave_backups': True, 'display.colorspace': u'srgb', 'input.barrel_rotation_offset': 0.5, 'ui.rendered_tile_cache_size': 16384, 'ui.hide_subwindows_in_fullscreen': True, u'ui.file_compat_warning_mild': True, 'display.colorspace_EOTF': 2.2, 'input.use_barrel_rotation': True, u'colors.history': ['#272727', '#565757', '#007f6a', '#3e3d3e', '#2e2d2d'], 'saving.scrap_prefix': u'~/MyPaint/scrap', 'ui.hide_menubar_in_fullscreen': True, u'ui.file_compat_warning_severe': True, 'input.barrel_rotation_subtract_ascension': True, 'input.global_pressure_mapping': [[0.0, 1.0], [1.0, 0.0]], 'workspace.layout': {u'fullscreen': False, u'right_sidebar': {u'h': 898, u'groups': [{u'h': 412, u'tools': [[u'MyPaintLayersTool']], u'w': 331, u'active_page': 0}, {u'h': 474, u'tools': [[u'MyPaintBrushGroupTool', u'Classic']], u'w': 331, u'active_page': 0}, {u'tools': [], u'active_page': -1}], u'w': 331}, u'autohide': True, u'maximized': True, u'position': {}, u'floating': [], u'left_sidebar': {u'h': 898, u'groups': [{u'h': 237, u'tools': [[u'MyPaintHCYWheelTool']], u'w': 222, u'active_page': 0}, {u'tools': [], u'active_page': -1}], u'w': 222}}, 'compat_behavior_when_unknown': u'unless-pigment-layer-1.x', 'saving.default_format': u'openraster', 'brushmanager.selected_brush': u'classic/blur', u'ui.support_smooth_scrolling': True, u'input.devices': {u'Virtual core XTEST pointer:mouse:2': {}, u'xwayland-touch:16:touchscreen:2': {}, u'xwayland-relative-pointer:16:mouse:2': {}, u'xwayland-pointer:16:mouse:4': {}, u'xwayland-eraser:16:eraser:6': {}, u'xwayland-cursor:16:cursor:6': {}, u'xwayland-stylus:16:touchscreen:6': {}}, 'view.real_alpha_checks': True, 'input.device_mode': u'screen', 'document.autosave_interval': 10, 'scratchpad.last_opened_scratchpad': u'/home/max/.local/share/mypaint/scratchpads/autosave.ora', 'compability_settings': {u'2.x': {u'pigment_on_by_default': True, u'pigment_layer_is_default': True}, u'1.x': {u'pigment_on_by_default': False, u'pigment_layer_is_default': False}}})), 'G': ('local', u'\u201eMax2.ora"'), 'F': ('local', 'load'), 'H': (None, []), 'convert_to_srgb': (None, []), 'incompatible_ora_cb': (None, []), 'A.app': ('local', <gui.application.Application object at 0x7f241dea5c90>), 'compat_handler': ('local', None), 'arg': ('local', u'/home/max/Downloads/Max2.ora'), '_IOProgressUI.format_files_summary': ('global', <function format_files_summary at 0x7f241c710ed8>), 'False': ('builtin', False), 'B': ('local', <function A at 0x7f2419b26c80>), 'method': ('local', <bound method Document.load of <Document nlayers=1 bbox=Rect(0, 0, 0, 0) paintonly=False>>), 'is_import': ('local', False)}
  File "/tmp/.mount_MyPainVrCI2A/usr/lib/mypaint/gui/filehandling.py", line 43, __init__(A=<gui.filehandling._IOProgressUI instance>, app=<gui.application.Application object>, op_type='load', files_summary=u'\u201eMax2.ora"', use_statusbar=True, use_dialogs=True)
        if B not in A._OP_DURATION_TEMPLATES:raise ValueError('Unknown operation type %r'%(B,))
        C=A._OP_DURATION_TEMPLATES[B].format(files_summary=D);A._duration_msg=C;C=A._OP_SUCCEEDED_TEMPLATES[B].format(files_summary=D);A._success_msg=C;C=A._OP_FAILED_TEMPLATES[B].format(files_summary=D);A._fail_msg=C;C=A._OP_FAIL_DIALOG_TITLES[B];A._fail_dialog_title=C;A._is_write=B in['save','export'];E=A._app.statusbar.get_context_id('filehandling-message');A._statusbar_context_id=E;A._use_statusbar=bool(use_statusbar);A._use_dialogs=bool(use_dialogs);A.success=False;A._progress_dialog=None;A._progress_bar=None;A._start_time=None;A._last_pulse=None
      @with_wait_cursor
  variables: {'C': (None, []), 'B': ('local', 'load'), 'D': ('local', u'\u201eMax2.ora"'), 'format': ('builtin', <built-in function format>), 'files_summary': ('local', u'\u201eMax2.ora"'), 'A._OP_DURATION_TEMPLATES': ('local', {'load': u'\u201e{file_summary}\u201c wird geladen \u2026', 'import': u'Importiere Ebenen aus \u201e{files_summary}"\u2026', 'save': u'\u201e{files_summary}\u201c wird gespeichert \u2026', 'export': u'Export nach \u201e{files_summary}\u201c l\xe4uft \u2026'})}
KeyError: u'file_summary'
```
```

**Comment by bromosky** [comment]
So i tried the rolling release, and with that version (2.1.0) it works flawless.

Sorry for this bug report.
