### ISSUE TITLE
KISS linux mypaint

### ISSUE THREAD

**Issue by muevoid** [mypaint/mypaint#1075]
#### Description of the problem
The mypaint demo seems to not start on my pc. I have gone through and packaged all the dependencies on my personal repo. I have not yet packaged mypaint yet and was doing testing outside my repo. However you can see all the packages I have here https://github.com/muevoid/kiss-mue plus some from the official repos such as glib and gtk+3. When I was doing testing originally I could not get it to build with the latest source tarball so I tried cloing the latest 2.0 release from the github branch however it would build the demo now but I get a Traceback error saying no namespace Gtk. 

#### Operating system details

MyPaint version: Latest git release on the v2.0.x branch
Operating system: KISS Linux
Window Manager: sowm

#### Steps to reproduce
1. Clone latest release on v2.0.x branch
2. run python setup.py demo
3. The error shows up

#### Backtraces or error messages

```
I recieve this error:

Traceback (most recent call last):
  File "/tmp/demo-4vsc7gv8/bin/mypaint", line 294, in <module>
    = get_paths()
  File "/tmp/demo-4vsc7gv8/bin/mypaint", line 241, in get_paths
    from lib import fileutils
  File "/tmp/demo-4vsc7gv8/lib/mypaint/lib/fileutils.py", line 25, in <module>
    import lib.gichecks
  File "/tmp/demo-4vsc7gv8/lib/mypaint/lib/gichecks.py", line 20, in <module>
    gi.require_version('Gtk', '3.0')
  File "/usr/lib/python3.8/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
Demo: cleaning up '/tmp/demo-4vsc7gv8'...
Traceback (most recent call last):
  File "setup.py", line 935, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/setuptools-46.1.3.post20200422-py3.8.egg/setuptools/__init__.py", line 144, in setup
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 535, in run
    subprocess.check_call(demo_cmd)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '/tmp/demo-4vsc7gv8/bin/mypaint', '-c', '/tmp/demo-4vsc7gv8/_config']' returned non-zero exit status 1.
```

**Comment by muevoid** [comment]
This was entirely my fault gtk+3 and pango were compiled without interprosection enabled.
