### ISSUE TITLE
Unkown error message appears on screen when i start it up.

### ISSUE THREAD

**Issue by Soulgaming1** [mypaint/mypaint#1076]
I started the app up and then it just gives me the error and i do not know how to resolve this.

```python
Mypaint version: 2.0.0-alpha+git.e7e9b6fd
System information: Windows-10-10.0.18362-SP0
Using: Python 2.7.17, GTK 3.24.12, GdkPixbuf 2.40.0, Cairo 1.16.0, GLib 2.62.1
Traceback (most recent call last):
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/gui/application.py", line 459, _at_application_start(self=<gui.application.Application object>, filenames=[], fullscreen=None)
                autosave_recovery = gui.autorecover.Presenter(self)
                autosave_recovery.run(startup=True)
  variables: {'autosave_recovery.run': ('local', <bound method Presenter.run of <gui.autorecover.Presenter object at 0x0000000010072f90>>), 'True': ('builtin', True), 'startup': (None, [])}
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/gui/autorecover.py", line 133, run(self=<gui.autorecover.Presenter object>, startup=True)
            # Only run if there are autosaves which can be recovered.
            autosaves = self._reload_liststore()
            if not autosaves:
  variables: {'autosaves': (None, []), 'self._reload_liststore': ('local', <bound method Presenter._reload_liststore of <gui.autorecover.Presenter object at 0x0000000010072f90>>)}
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/gui/autorecover.py", line 79, _reload_liststore(self=<gui.autorecover.Presenter object>)
            autosaves = []
            for asav in lib.document.get_available_autosaves():
                # Another instance may be working in there.
  variables: {'lib.document.get_available_autosaves': ('global', <function get_available_autosaves at 0x000000000d674bd0>), 'asav': (None, [])}
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/lib/document.py", line 2146, get_available_autosaves()
                continue
            yield AutosaveInfo.new_for_path(autosave_path)
  variables: {'AutosaveInfo.new_for_path': ('global', <bound method type.new_for_path of <class 'lib.document.AutosaveInfo'>>), 'autosave_path': ('local', u'C:\\Users\\Leergeld\\AppData\\Local\\Microsoft\\Windows\\INetCache/mypaint/doc.iew72qx4/autosave')}
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/lib/document.py", line 160, new_for_path(cls=<class 'lib.document.AutosaveInfo'>, path=u'C:\\Users\\Leergeld\\AppData\\Local\\Microsoft\\Windows\\INetCache/mypaint/doc.iew72qx4/autosave')
            if os.path.exists(thumbnail_path):
                thumbnail = lib.pixbuf.load_from_file(thumbnail_path)
            cache_in_use = False
  variables: {'thumbnail_path': ('local', u'C:\\Users\\Leergeld\\AppData\\Local\\Microsoft\\Windows\\INetCache/mypaint/doc.iew72qx4/autosave/Thumbnails/thumbnail.png'), 'lib.pixbuf.load_from_file': ('global', <function load_from_file at 0x000000000cf86650>), 'thumbnail': ('local', None)}
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/lib/pixbuf.py", line 113, load_from_file(filename=u'C:\\Users\\Leergeld\\AppData\\Local\\Microsoft...t/doc.iew72qx4/autosave/Thumbnails/thumbnail.png', progress=<Progress 2410.0/2410>)
            progress.items = size
            pixbuf = load_from_stream(fp, progress=progress)
  variables: {'fp': ('local', <closed file u'C:\\Users\\Leergeld\\AppData\\Local\\Microsoft\\Windows\\INetCache/mypaint/doc.iew72qx4/autosave/Thumbnails/thumbnail.png', mode 'rb' at 0x00000000101e3150>), 'progress': ('local', <Progress 2410.0/2410>), 'pixbuf': (None, []), 'load_from_stream': ('global', <function load_from_stream at 0x000000000cf84050>)}
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/lib/pixbuf.py", line 149, load_from_stream(fp=<closed file u'C:\\Users\\Leergeld\\AppData\\Loc...x4/autosave/Thumbnails/thumbnail.png', mode 'rb'>, progress=<Progress 2410.0/2410>)
                progress += len(buf)
        loader.close()
        return loader.get_pixbuf()
  variables: {'loader.close': ('local', gi.FunctionInfo(close))}
Error: gdk-pixbuf-error-quark: Unrecognized image file format (3)
```

**Comment by jplloyd** [comment]
The version you're running is an alpha version of 2.0.0, but my guess is that this is a question of a corrupted autosave file, so it probably makes no difference. Did you have a power outage or any kind of hard crash prior to this happening?

Clicking the "Ignore Error" button, drawing something on the canvas and then waiting 10 seconds (unless you changed the autosave time in the preferences) should overwrite the existing autosave.

**Comment by jplloyd** [comment]
I'll assume that the issue has not reoccurred with the release version and was resolved by the previous suggestion. If not, you can request the issue to be reopened in a comment.
