### ISSUE TITLE
MyPaint crashes when trying to adjust a frame

### ISSUE THREAD

**Issue by HughR** [mypaint/mypaint#1106]
#### Description

Crashes when trying to adjust a frame (I probably used the wrong tool).

#### Steps to reproduce

very first use, ever.  I don't know how to use MyPaint, so I blundered into this.
I drew a stick figure and then decided I wanted to clip the picture.  Tried frame stuff.  Boom.

#### Traceback

```python
Mypaint version: 2.0.0-beta.0+unknown
System information: Linux-5.8.4-200.fc32.x86_64-x86_64-with-glibc2.2.5
Using: Python 3.8.5, GTK 3.24.22, GdkPixbuf 2.40.0, Cairo 1.16.0, GLib 2.64.1
Traceback (most recent call last):
  File "/usr/lib64/mypaint/gui/document.py", line 2184, mode_radioaction_changed_cb(self=<gui.document.Document object>, action=<Gtk.RadioAction object at 0x7f8917ec7140 (GtkRadioAction at 0x7f88f0010600)>, current_action=<Gtk.RadioAction object at 0x7f8917ec7300 (GtkRadioAction at 0x7f88f00138d0)>)
                    mode = mode_class()
                self.modes.context_push(mode)
  variables: {'self.modes.context_push': ('local', <bound method ModeStack.context_push of <ModeStack [FreehandMode, FrameEditMode]>>), 'mode': ('local', <gui.framewindow.FrameEditMode object at 0x7f8917a619a0>)}
  File "/usr/lib64/mypaint/gui/mode.py", line 1369, context_push(self=<ModeStack [FreehandMode, FrameEditMode]>, mode=<gui.framewindow.FrameEditMode object>)
            self._stack.append(mode)
            mode.enter(doc=self._doc)
            self.changed(old=old_mode, new=mode)
  variables: {'mode.enter': ('local', <bound method FrameEditMode.enter of <gui.framewindow.FrameEditMode object at 0x7f8917a619a0>>), 'doc': (None, []), 'self._doc': ('local', <gui.document.Document object at 0x7f8918aadbe0>)}
  File "/usr/lib64/mypaint/gui/framewindow.py", line 116, enter(self=<gui.framewindow.FrameEditMode object>, doc=<gui.document.Document object>, **kwds={})
            """Enter the mode"""
            super(FrameEditMode, self).enter(doc, **kwds)
            # Assign cursors
  variables: {'super': ('builtin', <class 'super'>), 'FrameEditMode': ('global', <class 'gui.framewindow.FrameEditMode'>), 'self': ('local', <gui.framewindow.FrameEditMode object at 0x7f8917a619a0>), 'enter': (None, []), 'doc': ('local', <gui.document.Document object at 0x7f8918aadbe0>), 'kwds': ('local', {})}
  File "/usr/lib64/mypaint/gui/mode.py", line 442, enter(self=<gui.framewindow.FrameEditMode object>, doc=<gui.document.Document object>, **kwds={})
            self.__reset_delta_totals()
            return super(ScrollableModeMixin, self).enter(doc, **kwds)
  variables: {'super': ('builtin', <class 'super'>), 'ScrollableModeMixin': ('global', <class 'gui.mode.ScrollableModeMixin'>), 'self': ('local', <gui.framewindow.FrameEditMode object at 0x7f8917a619a0>), 'enter': (None, []), 'doc': ('local', <gui.document.Document object at 0x7f8918aadbe0>), 'kwds': ('local', {})}
  File "/usr/lib64/mypaint/gui/mode.py", line 1108, enter(self=<gui.framewindow.FrameEditMode object>, doc=<gui.document.Document object>, **kwds={})
                try:
                    self.inactive_cursor = self.doc.app.cursors. \
                            get_action_cursor(self.ACTION_NAME,
  variables: {'self.inactive_cursor': ('local', <gui.framewindow.FrameEditMode object at 0x7f8917a619a0>), 'self.doc.app.cursors.get_action_cursor': ('local', <bound method CustomCursorMaker.get_action_cursor of <gui.cursor.CustomCursorMaker object at 0x7f8919031700>>), 'self.ACTION_NAME': ('local', 'FrameEditMode'), 'gui.cursor.Name.ARROW': ('global', 'cursor_arrow')}
  File "/usr/lib64/mypaint/gui/cursor.py", line 331, get_action_cursor(self=<gui.cursor.CustomCursorMaker object>, action_name='FrameEditMode', cursor_name='cursor_arrow')
                return Gdk.Cursor.new(Gdk.CursorType.ARROW)
            return self.get_icon_cursor(icon_name, cursor_name)
  variables: {'self.get_icon_cursor': ('local', <bound method CustomCursorMaker.get_icon_cursor of <gui.cursor.CustomCursorMaker object at 0x7f8919031700>>), 'icon_name': ('local', 'mypaint-frame-symbolic'), 'cursor_name': ('local', 'cursor_arrow')}
  File "/usr/lib64/mypaint/gui/cursor.py", line 351, get_icon_cursor(self=<gui.cursor.CustomCursorMaker object>, icon_name='mypaint-frame-symbolic', cursor_name='cursor_arrow')
                if "symbolic" in icon_name:
                    icon_pixbuf = gui.drawutils.load_symbolic_icon(
                        icon_name, 18,
  variables: {'icon_pixbuf': (None, []), 'gui.drawutils.load_symbolic_icon': ('global', <function load_symbolic_icon at 0x7f8918f8d550>), 'icon_name': ('local', 'mypaint-frame-symbolic'), 'fg': (None, []), 'outline': (None, [])}
  File "/usr/lib64/mypaint/gui/drawutils.py", line 300, load_symbolic_icon(icon_name='mypaint-frame-symbolic', size=16, fg=(1, 1, 1, 1), success=None, warning=None, error=None, outline=(0, 0, 0, 1))
        icon_pixbuf, was_symbolic = info.load_symbolic(
            fg=rgba_or_none(fg),
  variables: {'icon_pixbuf': (None, []), 'was_symbolic': (None, []), 'info.load_symbolic': ('local', gi.FunctionInfo(load_symbolic)), 'fg': ('local', (1, 1, 1, 1)), 'rgba_or_none': ('local', <function load_symbolic_icon.<locals>.rgba_or_none at 0x7f89178b18b0>), 'success_color': (None, []), 'success': ('local', None), 'warning_color': (None, []), 'warning': ('local', None), 'error_color': (None, []), 'error': ('local', None)}
Error: rsvg-error-quark: XML parse error: error code=201 (3) in (null):26:121: Namespace prefix xlink for href on use is not defined
 (0)
```

**Comment by jplloyd** [comment]
Thanks for reporting, this is a known issue with the 2.0.0 release (this is the sixth duplicate).

See this comment for further details/references: https://github.com/mypaint/mypaint/issues/1082#issuecomment-633699893
