### ISSUE TITLE
MyPaint no longer working after recent update -mypaint (2.0.0-1 -> 2.0.0-2)

### ISSUE THREAD

**Issue by ahloiscreamo** [mypaint/mypaint#1121]
#### Description of the problem

Hello!
Today i issues daily system update and it prompted me to latest mypaint and bunch of other packages
```

[2020-12-02T15:53:11+0800] [ALPM] transaction started
[2020-12-02T15:53:11+0800] [ALPM] upgraded arandr (0.1.10-4 -> 0.1.10-5)
[2020-12-02T15:53:11+0800] [ALPM] upgraded feh (3.5-1 -> 3.6-1)
[2020-12-02T15:53:11+0800] [ALPM] upgraded gnupg (2.2.23-1 -> 2.2.24-1)
[2020-12-02T15:53:11+0800] [ALPM] upgraded i2c-tools (4.1-5 -> 4.1-6)
[2020-12-02T15:53:11+0800] [ALPM] upgraded kitty-terminfo (0.19.1-1 -> 0.19.2-2)
[2020-12-02T15:53:11+0800] [ALPM] upgraded kitty (0.19.1-1 -> 0.19.2-2)
[2020-12-02T15:53:12+0800] [ALPM] upgraded krita (4.4.1-5 -> 4.4.1-6)
[2020-12-02T15:53:12+0800] [ALPM] upgraded libixion (0.16.1-1 -> 0.16.1-3)
[2020-12-02T15:53:12+0800] [ALPM] upgraded liborcus (0.16.1-1 -> 0.16.1-3)
[2020-12-02T15:53:13+0800] [ALPM] upgraded libreoffice-fresh (7.0.3-2 -> 7.0.3-3)
[2020-12-02T15:53:14+0800] [ALPM] upgraded mypaint (2.0.0-1 -> 2.0.0-2)
[2020-12-02T15:53:14+0800] [ALPM] upgraded playerctl (2.2.1-1 -> 2.3.1-1)
[2020-12-02T15:53:14+0800] [ALPM] upgraded python-configargparse (1.2.3-1 -> 1.2.3-3)
[2020-12-02T15:53:14+0800] [ALPM] upgraded python-mpd2 (1.1.0-1 -> 1.1.0-2)
[2020-12-02T15:53:14+0800] [ALPM] upgraded ranger (1.9.3-2 -> 1.9.3-3)
[2020-12-02T15:53:14+0800] [ALPM] upgraded semver (7.3.2-1 -> 7.3.3-1)
[2020-12-02T15:53:14+0800] [ALPM] upgraded xorg-server-common (1.20.9+21+g5c400cae1-1 -> 1.20.10-1)
[2020-12-02T15:53:14+0800] [ALPM] upgraded xorg-server (1.20.9+21+g5c400cae1-1 -> 1.20.10-1)
[2020-12-02T15:53:14+0800] [ALPM] upgraded youtube-dl (2020.11.26-1 -> 2020.11.29-2)
[2020-12-02T15:53:14+0800] [ALPM] transaction completed
```
Mypaint no longer work after that.

#### Basic system details

MyPaint version: 2.0.0-2
Operating system: Artix 
Desktop environment: i3wm

#### Steps to reproduce

1. Update system 
2. MyPaint update from 2.0.0-1 to 2.0.0-2
3. Start MyPaint
4.No Response

#### Backtraces or error messages

Terminal output-:
```
❯ mypaint
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix '/usr'
Traceback (most recent call last):
  File "/usr/bin/mypaint", line 294, in <module>
    = get_paths()
  File "/usr/bin/mypaint", line 241, in get_paths
    from lib import fileutils
  File "/usr/lib/mypaint/lib/fileutils.py", line 26, in <module>
    import lib.helpers
  File "/usr/lib/mypaint/lib/helpers.py", line 26, in <module>
    from . import mypaintlib
  File "/usr/lib/mypaint/lib/mypaintlib.py", line 13, in <module>
    from . import _mypaintlib
ImportError: cannot import name '_mypaintlib' from 'lib' (/usr/lib/mypaint/lib/__init__.py)
~
❯
```

Is this related to libpython?
MyPaint and Libmypaint all installed via Arch repository.
Thanks!

**Comment by ahloiscreamo** [comment]
Update -
after few hour, i got another system update rolled out and upgrade:

```
[2020-12-02T17:43:03+0800] [PACMAN] starting full system upgrade
[2020-12-02T17:44:18+0800] [ALPM] transaction started
[2020-12-02T17:44:18+0800] [ALPM] upgraded util-linux-libs (2.36.1-3 -> 2.36.1-4)
[2020-12-02T17:44:18+0800] [ALPM] upgraded gcc-libs (10.2.0-3 -> 10.2.0-4)
[2020-12-02T17:44:18+0800] [ALPM] upgraded audit (2.8.5-7 -> 2.8.5-9)
[2020-12-02T17:44:18+0800] [ALPM] upgraded boost-libs (1.72.0-2 -> 1.72.0-4)
[2020-12-02T17:44:18+0800] [ALPM] upgraded brotli (1.0.9-2 -> 1.0.9-4)
[2020-12-02T17:44:18+0800] [ALPM] upgraded btrfs-progs (5.9-1 -> 5.9-3)
[2020-12-02T17:44:19+0800] [ALPM] upgraded gcc (10.2.0-3 -> 10.2.0-4)
[2020-12-02T17:44:19+0800] [ALPM] upgraded glib2 (2.66.2-1 -> 2.66.3-1)
[2020-12-02T17:44:19+0800] [ALPM] upgraded gpgme (1.15.0-1 -> 1.15.0-2)
[2020-12-02T17:44:19+0800] [ALPM] upgraded libxml2 (2.9.10-3 -> 2.9.10-7)
[2020-12-02T17:44:19+0800] [ALPM] upgraded llvm-libs (11.0.0-1 -> 11.0.0-3)
[2020-12-02T17:44:19+0800] [ALPM] upgraded libseccomp (2.4.2-1 -> 2.5.1-2)
[2020-12-02T17:44:19+0800] [ALPM] upgraded util-linux (2.36.1-3 -> 2.36.1-4)
[2020-12-02T17:44:19+0800] [ALPM] upgraded kwidgetsaddons (5.76.0-1 -> 5.76.0-2)
[2020-12-02T17:44:19+0800] [ALPM] upgraded kconfig (5.76.0-1 -> 5.76.0-2)
[2020-12-02T17:44:19+0800] [ALPM] upgraded kcompletion (5.76.0-1 -> 5.76.0-2)
[2020-12-02T17:44:19+0800] [ALPM] upgraded kcoreaddons (5.76.0-1 -> 5.76.0-2)
[2020-12-02T17:44:19+0800] [ALPM] upgraded kguiaddons (5.76.0-1 -> 5.76.0-2)
[2020-12-02T17:44:19+0800] [ALPM] upgraded ki18n (5.76.0-1 -> 5.76.0-2)
[2020-12-02T17:44:19+0800] [ALPM] upgraded kitemmodels (5.76.0-1 -> 5.76.0-2)
[2020-12-02T17:44:19+0800] [ALPM] upgraded kitemviews (5.76.0-1 -> 5.76.0-2)
[2020-12-02T17:44:19+0800] [ALPM] upgraded protobuf (3.12.4-1 -> 3.12.4-3)
[2020-12-02T17:44:20+0800] [ALPM] upgraded python (3.8.6-1 -> 3.9.0-1)
[2020-12-02T17:44:20+0800] [ALPM] upgraded python-cairo (1.20.0-1 -> 1.20.0-3.1)
[2020-12-02T17:44:20+0800] [ALPM] upgraded python-six (1.15.0-1 -> 1.15.0-3)
[2020-12-02T17:44:20+0800] [ALPM] upgraded python-pycparser (2.20-1 -> 2.20-3)
[2020-12-02T17:44:20+0800] [ALPM] upgraded python-ordered-set (4.0.2-1 -> 4.0.2-3)
[2020-12-02T17:44:20+0800] [ALPM] upgraded python-pyparsing (2.4.7-1 -> 2.4.7-3)
[2020-12-02T17:44:20+0800] [ALPM] upgraded python-packaging (20.4-1 -> 20.7-1)
[2020-12-02T17:44:20+0800] [ALPM] upgraded python-cryptography (3.2.1-1 -> 3.2.1-3)
[2020-12-02T17:44:20+0800] [ALPM] upgraded python-dbus-common (1.2.16-1 -> 1.2.16-3)
[2020-12-02T17:44:20+0800] [ALPM] upgraded python-dbus (1.2.16-1 -> 1.2.16-3)
[2020-12-02T17:44:20+0800] [ALPM] upgraded python-lxml (4.6.1-1 -> 4.6.2-1)
[2020-12-02T17:44:20+0800] [ALPM] upgraded python-numpy (1.19.4-1 -> 1.19.4-3)
[2020-12-02T17:44:20+0800] [ALPM] upgraded python-pep517 (0.9.1-1 -> 0.9.1-3)
[2020-12-02T17:44:20+0800] [ALPM] upgraded python-urllib3 (1.25.10-2 -> 1.25.10-4)
[2020-12-02T17:44:20+0800] [ALPM] upgraded python-requests (2.24.0-1 -> 2.25.0-1)
[2020-12-02T17:44:20+0800] [ALPM] upgraded python-resolvelib (0.5.1-1 -> 0.5.2-1)
[2020-12-02T17:44:20+0800] [ALPM] upgraded python-pip (20.2-1 -> 20.2-3)
[2020-12-02T17:44:20+0800] [ALPM] upgraded sudo (1.9.3.p1-1 -> 1.9.4-1)
[2020-12-02T17:44:20+0800] [ALPM] upgraded syslog-ng (3.29.1-2 -> 3.29.1-3)
[2020-12-02T17:44:20+0800] [ALPM] upgraded vim-runtime (8.2.1704-1 -> 8.2.1989-3)
[2020-12-02T17:44:20+0800] [ALPM] upgraded vim (8.2.1704-1 -> 8.2.1989-3)
[2020-12-02T17:44:21+0800] [ALPM] transaction completed
```

Now when i try to start MyPaint, terminal output-

```
❯ mypaint
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix '/usr'
Traceback (most recent call last):
  File "/usr/bin/mypaint", line 294, in <module>
    = get_paths()
  File "/usr/bin/mypaint", line 241, in get_paths
    from lib import fileutils
  File "/usr/lib/mypaint/lib/fileutils.py", line 25, in <module>
    import lib.gichecks
  File "/usr/lib/mypaint/lib/gichecks.py", line 18, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
```
What packages provide gi actually? i have python-gobject installed (python-gobject-3.38.0-1)

**Comment by ahloiscreamo** [comment]
Update-

So shortly after hour figuring whats wrong blah blah
i build PyGObject & numpy through pip3 and now mypaint is working again.
Thank you, i will close the issue.
