### ISSUE TITLE
Bug while moving the page

### ISSUE THREAD

**Issue by NaorAnhaisy** [mypaint/mypaint#1128]
#### Description

Give this report a short descriptive title. Use something like "{feature-that-broke}: {what-went-wrong}" for the title, if you can. Then please replace this text with a longer description of the bug. Screenshots or videos are great, too!

#### Steps to reproduce

Please tell us what you were doing when the error message popped up. If you can provide step-by-step instructions on how to reproduce the bug, that's even better.

#### Traceback

```python
Mypaint version: 2.0.0-alpha+git.55678ec2
System information: Windows-10-10.0.19041-SP0
Using: Python 2.7.16, GTK 3.24.9, GdkPixbuf 2.38.1, Cairo 1.16.0, GLib 2.60.4
Traceback (most recent call last):
  File "C:/Program Files/WindowsApps/D5BE6627.UltraPaint_2.0.3.0_x86__9pm2v9747qaaa/mingw32/lib/mypaint/gui/tileddrawwidget.py", line 1116, _draw_cb(self=<tileddrawwidget.CanvasRenderer object at 0x1352...ui+tileddrawwidget+CanvasRenderer at 0x13b970c0)>, widget=<tileddrawwidget.CanvasRenderer object at 0x1352...ui+tileddrawwidget+CanvasRenderer at 0x13b970c0)>, cr=<cairo.Context object>)
            transformation, surface, sparse, mipmap_level, clip_rect = \
                self._render_prepare(cr)
  variables: {'cr': ('local', <cairo.Context object at 0x03d44d20>), 'self._render_prepare': ('local', <bound method CanvasRenderer._render_prepare of <tileddrawwidget.CanvasRenderer object at 0x1352f080 (gui+tileddrawwidget+CanvasRenderer at 0x13b970c0)>>)}
  File "C:/Program Files/WindowsApps/D5BE6627.UltraPaint_2.0.3.0_x86__9pm2v9747qaaa/mingw32/lib/mypaint/gui/tileddrawwidget.py", line 1333, _render_prepare(self=<tileddrawwidget.CanvasRenderer object at 0x1352...ui+tileddrawwidget+CanvasRenderer at 0x13b970c0)>, cr=<cairo.Context object>)
            surface = pixbufsurface.Surface(x1, y1, x2 - x1 + 1, y2 - y1 + 1)
            return transformation, surface, sparse, mipmap_level, clip_rect
  variables: {'y2': ('local', 1377), 'surface': (None, []), 'x2': ('local', 3935), 'pixbufsurface.Surface': ('global', <class 'lib.pixbufsurface.Surface'>), 'y1': ('local', -137), 'x1': ('local', 1171)}
  File "C:/Program Files/WindowsApps/D5BE6627.UltraPaint_2.0.3.0_x86__9pm2v9747qaaa/mingw32/lib/mypaint/lib/pixbufsurface.py", line 95, __init__(self=<lib.pixbufsurface.Surface object>, x=1171, y=-137, w=2765, h=1515, data=None)
                logger.exception("GdkPixbuf.Pixbuf.new() failed")
                raise AllocationError(_POSSIBLE_OOM_USERTEXT)
            if self.epixbuf is None:
  variables: {'_POSSIBLE_OOM_USERTEXT': ('global', u'Unable to construct a vital internal object. Your system may not have enough memory to perform this operation.'), 'AllocationError': ('global', <class 'lib.errors.AllocationError'>)}
AllocationError: Unable to construct a vital internal object. Your system may not have enough memory to perform this operation.
```

**Comment by jplloyd** [comment]
The version of mypaint used here, as indicated by the version string, is an alpha from `Wed Jun 19 09:59:01 2019 -0700`. I would suggest using the latest stable release, which is 2.0.1.

Secondly, I don't know what UltraPaint is, but if this is a repackaged version of mypaint I would suggest you contact the repackagers and ask them to update.

Thirdly, if you can reproduce the bug in the latest stable release, please include instructions on how to reproduce it - and since the error in the traceback tells us that it's an allocation problem, it will be helpful if you include your system specifications in the report.
