### ISSUE TITLE
It says a bug was detected.

### ISSUE THREAD

**Issue by Awesomeness7661** [mypaint/mypaint#1134]
#### Description

Give this report a short descriptive title. Use something like "{feature-that-broke}: {what-went-wrong}" for the title, if you can. Then please replace this text with a longer description of the bug. Screenshots or videos are great, too!

#### Steps to reproduce

Please tell us what you were doing when the error message popped up. If you can provide step-by-step instructions on how to reproduce the bug, that's even better.

#### Traceback

```python
Mypaint version: 2.0.0-alpha+git.55678ec2
System information: Windows-10-10.0.19041-SP0
Using: Python 2.7.16, GTK 3.24.9, GdkPixbuf 2.38.1, Cairo 1.16.0, GLib 2.60.4
Traceback (most recent call last):
  File "C:/Program Files/WindowsApps/D5BE6627.UltraPaint_2.0.3.0_x86__9pm2v9747qaaa/mingw32/lib/mypaint/gui/drawwindow.py", line 147, showPopup(self=<drawwindow.DrawWindow object at 0x02f5bee0 (MyPaintDrawWindow at 0x02f15420)>)
            settings = SettingsManager()
            if SettingsManager.bFirstLaunch:
  variables: {'SettingsManager': ('global', <class gui.settingsmanager.SettingsManager at 0x0e48e260>), 'settings': (None, [])}
  File "C:/Program Files/WindowsApps/D5BE6627.UltraPaint_2.0.3.0_x86__9pm2v9747qaaa/mingw32/lib/mypaint/gui/settingsmanager.py", line 29, __init__(self=<gui.settingsmanager.SettingsManager instance>)
                if not os.path.isdir(os.path.join(appdataPath , 'Ultra Paint')):
                    os.makedirs(os.path.join(appdataPath , 'Ultra Paint'))
                f = open(programIniPath,'w+')
  variables: {'os.path.join': ('global', <function join at 0x00b8c030>), 'os.makedirs': ('global', <function makedirs at 0x00b449f0>), 'appdataPath': ('local', 'C:\\Users\\mcmil\\AppData\\Roaming')}
  File "C:\Program Files\WindowsApps\D5BE6627.UltraPaint_2.0.3.0_x86__9pm2v9747qaaa/mingw32/lib/python2.7/os.py", line 157, makedirs(name=r'C:\Users\mcmil\AppData\Roaming/Ultra Paint', mode=511)
                return
        mkdir(name, mode)
  variables: {'mkdir': ('global', <built-in function mkdir>), 'name': ('local', 'C:\\Users\\mcmil\\AppData\\Roaming/Ultra Paint'), 'mode': ('local', 511)}
WindowsError: [Error 183] Cannot create a file when that file already exists: 'C:\\Users\\mcmil\\AppData\\Roaming/Ultra Paint'
```

**Comment by jplloyd** [comment]
A repackaging of an old alpha release - presumably released on the microsoft store by someone trying to make a quick buck from people who don't know better, same is in #1128

I would suggest using [official releases](https://github.com/mypaint/mypaint/releases/) - Mypaint is open source software, and you don't have to pay anything for it.
