### ISSUE TITLE
The application “MyPaint” can’t be opened.

### ISSUE THREAD

**Issue by abhimandesh** [mypaint/mypaint#1154]
The application does not open

The icon bounces on the dock and does not open

MyPaint version: v 2.0.1
Operating system: macOS High Sierra v 10.13.6

**Comment by gselsidi** [comment]
same issue macbook air m1

**Comment by ashkaps** [comment]
Same issue on my Monterey.
<img width="334" alt="Screenshot 2022-01-17 at 10 47 19 AM" src="https://user-images.githubusercontent.com/31744402/149711954-bf34d51b-3259-4863-be02-6b203ef66ae6.png">

**Comment by Kim3r** [comment]
i also have the same problem on Osx Sierra 10.12.6.

**Comment by myrpg-fun** [comment]
Monterey OS

```
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix '/opt/local/Library/Frameworks/Python.framework/Versions/3.8'
WARNING: gui.userconfig: Failed to load settings file: /Users/liz2k/.config/mypaint/settings.json
WARNING: gui.userconfig: Failed to load settings: using defaults
INFO: gui.main: No locale setting found, using system locale
INFO: lib.i18n: OSX: imported AppKit.NSLocale OK. Will use for LANG, and for LANGUAGE order.
INFO: lib.i18n: OSX: LANG='en_RU'
INFO: lib.i18n: OSX: LANGUAGE='en_RU:ru_RU'
INFO: lib.i18n: Value of LANGUAGE after cleanup: 'en_RU:C:ru_RU'

(mypaint:98245): Gtk-CRITICAL **: 10:54:54.476: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/opt/local/bin/mypaint", line 309, in <module>
    main.main(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/mypaint/gui/main.py", line 231, in main
    run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/mypaint/gui/main.py", line 195, in run
    app = application.Application(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/mypaint/gui/application.py", line 240, in __init__
    _init_icons(state_dirs.app_icons)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/mypaint/gui/application.py", line 118, in _init_icons
    icon_theme.append_search_path(icon_path)
AttributeError: 'NoneType' object has no attribute 'append_search_path'
```

**Comment by ryandesign** [comment]
In a default MacPorts installation, MyPaint uses X11. Therefore you must install an X11 server. MacPorts doesn't do it automatically because it doesn't know which one you want but the usual one to use is the one you get when you run `sudo port install xorg-server`. Log out and log back in afterward.

**Comment by AesaraB** [comment]
This should ideally be dealt with by the packagers, as it's a packaging issue and not a MyPaint one, but I've added it to the FAQ for the new website.

**Comment by ryandesign** [comment]
> This should ideally be dealt with by the packagers

I'm the packager of MyPaint for MacPorts and I've dealt with the issue by explaining in the comment preceding yours how MacPorts works. This issue can be closed; there's nothing that needs to be changed.

**Comment by ryandesign** [comment]
That is to say, there's nothing to be changed from the MacPorts side. We don't include xorg-server as a dependency of any ports that use X11; it's up to the user to install the X server they want to use. From the MyPaint side, a more helpful error message when an X server is not available might be a good idea, so I suggest changing the title of this issue back to what it was before.

**Comment by AesaraB** [comment]
I'll need to take some time to think about how to approach this. I know we have good error messages when MyPaint can't find parts of itself, but I think it would be out of scope for MyPaint to do dependency management. I think the ideal solution would be to build MyPaint for macOS without the xorg-server dependency. It's something I'll look into when we migrate to GTK4
