### ISSUE TITLE
Insufficient memory to save large files despite large amount of free system RAM; how to increase max allocated RAM?

### ISSUE THREAD

**Issue by colin-heberling** [mypaint/mypaint#1155]
#### Description of the problem

I am having frequent memory issues when trying to save large OpenRaster projects with multiple layers (memory overflow), in MyPaint 1.0.0.  Sometimes MyPaint crashes when moving the canvas view to a larger frame as well, which also suggests a memory overflow problem.

My system memory is quite large: 64 GB, and so my guess is that MyPaint is written with a max threshold on memory consumption, as a safety precaution to accommodate systems with lower memory specifications.  At max, MyPaint only consumed ~1.6 GB RAM, while I still had ~40 GB RAM free.

Is there a way I could override this in the program itself or in the source code?  I have tried out MyPaint 2.0 already and decided that I liked 1.0.0 better due to a slimmer set of features and therefore less processor/memory usage and therefore less latency when drawing/painting.  So I would prefer to stick with version 1.0.0.  If MyPaint is limiting my memory usage then there must be a way to increase the threshold.  

#### Basic system details

MyPaint version: 1.0.0
Operating system: Windows 10
RAM: 64 GB
Processor: 11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz   3.60 
Offending file size: 71.2 MB
Memory usage: ~1.6 GB

#### Backtraces or error messages

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\MyPaint\library.zip\gui\filehandling.py", line 429, save_cb(no details)
            else:
                self.save_file(self.filename)
  File "C:\Program Files (x86)\MyPaint\library.zip\gui\drawwindow.py", line 46, wrapper(self=<gui.filehandling.FileHandler object>, *args=(u'C:\\Users\\Colin Heberling\\Creative_Developme...gital_Art\\MyPaint\\fe_linde\\fe_linde_color.ora',), **kwargs={})
            try:
                func(self, *args, **kwargs)
                # gtk main loop may be called in here...
  File "C:\Program Files (x86)\MyPaint\library.zip\gui\filehandling.py", line 278, save_file(no details)
        def save_file(self, filename, export=False, **options):
            thumbnail_pixbuf = self.save_doc_to_file(filename, self.doc, export=export, **options)
            if not export:
  File "C:\Program Files (x86)\MyPaint\library.zip\gui\filehandling.py", line 311, save_doc_to_file(no details)
                    w, h = tiledsurface.N, tiledsurface.N # TODO: support for other sizes
                thumbnail_pixbuf = doc.model.save(filename, feedback_cb=self.gtk_main_tick, **options)
                self.lastsavefailed = False
  File "C:\Program Files (x86)\MyPaint\library.zip\lib\document.py", line 367, save(no details)
            try:
                save(filename, **kwargs)
            except gobject.GError, e:
  File "C:\Program Files (x86)\MyPaint\library.zip\lib\document.py", line 546, save_ora(self=<lib.document.Document instance>, filename=u'C:\\Users\\Colin Heberling\\Creative_Developme...gital_Art\\MyPaint\\fe_linde\\fe_linde_color.ora', options=None, **kwargs={'feedback_cb': <function gtk_main_tick>})
                sio = StringIO()
                l.save_strokemap_to_file(sio, -x, -y)
                data = sio.getvalue(); sio.close()
  File "C:\Program Files (x86)\MyPaint\library.zip\lib\layer.py", line 122, save_strokemap_to_file(no details)
                f.write(struct.pack('>II', brush2id[stroke.brush_string], len(s)))
                f.write(s)
            f.write('}')
MemoryError: out of memory
```

**Comment by QuLogic** [comment]
>   File "C:\Program Files **(x86)**\MyPaint\library.zip\gui\filehandling.py", line 429, save_cb(no details)

That means you have it installed as a 32-bit application, which will likely have no way of using more than ~3G of memory space.

**Comment by colin-heberling** [comment]
Will it fix the problem if I install the 64 bit version instead?  Or will it still have a (lowish) memory limit?

**Comment by QuLogic** [comment]
I would think so; I wouldn't think there's an internal limit. I don't know about Windows any more than that.

**Comment by colin-heberling** [comment]
I've been able to continue editing the file through version 2.0 just fine.  Does 2.0 have an internal RAM limit?  I wouldn't want to come across this issue again.

**Comment by colin-heberling** [comment]
I've run into a similar problem on version 2.0 (at least I think it may be similar?).  When I try to save, the save progress bar doesn't show, or else only shows for a split second without filling up all the way, then it creates a file of the format `.tmpsave.`[original_file_name], which never gets past 1 KB in size.  Then if I try to exit the application, it asks me if I'm sure, because I will lose X minutes of painting.  If I try to save again, it says: 

"Failed to save [file].  Unable to write [file]: [WinError 32] The process cannot access the file because it is being used by another process: `.tmpsave.`[file]".

I am in compatibility mode for version 1.x.  Is that creating a memory limit like in version 1?  I tried switching compatibility to 2.x, but that doesn't change anything, and the app title at top of window still says MyPaint (1.x).  Would it change to 2.x upon reopening the app?

**Comment by AesaraB** [comment]
Possibly related to #1155
