### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'can_insert_node', AttributeError: 'NoneType' object has no attribute 'tdw' and ReferenceError: weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by TruncatedDinosour** [mypaint/mypaint#1160]
#### Description of the problem

I was playing around with mypaint and got an error - noone else has reported it so I decided to do it

#### Basic system details

MyPaint version: 
```
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix '/usr'
MyPaint version 2.0.1+gitexport.478280f
```
Operating system: Gentoo/Linux x86_64
Window manager: DWM

#### Steps to reproduce

1. Start MyPaint
2. hold `i`
3. paint
4. see the error

#### Backtraces or error messages

```python
Mypaint version: 2.0.1+gitexport.478280f
System information: Linux-5.14.8-gentoo-x86_64-Intel-R-_Core-TM-_i3-8130U_CPU_@_2.20GHz-with-glibc2.33
Using: Python 3.9.6, GTK 3.24.29, GdkPixbuf 2.42.6, Cairo 1.16.0, GLib 2.68.3
Traceback (most recent call last):
  File "/usr/lib/mypaint/gui/mvp.py", line 180, method_wrapper(inst=<gui.inktool.OptionsUI object>, *args=(), **kwargs={})
                try:
                    return func(inst, *args, **kwargs)
                except:
  variables: {'func': ('local', <function OptionsUI._update_ui_for_current_target at 0x7f8da89495e0>), 'inst': ('local', <gui.inktool.OptionsUI object at 0x7f8d9f49faf0>), 'args': ('local', ()), 'kwargs': ('local', {})}
  File "/usr/lib/mypaint/gui/inktool.py", line 1270, _update_ui_for_current_target(self=<gui.inktool.OptionsUI object>)
            button_sensitivities = [
                (self.view.insert_point_button, inkmode.can_insert_node(cn_idx)),
                (self.view.delete_point_button, inkmode.can_delete_node(cn_idx)),
  variables: {'self.view.insert_point_button': ('local', <Gtk.Button object at 0x7f8d9f483ac0 (GtkButton at 0x56005a033f80)>), 'inkmode': ('local', None), 'cn_idx': ('local', None)}
AttributeError: 'NoneType' object has no attribute 'can_insert_node'
```

**Comment by TruncatedDinosour** [comment]
just got this error too:
```python
Mypaint version: 2.0.1+gitexport.478280f
System information: Linux-5.14.8-gentoo-x86_64-Intel-R-_Core-TM-_i3-8130U_CPU_@_2.20GHz-with-glibc2.33
Using: Python 3.9.6, GTK 3.24.29, GdkPixbuf 2.42.6, Cairo 1.16.0, GLib 2.68.3
Traceback (most recent call last):
  File "/usr/lib/mypaint/gui/inktool.py", line 544, _task_queue_runner_cb(self=<gui.inktool.InkingMode object>)
            else:
                callback(*args, **kwargs)
                return True
  variables: {'callback': ('local', <bound method InkingMode._draw_curve_segment of <gui.inktool.InkingMode object at 0x7f8d9f3970a0>>), 'args': ('local', (<Document nlayers=1 bbox=Rect(-64, -128, 896, 2176) paintonly=False>, array([4.38456570e+02, 1.64672273e+03, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 4.25608100e+04, 1.28402542e+00, 0.00000000e+00,
       0.00000000e+00]), array([4.38456570e+02, 1.64672273e+03, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 4.25608100e+04, 1.28402542e+00, 0.00000000e+00,
       0.00000000e+00]), array([4.35261177e+02, 1.65413303e+03, 5.00000000e-01, 0.00000000e+00,
       0.00000000e+00, 4.25608260e+04, 1.28402542e+00, 0.00000000e+00,
       0.00000000e+00]), array([4.23884430e+02, 1.68345276e+03, 5.00000000e-01, 0.00000000e+00,
       0.00000000e+00, 4.25608580e+04, 1.28402542e+00, 0.00000000e+00,
       0.00000000e+00]))), 'kwargs': ('local', {'state': {'t_abs': 42560.81}})}
  File "/usr/lib/mypaint/gui/inktool.py", line 504, _draw_curve_segment(self=<gui.inktool.InkingMode object>, model=<Document nlayers=1 bbox=Rect(-64, -128, 896, 2176) paintonly=False>, p_1=array([4.38456570e+02, 1.64672273e+03, 0.0000000...2542e+00, 0.00000000e+00,
       0.00000000e+00]), p0=array([4.38456570e+02, 1.64672273e+03, 0.0000000...2542e+00, 0.00000000e+00,
       0.00000000e+00]), p1=array([4.35261177e+02, 1.65413303e+03, 5.0000000...2542e+00, 0.00000000e+00,
       0.00000000e+00]), p2=array([4.23884430e+02, 1.68345276e+03, 5.0000000...2542e+00, 0.00000000e+00,
       0.00000000e+00]), state={'t_abs': 42560.81})
                dtime = t_abs - last_t_abs
                viewzoom = self.doc.tdw.scale
                viewrotation = self.doc.tdw.rotation
  variables: {'viewzoom': ('local', 1.2840254166877405)}
AttributeError: 'NoneType' object has no attribute 'tdw'
```

**Comment by TruncatedDinosour** [comment]
Jesus, errors after errors:
```python
Exception while analyzing the exception.
Traceback (most recent call last):
  File "/usr/lib/mypaint/gui/tileddrawwidget.py", line 1157, in _draw_cb
    overlay.paint(cr)
  File "/usr/lib/mypaint/gui/inktool.py", line 1046, in paint
    for i, node, x, y in self._get_onscreen_nodes():
  File "/usr/lib/mypaint/gui/inktool.py", line 1030, in _get_onscreen_nodes
    for i, node in enumerate(mode.nodes):
ReferenceError: weakly-referenced object no longer exists

```

**Comment by odysseywestra** [comment]
Could you update mypaint to the latest git version and test it again? Just want to verify these are still existing issues in the master branch.

**Comment by TruncatedDinosour** [comment]
the issues have been fixed after reinstalling after few days
