### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by chiphizeta** [mypaint/mypaint#1174]
#### Description

Give this report a short descriptive title. Use something like "{feature-that-broke}: {what-went-wrong}" for the title, if you can. Then please replace this text with a longer description of the bug. Screenshots or videos are great, too!

#### Steps to reproduce

Please tell us what you were doing when the error message popped up. If you can provide step-by-step instructions on how to reproduce the bug, that's even better.

#### Traceback

```python
Mypaint version: 2.0.0-alpha+git.55678ec2
System information: Windows-10-10.0.22000-SP0
Using: Python 2.7.16, GTK 3.24.9, GdkPixbuf 2.38.1, Cairo 1.16.0, GLib 2.60.4
Traceback (most recent call last):
  File "C:/Program Files/WindowsApps/D5BE6627.UltraPaint_2.0.3.0_x86__9pm2v9747qaaa/mingw32/lib/mypaint/gui/document.py", line 521, undo_cb(self=<gui.document.Document object>, action=<Gtk.Action object at 0x0ed94670 (GtkAction at 0x0ed47c28)>)
            """Undo action callback"""
            self.model.undo()
  variables: {'self.model.undo': ('local', <bound method Document.undo of <Document nlayers=2 bbox=Rect(0, -64, 960, 768) paintonly=False>>)}
  File "C:/Program Files/WindowsApps/D5BE6627.UltraPaint_2.0.3.0_x86__9pm2v9747qaaa/mingw32/lib/mypaint/lib/document.py", line 1138, undo(self=<Document nlayers=2 bbox=Rect(0, -64, 960, 768) paintonly=False>)
            while True:
                cmd = self.command_stack.undo()
                if not cmd or not cmd.automatic_undo:
  variables: {'cmd': (None, []), 'self.command_stack.undo': ('local', <bound method CommandStack.undo of <CommandStack undo_len=19 redo_len=1>>)}
  File "C:/Program Files/WindowsApps/D5BE6627.UltraPaint_2.0.3.0_x86__9pm2v9747qaaa/mingw32/lib/mypaint/lib/command.py", line 93, undo(self=<CommandStack undo_len=19 redo_len=1>)
            command = self.undo_stack.pop()
            command.undo()
            self.redo_stack.append(command)
  variables: {'command.undo': ('local', <bound method SetActiveLayerViewLocked.undo of <Lock Layer View>>)}
  File "C:/Program Files/WindowsApps/D5BE6627.UltraPaint_2.0.3.0_x86__9pm2v9747qaaa/mingw32/lib/mypaint/lib/layervis.py", line 684, undo(self=<Lock Layer View>)
        def undo(self):
            self._lvm.set_active_view_locked(self._old_locked)
            self._old_locked = None
  variables: {'self._lvm.set_active_view_locked': ('local', <bound method LayerViewManager.set_active_view_locked of <lib.layervis.LayerViewManager object at 0x0eb3aff0>>), 'self._old_locked': ('local', True)}
  File "C:/Program Files/WindowsApps/D5BE6627.UltraPaint_2.0.3.0_x86__9pm2v9747qaaa/mingw32/lib/mypaint/lib/layervis.py", line 543, set_active_view_locked(self=<lib.layervis.LayerViewManager object>, locked=True)
            if view is None:
                raise ValueError("Cannot lock or unlock the default view.")
            locked = bool(locked)
  variables: {'ValueError': ('builtin', <type 'exceptions.ValueError'>)}
ValueError: Cannot lock or unlock the default view.
```

**Comment by AesaraB** [comment]
Closed as stale and no info. Please provide information about the bug and I'll reopen it.
