### ISSUE TITLE
Bug in ultra paint

### ISSUE THREAD

**Issue by Purplechaos77** [mypaint/mypaint#1177]
#### Description

Give this report a short descriptive title. Use something like "{feature-that-broke}: {what-went-wrong}" for the title, if you can. Then please replace this text with a longer description of the bug. Screenshots or videos are great, too!

#### Steps to reproduce

Please tell us what you were doing when the error message popped up. If you can provide step-by-step instructions on how to reproduce the bug, that's even better.

#### Traceback

```python
Mypaint version: 2.0.0-alpha+git.55678ec2
System information: Windows-10-10.0.22000-SP0
Using: Python 2.7.16, GTK 3.24.9, GdkPixbuf 2.38.1, Cairo 1.16.0, GLib 2.60.4
Traceback (most recent call last):
  File "C:/Program Files/WindowsApps/D5BE6627.UltraPaint_2.0.3.0_x86__9pm2v9747qaaa/mingw32/lib/mypaint/gui/tileddrawwidget.py", line 1116, _draw_cb(self=<tileddrawwidget.CanvasRenderer object at 0x0e93...ui+tileddrawwidget+CanvasRenderer at 0x0ef8f0c0)>, widget=<tileddrawwidget.CanvasRenderer object at 0x0e93...ui+tileddrawwidget+CanvasRenderer at 0x0ef8f0c0)>, cr=<cairo.Context object>)
            transformation, surface, sparse, mipmap_level, clip_rect = \
                self._render_prepare(cr)
  variables: {'cr': ('local', <cairo.Context object at 0x039225c0>), 'self._render_prepare': ('local', <bound method CanvasRenderer._render_prepare of <tileddrawwidget.CanvasRenderer object at 0x0e9341e8 (gui+tileddrawwidget+CanvasRenderer at 0x0ef8f0c0)>>)}
  File "C:/Program Files/WindowsApps/D5BE6627.UltraPaint_2.0.3.0_x86__9pm2v9747qaaa/mingw32/lib/mypaint/gui/tileddrawwidget.py", line 1333, _render_prepare(self=<tileddrawwidget.CanvasRenderer object at 0x0e93...ui+tileddrawwidget+CanvasRenderer at 0x0ef8f0c0)>, cr=<cairo.Context object>)
            surface = pixbufsurface.Surface(x1, y1, x2 - x1 + 1, y2 - y1 + 1)
            return transformation, surface, sparse, mipmap_level, clip_rect
  variables: {'y2': ('local', 522), 'surface': (None, []), 'x2': ('local', 921), 'pixbufsurface.Surface': ('global', <class 'lib.pixbufsurface.Surface'>), 'y1': ('local', -824), 'x1': ('local', -1221)}
  File "C:/Program Files/WindowsApps/D5BE6627.UltraPaint_2.0.3.0_x86__9pm2v9747qaaa/mingw32/lib/mypaint/lib/pixbufsurface.py", line 95, __init__(self=<lib.pixbufsurface.Surface object>, x=-1221, y=-824, w=2143, h=1347, data=None)
                logger.exception("GdkPixbuf.Pixbuf.new() failed")
                raise AllocationError(_POSSIBLE_OOM_USERTEXT)
            if self.epixbuf is None:
  variables: {'_POSSIBLE_OOM_USERTEXT': ('global', u'Unable to construct a vital internal object. Your system may not have enough memory to perform this operation.'), 'AllocationError': ('global', <class 'lib.errors.AllocationError'>)}
AllocationError: Unable to construct a vital internal object. Your system may not have enough memory to perform this operation.
```

**Comment by ChengduLittleA** [comment]
Looks like out of memory. @briend Maybe take a look? I don't know this ultra paint also uses mypaint GUI?

**Comment by briend** [comment]
Yeah looks like out of memory.  Ultrapaint is in the Windows Store.
Hopefully it is legitimate

**Comment by odysseywestra** [comment]
Hence really why I closed it, We don't officially or through another trusted 3rd party have a copy of MyPaint on the Windows store. Plus we really don't have the resources to support their forks including our own.
