### ISSUE TITLE
brushes

### ISSUE THREAD

**Issue by Purplechaos77** [mypaint/mypaint#1180]
#### Description

Give this report a short descriptive title. Use something like "{feature-that-broke}: {what-went-wrong}" for the title, if you can. Then please replace this text with a longer description of the bug. Screenshots or videos are great, too!

#### Steps to reproduce

Please tell us what you were doing when the error message popped up. If you can provide step-by-step instructions on how to reproduce the bug, that's even better.

#### Traceback

```python
Mypaint version: 2.0.0-alpha+git.55678ec2
System information: Windows-10-10.0.22000-SP0
Using: Python 2.7.16, GTK 3.24.9, GdkPixbuf 2.38.1, Cairo 1.16.0, GLib 2.60.4
Traceback (most recent call last):
  File "C:/Program Files/WindowsApps/D5BE6627.UltraPaint_2.0.3.0_x86__9pm2v9747qaaa/mingw32/lib/mypaint/gui/drawwindow.py", line 739, import_brush_pack_cb(self=<drawwindow.DrawWindow object at 0x0e71cdf0 (MyPaintDrawWindow at 0x02e65420)>, *junk=(<Gtk.Action object at 0x102ba580 (GtkAction at 0x0ecae950)>,))
                return
            imported = self.app.brushmanager.import_brushpack(filename, self)
            logger.info("Imported brush groups %r", imported)
  variables: {'self': ('local', <drawwindow.DrawWindow object at 0x0e71cdf0 (MyPaintDrawWindow at 0x02e65420)>), 'imported': (None, []), 'self.app.brushmanager.import_brushpack': ('local', <bound method BrushManager.import_brushpack of <gui.brushmanager.BrushManager object at 0x0e9a1f10>>), 'filename': ('local', u'C:\\Users\\Purpl\\Downloads\\deevad-v8-2 (3).zip')}
  File "C:/Program Files/WindowsApps/D5BE6627.UltraPaint_2.0.3.0_x86__9pm2v9747qaaa/mingw32/lib/mypaint/gui/brushmanager.py", line 609, import_brushpack(self=<gui.brushmanager.BrushManager object>, path=u'C:\\Users\\Purpl\\Downloads\\deevad-v8-2 (3).zip', window=<drawwindow.DrawWindow object at 0x0e71cdf0 (MyPaintDrawWindow at 0x02e65420)>)
                    ).format(
                        order_conf_file = _BRUSHPACK_ORDERCONF,
                    ))
  variables: {'_BRUSHPACK_ORDERCONF': ('global', 'order.conf'), 'order_conf_file': (None, [])}
InvalidBrushpack: No file named “order.conf”. This is not a brushpack.
```

**Comment by odysseywestra** [comment]
Once again we don't accept issue tickets from forked apps like ultra paint. Though from this error, looks like you were opening the wrong file in the program thinking it was a brushpak. More information about our brush packs are found here: https://github.com/mypaint/mypaint/wiki/Brush-Packages
