### ISSUE TITLE
ERROR: lib.i18n: Exception when getting default locale!

### ISSUE THREAD

**Issue by ladypython247** [mypaint/mypaint#1181]
When trying to setup myPaint app Image I encountered this error

ERROR: lib.i18n: Exception when getting default locale!
Traceback (most recent call last):
  File "/tmp/.mount_MyPainfYi5fT/usr/lib/mypaint/lib/i18n.py", line 6, in getdefaultlocale
    try:return locale.getdefaultlocale()
  File "/tmp/.mount_MyPainfYi5fT/usr/lib64/python2.7/locale.py", line 426, in getdefaultlocale
    return _parse_localename(localename)
  File "/tmp/.mount_MyPainfYi5fT/usr/lib64/python2.7/locale.py", line 407, in _parse_localename
    raise ValueError,'unknown locale: %s'%localename
ValueError: unknown locale: en_NG
Traceback (most recent call last):
  File "/tmp/.mount_MyPainfYi5fT/usr/bin/mypaint", line 58, in <module>
    from gui import main;main.main(datapath,iconspath,localepath,old_confpath,version=version,debug=debug)
  File "/tmp/.mount_MyPainfYi5fT/usr/lib/mypaint/gui/main.py", line 44, in main
    else:K()
  File "/tmp/.mount_MyPainfYi5fT/usr/lib/mypaint/gui/main.py", line 39, in K
    logger.debug('user_datapath: %r',B);logger.debug('user_confpath: %r',C);set_user_configured_locale(C);from lib.gettext_setup import init_gettext as J;J(localepath);from gui import application as H;K=H.StateDirs(app_data=datapath,app_icons=iconspath,user_data=B,user_config=C);I=H.Application(filenames=L,state_dirs=K,version=G,fullscreen=A.fullscreen);from lib.gibindings import Gtk as E;M=E.Settings.get_default();N=I.preferences.get('ui.dark_theme_variant',True);M.set_property('gtk-application-prefer-dark-theme',N)
  File "/tmp/.mount_MyPainfYi5fT/usr/lib/mypaint/lib/gettext_setup.py", line 10, in init_gettext
    for R in sorted(T):logger.debug('getlocale(%s): %r',R,B.getlocale(getattr(B,R)))
  File "/tmp/.mount_MyPainfYi5fT/usr/lib64/python2.7/locale.py", line 430, in getlocale
    return _parse_localename(localename)
  File "/tmp/.mount_MyPainfYi5fT/usr/lib64/python2.7/locale.py", line 407, in _parse_localename
    raise ValueError,'unknown locale: %s'%localename
ValueError: unknown locale: en_NG

**Comment by 0ion9** [comment]
This may mean your locale files are not correctly configured or compiled. See `man locale-gen` and / or https://wiki.archlinux.org/title/locale  - it is necessary to enable the particular locale you want in the config file, and then to recompile locales.

**Comment by odysseywestra** [comment]
@ladypython247 were you able to look into what @0ion9 was saying. He probably right with with looking into your locale files. I've also noticed that you didn't post what version of mypaint you are uisng and what distro you are using. All we have is an error log with no context. If we don't get that information, we'll probably have to close this issue.
