### ISSUE TITLE
Error saving a large file 

### ISSUE THREAD

**Issue by 2201157** [mypaint/mypaint#1190]
After painting a large number of pixels the program just give an error during the saving. 
Normally i use a 3000 x 3000 pixel board to do my draws.
This problem isnt new, since i use this program for years, and in different computers, and i get the same error everytime. 
It's annoying because  everytime i click on the "save" button i dont know if im gonna lose all the progress i made since the last save. 

#### Basic system details

MyPaint version: [✍ 2.0.1+git.478280f2  ]
Operating system: [✍ Windows 10]

#### Steps to reproduce

1. Start MyPaint
2. Have at least 3000 x 3000 pixel background to work with.
3. Make a draw that needs a lot of different colors.
4.  Save frequently 

#### Backtraces or error messages

```

ERROR: lib.fileutils: Save method failed
TypeError: file arg has no file descriptor or FILE* associated with it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/fileutils.py", line 108, in _wrapped_save_method
    save_result = save_method(self, temp_path, *args, **kwds)
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/document.py", line 1776, in save_ora
    thumbnail = _save_layers_to_new_orazip(
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/document.py", line 2085, in _save_layers_to_new_orazip
    root_stack_elem = root_stack.save_to_openraster(
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/tree.py", line 2541, in save_to_openraster
    stack_elem = super(RootLayerStack, self).save_to_openraster(
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/group.py", line 527, in save_to_openraster
    layer_elem = layer.save_to_openraster(orazip, tmpdir, layer_path,
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/group.py", line 527, in save_to_openraster
    layer_elem = layer.save_to_openraster(orazip, tmpdir, layer_path,
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/data.py", line 1642, in save_to_openraster
    elem = super(StrokemappedPaintingLayer, self).save_to_openraster(
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/data.py", line 411, in save_to_openraster
    return self._save_rect_to_ora(orazip, tmpdir, "layer", path,
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/data.py", line 472, in _save_rect_to_ora
    self._surface.save_as_png(pngpath, *rect, progress=progress, **kwargs)
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/tiledsurface.py", line 651, in save_as_png
    lib.surface.save_as_png(self, filename, *args, **kwargs)
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/surface.py", line 277, in save_as_png
    pngsave = mypaintlib.ProgressivePNGWriter(
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/mypaintlib.py", line 777, in __init__
    _mypaintlib.ProgressivePNGWriter_swiginit(self, _mypaintlib.new_ProgressivePNGWriter(file, w, h, has_alpha, save_srgb_chunks))
SystemError: <built-in function new_ProgressivePNGWriter> returned a result with an error set
ERROR: lib.fileutils: cleanup: failed to remove temp path too
TypeError: file arg has no file descriptor or FILE* associated with it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/gui/filehandling.py", line 1170, in save_cb
    self.save_file(self.filename)
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/gui/filehandling.py", line 926, in save_file
    thumbnail_pixbuf = self._save_doc_to_file(
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/gui/filehandling.py", line 1001, in _save_doc_to_file
    thumbnail_pixbuf = ioui.call(doc.model.save, filename, **options)
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/gui/widgets.py", line 182, in wrapper
    return func(self, *args, **kwargs)
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/gui/filehandling.py", line 319, in call
    result = func(*args, **kwargs)
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/document.py", line 1441, in save
    result = save(filename, **kwargs)
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/fileutils.py", line 115, in _wrapped_save_method
    raise ex
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/fileutils.py", line 108, in _wrapped_save_method
    save_result = save_method(self, temp_path, *args, **kwds)
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/document.py", line 1776, in save_ora
    thumbnail = _save_layers_to_new_orazip(
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/document.py", line 2085, in _save_layers_to_new_orazip
    root_stack_elem = root_stack.save_to_openraster(
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/tree.py", line 2541, in save_to_openraster
    stack_elem = super(RootLayerStack, self).save_to_openraster(
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/group.py", line 527, in save_to_openraster
    layer_elem = layer.save_to_openraster(orazip, tmpdir, layer_path,
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/group.py", line 527, in save_to_openraster
    layer_elem = layer.save_to_openraster(orazip, tmpdir, layer_path,
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/data.py", line 1642, in save_to_openraster
    elem = super(StrokemappedPaintingLayer, self).save_to_openraster(
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/data.py", line 411, in save_to_openraster
    return self._save_rect_to_ora(orazip, tmpdir, "layer", path,
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/data.py", line 472, in _save_rect_to_ora
    self._surface.save_as_png(pngpath, *rect, progress=progress, **kwargs)
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/tiledsurface.py", line 651, in save_as_png
    lib.surface.save_as_png(self, filename, *args, **kwargs)
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/surface.py", line 277, in save_as_png
    pngsave = mypaintlib.ProgressivePNGWriter(
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/mypaintlib.py", line 777, in __init__
    _mypaintlib.ProgressivePNGWriter_swiginit(self, _mypaintlib.new_ProgressivePNGWriter(file, w, h, has_alpha, save_srgb_chunks))
SystemError: <built-in function new_ProgressivePNGWriter> returned a result with an error set
TypeError: file arg has no file descriptor or FILE* associated with it

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/document.py", line 591, in _autosave_countdown_cb
    self._queue_autosave_writes()
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/document.py", line 630, in _queue_autosave_writes
    root_elem = self.layer_stack.queue_autosave(
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/tree.py", line 2565, in queue_autosave
    stack_elem = super(RootLayerStack, self).queue_autosave(
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/group.py", line 554, in queue_autosave
    layer_elem = layer.queue_autosave(
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/group.py", line 554, in queue_autosave
    layer_elem = layer.queue_autosave(
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/data.py", line 1682, in queue_autosave
    elem = super(StrokemappedPaintingLayer, self).queue_autosave(
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/data.py", line 435, in queue_autosave
    task = tiledsurface.PNGFileUpdateTask(
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/tiledsurface.py", line 1287, in __init__
    self._png_writer = mypaintlib.ProgressivePNGWriter(
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/mypaintlib.py", line 777, in __init__
    _mypaintlib.ProgressivePNGWriter_swiginit(self, _mypaintlib.new_ProgressivePNGWriter(file, w, h, has_alpha, save_srgb_chunks))
SystemError: <built-in function new_ProgressivePNGWriter> returned a result with an error set

```

``` python
Mypaint version: 2.0.1+git.478280f2
System information: Windows-10-10.0.19041-SP0
Using: Python 3.8.3, GTK 3.24.20, GdkPixbuf 2.40.0, Cairo 1.16.0, GLib 2.64.1
Traceback (most recent call last):
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/gui/filehandling.py", line 1170, save_cb(self=<gui.filehandling.FileHandler object>, action=<Gtk.Action object at 0x00000000123afec0 (GtkAction at 0x0000000011576a00)>)
            else:
                self.save_file(self.filename)
  variables: {'self.save_file': ('local', <bound method FileHandler.save_file of <gui.filehandling.FileHandler object at 0x0000000012399d60>>), 'self.filename': ('local', 'C:/Users/35191/Desktop/deub.ora')}
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/gui/filehandling.py", line 926, save_file(self=<gui.filehandling.FileHandler object>, filename='C:/Users/35191/Desktop/deub.ora', export=False, **options={})
            """
            thumbnail_pixbuf = self._save_doc_to_file(
                filename,
  variables: {'thumbnail_pixbuf': (None, []), 'self._save_doc_to_file': ('local', <bound method FileHandler._save_doc_to_file of <gui.filehandling.FileHandler object at 0x0000000012399d60>>), 'filename': ('local', 'C:/Users/35191/Desktop/deub.ora'), 'self.doc': ('local', <gui.document.Document object at 0x00000000124cae50>), 'export': ('local', False), 'use_statusbar': (None, []), 'options': ('local', {})}
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/gui/filehandling.py", line 1001, _save_doc_to_file(self=<gui.filehandling.FileHandler object>, filename='C:/Users/35191/Desktop/deub.ora', doc=<gui.document.Document object>, export=False, use_statusbar=True, **options={'save_srgb_chunks': True})
            thumbnail_pixbuf = ioui.call(doc.model.save, filename, **options)
            self.lastsavefailed = not ioui.success
  variables: {'thumbnail_pixbuf': ('local', None), 'ioui.call': ('local', <bound method _IOProgressUI.call of <gui.filehandling._IOProgressUI object at 0x0000000015d51970>>), 'doc.model.save': ('local', <bound method Document.save of <Document nlayers=92 bbox=Rect(-64, -1472, 3136, 3072) paintonly=False>>), 'filename': ('local', 'C:/Users/35191/Desktop/deub.ora'), 'options': ('local', {'save_srgb_chunks': True})}
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/gui/widgets.py", line 182, wrapper(self=<gui.filehandling._IOProgressUI object>, *args=(<bound method Document.save of <Document nlayers...ox=Rect(-64, -1472, 3136, 3072) paintonly=False>>, 'C:/Users/35191/Desktop/deub.ora'), **kwargs={'save_srgb_chunks': True})
            try:
                return func(self, *args, **kwargs)
                # gtk main loop may be called in here...
  variables: {'func': ('local', <function _IOProgressUI.call at 0x00000000120044c0>), 'self': ('local', <gui.filehandling._IOProgressUI object at 0x0000000015d51970>), 'args': ('local', (<bound method Document.save of <Document nlayers=92 bbox=Rect(-64, -1472, 3136, 3072) paintonly=False>>, 'C:/Users/35191/Desktop/deub.ora')), 'kwargs': ('local', {'save_srgb_chunks': True})}
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/gui/filehandling.py", line 319, call(self=<gui.filehandling._IOProgressUI object>, func=<bound method Document.save of <Document nlayers...ox=Rect(-64, -1472, 3136, 3072) paintonly=False>>, *args=('C:/Users/35191/Desktop/deub.ora',), **kwargs={'progress': <Progress 51.7/100>, 'save_srgb_chunks': True})
            try:
                result = func(*args, **kwargs)
            except (FileHandlingError, AllocationError, MemoryError) as e:
  variables: {'result': ('local', None), 'func': ('local', <bound method Document.save of <Document nlayers=92 bbox=Rect(-64, -1472, 3136, 3072) paintonly=False>>), 'args': ('local', ('C:/Users/35191/Desktop/deub.ora',)), 'kwargs': ('local', {'save_srgb_chunks': True, 'progress': <Progress 51.7/100>})}
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/document.py", line 1441, save(self=<Document nlayers=92 bbox=Rect(-64, -1472, 3136, 3072) paintonly=False>, filename='C:/Users/35191/Desktop/deub.ora', **kwargs={'progress': <Progress 51.7/100>, 'save_srgb_chunks': True})
            try:
                result = save(filename, **kwargs)
            except GObject.GError as e:
  variables: {'result': ('local', None), 'save': ('local', <bound method Document.save_ora of <Document nlayers=92 bbox=Rect(-64, -1472, 3136, 3072) paintonly=False>>), 'filename': ('local', 'C:/Users/35191/Desktop/deub.ora'), 'kwargs': ('local', {'save_srgb_chunks': True, 'progress': <Progress 51.7/100>})}
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/fileutils.py", line 115, _wrapped_save_method(self=<Document nlayers=92 bbox=Rect(-64, -1472, 3136, 3072) paintonly=False>, filename='C:/Users/35191/Desktop/deub.ora', *args=(), **kwds={'progress': <Progress 51.7/100>, 'save_srgb_chunks': True})
                    logger.error("cleanup: failed to remove temp path too")
                raise ex
            if not os.path.exists(temp_path):
  variables: {'ex': (None, [])}
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/fileutils.py", line 108, _wrapped_save_method(self=<Document nlayers=92 bbox=Rect(-64, -1472, 3136, 3072) paintonly=False>, filename='C:/Users/35191/Desktop/deub.ora', *args=(), **kwds={'progress': <Progress 51.7/100>, 'save_srgb_chunks': True})
                logger.debug("Writing to temp path %r", temp_path)
                save_result = save_method(self, temp_path, *args, **kwds)
            except Exception as ex:
  variables: {'save_result': (None, []), 'save_method': ('local', <function Document.save_ora at 0x0000000011d09a60>), 'self': ('local', <Document nlayers=92 bbox=Rect(-64, -1472, 3136, 3072) paintonly=False>), 'temp_path': ('local', 'C:/Users/35191/Desktop/.tmpsave.deub.ora'), 'args': ('local', ()), 'kwds': ('local', {'save_srgb_chunks': True, 'progress': <Progress 51.7/100>})}
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/document.py", line 1776, save_ora(self=<Document nlayers=92 bbox=Rect(-64, -1472, 3136, 3072) paintonly=False>, filename='C:/Users/35191/Desktop/.tmpsave.deub.ora', options=None, **kwargs={'progress': <Progress 51.7/100>, 'save_srgb_chunks': True})
            self.sync_pending_changes(flush=True)
            thumbnail = _save_layers_to_new_orazip(
                self.layer_stack,
  variables: {'thumbnail': (None, []), '_save_layers_to_new_orazip': ('global', <function _save_layers_to_new_orazip at 0x0000000011b39dc0>), 'self.layer_stack': ('local', <RootLayerStack len=8 'Raiz'>), 'filename': ('local', 'C:/Users/35191/Desktop/.tmpsave.deub.ora'), 'bbox': (None, []), 'tuple': ('builtin', <class 'tuple'>), 'self.get_user_bbox': ('local', <bound method Document.get_user_bbox of <Document nlayers=92 bbox=Rect(-64, -1472, 3136, 3072) paintonly=False>>), 'xres': (None, []), 'self._xres': ('local', <Document nlayers=92 bbox=Rect(-64, -1472, 3136, 3072) paintonly=False>), 'yres': (None, []), 'self._yres': ('local', <Document nlayers=92 bbox=Rect(-64, -1472, 3136, 3072) paintonly=False>), 'frame_active': (None, []), 'self.frame_enabled': ('local', True), 'settings': (None, []), 'dict': ('builtin', <class 'dict'>), 'self._settings': ('local', ObservableDict({'layervis': {'views': [], 'active_view': None, 'layer_views': [[[0], []], [[0, 0], []], [[0, 1], []], [[0, 2], []], [[0, 3], []], [[0, 4], []], [[0, 5], []], [[0, 6], []], [[0, 7], []], [[1], []], [[1, 0], []], [[1, 1], []], [[2], []], [[2, 0], []], [[2, 1], []], [[2, 2], []], [[2, 3], []], [[2, 4], []], [[3], []], [[3, 0], []], [[3, 1], []], [[3, 2], []], [[3, 3], []], [[3, 4], []], [[3, 5], []], [[3, 6], []], [[3, 7], []], [[3, 8], []], [[3, 9], []], [[3, 10], []], [[3, 11], []], [[3, 12], []], [[3, 13], []], [[3, 14], []], [[3, 15], []], [[3, 16], []], [[4], []], [[4, 0], []], [[4, 1], []], [[4, 2], []], [[4, 3], []], [[5], []], [[5, 0], []], [[5, 1], []], [[5, 2], []], [[5, 3], []], [[5, 4], []], [[5, 5], []], [[5, 6], []], [[5, 7], []], [[5, 8], []], [[5, 9], []], [[5, 10], []], [[5, 11], []], [[5, 12], []], [[5, 13], []], [[5, 14], []], [[5, 15], []], [[5, 16], []], [[5, 17], []], [[5, 18], []], [[5, 19], []], [[5, 20], []], [[5, 21], []], [[5, 22], []], [[5, 23], []], [[5, 24], []], [[5, 25], []], [[5, 26], []], [[5, 27], []], [[5, 28], []], [[5, 29], []], [[5, 30], []], [[5, 31], []], [[5, 32], []], [[5, 33], []], [[5, 34], []], [[5, 35], []], [[5, 36], []], [[5, 37], []], [[5, 38], []], [[5, 39], []], [[5, 40], []], [[5, 41], []], [[6], []], [[6, 0], []], [[6, 1], []], [[6, 2], []], [[6, 3], []], [[6, 4], []], [[6, 5], []], [[7], []]]}})), 'kwargs': ('local', {'save_srgb_chunks': True, 'progress': <Progress 51.7/100>})}
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/document.py", line 2085, _save_layers_to_new_orazip(root_stack=<RootLayerStack len=8 'Raiz'>, filename='C:/Users/35191/Desktop/.tmpsave.deub.ora', bbox=(0, 0, 3000, 1552), xres=None, yres=None, frame_active=True, progress=<Progress 51.7/100>, settings={'layervis': {'active_view': None, 'layer_views': [[[0], []], [[0, 0], []], [[0, 1], []], [[0, 2], []], [[0, 3], []], [[0, 4], []], [[0, 5], []], [[0, 6], []], [[0, 7], []], [[1], []], [[1, 0], []], [[1, 1], []], [[2], []], [[2, 0], []], [[2, 1], []], [[2, 2], []], [[2, 3], []], [[2, 4], []], [[3], []], [[3, 0], []], ...], 'views': []}}, **kwargs={'save_srgb_chunks': True})
        root_stack_path = ()
        root_stack_elem = root_stack.save_to_openraster(
            orazip, tempdir, root_stack_path,
  variables: {'root_stack_elem': (None, []), 'root_stack.save_to_openraster': ('local', <bound method RootLayerStack.save_to_openraster of <RootLayerStack len=8 'Raiz'>>), 'orazip': ('local', <zipfile.ZipFile filename='C:/Users/35191/Desktop/.tmpsave.deub.ora' mode='w'>), 'tempdir': ('local', 'C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint'), 'root_stack_path': ('local', ()), 'data_bbox': ('local', (-64, -1472, 3136, 3072)), 'bbox': ('local', (0, 0, 3000, 1552)), 'progress': ('local', <Progress 51.7/100>), 'progress.open': ('local', <bound method Progress.open of <Progress 51.7/100>>), 'kwargs': ('local', {'save_srgb_chunks': True})}
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/tree.py", line 2541, save_to_openraster(self=<RootLayerStack len=8 'Raiz'>, orazip=<zipfile.ZipFile filename='C:/Users/35191/Desktop/.tmpsave.deub.ora' mode='w'>, tmpdir='C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint', path=(), canvas_bbox=(-64, -1472, 3136, 3072), frame_bbox=(0, 0, 3000, 1552), progress=<Progress 5.7/10>, **kwargs={'save_srgb_chunks': True})
            # First 90%: save the stack contents normally.
            stack_elem = super(RootLayerStack, self).save_to_openraster(
                orazip, tmpdir, path, canvas_bbox,
  variables: {'stack_elem': (None, []), 'super': ('builtin', <class 'super'>), 'RootLayerStack': ('global', <class 'lib.layer.tree.RootLayerStack'>), 'self': ('local', <RootLayerStack len=8 'Raiz'>), 'save_to_openraster': (None, []), 'orazip': ('local', <zipfile.ZipFile filename='C:/Users/35191/Desktop/.tmpsave.deub.ora' mode='w'>), 'tmpdir': ('local', 'C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint'), 'path': ('local', ()), 'canvas_bbox': ('local', (-64, -1472, 3136, 3072)), 'frame_bbox': ('local', (0, 0, 3000, 1552)), 'progress': ('local', <Progress 5.7/10>), 'progress.open': ('local', <bound method Progress.open of <Progress 5.7/10>>), 'kwargs': ('local', {'save_srgb_chunks': True})}
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/group.py", line 527, save_to_openraster(self=<RootLayerStack len=8 'Raiz'>, orazip=<zipfile.ZipFile filename='C:/Users/35191/Desktop/.tmpsave.deub.ora' mode='w'>, tmpdir='C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint', path=(), canvas_bbox=(-64, -1472, 3136, 3072), frame_bbox=(0, 0, 3000, 1552), progress=<Progress 5.7/9>, **kwargs={'save_srgb_chunks': True})
                layer_path = tuple(list(path) + [layer_idx])
                layer_elem = layer.save_to_openraster(orazip, tmpdir, layer_path,
                                                      canvas_bbox, frame_bbox,
  variables: {'layer_elem': ('local', <Element 'stack' at 0x0000000015bbdc20>), 'layer.save_to_openraster': ('local', <bound method LayerStack.save_to_openraster of <LayerStack len=42 'Grupo 1'>>), 'orazip': ('local', <zipfile.ZipFile filename='C:/Users/35191/Desktop/.tmpsave.deub.ora' mode='w'>), 'tmpdir': ('local', 'C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint'), 'layer_path': ('local', (5,)), 'canvas_bbox': ('local', (-64, -1472, 3136, 3072)), 'frame_bbox': ('local', (0, 0, 3000, 1552)), 'progress': ('local', <Progress 5.7/9>), 'progress.open': ('local', <bound method Progress.open of <Progress 5.7/9>>), 'kwargs': ('local', {'save_srgb_chunks': True})}
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/group.py", line 527, save_to_openraster(self=<LayerStack len=42 'Grupo 1'>, orazip=<zipfile.ZipFile filename='C:/Users/35191/Desktop/.tmpsave.deub.ora' mode='w'>, tmpdir='C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint', path=(5,), canvas_bbox=(-64, -1472, 3136, 3072), frame_bbox=(0, 0, 3000, 1552), progress=<Progress 32.0/43>, **kwargs={'save_srgb_chunks': True})
                layer_path = tuple(list(path) + [layer_idx])
                layer_elem = layer.save_to_openraster(orazip, tmpdir, layer_path,
                                                      canvas_bbox, frame_bbox,
  variables: {'layer_elem': ('local', <Element 'layer' at 0x0000000015d62400>), 'layer.save_to_openraster': ('local', <bound method StrokemappedPaintingLayer.save_to_openraster of <PaintingLayer 'Camada 16'>>), 'orazip': ('local', <zipfile.ZipFile filename='C:/Users/35191/Desktop/.tmpsave.deub.ora' mode='w'>), 'tmpdir': ('local', 'C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint'), 'layer_path': ('local', (5, 32)), 'canvas_bbox': ('local', (-64, -1472, 3136, 3072)), 'frame_bbox': ('local', (0, 0, 3000, 1552)), 'progress': ('local', <Progress 32.0/43>), 'progress.open': ('local', <bound method Progress.open of <Progress 32.0/43>>), 'kwargs': ('local', {'save_srgb_chunks': True})}
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/data.py", line 1642, save_to_openraster(self=<PaintingLayer 'Camada 16'>, orazip=<zipfile.ZipFile filename='C:/Users/35191/Desktop/.tmpsave.deub.ora' mode='w'>, tmpdir='C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint', path=(5, 32), canvas_bbox=(-64, -1472, 3136, 3072), frame_bbox=(0, 0, 3000, 1552), **kwargs={'progress': <Progress 0.0/6>, 'save_srgb_chunks': True})
            elem = super(StrokemappedPaintingLayer, self).save_to_openraster(
                orazip, tmpdir, path,
  variables: {'elem': (None, []), 'super': ('builtin', <class 'super'>), 'StrokemappedPaintingLayer': ('global', <class 'lib.layer.data.StrokemappedPaintingLayer'>), 'self': ('local', <PaintingLayer 'Camada 16'>), 'save_to_openraster': (None, []), 'orazip': ('local', <zipfile.ZipFile filename='C:/Users/35191/Desktop/.tmpsave.deub.ora' mode='w'>), 'tmpdir': ('local', 'C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint'), 'path': ('local', (5, 32)), 'canvas_bbox': ('local', (-64, -1472, 3136, 3072)), 'frame_bbox': ('local', (0, 0, 3000, 1552)), 'kwargs': ('local', {'progress': <Progress 0.0/6>, 'save_srgb_chunks': True})}
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/data.py", line 411, save_to_openraster(self=<PaintingLayer 'Camada 16'>, orazip=<zipfile.ZipFile filename='C:/Users/35191/Desktop/.tmpsave.deub.ora' mode='w'>, tmpdir='C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint', path=(5, 32), canvas_bbox=(-64, -1472, 3136, 3072), frame_bbox=(0, 0, 3000, 1552), **kwargs={'progress': <Progress 0.0/6>, 'save_srgb_chunks': True})
            rect = self.get_bbox()
            return self._save_rect_to_ora(orazip, tmpdir, "layer", path,
                                          frame_bbox, rect, **kwargs)
  variables: {'self._save_rect_to_ora': ('local', <bound method SurfaceBackedLayer._save_rect_to_ora of <PaintingLayer 'Camada 16'>>), 'orazip': ('local', <zipfile.ZipFile filename='C:/Users/35191/Desktop/.tmpsave.deub.ora' mode='w'>), 'tmpdir': ('local', 'C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint'), 'path': ('local', (5, 32)), 'frame_bbox': ('local', (0, 0, 3000, 1552)), 'rect': ('local', Rect(2048, 704, 128, 320)), 'kwargs': ('local', {'progress': <Progress 0.0/6>, 'save_srgb_chunks': True})}
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/layer/data.py", line 472, _save_rect_to_ora(self=<PaintingLayer 'Camada 16'>, orazip=<zipfile.ZipFile filename='C:/Users/35191/Desktop/.tmpsave.deub.ora' mode='w'>, tmpdir='C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint', prefix='layer', path=(5, 32), frame_bbox=(0, 0, 3000, 1552), rect=Rect(2048, 704, 128, 320), progress=<Progress 0.0/6>, **kwargs={'save_srgb_chunks': True})
            t0 = time.time()
            self._surface.save_as_png(pngpath, *rect, progress=progress, **kwargs)
            t1 = time.time()
  variables: {'self._surface.save_as_png': ('local', <bound method MyPaintSurface.save_as_png of <lib.tiledsurface.MyPaintSurface object at 0x0000000019db7ee0>>), 'pngpath': ('local', 'C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint/layer-05-32.png'), 'rect': ('local', Rect(2048, 704, 128, 320)), 'progress': ('local', <Progress 0.0/6>), 'kwargs': ('local', {'save_srgb_chunks': True})}
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/tiledsurface.py", line 651, save_as_png(self=<lib.tiledsurface.MyPaintSurface object>, filename='C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint/layer-05-32.png', *args=(2048, 704, 128, 320), **kwargs={'alpha': True, 'progress': <Progress 0.0/6>, 'save_srgb_chunks': True})
                kwargs['single_tile_pattern'] = True
            lib.surface.save_as_png(self, filename, *args, **kwargs)
  variables: {'lib.surface.save_as_png': ('global', <function save_as_png at 0x0000000004302550>), 'self': ('local', <lib.tiledsurface.MyPaintSurface object at 0x0000000019db7ee0>), 'filename': ('local', 'C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint/layer-05-32.png'), 'args': ('local', (2048, 704, 128, 320)), 'kwargs': ('local', {'progress': <Progress 0.0/6>, 'save_srgb_chunks': True, 'alpha': True})}
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/surface.py", line 277, save_as_png(surface=<lib.tiledsurface.MyPaintSurface object>, filename='C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint/layer-05-32.png', *rect=(2048, 704, 128, 320), **kwargs={})
            with open(filename, "wb") as writer_fp:
                pngsave = mypaintlib.ProgressivePNGWriter(
                    writer_fp,
  variables: {'pngsave': (None, []), 'mypaintlib.ProgressivePNGWriter': ('global', <class 'lib.mypaintlib.ProgressivePNGWriter'>), 'writer_fp': ('local', <_io.BufferedWriter name='C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint/layer-05-32.png'>), 'w': ('local', 128), 'h': ('local', 320), 'alpha': ('local', True), 'save_srgb_chunks': ('local', True)}
  File "C:/Program Files/mypaint-w64/mingw64/lib/mypaint/lib/mypaintlib.py", line 777, __init__(self=<lib.mypaintlib.ProgressivePNGWriter;  >, file=<_io.BufferedWriter name='C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint/layer-05-32.png'>, w=128, h=320, has_alpha=True, save_srgb_chunks=True)
        def __init__(self, file, w, h, has_alpha, save_srgb_chunks):
            _mypaintlib.ProgressivePNGWriter_swiginit(self, _mypaintlib.new_ProgressivePNGWriter(file, w, h, has_alpha, save_srgb_chunks))
  variables: {'_mypaintlib.ProgressivePNGWriter_swiginit': ('global', <built-in function ProgressivePNGWriter_swiginit>), 'self': ('local', <lib.mypaintlib.ProgressivePNGWriter;  >), '_mypaintlib.new_ProgressivePNGWriter': ('global', <built-in function new_ProgressivePNGWriter>), 'file': ('local', <_io.BufferedWriter name='C:/Users/35191/AppData/Local/Temp/save77inbbwqmypaint/layer-05-32.png'>), 'w': ('local', 128), 'h': ('local', 320), 'has_alpha': ('local', True), 'save_srgb_chunks': ('local', True)}
SystemError: <built-in function new_ProgressivePNGWriter> returned a result with an error set
```

**Comment by AesaraB** [comment]
Possibly related to #1155

**Comment by AesaraB** [comment]
Possibly also related to #1125
