### ISSUE TITLE
Can't drag and drop image to MyPaint

### ISSUE THREAD

**Issue by FMHR78** [mypaint/mypaint#1199]
Hello.
I work with Ubuntu-Studio and Mypaint. 
When I drag and drop an image file from the Dolphin file manager, then I get an error message from MyPaint.

MyPaint version: [2.0.1+gitexport.478280f]
Operating system: [Ubuntu-Studio 22.04.2]
Desktop environment: [KDE Plasma 5.24.4]
File Manager: [Dolphin 4:21.12.3-0ubuntu1]

#### Steps to reproduce

1. Start MyPaint
2. Add a new layer
3. drag and drop an image from file manager

#### Backtraces or error messages

````python
Mypaint version: 2.0.1+gitexport.478280f
System information: Linux-5.19.0-1023-lowlatency-x86_64-with-glibc2.35
Using: Python 3.10.6, GTK 3.24.33, GdkPixbuf 2.42.8, Cairo 1.16.0, GLib 2.71.3
Traceback (most recent call last):
  File "/usr/lib/mypaint/gui/drawwindow.py", line 290, _drag_data_received_cb(self=<drawwindow.DrawWindow object at 0x7f7e6c270c00 (MyPaintDrawWindow at 0x55813ad882a0)>, widget=<drawwindow.DrawWindow object at 0x7f7e6c270c00 (MyPaintDrawWindow at 0x55813ad882a0)>, context=<GdkX11.X11DragContext object at 0x7f7e6987bf00 (GdkX11DragContext at 0x55813b132eb0)>, x=929, y=576, data=<Gtk.SelectionData object at 0x7f7e68346980 (GtkSelectionData at 0x7ffda2131e40)>, info=1, time=5785712)
                # working file.
                uri = rawdata.split("\r\n")[0]
                file_path, _h = lib.glib.filename_from_uri(uri)
  variables: {'uri': (None, []), 'rawdata.split': ('local', <built-in method split of bytes object at 0x7f7e69917590>)}
TypeError: a bytes-like object is required, not 'str'
```
The Terminal says:
$ mypaint
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix '/usr'
INFO: gui.main: No locale setting found, using system locale
INFO: lib.i18n: POSIX: LANG='en_US.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE='en_US:es'
INFO: lib.i18n: Value of LANGUAGE after cleanup: 'en_US:C:es'

(mypaint:31958): Gtk-WARNING **: 11:05:48.581: Theme directory places/128 of theme ubuntustudio has no size field


(mypaint:31958): Gtk-WARNING **: 11:05:48.581: Theme directory places/scalable of theme ubuntustudio has no size field

INFO: gui.compatibility: Setting mode to 2.x (standard)
INFO: gui.compatibility: Setting default layer type to Pigment
INFO: gui.device: New device 'XP-PEN ERASER Eraser (0)' (GDK_SOURCE_ERASER, axes:5, class=X11DeviceXI2, vendor='28bd', product='0002')
INFO: gui.device: New device 'XP-PEN STYLUS Pen (0)' (GDK_SOURCE_PEN, axes:6, class=X11DeviceXI2, vendor='28bd', product='0002')
INFO: gui.device: New device 'UGTABLET 10 inch PenTablet Mouse' (GDK_SOURCE_PEN, axes:4, class=X11DeviceXI2, vendor='28bd', product='0905')
INFO: gui.device: New device 'XP-PEN MOUSE' (GDK_SOURCE_PEN, axes:4, class=X11DeviceXI2, vendor='28bd', product='0002')
INFO: gui.device: New device 'USB usb keyboard Consumer Control' (GDK_SOURCE_MOUSE, axes:4, class=X11DeviceXI2, vendor='c0f4', product='01b0')
INFO: gui.device: New device 'Logitech K230' (GDK_SOURCE_MOUSE, axes:4, class=X11DeviceXI2, vendor='046d', product='400d')
INFO: gui.device: New device 'Logitech G203 LIGHTSYNC Gaming Mouse Keyboard' (GDK_SOURCE_MOUSE, axes:4, class=X11DeviceXI2, vendor='046d', product='c092')
INFO: gui.device: New device 'Logitech G203 LIGHTSYNC Gaming Mouse' (GDK_SOURCE_MOUSE, axes:4, class=X11DeviceXI2, vendor='046d', product='c092')
INFO: gui.device: New device 'Virtual core XTEST pointer' (GDK_SOURCE_MOUSE, axes:2, class=X11DeviceXI2, vendor=None, product=None)
INFO: gui.document: Initialized background from '/usr/share/mypaint/backgrounds/mrmamurk/mamurk_e_1.png'
WARNING: gui.keyboard: Ignoring keybinding for '<Actions>/BrushModifierActions/BlendModeMenu'
INFO: gui.brushmanager: Switching default pigment setting to On
INFO: lib.document: load_ora: '/home/administardor/.local/share/mypaint/scratchpads/autosave.ora'
INFO: lib.document: 0.029s load_ora total
INFO: gui.filehandling: Loaded scratchpad from '/home/administardor/.local/share/mypaint/scratchpads/autosave.ora'
INFO: gui.compatibility: Setting default layer type to Pigment
Traceback (most recent call last):
  File "/usr/lib/mypaint/gui/drawwindow.py", line 290, in _drag_data_received_cb
    uri = rawdata.split("\r\n")[0]
TypeError: a bytes-like object is required, not 'str'

Is there a way to fix this issue?

**Comment by cortexer** [comment]
Thank you for your bug report.
This problem is already fixed in commit 66b2ba98bd953afa73d0d6ac71040b14a4ea266b.
Your problem should be solved with release of the next MyPaint version.
