### ISSUE TITLE
Mac OS X 10.6.8 problems with Saving Files, Wacom Tablet and Accessing MP Tools

### ISSUE THREAD

**Issue by Pinzgauer** [mypaint/mypaint#120]
Hi,

Regarding my 5 minute old MP download, eraser and various other functions do not work, MP informed me of a "Programming Error" 15 min. into my efforts to get things to work when I tried to save a rough sketch for my machinist:

```
Traceback (most recent call last):
  File "/opt/mypaint/share/mypaint/gui/filehandling.py", line 449, save_as_cb(self=<gui.filehandling.FileHandler object>, action=<gtk.Action object at 0x114a66960 (GtkAction at 0x100d03300)>)
                # Do not change working file
                self.save_as_dialog(self.save_file, suggested_filename = current_filename, export=True)
            else:
  variables: {'self.save_file': ('local', <bound method FileHandler.wrapper of <gui.filehandling.FileHandler object at 0x114a48d10>>), 'self.save_as_dialog': ('local', <bound method FileHandler.save_as_dialog of <gui.filehandling.FileHandler object at 0x114a48d10>>), 'current_filename': ('local', u'/Users/michaelbarna/Documents/Airgun/Ernie Olson Picatinny Bottom Rail Suggestion.ora'), 'export': (None, []), 'suggested_filename': (None, []), 'True': ('builtin', True)}
  File "/opt/mypaint/share/mypaint/gui/filehandling.py", line 509, save_as_dialog(self=<gui.filehandling.FileHandler object>, save_method_reference=<bound method FileHandler.wrapper of <gui.filehandling.FileHandler object>>, suggested_filename=u'/Users/michaelbarna/Documents/Airgun/Ernie Olson Picatinny Bottom Rail Suggestion.ora', start_in_folder=None, export=True, **options={'quality': 90})
                            # Do not change working file
                            save_method_reference(filename, True, **options)
                        else:
  variables: {'True': ('builtin', True), 'options': ('local', {'quality': 90}), 'save_method_reference': ('local', <bound method FileHandler.wrapper of <gui.filehandling.FileHandler object at 0x114a48d10>>), 'filename': ('local', u'/Users/michaelbarna/Documents/Airgun/Ernie Olson Picatinny Bottom Rail Suggestion.jpg')}
  File "/opt/mypaint/share/mypaint/gui/drawwindow.py", line 46, wrapper(self=<gui.filehandling.FileHandler object>, *args=(u'/Users/michaelbarna/Documents/Airgun/Ernie Olson Picatinny Bottom Rail Suggestion.jpg', True), **kwargs={'quality': 90})
            try:
                func(self, *args, **kwargs)
                # gtk main loop may be called in here...
  variables: {'self': ('local', <gui.filehandling.FileHandler object at 0x114a48d10>), 'args': ('local', (u'/Users/michaelbarna/Documents/Airgun/Ernie Olson Picatinny Bottom Rail Suggestion.jpg', True)), 'func': ('local', <function save_file at 0x1148796e0>), 'kwargs': ('local', {'quality': 90})}
  File "/opt/mypaint/share/mypaint/gui/filehandling.py", line 292, save_file(self=<gui.filehandling.FileHandler object>, filename=u'/Users/michaelbarna/Documents/Airgun/Ernie Olson Picatinny Bottom Rail Suggestion.jpg', export=True, **options={'quality': 90})
                thumbnail_pixbuf = self.doc.model.render_thumbnail()
            helpers.freedesktop_thumbnail(filename, thumbnail_pixbuf)
  variables: {'thumbnail_pixbuf': ('local', <gtk.gdk.Pixbuf object at 0x1159b3f00 (GdkPixbuf at 0x100ce5ad0)>), 'helpers.freedesktop_thumbnail': ('global', <function freedesktop_thumbnail at 0x102a6f1b8>), 'filename': ('local', u'/Users/michaelbarna/Documents/Airgun/Ernie Olson Picatinny Bottom Rail Suggestion.jpg')}
  File "/opt/mypaint/share/mypaint/lib/helpers.py", line 152, freedesktop_thumbnail(filename=u'/Users/michaelbarna/Documents/Airgun/Ernie Olson Picatinny Bottom Rail Suggestion.jpg', pixbuf=<gtk.gdk.Pixbuf object at 0x1159b3f00 (GdkPixbuf at 0x100ce5ad0)>)
        file_mtime = str(int(os.stat(filename).st_mtime))
  variables: {'st_mtime': (None, []), 'int': ('builtin', <type 'int'>), 'file_mtime': (None, []), 'os.stat': ('global', <built-in function stat>), 'filename': ('local', u'/Users/michaelbarna/Documents/Airgun/Ernie Olson Picatinny Bottom Rail Suggestion.jpg'), 'str': ('builtin', <type 'str'>)}
OSError: [Errno 2] No such file or directory: '/Users/michaelbarna/Documents/Airgun/Ernie Olson Picatinny Bottom Rail Suggestion.jpg'
```

**Comment by achadwick** [comment]
I suspect this is a dup of #202, and as such may be resolved by now. Could you follow up there please @Pinzgauer, and let us know if a new MacPorts version has fixed the issue for you?

Closing in favour of #202
