### ISSUE TITLE
MyPaint flatpak version fails to start

### ISSUE THREAD

**Issue by Flashwalker** [mypaint/mypaint#1202]
#### Description of the problem

MyPaint flatpak version fails to start.

#### Basic system details

MyPaint version: 

```
$ flatpak info org.mypaint.MyPaint

MyPaint - Painting program for digital artists

          ID: org.mypaint.MyPaint
         Ref: app/org.mypaint.MyPaint/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2.0.1
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 37.7 MB
     Runtime: org.gnome.Platform/x86_64/42
         Sdk: org.gnome.Sdk/x86_64/42

      Commit: 1df381ac36cc96abcabf0f1df305bc434db2c533bf6b863bfe07471d8f33a321
      Parent: a740f6318033513cf0688f3f366bb3e20a5e5520c19a0658a7b94a875261d8e6
     Subject: Update to GNOME 42 (7fe4a97b)
        Date: 2022-09-02 04:23:53 +0000
```
Operating system: Ubuntu 22.04
Desktop environment: Xfce

#### Steps to reproduce

1. Start Flatpak MyPaint

#### Backtraces or error messages

```
$ flatpak run --branch=stable --arch=x86_64 --command=mypaint --file-forwarding org.mypaint.MyPaint

Traceback (most recent call last):
  File "/app/bin/mypaint", line 35, in <module>
    import re
  File "/usr/lib/python3.9/re.py", line 127, in <module>
    import functools
  File "/usr/lib/python3.9/functools.py", line 18, in <module>
    from collections import namedtuple
  File "/usr/lib/python3.9/collections/__init__.py", line 37, in <module>
    from operator import eq as _eq
ModuleNotFoundError: No module named 'operator'
```

**Comment by AesaraB** [comment]
Hi, I'm a new developer for MyPaint.

Are you still available to debug this issue? Does it still occur?

**Comment by Flashwalker** [comment]
@AesaraB Hi,
I'll test the fresh package in a few days
