### ISSUE TITLE
MyPaint version: 2.0.1 not opening after install on raspberry pi

### ISSUE THREAD

**Issue by krishauga** [mypaint/mypaint#1204]
#### Description of the problem
#mypaint is installing with the following command:
raspberrypi:~ $ sudo apt install mypaint

#However it is not running when started:
raspberrypi:~ $ mypaint
I

#### Basic system details

MyPaint version: MyPaint version: 2.0.1-9
Operating system: Debian GNU/Linux 12 (bookworm)
Desktop environment: Default for Raspberry Pi

#### Steps to reproduce

1. Install mypaint: raspberrypi:~ $ sudo apt install mypaint 
2. start mypaint from terminal: raspberrypi:~ $ mypaint

#### Backtraces or error messages

```
NFO: mypaint: Installation layout: conventional POSIX-like structure with prefix '/usr'
WARNING: gui.userconfig: Failed to load settings file: /home/usr/.config/mypaint/settings.json
WARNING: gui.userconfig: Failed to load settings: using defaults
INFO: gui.main: No locale setting found, using system locale
INFO: lib.i18n: POSIX: LANG='nn_NO'
INFO: lib.i18n: POSIX: LANGUAGE='nn_NO'
INFO: lib.i18n: Value of LANGUAGE after cleanup: 'nn_NO'
Traceback (most recent call last):
  File "/usr/bin/mypaint", line 309, in <module>
    main.main(
  File "/usr/lib/mypaint/gui/main.py", line 231, in main
    run()
  File "/usr/lib/mypaint/gui/main.py", line 187, in run
    from gui import application
  File "/usr/lib/mypaint/gui/application.py", line 49, in <module>
    import lib.document
  File "/usr/lib/mypaint/lib/document.py", line 37, in <module>
    import lib.tiledsurface as tiledsurface
  File "/usr/lib/mypaint/lib/tiledsurface.py", line 25, in <module>
    from . import pixbufsurface
  File "/usr/lib/mypaint/lib/pixbufsurface.py", line 37, in <module>
    _POSSIBLE_OOM_USERTEXT = C_(
                             ^^^
  File "/usr/lib/mypaint/lib/gettext.py", line 70, in C_
    result = g_dpgettext2(None, context, msgid)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 13: invalid continuation byte
```

**Comment by krishauga** [comment]
Changing language fixed it LANG=US in PATH
