### ISSUE TITLE
Can not open old ora files

### ISSUE THREAD

**Issue by mitvitaminen** [mypaint/mypaint#1209]
#### Description of the problem
As stated I can not open old ora files, but filemanagers preview shows file just fine.
Pls Note that I can not open the file in gimp either, so I suppose it is some kind of wrong formatted save file. Can I fix this or are my pictures lost? Maybe open the file in text browser and edit it there somehow. Gimp says it is unsupported file format with newest gimp version in arch repo.

#### Basic system details
MyPaint version: 2.0.1+gitexport.478280f
Operating system: Arch Linux 6.6.7-arch1-1
Desktop environment: Gnome Desktop

#### Steps to reproduce
1. Start MyPaint
2. Open File
or
1. Open file from filemanager

#### Backtraces or error messages

```python
Mypaint version: 2.0.1+gitexport.478280f
System information: Linux-6.6.7-arch1-1-x86_64-with-glibc2.38
Using: Python 3.11.6, GTK 3.24.39, GdkPixbuf 2.42.10, Cairo 1.18.0, GLib 2.78.0
Traceback (most recent call last):
  File "/usr/lib/mypaint/gui/tileddrawwidget.py", line 855, _state_changed_cb(self=<tileddrawwidget.CanvasRenderer object at 0x7f4e...ileddrawwidget+CanvasRenderer at 0x55de2563fcf0)>, widget=<tileddrawwidget.CanvasRenderer object at 0x7f4e...ileddrawwidget+CanvasRenderer at 0x55de2563fcf0)>, oldstate=<enum GTK_STATE_INSENSITIVE of type Gtk.StateType>)
                self._insensitive_state_content = None
            self.update_cursor()
  variables: {'self.update_cursor': ('local', <bound method DrawCursorMixin.update_cursor of <tileddrawwidget.CanvasRenderer object at 0x7f4ec3bf3a80 (gui+tileddrawwidget+CanvasRenderer at 0x55de2563fcf0)>>)}
  File "/usr/lib/mypaint/gui/tileddrawwidget.py", line 590, update_cursor(self=<tileddrawwidget.CanvasRenderer object at 0x7f4e...ileddrawwidget+CanvasRenderer at 0x55de2563fcf0)>)
                # Often a red circle with a diagonal bar through it.
                c = Gdk.Cursor.new_for_display(
                    window.get_display(), Gdk.CursorType.CIRCLE)
  variables: {'c': (None, []), 'Gdk.Cursor.new_for_display': ('global', gi.FunctionInfo(new_for_display, bound=<class 'gi.overrides.Gdk.Cursor'>)), 'window.get_display': ('local', gi.FunctionInfo(get_display, bound=<__gi__.GdkWaylandWindow object at 0x7f4eaa568a80 (GdkWaylandWindow at 0x55de26193b00)>)), 'Gdk.CursorType.CIRCLE': ('global', <enum GDK_CIRCLE of type Gdk.CursorType>)}
TypeError: constructor returned NULL
```
See example file: https://file.io/gUejz4XITeVG

**Comment by mitvitaminen** [comment]
I checked and can not open new ora files in gimp either. They are supported by this are they not?

**Comment by mitvitaminen** [comment]
I just tested krita and it can open the file so I suppose it is a mypaint and gimp problem

**Comment by jtojnar** [comment]
Looks like this is because Adwaita icon theme removed `circle` cursor: https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/commit/fb133a3989ee155c24201e30bab7dbc1c7c843fd

**Comment by mitvitaminen** [comment]
Is this seriously fixed? I just tried to open a file with mypaint got an error and opened it in krita which completed successfull so i saved it from within krita as .ora but I still get same error on opening the file 
```python
Mypaint version: 2.0.1+gitexport.478280f
System information: Linux-6.8.1-arch1-1-x86_64-with-glibc2.39
Using: Python 3.11.8, GTK 3.24.41, GdkPixbuf 2.42.10, Cairo 1.18.0, GLib 2.78.0
Traceback (most recent call last):
  File "/usr/lib/mypaint/gui/tileddrawwidget.py", line 855, _state_changed_cb(self=<tileddrawwidget.CanvasRenderer object at 0x7086...ileddrawwidget+CanvasRenderer at 0x61630296b2b0)>, widget=<tileddrawwidget.CanvasRenderer object at 0x7086...ileddrawwidget+CanvasRenderer at 0x61630296b2b0)>, oldstate=<enum GTK_STATE_NORMAL of type Gtk.StateType>)
                self._insensitive_state_content = None
            self.update_cursor()
  variables: {'self.update_cursor': ('local', <bound method DrawCursorMixin.update_cursor of <tileddrawwidget.CanvasRenderer object at 0x7086661ab0c0 (gui+tileddrawwidget+CanvasRenderer at 0x61630296b2b0)>>)}
  File "/usr/lib/mypaint/gui/tileddrawwidget.py", line 590, update_cursor(self=<tileddrawwidget.CanvasRenderer object at 0x7086...ileddrawwidget+CanvasRenderer at 0x61630296b2b0)>)
                # Often a red circle with a diagonal bar through it.
                c = Gdk.Cursor.new_for_display(
                    window.get_display(), Gdk.CursorType.CIRCLE)
  variables: {'c': (None, []), 'Gdk.Cursor.new_for_display': ('global', gi.FunctionInfo(new_for_display, bound=<class 'gi.overrides.Gdk.Cursor'>)), 'window.get_display': ('local', gi.FunctionInfo(get_display, bound=<__gi__.GdkWaylandWindow object at 0x70866448e680 (GdkWaylandWindow at 0x6163034be5f0)>)), 'Gdk.CursorType.CIRCLE': ('global', <enum GDK_CIRCLE of type Gdk.CursorType>)}
TypeError: constructor returned NULL
```
New files I created with mypaint open seamingless
any advice?
greets Chris

**Comment by jtojnar** [comment]
Yes, it is fixed but no new version of MyPaint has been released yet. I will try to do that soon.

**Comment by mitvitaminen** [comment]
thx 4 ure effort two thumbs up and a for bravery facing this shithole we call home alone go take a puppet with you
