### ISSUE TITLE
MacPorts: AttributeError: 'NoneType' object has no attribute 'append_search_path'

### ISSUE THREAD

**Issue by AesaraB** [mypaint/mypaint#1232]
### Description of bug

MyPaint does not start. This bug was copied from the [community forums](https://community.mypaint.app/t/install-mypaint-on-mac-with-m2-chip/4453/3)

### Steps to reproduce

I tried to install via macports ``sudo port install mypaint``.

### Backtraces or error messages

```shell
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix '/opt/local/Library/Frameworks/Python.framework/Versions/3.8'
WARNING: gui.userconfig: Failed to load settings file: /Users/slisakov/.config/mypaint/settings.json
WARNING: gui.userconfig: Failed to load settings: using defaults
INFO: gui.main: No locale setting found, using system locale
INFO: lib.i18n: OSX: imported AppKit.NSLocale OK. Will use for LANG, and for LANGUAGE order.
INFO: lib.i18n: OSX: LANG='en_FR'
INFO: lib.i18n: OSX: LANGUAGE='en_FR:ru_FR'
INFO: lib.i18n: Value of LANGUAGE after cleanup: 'en_FR:C:ru_FR'

(mypaint:2181): Gtk-CRITICAL **: 14:33:00.159: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/opt/local/bin/mypaint", line 309, in <module>
    main.main(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/mypaint/gui/main.py", line 231, in main
    run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/mypaint/gui/main.py", line 195, in run
    app = application.Application(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/mypaint/gui/application.py", line 240, in __init__
    _init_icons(state_dirs.app_icons)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/mypaint/gui/application.py", line 118, in _init_icons
    icon_theme.append_search_path(icon_path)
AttributeError: 'NoneType' object has no attribute 'append_search_path'
```

### MyPaint version

v2.0.1+gitexport.478280f

### Operating System(s)

Mac OS 13.5 (22G74) Ventura

### Code of Conduct

- [X] I acknowledge that my conduct contributes to shaping the community.

**Comment by AesaraB** [comment]
Duplicate of #1154
