### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by aleksejrs** [mypaint/mypaint#1271]
### Description of bug

crashes when drawing

### Steps to reproduce

Draw a stroke

### Backtraces or error messages

```shell
Traceback (most recent call last):
  File "/usr/lib/mypaint/gui/application.py", line 479, in _at_application_start
    self.apply_settings()
  File "/usr/lib/mypaint/gui/application.py", line 511, in apply_settings
    self._apply_pressure_mapping_settings()
  File "/usr/lib/mypaint/gui/application.py", line 590, in _apply_pressure_mapping_settings
    for i, (x, y) in enumerate(p):
           ^^^^^^
TypeError: cannot unpack non-iterable NoneType object
fish: Job 1, 'mypaint' terminated by signal SIGSEGV (Address boundary error)
```

### MyPaint version

2.0.1+gitexport.478280f  (Python 3.12.7, GTK 3.24.43, GdkPixbuf 2.42.12, Cairo 1.18.2, GLib 2.82.2)

### Operating System(s)

Debian testing (not fully updated)

### Desktop Environment (Linux)

Xfce4

### Code of Conduct

- [X] I acknowledge that my conduct contributes to shaping the community.

**Comment by AesaraB** [comment]
Does this only happen with a drawing tablet, or does it also happen with mouse input?

**Comment by aleksejrs** [comment]
Both, same if I disable the second display in Xfce Display settings.
The faster I draw, the sooner it crashes.

**Comment by AesaraB** [comment]
Possibly related issue #927

**Comment by AesaraB** [comment]
This is where things fail

https://github.com/mypaint/mypaint/blob/4a091c9a193c0bb426681568d3487f9bb61f5099/gui/application.py#L594-L610

Reference to https://github.com/mypaint/mypaint/issues/275

**Comment by AesaraB** [comment]
@aleksejrs What does your pressure mapping settings in MyPaint preferences look like?

**Comment by aleksejrs** [comment]
There is an error message on startup now:

```python
Mypaint version: 2.0.1+gitexport.478280f
System information: Linux-6.12.6-amd64-x86_64-with-glibc2.40
Using: Python 3.12.8, GTK 3.24.43, GdkPixbuf 2.42.12, Cairo 1.18.2, GLib 2.82.4
Traceback (most recent call last):
  File "/usr/lib/mypaint/gui/application.py", line 479, _at_application_start(self=<gui.application.Application object>, filenames=[], fullscreen=None)
            self.apply_settings()
            self.drawWindow.present()
  variables: {'self.apply_settings': ('local', <bound method Application.apply_settings of <gui.application.Application object at 0x7f0806627ec0>>)}
  File "/usr/lib/mypaint/gui/application.py", line 511, apply_settings(self=<gui.application.Application object>)
            """
            self._apply_pressure_mapping_settings()
            self._apply_button_mapping_settings()
  variables: {'self._apply_pressure_mapping_settings': ('local', <bound method Application._apply_pressure_mapping_settings of <gui.application.Application object at 0x7f0806627ec0>>)}
  File "/usr/lib/mypaint/gui/application.py", line 590, _apply_pressure_mapping_settings(self=<gui.application.Application object>)
                m.set_n(0, len(p))
                for i, (x, y) in enumerate(p):
                    m.set_point(0, i, x, 1.0-y)
  variables: {'i': ('local', 7), 'x': ('local', 0.57415771484375), 'y': ('local', 0.16366125242801646), 'enumerate': ('builtin', <class 'enumerate'>), 'p': ('local', [[0.0, 1.0], [0.04013249619202044, 0.8863658364821623], [0.11424874068723989, 0.6654086208866545], [0.22375401191847502, 0.46889081602776506], [0.33737157216111774, 0.34299503863402653], [0.4670402173054771, 0.2430535966779022], [0.57415771484375, 0.16366125242801646], None, [0.7329105916970124, 0.06453569541247715], [0.7912117213046225, 0.03781657942470292], [0.8404260878046967, 0.0113525390625], [0.8783648442144768, 0.0015112617116087752], [1.0, 0.0]])}
TypeError: cannot unpack non-iterable NoneType object
```

For some reason, the pressure curve has a negative slope:

![Screenshot_2025-01-03-inverted-curve](https://github.com/user-attachments/assets/b8e27b13-cab4-423d-8665-cffc55d7bfdc)

**Comment by aleksejrs** [comment]
> What happens when you delete your MyPaint config directory?

Crashes consistently on drawing, but without the details (user name is redacted):

mypaint                                                                                                                      10:22
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix '/usr'
WARNING: gui.userconfig: Failed to load settings file: /home/user/.config/mypaint/settings.json
WARNING: gui.userconfig: Failed to load settings: using defaults
INFO: gui.main: No locale setting found, using system locale
INFO: lib.i18n: POSIX: LANG='en_GB.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE='en'
INFO: lib.i18n: Value of LANGUAGE after cleanup: 'en:C'

(mypaint:1525526): dbind-WARNING **: 10:22:35.095: Couldn't connect to accessibility bus: Failed to connect to socket /home/im/.cache/at-spi/bus_0.0: Permission denied
INFO: gui.application: Created basedir '/home/user/.config/mypaint'
INFO: gui.application: Created basedir '/home/user/.local/share/mypaint'
INFO: gui.application: Created data subdir '/home/user/.local/share/mypaint/backgrounds'
INFO: gui.application: Created data subdir '/home/user/.local/share/mypaint/brushes'
INFO: gui.application: Created data subdir '/home/user/.local/share/mypaint/scratchpads'
WARNING: gui.userconfig: Failed to load settings file: /home/user/.config/mypaint/settings.json
WARNING: gui.userconfig: Failed to load settings: using defaults
INFO: gui.compatibility: Setting mode to 2.x (standard)
INFO: gui.compatibility: Setting default layer type to Pigment
INFO: gui.brushmanager: Merging upstream brush changes into your collection.
INFO: gui.device: New device 'Winry Winry315 Mouse' (GDK_SOURCE_MOUSE, axes:4, class=X11DeviceXI2, vendor='f1f1', product='0315')
INFO: gui.device: New device 'Winry Winry315 Consumer Control' (GDK_SOURCE_MOUSE, axes:4, class=X11DeviceXI2, vendor='f1f1', product='0315')
INFO: gui.device: New device 'USB Gaming Mouse Consumer Control' (GDK_SOURCE_MOUSE, axes:4, class=X11DeviceXI2, vendor='04d9', product='fc41')
INFO: gui.device: New device 'USB Gaming Mouse' (GDK_SOURCE_MOUSE, axes:4, class=X11DeviceXI2, vendor='04d9', product='fc41')
INFO: gui.device: New device 'Virtual core XTEST pointer' (GDK_SOURCE_MOUSE, axes:2, class=X11DeviceXI2, vendor=None, product=None)
INFO: gui.document: Initialized background from '/usr/share/mypaint/backgrounds/mrmamurk/mamurk_e_1.png'
WARNING: gui.keyboard: Ignoring keybinding for '<Actions>/BrushModifierActions/BlendModeMenu'
INFO: gui.brushmanager: Switching default pigment setting to On
INFO: gui.compatibility: Setting default layer type to Pigment
fish: Job 1, 'mypaint' terminated by signal SIGSEGV (Address boundary error)

**Comment by AesaraB** [comment]
I'll try replicate this with XFCE Debian on my side

**Comment by aleksejrs** [comment]
It works now.

> In the meantime, can you use the flatpak?

I probably didn't try. If I did, I couldn't get to test the bug.
