### ISSUE TITLE
Fresh installation won't start 

### ISSUE THREAD

**Issue by Rimfrost** [mypaint/mypaint#1272]
### Description of bug

bash ~ % mypaint
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix '/opt/local/Library/Frameworks/Python.framework/Versions/3.12'
WARNING: gui.userconfig: Failed to load settings file: /Users/yhd429/.config/mypaint/settings.json
WARNING: gui.userconfig: Failed to load settings: using defaults
INFO: gui.main: No locale setting found, using system locale
INFO: lib.i18n: OSX: imported AppKit.NSLocale OK. Will use for LANG, and for LANGUAGE order.
INFO: lib.i18n: OSX: LANG='sv_SE.UTF-8'
INFO: lib.i18n: OSX: LANGUAGE='sv_SE'
INFO: lib.i18n: Value of LANGUAGE after cleanup: 'sv_SE'

(mypaint:59458): Gtk-CRITICAL **: 08:21:22.521: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/opt/local/bin/mypaint", line 309, in <module>
    main.main(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/mypaint/gui/main.py", line 231, in main
    run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/mypaint/gui/main.py", line 195, in run
    app = application.Application(
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/mypaint/gui/application.py", line 240, in __init__
    _init_icons(state_dirs.app_icons)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/mypaint/gui/application.py", line 118, in _init_icons
    icon_theme.append_search_path(icon_path)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'append_search_path'

### Steps to reproduce

1. install mypaint on Mac through Macports
2. Try and start mypaint from terminal 

### Backtraces or error messages

```shell
bash ~ % mypaint
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix '/opt/local/Library/Frameworks/Python.framework/Versions/3.12'
WARNING: gui.userconfig: Failed to load settings file: /Users/yhd429/.config/mypaint/settings.json
WARNING: gui.userconfig: Failed to load settings: using defaults
INFO: gui.main: No locale setting found, using system locale
INFO: lib.i18n: OSX: imported AppKit.NSLocale OK. Will use for LANG, and for LANGUAGE order.
INFO: lib.i18n: OSX: LANG='sv_SE.UTF-8'
INFO: lib.i18n: OSX: LANGUAGE='sv_SE'
INFO: lib.i18n: Value of LANGUAGE after cleanup: 'sv_SE'

(mypaint:59458): Gtk-CRITICAL **: 08:21:22.521: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/opt/local/bin/mypaint", line 309, in <module>
    main.main(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/mypaint/gui/main.py", line 231, in main
    run()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/mypaint/gui/main.py", line 195, in run
    app = application.Application(
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/mypaint/gui/application.py", line 240, in __init__
    _init_icons(state_dirs.app_icons)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.12/lib/mypaint/gui/application.py", line 118, in _init_icons
    icon_theme.append_search_path(icon_path)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'append_search_path'
```

### MyPaint version

v2.0.1

### Operating System(s)

macOS Sonoma 14.6

### Desktop Environment (Linux)

macOS (installed app with Macports)

### Code of Conduct

- [X] I acknowledge that my conduct contributes to shaping the community.

**Comment by AesaraB** [comment]
https://horizon.mypaint.app/en/docs/manuals/faq/macports/
