### ISSUE TITLE
can't save ora files

### ISSUE THREAD

**Issue by chocotier** [mypaint/mypaint#189]
everytime i try to save my work to ora something pops out and says:
Unable to save: Error
same thing happens to save as, export, and save scrap

```
Traceback (most recent call last):
  File "C:\Program Files\MyPaint\library.zip\gui\filehandling.py", line 427, save_cb(no details)
            if not self.filename:
                self.save_as_cb(action)
            else:
  File "C:\Program Files\MyPaint\library.zip\gui\filehandling.py", line 451, save_as_cb(no details)
            else:
                self.save_as_dialog(self.save_file, suggested_filename = current_filename)
  File "C:\Program Files\MyPaint\library.zip\gui\filehandling.py", line 511, save_as_dialog(no details)
                        else:
                            save_method_reference(filename, **options)
                        break
  File "C:\Program Files\MyPaint\library.zip\gui\drawwindow.py", line 46, wrapper(self=<gui.filehandling.FileHandler object>, *args=(u'C:\\Users\\acer\\Documents\\yea.ora',), **kwargs={})
            try:
                func(self, *args, **kwargs)
                # gtk main loop may be called in here...
  File "C:\Program Files\MyPaint\library.zip\gui\filehandling.py", line 292, save_file(no details)
                thumbnail_pixbuf = self.doc.model.render_thumbnail()
            helpers.freedesktop_thumbnail(self.filename, thumbnail_pixbuf)
  File "C:\Program Files\MyPaint\library.zip\lib\helpers.py", line 152, freedesktop_thumbnail(no details)
        file_mtime = str(int(os.stat(filename).st_mtime))
WindowsError: [Error 2] The system cannot find the file specified: u'C:\\Users\\acer\\Documents\\yea.ora'
```

**Comment by tumagonx** [comment]
Mypaint version?
and was C:\Users\acer\Documents\yea.ora exist and you have permission to modify it?

Would you like to try a bit newer version? http://sourceforge.net/projects/tumagcc/files/MyPaint-1.1.1a_win32.7z/download

**Comment by achadwick** [comment]
@chocotier I suspect this has been fixed at the version and build @tumagonx mentions.

**Comment by achadwick** [comment]
@chocotier Does the (probably) newer version above fix this problem?

This bug should be closed if it gathers no response within two weeks from today, i.e. Sun 5 April.

**Comment by achadwick** [comment]
Closing due to lack of reporter response. It's probably an unsupported old version too.
