### ISSUE TITLE
Frame editor tool: exception: "AttributeError: 'Label' object has no attribute 'set_margin_start'"

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#218]
My box is ubuntu gnome 14.04 and while I've tried use the frame editor this error appears:

```
jag@ubuntugnome:~/installs/mypaint-git-master$ ./mypaint
INFO: mypaint: Using the old-style configuration area found in u'/home/jag/.mypaint/'
INFO: mypaint: Its contents can be migrated to $XDG_CONFIG_HOMEand $XDG_DATA_HOME if you wish.
INFO: mypaint: See the XDG Base Directory Specification for info.
WARNING: gui.keyboard: Ignoring keybinding for '<Actions>/WindowActions/ModeOptionsTool'
WARNING: gui.keyboard: Ignoring keybinding for '<Actions>/WindowActions/ModeOptionsTool'
WARNING: gui.keyboard: Ignoring keybinding for '<Actions>/ModeStackActions/FlipSwitchableFreehandMode'
WARNING: gui.keyboard: Ignoring keybinding for '<Actions>/ModeStackActions/FlipSwitchableFreehandMode'
INFO: gui.application: Initialized background from u'/home/jag/.mypaint/backgrounds/default.png'

(mypaint:21000): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
WARNING: gui.keyboard: Ignoring keybinding for '<Actions>/BrushModifierActions/BlendMode'
WARNING: gui.workspace: Empty tab group in workspace, not added
WARNING: gui.workspace: Empty tab group in workspace, not added
INFO: lib.document: Using u'load_ora' to load u'/home/jag/.mypaint/scratchpads/autosave.ora' (kwargs={'feedback_cb': <function gtk_main_tick at 0x7fd731a7e578>})
INFO: lib.document: load_ora: u'/home/jag/.mypaint/scratchpads/autosave.ora'
INFO: lib.document: 0.055s load_ora total
INFO: gui.filehandling: Loaded scratchpad from u'/home/jag/.mypaint/scratchpads/autosave.ora'
ERROR: lib.observable: Failed to call observer <BoundObserverMethod gui.optionspanel.ModeOptionsTool._modestack_changed_cb>
Traceback (most recent call last):
  File "/home/jag/installs/mypaint-git-master/gui/document.py", line 1843, in mode_radioaction_changed_cb
    self.modes.context_push(mode)
  File "/home/jag/installs/mypaint-git-master/gui/mode.py", line 1132, in context_push
    self.changed(old=old_mode, new=mode)
  File "/home/jag/installs/mypaint-git-master/lib/observable.py", line 284, in __call__
    observer(observed, *args, **kwargs)
  File "/home/jag/installs/mypaint-git-master/lib/observable.py", line 467, in __call__
    self._observer_func(observer, observed, *args, **kwargs)
  File "/home/jag/installs/mypaint-git-master/gui/optionspanel.py", line 89, in _modestack_changed_cb
    self._update_ui()
  File "/home/jag/installs/mypaint-git-master/gui/optionspanel.py", line 98, in _update_ui
    new_options = mode.get_options_widget()
  File "/home/jag/installs/mypaint-git-master/gui/framewindow.py", line 392, in get_options_widget
    widget = FrameEditOptionsWidget()
  File "/home/jag/installs/mypaint-git-master/gui/framewindow.py", line 429, in __init__
    self._init_ui()
  File "/home/jag/installs/mypaint-git-master/gui/framewindow.py", line 449, in _init_ui
    height_label = self._new_key_label(_('Height:'))
  File "/home/jag/installs/mypaint-git-master/gui/framewindow.py", line 624, in _new_key_label
    label.set_margin_start(12)
AttributeError: 'Label' object has no attribute 'set_margin_start'

(mypaint:21000): Gdk-WARNING **: gdk_window_set_icon_list: icons too large
```

**Comment by achadwick** [comment]
Ugh, looks like gtk_widget_set_margin_start() is 3.12+ only. We should use the margin_left variant, but via a rtl/ltr aware compat function.

**Comment by achadwick** [comment]
Retitled. This is c6da802.
