### ISSUE TITLE
When loading ORA files: exception "Cannot create a file when that file already exists"

### ISSUE THREAD

**Issue by horkana** [mypaint/mypaint#219]
Mypaint 1.1.1-alpha.20150216+git.320a581

I've been exploring the OpenRaster file format and have crafted a few strange .ora files, including one where:  
layer0.svg 
replaces layer0.png 
(and the stack.xml points to layer0.svg)
but I was still surprised that MyPaint didn't open it successfully, and if I'm reading the error message it seems to have exposed a minor flaw in the way temp files are managed. 

The full error message follows, and sample file at end: 

```
Mypaint version: 1.1.1-alpha.20150216+git.320a581
System information: Windows-XP-5.1.2600-SP3
Traceback (most recent call last):
  File "C:\program files\MyPaint\mypaint-1.1.1a\win32\gui\drawwindow.py", line 298, _drag_data_received_cb(self=<DrawWindow object at 0x2db9170 (MyPaintDrawWindow at 0x2f0f150)>, widget=<DrawWindow object at 0x2db9170 (MyPaintDrawWindow at 0x2f0f150)>, context=<gtk.gdk.Win32DragContext object at 0x4a99670 (GdkWin32DragContext at 0x45fc800)>, x=499, y=383, data=<GtkSelectionData>, info=1L, time=1707631703L)
                    if self.app.filehandler.confirm_destructive_action():
                        self.app.filehandler.open_file(fn)
            elif info == 2:  # color
  variables: {'self.app.filehandler.open_file': ('local', <bound method FileHandler.open_file of <gui.filehandling.FileHandler object at 0x02DAB8D0>>), 'fn': ('local', u'C:\\Documents and Settings\\Family\\Desktop\\te22\\svg-fail.ora')}
  File "C:\program files\MyPaint\mypaint-1.1.1a\win32\gui\drawwindow.py", line 79, wrapper(self=<gui.filehandling.FileHandler object>, *args=(u'C:\\Documents and Settings\\Family\\Desktop\\te22\\svg-fail.ora',), **kwargs={})
            try:
                func(self, *args, **kwargs)
                # gtk main loop may be called in here...
  variables: {'self': ('local', <gui.filehandling.FileHandler object at 0x02DAB8D0>), 'args': ('local', (u'C:\\Documents and Settings\\Family\\Desktop\\te22\\svg-fail.ora',)), 'func': ('local', <function open_file at 0x01F2D4B0>), 'kwargs': ('local', {})}
  File "C:\program files\MyPaint\mypaint-1.1.1a\win32\gui\filehandling.py", line 292, open_file(self=<gui.filehandling.FileHandler object>, filename=u'C:\\Documents and Settings\\Family\\Desktop\\te22\\svg-fail.ora')
                    feedback_cb=self.gtk_main_tick,
                    convert_to_srgb=(display_colorspace_setting == "srgb"),
                )
  variables: {'convert_to_srgb': (None, []), 'display_colorspace_setting': ('local', u'srgb')}
  File "C:\program files\MyPaint\mypaint-1.1.1a\win32\lib\document.py", line 772, load(self=<Document nlayers=1 bbox=Rect(128, 320, 256, 192) paintonly=False>, filename=u'C:\\Documents and Settings\\Family\\Desktop\\te22\\svg-fail.ora', **kwargs={'convert_to_srgb': True, 'feedback_cb': <function gtk_main_tick>})
            try:
                load_method(filename, **kwargs)
            except GObject.GError as e:
  variables: {'kwargs': ('local', {'feedback_cb': <function gtk_main_tick at 0x01F2D470>, 'convert_to_srgb': True}), 'filename': ('local', u'C:\\Documents and Settings\\Family\\Desktop\\te22\\svg-fail.ora'), 'load_method': ('local', <bound method Document.load_ora of <Document nlayers=1 bbox=Rect(128, 320, 256, 192) paintonly=False>>)}
  File "C:\program files\MyPaint\mypaint-1.1.1a\win32\lib\document.py", line 970, load_ora(self=<Document nlayers=1 bbox=Rect(128, 320, 256, 192) paintonly=False>, filename=u'C:\\Documents and Settings\\Family\\Desktop\\te22\\svg-fail.ora', feedback_cb=<function gtk_main_tick>, **kwargs={'convert_to_srgb': True})
                                                  tempdir, feedback_cb, x=0, y=0,
                                                  **kwargs)
            assert len(self.layer_stack) > 0
  variables: {'kwargs': ('local', {'convert_to_srgb': True})}
  File "C:\program files\MyPaint\mypaint-1.1.1a\win32\lib\layer.py", line 3080, load_from_openraster(self=<RootLayerStack len=1 u'root'>, orazip=<zipfile.ZipFile object>, elem=<Element 'stack'>, tempdir=u'c:\\docume~1\\family\\locals~1\\temp\\tmpzezguzmypaint', feedback_cb=<function gtk_main_tick>, x=0, y=0, **kwargs={'convert_to_srgb': True})
                .load_from_openraster(orazip, elem, tempdir, feedback_cb,
                                      x=x, y=y, **kwargs)
            del self._no_background
  variables: {'y': ('local', 0), 'x': ('local', 0), 'kwargs': ('local', {'convert_to_srgb': True})}
  File "C:\program files\MyPaint\mypaint-1.1.1a\win32\lib\layer.py", line 1023, load_from_openraster(self=<RootLayerStack len=1 u'root'>, orazip=<zipfile.ZipFile object>, elem=<Element 'stack'>, tempdir=u'c:\\docume~1\\family\\locals~1\\temp\\tmpzezguzmypaint', feedback_cb=<function gtk_main_tick>, x=0, y=0, **kwargs={'convert_to_srgb': True})
                    orazip, child_elem,
                    tempdir, feedback_cb, x=x, y=y, **kwargs
                )
  variables: {'tempdir': ('local', u'c:\\docume~1\\family\\locals~1\\temp\\tmpzezguzmypaint'), 'feedback_cb': ('local', <function gtk_main_tick at 0x01F2D470>), 'kwargs': ('local', {'convert_to_srgb': True}), 'y': ('local', 0), 'x': ('local', 0)}
  File "C:\program files\MyPaint\mypaint-1.1.1a\win32\lib\layer.py", line 3136, load_child_layer_from_openraster(self=<RootLayerStack len=1 u'root'>, orazip=<zipfile.ZipFile object>, elem=<Element 'layer'>, tempdir=u'c:\\docume~1\\family\\locals~1\\temp\\tmpzezguzmypaint', feedback_cb=<function gtk_main_tick>, x=0, y=0, **kwargs={'convert_to_srgb': True})
                .load_child_layer_from_openraster(orazip, elem, tempdir,
                                                  feedback_cb, x=x, y=y, **kwargs)
  variables: {'feedback_cb': ('local', <function gtk_main_tick at 0x01F2D470>), 'x': ('local', 0), 'y': ('local', 0), 'kwargs': ('local', {'convert_to_srgb': True})}
  File "C:\program files\MyPaint\mypaint-1.1.1a\win32\lib\layer.py", line 1033, load_child_layer_from_openraster(self=<RootLayerStack len=1 u'root'>, orazip=<zipfile.ZipFile object>, elem=<Element 'layer'>, tempdir=u'c:\\docume~1\\family\\locals~1\\temp\\tmpzezguzmypaint', feedback_cb=<function gtk_main_tick>, x=0, y=0, **kwargs={'convert_to_srgb': True})
                                                  feedback_cb, self.root,
                                                  x=x, y=y, **kwargs)
            except LoadError:
  variables: {'y': ('local', 0), 'x': ('local', 0), 'kwargs': ('local', {'convert_to_srgb': True})}
  File "C:\program files\MyPaint\mypaint-1.1.1a\win32\lib\layer.py", line 4417, layer_new_from_openraster(orazip=<zipfile.ZipFile object>, elem=<Element 'layer'>, tempdir=u'c:\\docume~1\\family\\locals~1\\temp\\tmpzezguzmypaint', feedback_cb=<function gtk_main_tick>, root=<RootLayerStack len=1 u'root'>, x=0, y=0, **kwargs={'convert_to_srgb': True})
                                                       feedback_cb, root,
                                                       x=x, y=y, **kwargs)
            except LoadError:
  variables: {'y': ('local', 0), 'x': ('local', 0), 'kwargs': ('local', {'convert_to_srgb': True})}
  File "C:\program files\MyPaint\mypaint-1.1.1a\win32\lib\layer.py", line 266, new_from_openraster(cls=<class 'lib.layer.VectorLayer'>, orazip=<zipfile.ZipFile object>, elem=<Element 'layer'>, tempdir=u'c:\\docume~1\\family\\locals~1\\temp\\tmpzezguzmypaint', feedback_cb=<function gtk_main_tick>, root=<RootLayerStack len=1 u'root'>, x=0, y=0, **kwargs={'convert_to_srgb': True})
            layer.load_from_openraster(orazip, elem, tempdir, feedback_cb,
                                       x=x, y=y, **kwargs)
            return layer
  variables: {'y': ('local', 0), 'x': ('local', 0), 'kwargs': ('local', {'convert_to_srgb': True})}
  File "C:\program files\MyPaint\mypaint-1.1.1a\win32\lib\layer.py", line 3812, load_from_openraster(self=<VectorLayer u'Background'>, orazip=<zipfile.ZipFile object>, elem=<Element 'layer'>, tempdir=u'c:\\docume~1\\family\\locals~1\\temp\\tmpzezguzmypaint', feedback_cb=<function gtk_main_tick>, x=0, y=0, **kwargs={'convert_to_srgb': True})
            os.close(rev0_fd)
            os.rename(tmp_filename, rev0_filename)
            self._workfile = ManagedFile(rev0_filename)
  variables: {'tmp_filename': ('local', u'c:\\docume~1\\family\\locals~1\\temp\\tmpzezguzmypaint\\data/layer0.svg'), 'rev0_filename': ('local', u'c:\\docume~1\\family\\locals~1\\temp\\tmpzezguzmypaint\\tmpiyiiq5.svg'), 'os.rename': ('global', <built-in function rename>)}
WindowsError: [Error 183] Cannot create a file when that file already exists
```

[**EDIT**: triple backtick quoting -- achadwick]

![svg-fail ora](https://cloud.githubusercontent.com/assets/794282/6370694/fcdf8c5e-bcea-11e4-97d6-1bf1cdb326b4.png)

Uploaded sample file, renamed from .ora to .png to fool github

**Comment by achadwick** [comment]
Good old Windows, breaking the os.rename()-does-an-atomic-overwrite trick again.

A quick fix would be to insert a call to os.remove(rev0_filename) before the os.rename() line on the end of the above backtrace.

Maybe [_ManagedFile's constructor](https://github.com/mypaint/mypaint/blob/30f5382536caa7dda01ee702ada355d2274ffcd6/lib/layer.py#L3688) could be extended to cover this "rename then adopt" pattern. It can already do a "clone then adopt". That would be a better fix.

**Comment by horkana** [comment]
Thank you.
