### ISSUE TITLE
attempting to pan canvas consistently produces error.

### ISSUE THREAD

**Issue by mikshaw** [mypaint/mypaint#285]
Happens with both middlemouse and spacebar+leftmouse. Instead of panning the canvas, an error window immediately appears. Running MyPaint with fresh config has same result.

```python
Mypaint version: 1.1.1-alpha.20150407+git.9129169
System information: Linux-3.16.0-4-amd64-x86_64-with-debian-8.0
Traceback (most recent call last):
  File "/home/download/git/mypaint/gui/document.py", line 544, button_press_cb(self=<gui.document.Document object>, tdw=<TiledDrawWidget object at 0x7f5bed211c80 (TiledDrawWidget at 0x1073850)>, event=<void>)
                    return self._dispatch_named_action(None, tdw, event,
                                                       action_name)
            # User-configurable forbidding of particular devices
  variables: {'action_name': ('local', u'PanViewMode')}
  File "/home/download/git/mypaint/gui/document.py", line 674, _dispatch_named_action(self=<gui.document.Document object>, win=None, tdw=<TiledDrawWidget object at 0x7f5bed211c80 (TiledDrawWidget at 0x1073850)>, event=<void>, action_name=u'PanViewMode')
                    mode = handler()
                self.modes.push(mode)
                if win is not None:
  variables: {'self.modes.push': ('local', <bound method ModeStack.push of <ModeStack [FreehandMode, PanViewMode]>>), 'mode': ('local', <gui.viewmanip.PanViewMode object at 0x7f5be622e250>)}
  File "/home/download/git/mypaint/gui/mode.py", line 1326, push(self=<ModeStack [FreehandMode, PanViewMode]>, mode=<gui.viewmanip.PanViewMode object>)
            self._stack.append(mode)
            mode.enter(doc=self._doc)
            self.changed(old=old_mode, new=mode)
  variables: {'doc': (None, []), 'self._doc': ('local', <gui.document.Document object at 0x7f5bed229690>), 'mode.enter': ('local', <bound method PanViewMode.enter of <gui.viewmanip.PanViewMode object at 0x7f5be622e250>>)}
  File "/home/download/git/mypaint/gui/mode.py", line 430, enter(self=<gui.viewmanip.PanViewMode object>, doc=<gui.document.Document object>)
            self.__reset_delta_totals()
            return super(ScrollableModeMixin, self).enter(doc)
  variables: {'doc': ('local', <gui.document.Document object at 0x7f5bed229690>), 'self': ('local', <gui.viewmanip.PanViewMode object at 0x7f5be622e250>), 'super': ('builtin', <type 'super'>), 'ScrollableModeMixin': ('global', <class 'gui.mode.ScrollableModeMixin'>), 'enter': (None, [])}
TypeError: enter() takes exactly 1 argument (2 given)
```

**Comment by achadwick** [comment]
Please retest with d5e05e26099ae88f7f18052e9601333c3ee18471 or latest master. Should be fixed, but the commit an the report crossed I think.

**Comment by mikshaw** [comment]
yes, all fixed. thank you again. \o/
