### ISSUE TITLE
Trace during saving if no space left on /tmp

### ISSUE THREAD

**Issue by amarao** [mypaint/mypaint#316]
When there is no more space left on /tmp mypaint:

1) Can not save anything
2) Show a trace:

```python
Mypaint version: 1.2.0-alpha.20150505+git.2a10764
System information: Linux-3.16.0-4-amd64-x86_64-with-debian-stretch-sid
Traceback (most recent call last):
  File "/usr/local/share/mypaint/gui/filehandling.py", line 497, save_cb(self=<gui.filehandling.FileHandler object>, action=<Action object at 0x7f705245cdc0 (GtkAction at 0x3045d50)>)
            else:
                self.save_file(self.filename)
  variables: {'self.save_file': ('local', <bound method FileHandler.save_file of <gui.filehandling.FileHandler object at 0x7f70523bfc90>>), 'self.filename': ('local', u'/home/amarao/Pictures/drawing/ball_with_shadow.ora')}
  File "/usr/local/share/mypaint/gui/drawwindow.py", line 80, wrapper(self=<gui.filehandling.FileHandler object>, *args=(u'/home/amarao/Pictures/drawing/ball_with_shadow.ora',), **kwargs={})
            try:
                func(self, *args, **kwargs)
                # gtk main loop may be called in here...
  variables: {'self': ('local', <gui.filehandling.FileHandler object at 0x7f70523bfc90>), 'args': ('local', (u'/home/amarao/Pictures/drawing/ball_with_shadow.ora',)), 'func': ('local', <function save_file at 0x7f705288aa28>), 'kwargs': ('local', {})}
  File "/usr/local/share/mypaint/gui/filehandling.py", line 324, save_file(self=<gui.filehandling.FileHandler object>, filename=u'/home/amarao/Pictures/drawing/ball_with_shadow.ora', export=False, **options={})
                export=export,
                **options
                )
  variables: {'options': ('local', {})}
  File "/usr/local/share/mypaint/gui/filehandling.py", line 380, save_doc_to_file(self=<gui.filehandling.FileHandler object>, filename=u'/home/amarao/Pictures/drawing/ball_with_shadow.ora', doc=<gui.document.Document object>, export=False, **options={'save_srgb_chunks': True})
                    feedback_cb=self.gtk_main_tick,
                    **options
                )
  variables: {'options': ('local', {'save_srgb_chunks': True})}
  File "/usr/local/share/mypaint/lib/document.py", line 1168, save(self=<Document nlayers=3 bbox=Rect(0, 0, 2880, 1984) paintonly=False>, filename=u'/home/amarao/Pictures/drawing/ball_with_shadow.ora', **kwargs={'feedback_cb': <function gtk_main_tick>, 'save_srgb_chunks': True})
            try:
                result = save(filename, **kwargs)
            except GObject.GError, e:
  variables: {'kwargs': ('local', {'feedback_cb': <function gtk_main_tick at 0x7f705288a848>, 'save_srgb_chunks': True}), 'save': ('local', <bound method Document.save_ora of <Document nlayers=3 bbox=Rect(0, 0, 2880, 1984) paintonly=False>>), 'result': ('local', None), 'filename': ('local', u'/home/amarao/Pictures/drawing/ball_with_shadow.ora')}
  File "/usr/local/share/mypaint/lib/fileutils.py", line 126, _wrapped_save_method(self=<Document nlayers=3 bbox=Rect(0, 0, 2880, 1984) paintonly=False>, filename=u'/home/amarao/Pictures/drawing/ball_with_shadow.ora', *args=(), **kwds={'feedback_cb': <function gtk_main_tick>, 'save_srgb_chunks': True})
                    logger.error("cleanup: failed to remove temp path too")
                raise ex
            if not os.path.exists(temp_path):
  variables: {'ex': ('local', OSError(28, 'No space left on device'))}
OSError: [Errno 28] No space left on device: '/tmp/saveHkGtkfmypaint'
```

**Comment by jonnor** [comment]
What do you expect to happen? Better error message? Anthing else?

**Comment by amarao** [comment]
Use save directory for temp files? It can be mounted on different drive with free space (f.e. /home).

It is better than loosing a work because of 'no space on root drive'.

**Comment by achadwick** [comment]
This is tricky to deal with.

Note that it won't be an `OSError` in Windows, but for everything else we could catch `errno.ENOSPC` (= 28) ones [here](https://github.com/mypaint/mypaint/blob/542ec552864935b8eba77e008297450d0f36ca4c/lib/fileutils.py#L120) and present a more reasonable `lib.error.FileHandlingError` instead. That's supposed to show a nice user-facing string always. These days it can deliver a request for the error dialog to launch the user's file manager for "investigation purposes", which might be very appropriate in this case.

This falls into the category of things that it would be nice to have a nicer error message for.

**Comment by achadwick** [comment]
Don't forget autosave backups if you think you lost data. Hopefully unaffected by this.

If someone runs out of space on `/tmp`, that's kinda their fault. That exception handler could be improved slightly though (on POSIX systems).

Incidentally, `@via_tempfile` *does* use the save dir - for the save+replace tempfile. So this is something bubbling up from its wrapped save method, `lib.document.Document.save_ora()`. That uses a "/tmp" working dir, though maybe it shouldn't now we have a reasonable cache prefix elsewhere.

**Comment by achadwick** [comment]
**Triage note:** one maybe two small changes needed. The OSError -> FileHandlingError switch requires a string change. Hopefully someone else can pick it up?

**Comment by achadwick** [comment]
Okay, egg on face time. The fastpng writer code *was* supposed to detect an out-of-space condition, and it did - but the reporting of the error as an exception was broken. I've dived in and tidied things up, and the dialog error now looks like:

![image](https://cloud.githubusercontent.com/assets/61299/8444787/04049d76-1f8d-11e5-8e43-7832eb81b327.png)

Which should I hope be more informative.
