### ISSUE TITLE
error on save as png

### ISSUE THREAD

**Issue by cg-cnu** [mypaint/mypaint#334]
I started painting some practice stuff for quite some time and did a save as to png.
It throw the following error.

```
Mypaint version: 1.1.1-alpha.20150308+git.6b3a1e7
System information: Linux-3.10.0-123.el7.x86_64-x86_64-with-centos-7.0.1406-Core
Traceback (most recent call last):
  File "/home/salaati/codeMonk/mypaint/gui/filehandling.py", line 528, save_as_cb(self=<gui.filehandling.FileHandler object>, action=<Action object at 0x30de0a0 (GtkAction at 0x31b8090)>)
            else:
                self.save_as_dialog(self.save_file, suggested_filename=current_filename)
  variables: {'suggested_filename': (None, []), 'self.save_file': ('local', <bound method FileHandler.save_file of <gui.filehandling.FileHandler object at 0x30d9150>>), 'self.save_as_dialog': ('local', <bound method FileHandler.save_as_dialog of <gui.filehandling.FileHandler object at 0x30d9150>>), 'current_filename': ('local', '')}
  File "/home/salaati/codeMonk/mypaint/gui/filehandling.py", line 554, save_as_dialog(self=<gui.filehandling.FileHandler object>, save_method_reference=<bound method FileHandler.save_file of <gui.filehandling.FileHandler object>>, suggested_filename='', start_in_folder=None, export=False, **options={})
                while dialog.run() == gtk.RESPONSE_OK:
                    filename = dialog.get_filename().decode('utf-8')
                    name, ext = os.path.splitext(filename)
  variables: {'decode': (None, []), 'dialog.get_filename': ('local', <bound method FileChooserDialog.get_filename of <FileChooserDialog object at 0x8dca4b0 (GtkFileChooserDialog at 0x3f36d80)>>), 'filename': (None, [])}
AttributeError: 'NoneType' object has no attribute 'decode'
```

Tried reproducing it, but couldn't. 
Logging it here for now, will update if it happens again.

**Comment by achadwick** [comment]
This looks like a local build. Can you confirm that it's happening with the most recent git version please (`git update`, rebuild)? Newer ones are labelled 1.2.0-alpha.

Not an encoding issue here, we just need to handle `dialog. get_filename()` returning null more gracefully than that. Looks like an "until there's a workable filename" loop there, so a simple enough fix for a new Pythoneer ☺

**Comment by cg-cnu** [comment]
Let me get on to the latest version of gtk and if its a bit size I can take it up and work on it.
