### ISSUE TITLE
After clicking on the symmetry button MyPaint crashes.

### ISSUE THREAD

**Issue by Ico-dY** [mypaint/mypaint#351]
After clicking on the symmetry button MyPaint crashes and when selecting a new tool the options panel is not updated anymore.

```python
Mypaint version: 1.2.0-alpha.20150626+git.66739df
System information: Linux-3.13.0-55-generic-x86_64-with-Ubuntu-14.04-trusty
Traceback (most recent call last):
  File "/usr/local/share/mypaint/gui/document.py", line 1902, mode_radioaction_changed_cb(self=<gui.document.Document object>, action=<RadioAction object at 0x7fd134998e60 (GtkRadioAction at 0x210a600)>, current_action=<RadioAction object at 0x7fd134998aa0 (GtkRadioAction at 0x27425e0)>)
                    mode = mode_class()
                self.modes.context_push(mode)
  variables: {'self.modes.context_push': ('local', <bound method ModeStack.context_push of <ModeStack [SymmetryEditMode]>>), 'mode': ('local', <gui.symmetry.SymmetryEditMode object at 0x7fd11507b750>)}
  File "/usr/local/share/mypaint/gui/mode.py", line 1296, context_push(self=<ModeStack [SymmetryEditMode]>, mode=<gui.symmetry.SymmetryEditMode object>)
            mode.enter(doc=self._doc)
            self.changed(old=old_mode, new=mode)
  variables: {'old': (None, []), 'self.changed': ('local', <MethodWithObservers gui.mode.ModeStack.changed>), 'mode': ('local', <gui.symmetry.SymmetryEditMode object at 0x7fd11507b750>), 'new': (None, []), 'old_mode': ('local', <gui.freehand.FreehandMode object at 0x7fd11507b390>)}
  File "/usr/local/share/mypaint/lib/observable.py", line 284, __call__(self=<MethodWithObservers gui.mode.ModeStack.changed>, *args=(), **kwargs={'new': <gui.symmetry.SymmetryEditMode object>, 'old': <gui.freehand.FreehandMode object>})
                try:
                    observer(observed, *args, **kwargs)
                except BoundObserverMethod._ReferenceError:
  variables: {'observed': ('local', <ModeStack [SymmetryEditMode]>), 'args': ('local', ()), 'observer': ('local', <BoundObserverMethod gui.optionspanel.ModeOptionsTool._modestack_changed_cb>), 'kwargs': ('local', {'new': <gui.symmetry.SymmetryEditMode object at 0x7fd11507b750>, 'old': <gui.freehand.FreehandMode object at 0x7fd11507b390>})}
  File "/usr/local/share/mypaint/lib/observable.py", line 467, __call__(self=<BoundObserverMethod gui.optionspanel.ModeOptionsTool._modestack_changed_cb>, observed=<ModeStack [SymmetryEditMode]>, *args=(), **kwargs={'new': <gui.symmetry.SymmetryEditMode object>, 'old': <gui.freehand.FreehandMode object>})
                raise self._ReferenceError
            self._observer_func(observer, observed, *args, **kwargs)
            del observer
  variables: {'observed': ('local', <ModeStack [SymmetryEditMode]>), 'args': ('local', ()), 'self._observer_func': ('local', <function _modestack_changed_cb at 0x7fd134877ed8>), 'observer': ('local', <ModeOptionsTool object at 0x7fd115426cd0 (MyPaintModeOptionsTool at 0x33fe7b0)>), 'kwargs': ('local', {'new': <gui.symmetry.SymmetryEditMode object at 0x7fd11507b750>, 'old': <gui.freehand.FreehandMode object at 0x7fd11507b390>})}
  File "/usr/local/share/mypaint/gui/optionspanel.py", line 105, _modestack_changed_cb(self=<ModeOptionsTool object at 0x7fd115426cd0 (MyPaintModeOptionsTool at 0x33fe7b0)>, modestack=<ModeStack [SymmetryEditMode]>, old=<gui.freehand.FreehandMode object>, new=<gui.symmetry.SymmetryEditMode object>)
            """Update the UI when the mode changes"""
            self._update_ui()
  variables: {'self._update_ui': ('local', <bound method ModeOptionsTool._update_ui of <ModeOptionsTool object at 0x7fd115426cd0 (MyPaintModeOptionsTool at 0x33fe7b0)>>)}
  File "/usr/local/share/mypaint/gui/optionspanel.py", line 110, _update_ui(self=<ModeOptionsTool object at 0x7fd115426cd0 (MyPaintModeOptionsTool at 0x33fe7b0)>)
            mode = self._app.doc.modes.top
            self._update_ui_for_mode(mode)
  variables: {'self._update_ui_for_mode': ('local', <bound method ModeOptionsTool._update_ui_for_mode of <ModeOptionsTool object at 0x7fd115426cd0 (MyPaintModeOptionsTool at 0x33fe7b0)>>), 'mode': ('local', <gui.symmetry.SymmetryEditMode object at 0x7fd11507b750>)}
  File "/usr/local/share/mypaint/gui/optionspanel.py", line 119, _update_ui_for_mode(self=<ModeOptionsTool object at 0x7fd115426cd0 (MyPaintModeOptionsTool at 0x33fe7b0)>, mode=<gui.symmetry.SymmetryEditMode object>)
            if get_options_widget:
                new_options = get_options_widget()
            else:
  variables: {'get_options_widget': ('local', <bound method SymmetryEditMode.get_options_widget of <gui.symmetry.SymmetryEditMode object at 0x7fd11507b750>>), 'new_options': (None, [])}
  File "/usr/local/share/mypaint/gui/symmetry.py", line 164, get_options_widget(self=<gui.symmetry.SymmetryEditMode object>)
            if cls._OPTIONS_WIDGET is None:
                widget = SymmetryEditOptionsWidget()
                cls._OPTIONS_WIDGET = widget
  variables: {'widget': (None, []), 'SymmetryEditOptionsWidget': ('global', <class 'gui.symmetry.SymmetryEditOptionsWidget'>)}
  File "/usr/local/share/mypaint/gui/symmetry.py", line 340, __init__(self=<SymmetryEditOptionsWidget object at 0x7fd1151c5...symmetry+SymmetryEditOptionsWidget at 0x40de7a0)>)
            )
            self._init_ui()
            rootstack.symmetry_state_changed += self._symmetry_state_changed_cb
  variables: {'self._init_ui': ('local', <bound method SymmetryEditOptionsWidget._init_ui of <SymmetryEditOptionsWidget object at 0x7fd1151c5a50 (gui+symmetry+SymmetryEditOptionsWidget at 0x40de7a0)>>)}
  File "/usr/local/share/mypaint/gui/symmetry.py", line 389, _init_ui(self=<SymmetryEditOptionsWidget object at 0x7fd1151c5...symmetry+SymmetryEditOptionsWidget at 0x40de7a0)>)
            label.set_hexpand(False)
            label.set_xalign(0.0)
            button = Gtk.Button(self._POSITION_BUTTON_TEXT_INACTIVE)
AttributeError: 'Label' object has no attribute 'set_xalign'
```

**Comment by achadwick** [comment]
Oops. I need to read the API docs more:

> Since: 3.16

We're supposed to be targeting 3.10.
