### ISSUE TITLE
Sometimes, After Selecting a Brush from a Brushes Set,  MyPaint Crashes.

### ISSUE THREAD

**Issue by Ico-dY** [mypaint/mypaint#354]
Sometimes, after selecting a brush from a brushes set, MyPaint crashes.

```python
Mypaint version: 1.2.0-alpha.20150627+git.bfc9831
System information: Linux-3.13.0-55-generic-x86_64-with-Ubuntu-14.04-trusty
Traceback (most recent call last):
  File "/usr/local/share/mypaint/gui/brushselectionwindow.py", line 130, button_press_cb(self=<BrushList object at 0x7fba35c76a50 (gui+brushselectionwindow+BrushList at 0x2d45660)>, widget=<BrushList object at 0x7fba35c76a50 (gui+brushselectionwindow+BrushList at 0x2d45660)>, event=<void>)
            self.app.device_monitor.device_used(device)
            return pixbuflist.PixbufList.button_press_cb(self, widget, event)
  variables: {'widget': ('local', <BrushList object at 0x7fba35c76a50 (gui+brushselectionwindow+BrushList at 0x2d45660)>), 'self': ('local', <BrushList object at 0x7fba35c76a50 (gui+brushselectionwindow+BrushList at 0x2d45660)>), 'pixbuflist.PixbufList.button_press_cb': ('global', <unbound method PixbufList.button_press_cb>), 'event': ('local', <void at 0x46ed1d0>)}
  File "/usr/local/share/mypaint/gui/pixbuflist.py", line 309, button_press_cb(self=<BrushList object at 0x7fba35c76a50 (gui+brushselectionwindow+BrushList at 0x2d45660)>, widget=<BrushList object at 0x7fba35c76a50 (gui+brushselectionwindow+BrushList at 0x2d45660)>, event=<void>)
                self.set_selected(item)
                self.item_selected(item)
                if self.selected is not None:
  variables: {'item': ('local', <ManagedBrush u'shalpin/brushy_variance' p=None>), 'self.item_selected': ('local', <MethodWithObservers gui.brushselectionwindow.BrushList.item_selected>)}
  File "/usr/local/share/mypaint/lib/observable.py", line 284, __call__(self=<MethodWithObservers gui.brushselectionwindow.BrushList.item_selected>, *args=(<ManagedBrush u'shalpin/brushy_variance' p=None>,), **kwargs={})
                try:
                    observer(observed, *args, **kwargs)
                except BoundObserverMethod._ReferenceError:
  variables: {'observed': ('local', <BrushList object at 0x7fba35c76a50 (gui+brushselectionwindow+BrushList at 0x2d45660)>), 'args': ('local', (<ManagedBrush u'shalpin/brushy_variance' p=None>,)), 'observer': ('local', <BoundObserverMethod gui.brushselectionwindow.BrushList._item_selected_cb>), 'kwargs': ('local', {})}
  File "/usr/local/share/mypaint/lib/observable.py", line 467, __call__(self=<BoundObserverMethod gui.brushselectionwindow.BrushList._item_selected_cb>, observed=<BrushList object at 0x7fba35c76a50 (gui+brushselectionwindow+BrushList at 0x2d45660)>, *args=(<ManagedBrush u'shalpin/brushy_variance' p=None>,), **kwargs={})
                raise self._ReferenceError
            self._observer_func(observer, observed, *args, **kwargs)
            del observer
  variables: {'observed': ('local', <BrushList object at 0x7fba35c76a50 (gui+brushselectionwindow+BrushList at 0x2d45660)>), 'args': ('local', (<ManagedBrush u'shalpin/brushy_variance' p=None>,)), 'self._observer_func': ('local', <function _item_selected_cb at 0x7fba5503c8c0>), 'observer': ('local', <BrushList object at 0x7fba35c76a50 (gui+brushselectionwindow+BrushList at 0x2d45660)>), 'kwargs': ('local', {})}
  File "/usr/local/share/mypaint/gui/brushselectionwindow.py", line 169, _item_selected_cb(self=<BrushList object at 0x7fba35c76a50 (gui+brushselectionwindow+BrushList at 0x2d45660)>, self_=<BrushList object at 0x7fba35c76a50 (gui+brushselectionwindow+BrushList at 0x2d45660)>, brush=<ManagedBrush u'shalpin/brushy_variance' p=None>)
                    self.bm.brushes_changed(brushes)
            self.bm.select_brush(brush)
  variables: {'self.bm.select_brush': ('local', <bound method BrushManager.select_brush of <gui.brushmanager.BrushManager object at 0x7fba55022b90>>), 'brush': ('local', <ManagedBrush u'shalpin/brushy_variance' p=None>)}
  File "/usr/local/share/mypaint/gui/brushmanager.py", line 701, select_brush(self=<gui.brushmanager.BrushManager object>, brush=<ManagedBrush u'shalpin/brushy_variance' p=None>)
            # brush, amongst other things
            self.brush_selected(brush, brushinfo)
  variables: {'self.brush_selected': ('local', <MethodWithObservers gui.brushmanager.BrushManager.brush_selected>), 'brush': ('local', <ManagedBrush u'shalpin/brushy_variance' p=None>), 'brushinfo': ('local', <lib.brush.BrushInfo object at 0x7fba3c4211d0>)}
  File "/usr/local/share/mypaint/lib/observable.py", line 284, __call__(self=<MethodWithObservers gui.brushmanager.BrushManager.brush_selected>, *args=(<ManagedBrush u'shalpin/brushy_variance' p=None>, <lib.brush.BrushInfo object>), **kwargs={})
                try:
                    observer(observed, *args, **kwargs)
                except BoundObserverMethod._ReferenceError:
  variables: {'observed': ('local', <gui.brushmanager.BrushManager object at 0x7fba55022b90>), 'args': ('local', (<ManagedBrush u'shalpin/brushy_variance' p=None>, <lib.brush.BrushInfo object at 0x7fba3c4211d0>)), 'observer': ('local', <BoundObserverMethod gui.brushmodifier.BrushModifier.brush_selected_cb>), 'kwargs': ('local', {})}
  File "/usr/local/share/mypaint/lib/observable.py", line 467, __call__(self=<BoundObserverMethod gui.brushmodifier.BrushModifier.brush_selected_cb>, observed=<gui.brushmanager.BrushManager object>, *args=(<ManagedBrush u'shalpin/brushy_variance' p=None>, <lib.brush.BrushInfo object>), **kwargs={})
                raise self._ReferenceError
            self._observer_func(observer, observed, *args, **kwargs)
            del observer
  variables: {'observed': ('local', <gui.brushmanager.BrushManager object at 0x7fba55022b90>), 'args': ('local', (<ManagedBrush u'shalpin/brushy_variance' p=None>, <lib.brush.BrushInfo object at 0x7fba3c4211d0>)), 'self._observer_func': ('local', <function brush_selected_cb at 0x7fba55290668>), 'observer': ('local', <gui.brushmodifier.BrushModifier object at 0x7fba3cf4f690>), 'kwargs': ('local', {})}
  File "/usr/local/share/mypaint/gui/brushmodifier.py", line 215, brush_selected_cb(self=<gui.brushmodifier.BrushModifier object>, bm=<gui.brushmanager.BrushManager object>, managed_brush=<ManagedBrush u'shalpin/brushy_variance' p=None>, brushinfo=<lib.brush.BrushInfo object>)
            b.set_color_hsv(color)
            b.set_string_property("parent_brush_name", managed_brush.name)
  variables: {'color': ('local', None), 'b.set_color_hsv': ('local', <bound method BrushInfo.set_color_hsv of <lib.brush.BrushInfo object at 0x7fba552b0890>>)}
  File "/usr/local/share/mypaint/lib/brush.py", line 449, set_color_hsv(self=<lib.brush.BrushInfo object>, hsv=None)
            try:
                h, s, v = hsv
                self.set_base_value('color_h', h)
  variables: {'h': (None, []), 's': ('global', <libmypaint.brushsettings.BrushSetting instance at 0x7fba55d56098>), 'hsv': ('local', None), 'v': (None, [])}
TypeError: 'NoneType' object is not iterable
```

![mypaint_bug](https://cloud.githubusercontent.com/assets/10749813/8397094/1fe8acae-1dc0-11e5-992d-88df59af48f7.png)

**Comment by achadwick** [comment]
Does this happen *immediately when* you add the brushpack, or only when you try to
* draw, or
* choose a brush from the newly loaded group?

Can you share a brushpack .zip which reliably reproduces this error please? I guess it's the "shalpin" set, which I've never heard of :(

**Comment by Ico-dY** [comment]
It happens immediately after choosing any brush from any group, old or new, and the triggering is completely random: it doesn't happen every time with the same brush.

This problem appeared after the latest git updates.
I never experienced something like this before.

**Comment by Ico-dY** [comment]
If you're interested, you can download the Shalpin's brushpack from here: http://fav.me/d2tidop
But it happens with every brushes set, so...

**Comment by Ico-dY** [comment]
Here's another log file...

```python
Mypaint version: 1.2.0-alpha.20150627+git.bfc9831
System information: Linux-3.13.0-55-generic-x86_64-with-Ubuntu-14.04-trusty
Traceback (most recent call last):
  File "/usr/local/share/mypaint/gui/brushselectionwindow.py", line 130, button_press_cb(self=<BrushList object at 0x7efcc1b97a00 (gui+brushselectionwindow+BrushList at 0x3359ba0)>, widget=<BrushList object at 0x7efcc1b97a00 (gui+brushselectionwindow+BrushList at 0x3359ba0)>, event=<void>)
            self.app.device_monitor.device_used(device)
            return pixbuflist.PixbufList.button_press_cb(self, widget, event)
  variables: {'widget': ('local', <BrushList object at 0x7efcc1b97a00 (gui+brushselectionwindow+BrushList at 0x3359ba0)>), 'self': ('local', <BrushList object at 0x7efcc1b97a00 (gui+brushselectionwindow+BrushList at 0x3359ba0)>), 'pixbuflist.PixbufList.button_press_cb': ('global', <unbound method PixbufList.button_press_cb>), 'event': ('local', <void at 0x43df1b0>)}
  File "/usr/local/share/mypaint/gui/pixbuflist.py", line 309, button_press_cb(self=<BrushList object at 0x7efcc1b97a00 (gui+brushselectionwindow+BrushList at 0x3359ba0)>, widget=<BrushList object at 0x7efcc1b97a00 (gui+brushselectionwindow+BrushList at 0x3359ba0)>, event=<void>)
                self.set_selected(item)
                self.item_selected(item)
                if self.selected is not None:
  variables: {'item': ('local', <ManagedBrush u'kaerhon_v1/paint_radius_2_sm' p=None>), 'self.item_selected': ('local', <MethodWithObservers gui.brushselectionwindow.BrushList.item_selected>)}
  File "/usr/local/share/mypaint/lib/observable.py", line 284, __call__(self=<MethodWithObservers gui.brushselectionwindow.BrushList.item_selected>, *args=(<ManagedBrush u'kaerhon_v1/paint_radius_2_sm' p=None>,), **kwargs={})
                try:
                    observer(observed, *args, **kwargs)
                except BoundObserverMethod._ReferenceError:
  variables: {'observed': ('local', <BrushList object at 0x7efcc1b97a00 (gui+brushselectionwindow+BrushList at 0x3359ba0)>), 'args': ('local', (<ManagedBrush u'kaerhon_v1/paint_radius_2_sm' p=None>,)), 'observer': ('local', <BoundObserverMethod gui.brushselectionwindow.BrushList._item_selected_cb>), 'kwargs': ('local', {})}
  File "/usr/local/share/mypaint/lib/observable.py", line 467, __call__(self=<BoundObserverMethod gui.brushselectionwindow.BrushList._item_selected_cb>, observed=<BrushList object at 0x7efcc1b97a00 (gui+brushselectionwindow+BrushList at 0x3359ba0)>, *args=(<ManagedBrush u'kaerhon_v1/paint_radius_2_sm' p=None>,), **kwargs={})
                raise self._ReferenceError
            self._observer_func(observer, observed, *args, **kwargs)
            del observer
  variables: {'observed': ('local', <BrushList object at 0x7efcc1b97a00 (gui+brushselectionwindow+BrushList at 0x3359ba0)>), 'args': ('local', (<ManagedBrush u'kaerhon_v1/paint_radius_2_sm' p=None>,)), 'self._observer_func': ('local', <function _item_selected_cb at 0x7efce0f958c0>), 'observer': ('local', <BrushList object at 0x7efcc1b97a00 (gui+brushselectionwindow+BrushList at 0x3359ba0)>), 'kwargs': ('local', {})}
  File "/usr/local/share/mypaint/gui/brushselectionwindow.py", line 169, _item_selected_cb(self=<BrushList object at 0x7efcc1b97a00 (gui+brushselectionwindow+BrushList at 0x3359ba0)>, self_=<BrushList object at 0x7efcc1b97a00 (gui+brushselectionwindow+BrushList at 0x3359ba0)>, brush=<ManagedBrush u'kaerhon_v1/paint_radius_2_sm' p=None>)
                    self.bm.brushes_changed(brushes)
            self.bm.select_brush(brush)
  variables: {'self.bm.select_brush': ('local', <bound method BrushManager.select_brush of <gui.brushmanager.BrushManager object at 0x7efce0f60b90>>), 'brush': ('local', <ManagedBrush u'kaerhon_v1/paint_radius_2_sm' p=None>)}
  File "/usr/local/share/mypaint/gui/brushmanager.py", line 701, select_brush(self=<gui.brushmanager.BrushManager object>, brush=<ManagedBrush u'kaerhon_v1/paint_radius_2_sm' p=None>)
            # brush, amongst other things
            self.brush_selected(brush, brushinfo)
  variables: {'self.brush_selected': ('local', <MethodWithObservers gui.brushmanager.BrushManager.brush_selected>), 'brush': ('local', <ManagedBrush u'kaerhon_v1/paint_radius_2_sm' p=None>), 'brushinfo': ('local', <lib.brush.BrushInfo object at 0x7efcc90af1d0>)}
  File "/usr/local/share/mypaint/lib/observable.py", line 284, __call__(self=<MethodWithObservers gui.brushmanager.BrushManager.brush_selected>, *args=(<ManagedBrush u'kaerhon_v1/paint_radius_2_sm' p=None>, <lib.brush.BrushInfo object>), **kwargs={})
                try:
                    observer(observed, *args, **kwargs)
                except BoundObserverMethod._ReferenceError:
  variables: {'observed': ('local', <gui.brushmanager.BrushManager object at 0x7efce0f60b90>), 'args': ('local', (<ManagedBrush u'kaerhon_v1/paint_radius_2_sm' p=None>, <lib.brush.BrushInfo object at 0x7efcc90af1d0>)), 'observer': ('local', <BoundObserverMethod gui.brushmodifier.BrushModifier.brush_selected_cb>), 'kwargs': ('local', {})}
  File "/usr/local/share/mypaint/lib/observable.py", line 467, __call__(self=<BoundObserverMethod gui.brushmodifier.BrushModifier.brush_selected_cb>, observed=<gui.brushmanager.BrushManager object>, *args=(<ManagedBrush u'kaerhon_v1/paint_radius_2_sm' p=None>, <lib.brush.BrushInfo object>), **kwargs={})
                raise self._ReferenceError
            self._observer_func(observer, observed, *args, **kwargs)
            del observer
  variables: {'observed': ('local', <gui.brushmanager.BrushManager object at 0x7efce0f60b90>), 'args': ('local', (<ManagedBrush u'kaerhon_v1/paint_radius_2_sm' p=None>, <lib.brush.BrushInfo object at 0x7efcc90af1d0>)), 'self._observer_func': ('local', <function brush_selected_cb at 0x7efce11ed668>), 'observer': ('local', <gui.brushmodifier.BrushModifier object at 0x7efcc8e90690>), 'kwargs': ('local', {})}
  File "/usr/local/share/mypaint/gui/brushmodifier.py", line 215, brush_selected_cb(self=<gui.brushmodifier.BrushModifier object>, bm=<gui.brushmanager.BrushManager object>, managed_brush=<ManagedBrush u'kaerhon_v1/paint_radius_2_sm' p=None>, brushinfo=<lib.brush.BrushInfo object>)
            b.set_color_hsv(color)
            b.set_string_property("parent_brush_name", managed_brush.name)
  variables: {'color': ('local', None), 'b.set_color_hsv': ('local', <bound method BrushInfo.set_color_hsv of <lib.brush.BrushInfo object at 0x7efce120c890>>)}
  File "/usr/local/share/mypaint/lib/brush.py", line 449, set_color_hsv(self=<lib.brush.BrushInfo object>, hsv=None)
            try:
                h, s, v = hsv
                self.set_base_value('color_h', h)
  variables: {'h': (None, []), 's': ('global', <libmypaint.brushsettings.BrushSetting instance at 0x7efce1cae098>), 'hsv': ('local', None), 'v': (None, [])}
TypeError: 'NoneType' object is not iterable
```
