### ISSUE TITLE
Mypaint not starting on Fedora 20 due to UnicodeDecodeError 

### ISSUE THREAD

**Issue by samirosman** [mypaint/mypaint#360]
I'm getting a UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 0: invalid start byte after updating mypaint on fedora 20.

It use to work up to about 10 days ago.

Trace: http://www.pasteall.org/59342
Locale info: http://www.pasteall.org/59345

**Comment by achadwick** [comment]
Can you confirm what version of MyPaint this is please? Help→About MyPaint.

Fedora 20 is a couple of releases old. Are you able to check the version of libgtk-3-0 (it may be spelled differently - "gtk3"?) you're running please? We're supporting GTK 3.10 or greater in the upcoming release.

Traceback from the IRC report earlier today, via <http://www.pasteall.org/59342>. Thanks for reporting!

```python
Traceback (most recent call last):
  File "/usr/local/bin/mypaint", line 316, in <module>
    main.main(datapath, extradata, old_confpath, version=version)
  File "/usr/local/share/mypaint/gui/main.py", line 194, in main
    run()
  File "/usr/local/share/mypaint/gui/main.py", line 171, in run
    version=version, fullscreen=options.fullscreen
  File "/usr/local/share/mypaint/gui/application.py", line 251, in __init__
    model = lib.document.Document(self.brush)
  File "/usr/local/share/mypaint/lib/document.py", line 296, in __init__
    self.clear()
  File "/usr/local/share/mypaint/lib/document.py", line 789, in clear
    self.add_layer((-1,))
  File "/usr/local/share/mypaint/lib/document.py", line 1054, in add_layer
    **kwds
  File "/usr/local/share/mypaint/lib/document.py", line 975, in do
    self.command_stack.do(cmd)
  File "/usr/local/share/mypaint/lib/command.py", line 65, in do
    command.redo()
  File "/usr/local/share/mypaint/lib/command.py", line 804, in redo
    layers.deepinsert(self._insert_path, self._layer)
  File "/usr/local/share/mypaint/lib/layer/tree.py", line 1228, in deepinsert
    layer.name = self.get_unique_name(layer)
  File "/usr/local/share/mypaint/lib/layer/core.py", line 321, in name
    name = unicode(name)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 0: invalid start byte
```

The MyPaint functions in there look pretty new, and you're even running the same locale as me, `en_GB.utf8`. Very strange.

It looks like this happened when you were starting MyPaint up - is that correct?

**Comment by achadwick** [comment]
Also, could you try running it with debugging turned on and a throwaway clean configuration area? There are some messages about locale setup that are only seen with `MYPAINT_DEBUG` on.

```
<ent/MyPaintProject/mypaint$ MYPAINT_DEBUG=1 mypaint -c /tmp/cfgtmp1
INFO: mypaint: Debugging output enabled via MYPAINT_DEBUG
DEBUG: lib.helpers: Using builtin python 2.6 json support
INFO: mypaint: There is an old-style configuration area in u'/home/andrewc/.mypaint/'
INFO: mypaint: Its contents can be migrated to $XDG_CONFIG_HOME and $XDG_DATA_HOME if you wish.
INFO: mypaint: See the XDG Base Directory Specification for info.
DEBUG: mypaint: getlocale(): (None, None)
DEBUG: mypaint: localepath: u'/usr/share/locale'
DEBUG: mypaint: localepath_brushlib: u'/usr/share/locale'
DEBUG: gui.main: Adding GTK workarounds...
DEBUG: gui.main: GTK workarounds added.
DEBUG: gui.gtk2compat: Using GTK3
CRITICAL: gui.main: Test critical message, please ignore
DEBUG: gui.main: user_datapath: u'/tmp/cfgtmp1'
DEBUG: gui.main: user_confpath: u'/tmp/cfgtmp1'
[the rest doesn't matter much, hopefully]
```

**Comment by achadwick** [comment]
Finally (sorry to be a pain) could you confirm what python sees?

```sh
$ python2
```
```python
>>> import locale
>>> for c in "LC_ALL LC_COLLATE LC_CTYPE LC_MESSAGES LC_MONETARY LC_NUMERIC LC_TIME".split():
...     print (c, locale.getlocale(getattr(locale, c)))
... 
('LC_ALL', (None, None))
('LC_COLLATE', (None, None))
('LC_CTYPE', (None, None))
('LC_MESSAGES', (None, None))
('LC_MONETARY', (None, None))
('LC_NUMERIC', (None, None))
('LC_TIME', (None, None))
>>> locale.getpreferredencoding()
'UTF-8'
>>> locale.getdefaultlocale()
('en_GB', 'UTF-8')
>>> locale.setlocale(locale.LC_ALL, "")
'en_GB.utf8'
>>> for c in "LC_ALL LC_COLLATE LC_CTYPE LC_MESSAGES LC_MONETARY LC_NUMERIC LC_TIME".split():
...     print (c, locale.getlocale(getattr(locale, c)))
... 
('LC_ALL', ('en_GB', 'UTF-8'))
('LC_COLLATE', ('en_GB', 'UTF-8'))
('LC_CTYPE', ('en_GB', 'UTF-8'))
('LC_MESSAGES', ('en_GB', 'UTF-8'))
('LC_MONETARY', ('en_GB', 'UTF-8'))
('LC_NUMERIC', ('en_GB', 'UTF-8'))
('LC_TIME', ('en_GB', 'UTF-8'))
>>> locale.getpreferredencoding()
'UTF-8'
```

**Comment by samirosman** [comment]
Hi Andrew, thanks for looking into this.

Yes the error happens on starting MyPaint version 1.2.0-alpha.20150703+git.59f3dc5

This is the output of the debug:
```
INFO: mypaint: Debugging output enabled via MYPAINT_DEBUG
DEBUG: lib.helpers: Using builtin python 2.6 json support
DEBUG: mypaint: getlocale(): (None, None)
DEBUG: mypaint: localepath: u'/usr/local/share/locale'
DEBUG: mypaint: localepath_brushlib: u'/usr/local/share/locale'
DEBUG: gui.main: Adding GTK workarounds...
DEBUG: gui.main: GTK workarounds added.
DEBUG: gui.gtk2compat: Using GTK3
CRITICAL: gui.main: Test critical message, please ignore
DEBUG: gui.main: user_datapath: u'/tmp/cfgtmp1'
DEBUG: gui.main: user_confpath: u'/tmp/cfgtmp1'
INFO: gui.application: Created basedir u'/tmp/cfgtmp1'
INFO: gui.application: Created data subdir u'/tmp/cfgtmp1/backgrounds'
INFO: gui.application: Created data subdir u'/tmp/cfgtmp1/brushes'
INFO: gui.application: Created data subdir u'/tmp/cfgtmp1/scratchpads'
WARNING: py.warnings: /usr/local/share/mypaint/gui/application.py:549: DeprecationWarning: Gtk.get_action_groups is deprecated
  for ag in self.ui_manager.get_action_groups():

WARNING: py.warnings: /usr/local/share/mypaint/gui/application.py:550: DeprecationWarning: Gtk.get_action is deprecated
  result = ag.get_action(name)

WARNING: py.warnings: /usr/local/share/mypaint/gui/filehandling.py:81: DeprecationWarning: Gtk.list_actions is deprecated
  for action in ag.list_actions():

WARNING: py.warnings: /usr/local/share/mypaint/gui/keyboard.py:242: DeprecationWarning: Gtk.get_accel_path is deprecated
  self.update_keymap(action.get_accel_path())

WARNING: py.warnings: /usr/local/share/mypaint/gui/workspace.py:189: DeprecationWarning: Gtk.add_with_viewport is deprecated
  lscrolls.add_with_viewport(lstack)

DEBUG: gui.workspace: Adding GtkScrolledWindow around canvas
WARNING: py.warnings: /usr/local/share/mypaint/gui/workspace.py:2077: DeprecationWarning: Gdk.get_pointer is deprecated
  screen, ptr_x, ptr_y, _modmask = display.get_pointer()

WARNING: py.warnings: /usr/local/share/mypaint/gui/application.py:244: DeprecationWarning: Gtk.set_active is deprecated
  fs_autohide_action.set_active(workspace.autohide_enabled)

DEBUG: lib.document: Created working-doc cache dir u'/home/samirosman/.cache/mypaint/doc.9q2jC3'
DEBUG: lib.document: cache_updater started
Traceback (most recent call last):
  File "/usr/local/bin/mypaint", line 316, in <module>
    main.main(datapath, extradata, old_confpath, version=version)
  File "/usr/local/share/mypaint/gui/main.py", line 194, in main
    run()
  File "/usr/local/share/mypaint/gui/main.py", line 171, in run
    version=version, fullscreen=options.fullscreen
  File "/usr/local/share/mypaint/gui/application.py", line 251, in __init__
    model = lib.document.Document(self.brush)
  File "/usr/local/share/mypaint/lib/document.py", line 296, in __init__
    self.clear()
  File "/usr/local/share/mypaint/lib/document.py", line 789, in clear
    self.add_layer((-1,))
  File "/usr/local/share/mypaint/lib/document.py", line 1054, in add_layer
    **kwds
  File "/usr/local/share/mypaint/lib/document.py", line 975, in do
    self.command_stack.do(cmd)
  File "/usr/local/share/mypaint/lib/command.py", line 65, in do
    command.redo()
  File "/usr/local/share/mypaint/lib/command.py", line 804, in redo
    layers.deepinsert(self._insert_path, self._layer)
  File "/usr/local/share/mypaint/lib/layer/tree.py", line 1228, in deepinsert
    layer.name = self.get_unique_name(layer)
  File "/usr/local/share/mypaint/lib/layer/core.py", line 321, in name
    name = unicode(name)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 0: invalid start byte


and the python run:
```python
python2
Python 2.7.5 (default, Apr 10 2015, 08:09:05) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-7)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> for c in "LC_ALL LC_COLLATE LC_CTYPE LC_MESSAGES LC_MONETARY LC_NUMERIC LC_TIME".split():
...     print (c, locale.getlocale(getattr(locale, c)))
... 
('LC_ALL', (None, None))
('LC_COLLATE', (None, None))
('LC_CTYPE', (None, None))
('LC_MESSAGES', (None, None))
('LC_MONETARY', (None, None))
('LC_NUMERIC', (None, None))
('LC_TIME', (None, None))
>>> locale.getpreferredencoding()
'UTF-8'
>>> locale.getdefaultlocale()
('en_GB', 'UTF-8')
>>> locale.getdefaultlocale()
('en_GB', 'UTF-8')
>>> for c in "LC_ALL LC_COLLATE LC_CTYPE LC_MESSAGES LC_MONETARY LC_NUMERIC LC_TIME".split():
...     print (c, locale.getlocale(getattr(locale, c)))
... 
('LC_ALL', (None, None))
('LC_COLLATE', (None, None))
('LC_CTYPE', (None, None))
('LC_MESSAGES', (None, None))
('LC_MONETARY', (None, None))
('LC_NUMERIC', (None, None))
('LC_TIME', (None, None))
>>> locale.getpreferredencoding()
'UTF-8'

**Comment by achadwick** [comment]
Ah - I think the Python bit omits `locale.setlocale(locale.LC_ALL, "")`, which is kinda what i needed to see the effects of. Sorry, but can you update the info above (you may need to take `LC_ALL` out of the `"LC_ALL LC_BLAH".split()`, I shouldn't have included it in there).

**Comment by samirosman** [comment]
Here it is:

>>> import locale
>>> for c in "LC_ALL LC_COLLATE LC_CTYPE LC_MESSAGES LC_MONETARY LC_NUMERIC LC_TIME".split():
...     print (c, locale.getlocale(getattr(locale, c)))
... 
('LC_ALL', (None, None))
('LC_COLLATE', (None, None))
('LC_CTYPE', (None, None))
('LC_MESSAGES', (None, None))
('LC_MONETARY', (None, None))
('LC_NUMERIC', (None, None))
('LC_TIME', (None, None))
>>> locale.getpreferredencoding()
'UTF-8'
>>> locale.setlocale(locale.LC_ALL, "")
'en_GB.utf8'
>>> for c in "LC_ALL LC_COLLATE LC_CTYPE LC_MESSAGES LC_MONETARY LC_NUMERIC LC_TIME".split():
...     print (c, locale.getlocale(getattr(locale, c)))
... 
('LC_ALL', ('en_GB', 'UTF-8'))
('LC_COLLATE', ('en_GB', 'UTF-8'))
('LC_CTYPE', ('en_GB', 'UTF-8'))
('LC_MESSAGES', ('en_GB', 'UTF-8'))
('LC_MONETARY', ('en_GB', 'UTF-8'))
('LC_NUMERIC', ('en_GB', 'UTF-8'))
('LC_TIME', ('en_GB', 'UTF-8'))
>>> locale.setlocale(locale.LC_ALL, "")
'en_GB.utf8'
>>> locale.getpreferredencoding()
'UTF-8'
>>> 

Is this what you need?

**Comment by samirosman** [comment]
Working again!! Thanks!

**Comment by achadwick** [comment]
That's surprising! It was actually a bit of guess that the gettext setup could have been involved, and from the data above your system behaves much like mine...

Fingers crossed that turning that rock over has made all the bugs scurry away. Whatever they were :smiley:
