### ISSUE TITLE
Strange save (duplicates). ora~, jpg~, png~. Windows 10. Krita have same problem.

### ISSUE THREAD

**Issue by zb13y** [mypaint/mypaint#395]
I have such strange saves (duplicates) - ora~, jpg~, png~. I can rename them and they will work normally.
Save as - fine save without duplicates.
Export - fine save without duplicates.
Only 'Save' have such problem.
Krita have same problem, only 'File - Save'. I thought that i have some problems with my computer, but Paint.NET saves normally without duplicates. GIMP - i dont know where are there 'Save' option (only saves in .xcf).

**Comment by achadwick** [comment]
Those are backup files, made for safety when there's a pre-existng file having the same name. Nobody has complained about it till now :smile: See #203 for earlier discussion.

You're a Windows user, by the looks of it... would you prefer .ora.bak on that platform? `*~` is hidden on Linux much of the time.

**Comment by zb13y** [comment]
Hmm... i thought that this is backup and turn off autobackup, but it doesn't work so i writed here. Ok thx for explanation.

**Comment by achadwick** [comment]
It's weird behaviour, so it should be documented. Let's call them "backup copies made when overwriting files" in the docs, and explain that it means a different thing to the autosave backups.

If anyone really hates the behaviour, they can turn it off [in lib/fileutils.py](https://github.com/mypaint/mypaint/blob/193264857ced956ebb591e3451b428b707414cf0/lib/fileutils.py#L41) or change the suffix. There is no user-facing toggle yet, and one cannot be added until after the string freeze period we've promised our awesome translators — thank you! — has finished.

**Comment by achadwick** [comment]
I documented the weird behaviour: https://github.com/mypaint/mypaint/wiki/v1.2-Backup-Files-and-Autosaves

Now bumping this to a post-1.2 task for adding a user-facing toggle for this behaviour.

**Comment by achadwick** [comment]
Entry-level task for someone wanting to learn how to work with our prefs dialog. But post-1.2 still since it needs new strings.

**Comment by achadwick** [comment]
### Good new starter task

This is a moderately time-consuming addition of a switch in the preferences that would improve how MyPaint saves files quite a lot. It would be easy for one of us to do the job, but I'd like to give a first-timer the opportunity to learn, if possible.

In addition to the MyPaint specifics, you would be using the Glade UI designer, learning about GTK signals, and getting to grips with some basic Python code manipulation.

### What needs to be done

- Get yourself a Github account.
  - Check out the [hello-world tutorial](https://guides.github.com/activities/hello-world/) they suggest. It's good stuff.
  - Read up on the [branching model](https://guides.github.com/introduction/flow/) too.
- _Add a comment_ below saying that you want to work on this.
  - One of us will assign it to you
- _Fork_ the main MyPaint repository into _your personal area_ on Github.
  - This is a copy that you work on, with full control over it.
- _Clone_ your forked repository to your computer
  - `git clone git@github.com:YOURNAME/mypaint.git`
- _Branch_ your clone, just for this job
  - `git checkout -b issue395-copy-before-overwrite-toggle`
- **Make the edits, and test**. Here are the pieces you will need:
  - A recent [Glade UI designer](https://en.wikipedia.org/wiki/Glade_Interface_Designer), available in most Linux distros.
  - A working local build of MyPaint, inside your clone. [Here's how to get testing interactively](https://github.com/mypaint/mypaint/blob/master/README_LINUX.md).
  - Run GLADE like `glade/run.sh gui/preferenceswindow.glade`
  - Add a GtkSwitch to the Saving section on the Load and Save tab. You will need to add a row to the parent GtkGrid first.
  - Give it a better ID, perhaps "`copy_before_overwriting_switch`".
  - Give the switch a grid width of 2 in Packing, and an alignment that looks like the autosave switch below it.
  - Copy the label for "Prefix when saving scraps:" - this is marked for translation already, and has the right context for translators. Paste it in before the switch, and change the label text to "Make “*~” copies before overwriting:" (with a trailing colon)
  - You could use a GtkCheckButton ("Tick button") instead, and put the naming details in the suffix.
  - If it's a switch, you will need to nominate a signal handler for GObject's "notify" signal.
    - this will be a method in `gui/preferences.py` eventually
    - Open out Signals → GObject and type in a handler for "notify".
    - Call it "copy_before_overwriting_switch_active_notify_cb".
  - Check out [how the existing autosave switch is set up in `gui/preferences.py`](https://github.com/mypaint/mypaint/blob/v1.2.0/gui/preferenceswindow.py#L183). You will need to add something like that for a new prefs key.
    - Read the prefs key state when the window is initialized
    - Handle `copy_before_overwriting_switch_active_notify_cb` and make that write to prefs. Hint: there's one for the autosave switch already.
  - This can be tested now - use the interface you just wired up, and ensure that the setting is saved and loaded correctly.
  - Now the code needs to be modified so that the setting does something
    * The code that makes the annoying `*~` backups is in `lib/fileutils.py` - it's buried in a Python decorator
    * Search for `VIA_TEMPFILE_MAKES_BACKUP_COPY` :smile: 
    * This entire block needs moving to GUI code in `gui/filehandling.py` because stuff in `lib/` cannot normally see the GUI preferences `dict`.
    * It can be moved to [`lib.filehandling.FileHandler._save_doc_to_file()`](https://github.com/mypaint/mypaint/blob/v1.2.0/gui/filehandling.py#L473)
    * Make the backups happen before the call to `doc.model.save()`.
    * The prefs dict can be read here via `self.app.preferences`.
- **When you're done**
  - Test MyPaint can still run interactively from within your clone
  - Test that the toggle works like it should by saving some files and verifying the 
  - _Add_ your changes (protip: use `git gui` for this - it make it super easy to divide your commits into minimal, logical parts!)
  - _Commit_ what you added with `git commit`. [Here's how to write the commit message](https://github.com/mypaint/mypaint/wiki/Contributing-Patches#commit-messages).
- _Push_ your branch back to your area in Github
  - This publishes your changes so we can see them.
- Send a _Pull Request_ to us, from your branch to our `master` branch
  - You can refer to this issue in the PR's description or its comments as `mypaint/mypaint#395`.

You can ask us to help at any stage. There are no silly questions, and we all remember having to learn this stuff.

There are some really detailed video guides to this process on <http://makeapullrequest.com/>, and MyPaint has a growing text-based [Contributing guide](https://github.com/mypaint/mypaint/wiki/Contributing) in English on its wiki.

**Comment by achadwick** [comment]
A little update for first-timers wanting to take this on. With the latest git master, you need to install [libmypaint](https://github.com/mypaint/libmypaint)'s development headers separately before MyPaint will build. To make things simpler, our [MyPaint-testing PPA](https://launchpad.net/~achadwick/+archive/ubuntu/mypaint-testing) has a `libmypaint-dev` package available if you're on Ubuntu. Other [packages of libmypaint](https://github.com/mypaint/libmypaint/wiki/Packaging) are available.

**Comment by mauriciv** [comment]
Hey, I would like to work on this :smiley:

**Comment by achadwick** [comment]
@mauriciv 
Sorry for taking my time to respond! Are you still interested in taking this issue on?

**Comment by KyleRConway** [comment]
@achadwick -- I'm a first-timer and would love to give it a go (though I may need some guidance along the way). If you're open to a little mentoring I'd love for this to be my first code contribution.

**Comment by KyleRConway** [comment]
@achadwick -- I've hit my first snag with the `$ sudo python setup.py demo` command. It appears I don't have certain packages installed (though for many I do). I run Fedora Linux typically. I'll keep looking for solutions on my own -- but if there's an obvious thing I'm missing I'd love to know. Output below. Thanks!

> Package lcms2 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `lcms2.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'lcms2' found
> Package gtk+-3.0 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `gtk+-3.0.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'gtk+-3.0' found
> Package libmypaint-2.0 was not found in the pkg-config search path.
> Perhaps you should add the directory containing `libmypaint-2.0.pc'
> to the PKG_CONFIG_PATH environment variable
> No package 'libmypaint-2.0' found
> Traceback (most recent call last):
>   File "setup.py", line 599, in <module>
>     ext_modules=get_ext_modules(),
>   File "setup.py", line 508, in get_ext_modules
>     extra_compile_args=extra_compile_args,
>   File "setup.py", line 449, in pkgconfig
>     for conf_arg in subprocess.check_output(cmd).split():
>   File "/usr/lib64/python2.7/subprocess.py", line 219, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> subprocess.CalledProcessError: Command '['pkg-config', '--libs', 'pygobject-3.0', 'glib-2.0', 'libpng', 'lcms2', 'gtk+-3.0', 'libmypaint-2.0']' returned non-zero exit status 1

**Comment by KyleRConway** [comment]
@achadwick -- made it a bit further. Switched to xubuntu 17.04, learned (sort of) what a pkgconfig is (and how to set a PKG_CONFIG_PATH), and so on. At any rate, here's my error now:

```
$ python setup.py demo
running demo
running build_ext
building 'lib._mypaintlib' extension
swigging lib/mypaintlib.i to lib/mypaintlib_wrap.cpp
swig -python -Wall -noproxydel -c++ -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/libmypaint-2.0 -I/usr/include/pygobject-3.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DNO_TESTS -o lib/mypaintlib_wrap.cpp lib/mypaintlib.i
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-ZZaKJ6/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include/libmypaint-2.0 -I/usr/include/pygobject-3.0 -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/mirclient -I/usr/include/mircore -I/usr/include/mircookie -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/python2.7 -c lib/mypaintlib_wrap.cpp -o build/temp.linux-x86_64-2.7/lib/mypaintlib_wrap.o -Wall -Wno-sign-compare -Wno-write-strings -D_POSIX_C_SOURCE=200809L -DNO_TESTS -g -fopenmp -pthread -O3
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from lib/mypaintlib.hpp:13:0,
                 from lib/mypaintlib_wrap.cpp:3141:
lib/mapping.hpp:21:29: fatal error: mypaint-mapping.h: No such file or directory
 #include <mypaint-mapping.h>
                             ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

I'd be fine modifying the setup.py script [as suggested here](https://askubuntu.com/questions/758962/problem-to-compile-python-and-c-code-using-ubuntu-ubuntu-12-04-5-lts-problem) but that seems to be outside the purpose of confirming the demo works prior to installing. (Let me know if I'm misunderstanding something here).

Note: this link "[Here's how to get testing interactively](https://github.com/mypaint/mypaint/blob/master/README_LINUX.md)." was 404 above, so I'm trying to follow [this guide here](https://github.com/mypaint/mypaint).

**Comment by achadwick** [comment]
@KyleRConway Thanks for the interest!

Yes, the docs got consolidated since this issue started. Sorry about that. Your best bet is to start at the current "README":https://github.com/mypaint/mypaint/blob/master/README.md. The "Contributing Guide":https://github.com/mypaint/mypaint/blob/master/CONTRIBUTING.md should always contain useful links too.

**Comment by achadwick** [comment]
The old `README_LINUX`, `README_WINDOWS`, `README_...` files got merged into a new [Setup Guide](https://github.com/mypaint/mypaint/blob/922f73dfe6aeb9ebb1f9aa497a2d2de04eff9720/BUILDING.md), by the way. 

@KyleRConway 
It looks like you are missing the `libmypaint` library, which is not yet packaged for many systems. See the [Setup Guide's "Install libmypaint dependency" section](https://github.com/mypaint/mypaint/blob/922f73dfe6aeb9ebb1f9aa497a2d2de04eff9720/BUILDING.md#install-libmypaint-dependency).

(Stop me if you've got this bit sorted already!)

You can think of it this way. MyPaint is mostly Python, but there are some underlying C++ and C parts that need building: specifically the mypaint-ish column on the left in the block diagram below:

```
+---------------------------------------------+
| MyPaint (pure Python)                       |
+-------------------+-------+-----------------+
| C++ "_mypaintlib" | numpy | Python-GI       |
+-------------------+       +-----------------+
| C "libmypaint"    |       | GTK+, GLib, ... |
+-------------------+-------+-----------------+
```

Libmypaint is used by GIMP too, so it has to be built separately. Naturally it has its own set of dependencies... :smile: 

Your best bet is to follow the [generic libmypaint build instructions](https://github.com/mypaint/libmypaint/blob/master/README.md) on a Fedora system. For the remainder of the dependencies, you can use `yum` (... does Fedora use yum? Not sure, but the package names will be the same as in our RHEL/CentOS guides [1](https://github.com/mypaint/libmypaint/blob/dc6bb99d38dcf7174dba81ff7c1cf0057e36c66b/README.md), [2](https://github.com/mypaint/mypaint/blob/83fe7460a1c6e98f47b559f23fec6e681ffdad76/BUILDING.md)).

For Debian/Ubuntu systems, it gets a lot hairier, but you can make nice clean uninstallable `.deb` packages using [the .deb builder we use for the PPA](https://github.com/mypaint/libmypaint.deb).

**Comment by achadwick** [comment]
(I see you're racing ahead!)

While we're still on about libmypaint, please be aware that things are changing quite rapidly on the master branch of both projects (the libmypaint changes are all about being good citizens toward GIMP, but MyPaint needs to adapt!).  You will need the very latest sources for both projects.

Right now, if you can get the following commands to work and give similar output, you *should* be able to build the current MyPaint OK:

```
$ pkg-config --list-all | grep -i mypaint
libmypaint-2.0                      libmypaint - MyPaint's brushstroke rendering library (2.0.0-alpha)
$ pkg-config --libs libmypaint-2.0
-lmypaint-2.0 -ljson-c -lgobject-2.0 -lglib-2.0
$ pkg-config --cflags libmypaint-2.0
-I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libmypaint-2.0
```

That's on a Debian box I've done the .deb tick for, so everything's in /usr not /usr/local. But with the right settings, every machine should be able to compile against headers in `/usr/local/include/libmypaint-2.0`. Does that folder exist on your system? Is it permissioned so that you can read the files in it?

**Comment by KyleRConway** [comment]
Thanks so much! I've been able to start up mypaint (in xubuntu 17.04)!

I've run the commands as suggested. The output looks the same to me:

```
kyconway@xubu-virt:~/mypaint$ pkg-config --list-all | grep -i mypaint
libmypaint-2.0                      libmypaint - MyPaint's brushstroke rendering library (2.0.0-alpha)
kyconway@xubu-virt:~/mypaint$ pkg-config --libs libmypaint-2.0
-L/usr/local/lib -lmypaint-2.0 -ljson-c -lgobject-2.0 -lglib-2.0
kyconway@xubu-virt:~/mypaint$ pkg-config --cflags libmypaint-2.0
-I/usr/local/include/libmypaint-2.0 -I/usr/include/json-c -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
```

I do have `/usr/local/include/libmypaint-2.0` now! 

The error I was getting when mypaint started up (which I was unable to ignore) had the below message and the [search tracker sends me here](https://github.com/mypaint/mypaint/search?utf8=%E2%9C%93&q=TypeError+Couldn%27t+find+foreign+struct+converter+for+%27cairo.Context%27&type=Issues). It was fixed with `sudo apt install python-gi-cairo` thanks to the comments there.

```python
Mypaint version: 1.3.0-alpha+git.922f73df
System information: Linux-4.10.0-19-generic-x86_64-with-Ubuntu-17.04-zesty
Using: Python 2.7.13, GTK 3.22.11, GdkPixbuf 2.36.5, Cairo 1.14.8, GLib 2.52.0
Traceback (most recent call last):
TypeError: Couldn't find foreign struct converter for 'cairo.Context'
```

At any rate, now that it's working I'll begin the next steps as described in your post above. If I hit any other snags I'll reach out! Thanks again!

**Comment by KyleRConway** [comment]
First snaggle on this part here. Guidance helpful.

> Check out how the existing autosave switch is set up in gui/preferences.py. You will need to add something like that for a new prefs key.
> 
>     Read the prefs key state when the window is initialized
>     Handle copy_before_overwriting_switch_active_notify_cb and make that write to prefs. Hint: there's one for the autosave switch already.
> 
> This can be tested now - use the interface you just wired up, and ensure that the setting is saved and loaded correctly.

So I've modified and saved the *.glade file (image below) and am relatively confident I modified the preferences.py file (now named preferenceswindow.py) with the following:

```
def copy_before_overwriting_switch_active_notify_cb(self, switch, param):
        active = bool(switch.props.active)
        self.app.preferences["document.autosave_backups"] = active
        self._autosave_interval_spinbutton.set_sensitive(active)
```

When I go to run mypaint again it's not visually displaying the change under ```edit --> edit preferences```

The glade object is named: copy_before_overwriting_switch and the signals Gobject is ```copy_before_overwriting_switch_active_notify_cb```

I feel like I'm misunderstanding something fundamental to the process (or making a minor error somewhere). Any help appreciated. Thanks for your help so far (and thanks for MyPaint!)

![image](https://user-images.githubusercontent.com/5899012/27893356-cc4d562a-61ca-11e7-8518-e43c3dc12071.png)

**Comment by KyleRConway** [comment]
So, running ```python setup.py demo``` opens mypaint and allows me to see the change. Is this the best method of testing that it's there or is there something else I should be doing at each stage (like re-installing via ```python setup.py managed_install```)
