### ISSUE TITLE
Mypaint testing with GTK3+

### ISSUE THREAD

**Issue by jmaks** [mypaint/mypaint#408]
Hello again ALL!
Today I totally build a new version of gtk3+ and all of depends. Then try to build mypaint and again have some strange log in start up. Here is
```sh
DEBUG: lib.helpers: Using builtin python 2.6 json support
DEBUG: gui.gtk2compat: Using GTK3
WARNING: gui.gtk2compat: "import pygtkcompat" did not work, trying old deprecated way
CRITICAL: gui.main: Test critical message, please ignore
DEBUG: gui.main: user_datapath: u'/tmp/cfgtmp_throwaway_0'
DEBUG: gui.main: user_confpath: u'/tmp/cfgtmp_throwaway_0'
INFO: gui.application: Created basedir u'/tmp/cfgtmp_throwaway_0'
INFO: gui.application: Created data subdir u'/tmp/cfgtmp_throwaway_0/backgrounds'
INFO: gui.application: Created data subdir u'/tmp/cfgtmp_throwaway_0/brushes'
INFO: gui.application: Created data subdir u'/tmp/cfgtmp_throwaway_0/scratchpads'
[New Thread 0x7fffe0564700 (LWP 18354)]
DEBUG: gui.filehandling: Using regex /[.](?:jpeg|jpg|png|ora)$/i for filtering recent files
Traceback (most recent call last):
  File "./mypaint", line 462, in <module>
    main.main(datapath, iconspath, old_confpath, version=version)
  File "/home/jm4k5/bin/mypaint.git/gui/main.py", line 224, in main
    run()
  File "/home/jm4k5/bin/mypaint.git/gui/main.py", line 201, in run
    fullscreen = options.fullscreen,
  File "/home/jm4k5/bin/mypaint.git/gui/application.py", line 267, in __init__
    self.filehandler = filehandling.FileHandler(self)
  File "/home/jm4k5/bin/mypaint.git/gui/filehandling.py", line 107, in __init__
    gtk.RecentFilterFlags.URI
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
    return info.invoke(*args, **kwargs)
TypeError: add_custom() takes exactly 4 non-keyword arguments (1 given)
[Thread 0x7fffe0564700 (LWP 18354) exited]
[Inferior 1 (process 18347) exited with code 01]
```

My os and hardware still the same. In what package or depends bug still be? Dear @achadwick can u helps?

**Comment by jmaks** [comment]
Some of builds stuff
```sh
└> pkg-config --modversion gtk+-3.0                                             [20:27:25]
3.16.6

> pkg-config --modversion pygobject-3.0                                        [20:28:19]
3.10.2

└> pkg-config --modversion pycairo                                              [20:28:35]
1.8.8

└> pkg-config --modversion libpng12                                             [20:31:47]
1.2.49

└> pkg-config --modversion lcms2                                                [20:31:50]
2.7

└> pkg-config --modversion librsvg-2.0                                          [20:32:49]
2.40.10

> dpkg -l | grep ii | grep json-c                                              [20:34:34]
ii  libjson-c-dev:amd64                               0.11-3~bpo7+1

└> dpkg -l | grep ii| grep numpy                                                [20:31:09]
ii  python-numpy                                      1:1.6.2-1.2         
```

**Comment by achadwick** [comment]
This issue tracker isn't a user support forum, and chasing issues with very custom installs like these is very rarely productive. I'd recommend bumping your `python-gobject` to `3.16.2-1` though. Same deal with `python-gi`.

**Comment by achadwick** [comment]
Closing because I think our docs are up to date, and 

Please remember that we have forums too: <http://forum.intilinux.com/#c9> and a mailing list: <https://mail.gna.org/listinfo/mypaint-discuss> and IRC: <irc://freenode/mypaint>.
