### ISSUE TITLE
Regression after updating to GTK 3.18.0: sparse/while-painting drawing raises "AttributeError: 'gi.repository.Gdk' object has no attribute 'rectangle_intersect'"

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#433]
While painting with the most recent MSYS2, I get:

```python
Mypaint version: 1.2.0-beta.1.127+git.5ce9ff7.dirty
System information: Windows-7-6.1.7601-SP1
Traceback (most recent call last):
  File "./gui/tileddrawwidget.py", line 897, draw_cb(self=<CanvasRenderer object at 0x7e713c4 (gui+tileddrawwidget+CanvasRenderer at 0x28e2148)>, widget=<CanvasRenderer object at 0x7e713c4 (gui+tileddrawwidget+CanvasRenderer at 0x28e2148)>, cr=<cairo.Context object>)
            render_info = self._render_prepare(cr)
            self._render_execute(cr, *render_info)
            # Model coordinate space:
  variables: {'cr': ('local', <cairo.Context object at 0x029d6ee0>), 'render_info': ('local', (cairo.Matrix(1, 0, 0, 1, 427, 216), <lib.pixbufsurface.Surface object at 0x08aa3fcc>, True, 0, (779, 285, 10, 10))), 'self._render_execute': ('local', <bound method CanvasRenderer._render_execute of <CanvasRenderer object at 0x7e713c4 (gui+tileddrawwidget+CanvasRenderer at 0x28e2148)>>)}
  File "./gui/tileddrawwidget.py", line 1118, _render_execute(self=<CanvasRenderer object at 0x7e713c4 (gui+tileddrawwidget+CanvasRenderer at 0x28e2148)>, cr=<cairo.Context object>, transformation=cairo.Matrix(1, 0, 0, 1, 427, 216), surface=<lib.pixbufsurface.Surface object>, sparse=True, mipmap_level=0, clip_region=(779, 285, 10, 10))
                        clip_region,
                        translation_only,
                    )
  variables: {'translation_only': ('local', True)}
  File "./gui/tileddrawwidget.py", line 1017, _tile_is_visible(self=<CanvasRenderer object at 0x7e713c4 (gui+tileddrawwidget+CanvasRenderer at 0x28e2148)>, tx=5, ty=1, transformation=cairo.Matrix(1, 0, 0, 1, 427, 216), clip_region=(779, 285, 10, 10), translation_only=True)
            bb_r.x, bb_r.y, bb_r.width, bb_r.height = bbox
            intersects, isect_r = gdk.rectangle_intersect(bb_r, c_r)
            return intersects
  variables: {'isect_r': (None, []), 'intersects': (None, [])}
  File "C:/msys64/mingw32/lib/python2.7/site-packages/gi/overrides/__init__.py", line 39, __getattr__(self=<GdkProxyModule <IntrospectionModule 'Gdk' from ...ingw32\\lib\\girepository-1.0\\Gdk-3.0.typelib'>>, name='rectangle_intersect')
        def __getattr__(self, name):
            return getattr(self._introspection_module, name)
  variables: {'getattr': ('builtin', <built-in function getattr>), 'self._introspection_module': ('local', <IntrospectionModule 'Gdk' from 'C:\\msys64\\mingw32\\lib\\girepository-1.0\\Gdk-3.0.typelib'>), 'name': ('local', 'rectangle_intersect')}
  File "C:/msys64/mingw32/lib/python2.7/site-packages/gi/module.py", line 137, __getattr__(self=<IntrospectionModule 'Gdk' from 'C:\\msys64\\mingw32\\lib\\girepository-1.0\\Gdk-3.0.typelib'>, name='rectangle_intersect')
                raise AttributeError("%r object has no attribute %r" % (
                                     self.__name__, name))
  variables: {'self.__name__': ('local', 'gi.repository.Gdk'), 'name': ('local', 'rectangle_intersect')}
AttributeError: 'gi.repository.Gdk' object has no attribute 'rectangle_intersect'
```

This looks fun: that function was definitely there before!
My MSYS2 installation has recently upgraded GTK/GDK to version 3.18.0, so maybe that's it.

```
$ pacman -Ss mingw-w64.\*gtk3
mingw32/mingw-w64-i686-gtk3 3.18.0-1 [installed]
    GObject-based multi-platform GUI toolkit (v3) (mingw-w64)
mingw32/mingw-w64-i686-webkitgtk3 2.4.9-1
    GTK+ Web content engine library (mingw-w64)
mingw64/mingw-w64-x86_64-gtk3 3.18.0-1 [installed]
    GObject-based multi-platform GUI toolkit (v3) (mingw-w64)
mingw64/mingw-w64-x86_64-webkitgtk3 2.4.9-1
    GTK+ Web content engine library (mingw-w64)
```

**Comment by achadwick** [comment]
Happens on every attempt to paint.

Interestingly, loading a file or restoring an autosave will redraw the image without error.

Contrasting with my Debian amd64 development box, which uses gtk+ 3.16.6: no regression, painting works.

Contrasting MINGW32 vs. MINGW64 (MSYS2's terminology for native Windows 32-bit and 64-bit compile targets of mingw-w64): the regression is present with both.
