### ISSUE TITLE
Doesn't start -- 'TypeError: boxed cannot be created directly'[..]

### ISSUE THREAD

**Issue by 0ion9** [mypaint/mypaint#437]
Log:

```
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/usr/local'
/usr/local/share/mypaint/lib/fileutils.py:31: PyGIWarning: GdkPixbuf was imported without specifying a version first. Use gi.require_version('GdkPixbuf', '2.0') before import to ensure that the right version gets loaded.
  from gi.repository import GdkPixbuf
INFO: mypaint: There is an old-style configuration area in u'/home/kau/.mypaint/'
INFO: mypaint: Its contents can be migrated to $XDG_CONFIG_HOME and $XDG_DATA_HOME if you wish.
INFO: mypaint: See the XDG Base Directory Specification for info.
INFO: lib.i18n: POSIX: LANG='en_AU.UTF-8'
INFO: lib.i18n: POSIX: LANGUAGE=None
/usr/local/share/mypaint/gui/main.py:19: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
WARNING: gui.workspace: gdk_screen_get_monitor_geometry() returned NULL: using screen size instead as a fallback.
Traceback (most recent call last):
  File "/usr/local/bin/mypaint", line 462, in <module>
    main.main(datapath, iconspath, old_confpath, version=version)
  File "/usr/local/share/mypaint/gui/main.py", line 224, in main
    run()
  File "/usr/local/share/mypaint/gui/main.py", line 201, in run
    fullscreen = options.fullscreen,
  File "/usr/local/share/mypaint/gui/application.py", line 286, in __init__
    workspace.build_from_layout(self.preferences["workspace.layout"])
  File "/usr/local/share/mypaint/gui/workspace.py", line 284, in build_from_layout
    set_initial_window_position(toplevel_win, toplevel_pos)
  File "/usr/local/share/mypaint/gui/workspace.py", line 2112, in set_initial_window_position
    targ_geom = _get_target_area_geometry(screen, targ_mon_num)
  File "/usr/local/share/mypaint/gui/workspace.py", line 2214, in _get_target_area_geometry
    geom = Gdk.Rectangle()
TypeError: boxed cannot be created directly; try using a constructor, see: help(Gdk.Rectangle)
```

Platform:
* Arch Linux x86_64

gtk3 versions tested : 
* 3.17.8.r112.gcf0e087
* 3.18.1.r3.g40190c2

glib versions tested:
* 2.45.7.34.g4025b5a
* 2.46.0.55.g58ec667

**Comment by achadwick** [comment]
GTK/GDK 3.10.0 on Windows MSYS2:

```python
>>> from gi.repository import Gdk
__main__:1: PyGIWarning: Gdk was imported without specifying a version first. Use gi.require_version('Gdk', '3.0') before import to ensure that the right version gets loaded.
>>> Gdk.Rectangle()
<GdkRectangle at 0x254d1f0>
>>> r = Gdk.Rectangle()
>>> dir(r)
['__class__', '__del__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__gtype__', '__hash__', '__info__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_free_on_dealloc', 'copy', 'height', 'intersect', 'union', 'width', 'x', 'y']
>>> dir(Gdk.Rectangle)
['__class__', '__del__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__gtype__', '__hash__', '__info__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_free_on_dealloc', 'copy', 'height', 'intersect', 'union', 'width', 'x', 'y']
>>>
```

and on Debian with GDK/GTK 3.16.6:

```python
>>> from gi.repository import Gdk
>>> Gdk._version
'3.0'
>>> Gdk.Rectangle()
<CairoRectangleInt at 0x283bfc0>
>>> r = Gdk.Rectangle()
>>> dir(r)
['__class__', '__del__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__gtype__', '__hash__', '__info__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_free_on_dealloc', 'copy', 'height', 'width', 'x', 'y']
>>> dir(Gdk.Rectangle)
['__class__', '__del__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__gtype__', '__hash__', '__info__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_free_on_dealloc', 'copy', 'height', 'width', 'x', 'y']
>>>
```

There have been some changes in the way the GDK rectangle functions are annotated recently: see our otherwise unrelated commit ca55c4df3ef1d75587623a14fb3c12f60049e403. This might be another head of the same upstream messup.

The solution may just be to use our own rectangle class, just like the fix in the above commit. I'll see if I can add some construction sugar for that case.

**Comment by achadwick** [comment]
Sorry, that should read 3.18.0 above, for Windows+MSYS2.

Cannot reproduce on amd64 Debian unstable's `libgtk-3-0` version 3.18.1-1 or in 64-bit Windows 7 Professional N + MSYS2 using `mingw-w64-x86_64-gtk3` version 3.18.1-1.

This non-constructability of a fundamental GDK type should be reported to the Arch maintainers instead of in the MyPaint issue tracker. However other things are afoot with GdkRectangle that are making me reconsider using it generally. Watch this space.

**Comment by achadwick** [comment]
Patch is in, and needs testing in this unhappy case.

@0ion9 There may be other breakages that happen on your system, but I strongly suspect that it's because you have a broken gobject-introspection typelib for Gdk installed, or because Arch's is busted right now :fearful:

**Comment by 0ion9** [comment]
Yeah, I'm not sure what's going on. I updated gobject-introspection-git, glib2-git and gtk3-git, and this message is no longer occurring, instead I get 

Traceback (most recent call last):
  File "/usr/local/share/mypaint/gui/tileddrawwidget.py", line 196, in _size_allocate_cb
    new_pos = self.translate_coordinates(toplevel, alloc.x, alloc.y)
AttributeError: 'Rectangle' object has no attribute 'x'

Which looks like the typelib hypothesis, I guess..

**Comment by achadwick** [comment]
@0ion9 Do you need an equivalent of <http://packages.debian.org/gir1.2-freedesktop>? GTK3 uses a  typedef chain: GtkAllocation → GdkRectangle → cairo_rectangle_int_t.


Debian:
```
$ dpkg -L gir1.2-freedesktop
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/gir1.2-freedesktop
/usr/share/doc/gir1.2-freedesktop/AUTHORS
/usr/share/doc/gir1.2-freedesktop/NEWS.gz
/usr/share/doc/gir1.2-freedesktop/changelog.Debian.gz
/usr/share/doc/gir1.2-freedesktop/README
/usr/share/doc/gir1.2-freedesktop/copyright
/usr/share/doc/gir1.2-freedesktop/changelog.Debian.amd64.gz
/usr/share/doc/gir1.2-freedesktop/TODO
/usr/share/doc/gir1.2-freedesktop/CONTRIBUTORS
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/girepository-1.0
/usr/lib/x86_64-linux-gnu/girepository-1.0/xft-2.0.typelib
/usr/lib/x86_64-linux-gnu/girepository-1.0/xlib-2.0.typelib
/usr/lib/x86_64-linux-gnu/girepository-1.0/DBusGLib-1.0.typelib
/usr/lib/x86_64-linux-gnu/girepository-1.0/cairo-1.0.typelib
/usr/lib/x86_64-linux-gnu/girepository-1.0/GL-1.0.typelib
/usr/lib/x86_64-linux-gnu/girepository-1.0/DBus-1.0.typelib
/usr/lib/x86_64-linux-gnu/girepository-1.0/fontconfig-2.0.typelib
/usr/lib/x86_64-linux-gnu/girepository-1.0/freetype2-2.0.typelib
/usr/lib/x86_64-linux-gnu/girepository-1.0/xfixes-4.0.typelib
/usr/lib/x86_64-linux-gnu/girepository-1.0/xrandr-1.3.typelib
/usr/lib/x86_64-linux-gnu/girepository-1.0/libxml2-2.0.typelib
```

MSYS2 on Windows:

```
$ pacman -Qo /mingw64/lib/girepository-1.0/cairo-1.0.typelib
/mingw64/lib/girepository-1.0/cairo-1.0.typelib is owned by mingw-w64-x86_64-gobject-introspection-runtime 1.46.0-1
```

**Comment by 0ion9** [comment]
For me that's gobject-introspection-git, which is installed:

yaourt -Ql gobject-introspection-git | sed s/gobject-introspection-git\ // |grep typelib
/usr/include/gobject-introspection-1.0/gitypelib.h
/usr/lib/girepository-1.0/DBus-1.0.typelib
/usr/lib/girepository-1.0/DBusGLib-1.0.typelib
/usr/lib/girepository-1.0/GIRepository-2.0.typelib
/usr/lib/girepository-1.0/GL-1.0.typelib
/usr/lib/girepository-1.0/GLib-2.0.typelib
/usr/lib/girepository-1.0/GModule-2.0.typelib
/usr/lib/girepository-1.0/GObject-2.0.typelib
/usr/lib/girepository-1.0/Gio-2.0.typelib
/usr/lib/girepository-1.0/cairo-1.0.typelib
/usr/lib/girepository-1.0/fontconfig-2.0.typelib
/usr/lib/girepository-1.0/freetype2-2.0.typelib
/usr/lib/girepository-1.0/libxml2-2.0.typelib
/usr/lib/girepository-1.0/win32-1.0.typelib
/usr/lib/girepository-1.0/xfixes-4.0.typelib
/usr/lib/girepository-1.0/xft-2.0.typelib
/usr/lib/girepository-1.0/xlib-2.0.typelib
/usr/lib/girepository-1.0/xrandr-1.3.typelib

**Comment by 0ion9** [comment]
@achadwick Finally fixed upstream, I think. I can start mypaint and draw now.
This is after upgrading gtk3-git to 3.19.1.r395.g51dc487 and glib2-git to 2.47.1.28.gdb4df99.

Note that the following message is printed during startup:

```
/usr/lib/python2.7/site-packages/pygtkcompat/pygtkcompat.py:180: TypeError: Passing arguments to gi.types.Boxed.__init__() is deprecated. All arguments passed will be ignored.
  rect = Gdk.Rectangle(0, 0, 0, 0)
```

**Comment by achadwick** [comment]
Whoops, wrong issue reference in caacdac9960426fbeb49de5e0c471b2b8b8e87be. That second "May help with..." should be referring to #550.
