### ISSUE TITLE
"IOError: [Errno 32] Broken pipe" in v1.1.0

### ISSUE THREAD

**Issue by ronnietucker** [mypaint/mypaint#465]
I'm getting a Programming Error Detected message popping up every now and again:
![screenshot from 2015-10-27 19-22-04](https://cloud.githubusercontent.com/assets/10391379/10770362/ccf365e8-7ce2-11e5-8412-0df85d95edd8.jpg)

Here's a copy of the text error that is displayed in the window:

```
Traceback (most recent call last):
  File "/usr/share/mypaint/gui/drawwindow.py", line 352, key_release_event_cb(self=<Window object at 0x7fcf1e020640 (GtkWindow at 0x2a36090)>, win=<Window object at 0x7fcf1e020640 (GtkWindow at 0x2a36090)>, event=<gtk.gdk.Event at 0x7fcf1c0dbad0: GDK_KEY_RELEASE keyval=space>)
            # Forward the event (see above)
            return target_doc.modes.top.key_release_cb(win, target_tdw, event)
  variables: {'win': ('local', <Window object at 0x7fcf1e020640 (GtkWindow at 0x2a36090)>), 'target_tdw': ('local', <TiledDrawWidget object at 0x7fcf2ebc6780 (GtkEventBox at 0x27adef0)>), 'event': ('local', <gtk.gdk.Event at 0x7fcf1c0dbad0: GDK_KEY_RELEASE keyval=space>), 'target_doc.modes.top.key_release_cb': ('local', <bound method SwitchableFreehandMode.key_release_cb of <gui.canvasevent.SwitchableFreehandMode object at 0x7fcf2ebd8750>>)}
  File "/usr/share/mypaint/gui/canvasevent.py", line 1186, key_release_cb(self=<gui.canvasevent.PanViewMode object>, win=<Window object at 0x7fcf1e020640 (GtkWindow at 0x2a36090)>, tdw=<TiledDrawWidget object at 0x7fcf2ebc6780 (GtkEventBox at 0x27adef0)>, event=<gtk.gdk.Event at 0x7fcf1c0dbad0: GDK_KEY_RELEASE keyval=space>)
                return False
            return super(SpringLoadedDragMode, self).key_release_cb(win,tdw,event)
  variables: {'key_release_cb': (None, []), 'super': ('builtin', <type 'super'>), 'win': ('local', <Window object at 0x7fcf1e020640 (GtkWindow at 0x2a36090)>), 'self': ('local', <gui.canvasevent.PanViewMode object at 0x7fcf0e3aef90>), 'tdw': ('local', <TiledDrawWidget object at 0x7fcf2ebc6780 (GtkEventBox at 0x27adef0)>), 'event': ('local', <gtk.gdk.Event at 0x7fcf1c0dbad0: GDK_KEY_RELEASE keyval=space>), 'SpringLoadedDragMode': ('global', <class 'gui.canvasevent.SpringLoadedDragMode'>)}
  File "/usr/share/mypaint/gui/canvasevent.py", line 916, key_release_cb(self=<gui.canvasevent.PanViewMode object>, win=<Window object at 0x7fcf1e020640 (GtkWindow at 0x2a36090)>, tdw=<TiledDrawWidget object at 0x7fcf2ebc6780 (GtkEventBox at 0x27adef0)>, event=<gtk.gdk.Event at 0x7fcf1c0dbad0: GDK_KEY_RELEASE keyval=space>)
                    return True
            return super(SpringLoadedModeMixin,self).key_release_cb(win,tdw,event)
  variables: {'key_release_cb': (None, []), 'super': ('builtin', <type 'super'>), 'win': ('local', <Window object at 0x7fcf1e020640 (GtkWindow at 0x2a36090)>), 'self': ('local', <gui.canvasevent.PanViewMode object at 0x7fcf0e3aef90>), 'SpringLoadedModeMixin': ('global', <class 'gui.canvasevent.SpringLoadedModeMixin'>), 'tdw': ('local', <TiledDrawWidget object at 0x7fcf2ebc6780 (GtkEventBox at 0x27adef0)>), 'event': ('local', <gtk.gdk.Event at 0x7fcf1c0dbad0: GDK_KEY_RELEASE keyval=space>)}
  File "/usr/share/mypaint/gui/canvasevent.py", line 1139, key_release_cb(self=<gui.canvasevent.PanViewMode object>, win=<Window object at 0x7fcf1e020640 (GtkWindow at 0x2a36090)>, tdw=<TiledDrawWidget object at 0x7fcf2ebc6780 (GtkEventBox at 0x27adef0)>, event=<gtk.gdk.Event at 0x7fcf1c0dbad0: GDK_KEY_RELEASE keyval=space>)
                if event.keyval == self._start_keyval:
                    self._stop_drag()
                    self._start_keyval = None
  variables: {'self._stop_drag': ('local', <bound method PanViewMode._stop_drag of <gui.canvasevent.PanViewMode object at 0x7fcf0e3aef90>>)}
  File "/usr/share/mypaint/gui/canvasevent.py", line 959, _stop_drag(self=<gui.canvasevent.PanViewMode object>, t=0L)
            self._grab_widget = None
            self.drag_stop_cb()
            self._reset_drag_state()
  variables: {'self.drag_stop_cb': ('local', <bound method PanViewMode.drag_stop_cb of <gui.canvasevent.PanViewMode object at 0x7fcf0e3aef90>>)}
  File "/usr/share/mypaint/gui/canvasevent.py", line 1216, drag_stop_cb(self=<gui.canvasevent.PanViewMode object>)
                if not self.unmodified_persist:
                    self.doc.modes.pop()
            return super(OneshotDragModeMixin, self).drag_stop_cb()
  File "/usr/share/mypaint/gui/canvasevent.py", line 774, pop(self=<ModeStack [SwitchableFreehandMode]>)
            top_mode.enter(doc=self._doc)
            self._notify_observers()
  variables: {'self._notify_observers': ('local', <bound method ModeStack._notify_observers of <ModeStack [SwitchableFreehandMode]>>)}
  File "/usr/share/mypaint/gui/canvasevent.py", line 720, _notify_observers(self=<ModeStack [SwitchableFreehandMode]>)
            for func in self.observers:
                func(top_mode)
  variables: {'top_mode': ('local', <gui.canvasevent.SwitchableFreehandMode object at 0x7fcf2ebd8750>), 'func': ('local', <bound method Document.mode_stack_changed_cb of <gui.document.Document object at 0x7fcf2ebd8310>>)}
  File "/usr/share/mypaint/gui/document.py", line 1024, mode_stack_changed_cb(self=<gui.document.Document object>, mode=<gui.canvasevent.SwitchableFreehandMode object>)
            # Activate the action corresponding to the current top mode.
            print "DEBUG: mode stack updated:", self.modes
            action_name = getattr(mode, '__action_name__', None)
  variables: {'self.modes': ('local', <ModeStack [SwitchableFreehandMode]>)}
IOError: [Errno 32] Broken pipe
```

I'm using Ubuntu 15.10, MyPaint 1.1.0 with a Wacom Bamboo. I've never had this problem is previous versions.

**Comment by achadwick** [comment]
Are you redirecting the output somewhere and then killing whatever's reading from the pipe?
On Ubuntu, that might include things the system ships that help when reporting errors.
Basically, a "broken pipe" signal in response to a basic I/O call like "print" generally indicates some external misconfiguration, but I can't tell from looking at this what that might be.
A look in the system logs might help identify the culprit.

Anyway, that debug statement should never have been a `print` statement anyway! So it was changed after v1.1.0: https://github.com/mypaint/mypaint/blob/719baccbba884e78071220faad003deec706ce7f/gui/document.py#L1912

Is this issue still happening with your desktop/system configuration and the most recent v1.2.0-beta?

**Comment by ronnietucker** [comment]
Case closed. The 1.2b version is spot on and has no errors.

Glad I upgraded.   :)

Thanks!
