### ISSUE TITLE
Autosave error - last commit 1.3.0-alpha+git.f31a4be

### ISSUE THREAD

**Issue by americogobbo** [mypaint/mypaint#589]
#### Description
Error after that I have updated the git master today.

#### Steps to reproduce

Open MyPaint in the default way.

#### Traceback

```python
Mypaint version: 1.3.0-alpha+git.f31a4be
System information: Linux-3.16.0-60-generic-x86_64-with-Ubuntu-14.04-trusty
Traceback (most recent call last):
  File "/home/jag/installs/mypaint/gui/application.py", line 412, _at_application_start(self=<gui.application.Application object>, filenames=[], fullscreen=None)
                autosave_recovery = gui.autorecover.Presenter(self)
                autosave_recovery.run(startup=True)
  variables: {'autosave_recovery.run': ('local', <bound method Presenter.run of <gui.autorecover.Presenter object at 0x7fd0b4e37f10>>), 'True': ('builtin', True), 'startup': (None, [])}
  File "/home/jag/installs/mypaint/gui/autorecover.py", line 132, run(self=<gui.autorecover.Presenter object>, startup=True)
            # Only run if there are autosaves which can be recovered.
            autosaves = self._reload_liststore()
            if not autosaves:
  variables: {'autosaves': (None, []), 'self._reload_liststore': ('local', <bound method Presenter._reload_liststore of <gui.autorecover.Presenter object at 0x7fd0b4e37f10>>)}
  File "/home/jag/installs/mypaint/gui/autorecover.py", line 119, _reload_liststore(self=<gui.autorecover.Presenter object>)
                self._liststore.append((thumb, desc, autosave.path))
            return autosave
  variables: {'autosave': (None, [])}
UnboundLocalError: local variable 'autosave' referenced before assignment
```

**Comment by odysseywestra** [comment]
I received  a similar error as well for 96101ba. 

```python
Mypaint version: 1.3.0-alpha+git.96101ba
System information: Linux-4.2.0-27-generic-x86_64-with-Ubuntu-15.10-wily
Traceback (most recent call last):
  File "/usr/local/share/mypaint/gui/autorecover.py", line 227, _delete_autosave_button_clicked_cb(self=<gui.autorecover.Presenter object>, button=<Button object at 0x7f72f48b97d0 (GtkButton at 0x3c65f30)>)
                logger.info("Deleted %r successfully.", autosave.path)
            self._reload_liststore()
  variables: {'self._reload_liststore': ('local', <bound method Presenter._reload_liststore of <gui.autorecover.Presenter object at 0x7f72f45ae8d0>>)}
  File "/usr/local/share/mypaint/gui/autorecover.py", line 119, _reload_liststore(self=<gui.autorecover.Presenter object>)
                self._liststore.append((thumb, desc, autosave.path))
            return autosave
  variables: {'autosave': (None, [])}
UnboundLocalError: local variable 'autosave' referenced before assignment

**Comment by Ico-dY** [comment]
Same problem, here:

```python
Mypaint version: 1.3.0-alpha+git.96101ba
System information: Linux-3.13.0-77-generic-x86_64-with-Ubuntu-14.04-trusty
Traceback (most recent call last):
  File "/usr/local/share/mypaint/gui/application.py", line 412, _at_application_start(self=<gui.application.Application object>, filenames=[], fullscreen=None)
                autosave_recovery = gui.autorecover.Presenter(self)
                autosave_recovery.run(startup=True)
  variables: {'autosave_recovery.run': ('local', <bound method Presenter.run of <gui.autorecover.Presenter object at 0x7f88c3157f10>>), 'True': ('builtin', True), 'startup': (None, [])}
  File "/usr/local/share/mypaint/gui/autorecover.py", line 132, run(self=<gui.autorecover.Presenter object>, startup=True)
            # Only run if there are autosaves which can be recovered.
            autosaves = self._reload_liststore()
            if not autosaves:
  variables: {'autosaves': (None, []), 'self._reload_liststore': ('local', <bound method Presenter._reload_liststore of <gui.autorecover.Presenter object at 0x7f88c3157f10>>)}
  File "/usr/local/share/mypaint/gui/autorecover.py", line 119, _reload_liststore(self=<gui.autorecover.Presenter object>)
                self._liststore.append((thumb, desc, autosave.path))
            return autosave
  variables: {'autosave': (None, [])}
UnboundLocalError: local variable 'autosave' referenced before assignment
```

**Comment by dothiko** [comment]
I recieved same error:

```python
Mypaint version: 1.3.0-alpha+git.1ac76bc
System information: Linux-3.16.0-45-generic-x86_64-with-Ubuntu-14.04-trusty
Traceback (most recent call last):
  File "/home/dothiko/python/others/mypaint_src/mypaint/gui/application.py", line 412, _at_application_start(self=<gui.application.Application object>, filenames=[], fullscreen=None)
                autosave_recovery = gui.autorecover.Presenter(self)
                autosave_recovery.run(startup=True)
  variables: {'autosave_recovery.run': ('local', <bound method Presenter.run of <gui.autorecover.Presenter object at 0x7f5f479677d0>>), 'True': ('builtin', True), 'startup': (None, [])}
  File "/home/dothiko/python/others/mypaint_src/mypaint/gui/autorecover.py", line 132, run(self=<gui.autorecover.Presenter object>, startup=True)
            # Only run if there are autosaves which can be recovered.
            autosaves = self._reload_liststore()
            if not autosaves:
  variables: {'autosaves': (None, []), 'self._reload_liststore': ('local', <bound method Presenter._reload_liststore of <gui.autorecover.Presenter object at 0x7f5f479677d0>>)}
  File "/home/dothiko/python/others/mypaint_src/mypaint/gui/autorecover.py", line 119, _reload_liststore(self=<gui.autorecover.Presenter object>)
                self._liststore.append((thumb, desc, autosave.path))
            return autosave
  variables: {'autosave': (None, [])}
UnboundLocalError: local variable 'autosave' referenced before assignment
```

I created a patch to avoid this annoying startup exception,but something going wrong,so deleted it.
only inserting 
```python
        autosave = None
```
at line 106 of gui/autorecover.py can avoid this exception, at least for me.
