### ISSUE TITLE
JPEG saving sometimes fails for huge canvases (insufficient memory? 'RuntimeError: could not create GdkPixbuf object') (was: Won't let me save a jpg?)

### ISSUE THREAD

**Issue by Lumil** [mypaint/mypaint#62]
I will try and save my work as a jpg or jpeg and it will not work. 
these are the details I get. I'm not a technical wizz so sorry if the answer is obvious but the problem is stopping me from showing any pieces of my work.Everything had been working fine till now. 

```
Anyway these are the details that keep popping up
Traceback (most recent call last):
  File "C:\Program Files\MyPaint\library.zip\gui\filehandling.py", line 451, save_as_cb(self=<gui.filehandling.FileHandler object>, action=<gtk.Action object at 0x2d4acf0 (GtkAction at 0x32187e0)>)
            else:
                self.save_as_dialog(self.save_file, suggested_filename = current_filename)
  File "C:\Program Files\MyPaint\library.zip\gui\filehandling.py", line 511, save_as_dialog(self=<gui.filehandling.FileHandler object>, save_method_reference=<bound method FileHandler.wrapper of <gui.filehandling.FileHandler object>>, suggested_filename=u'C:\\Users\\Izzie\\Documents\\MyPaint\\Me- dwarf.bmp', start_in_folder=None, export=False, **options={'quality': 90})
                        else:
                            save_method_reference(filename, **options)
                        break
  File "C:\Program Files\MyPaint\library.zip\gui\drawwindow.py", line 46, wrapper(self=<gui.filehandling.FileHandler object>, *args=(u'C:\\Users\\Izzie\\Documents\\MyPaint\\Me- dwarf.jpg',), **kwargs={'quality': 90})
            try:
                func(self, *args, **kwargs)
                # gtk main loop may be called in here...
  File "C:\Program Files\MyPaint\library.zip\gui\filehandling.py", line 278, save_file(self=<gui.filehandling.FileHandler object>, filename=u'C:\\Users\\Izzie\\Documents\\MyPaint\\Me- dwarf.jpg', export=False, **options={'quality': 90})
        def save_file(self, filename, export=False, **options):
            thumbnail_pixbuf = self.save_doc_to_file(filename, self.doc, export=export, **options)
            if not export:
  File "C:\Program Files\MyPaint\library.zip\gui\filehandling.py", line 311, save_doc_to_file(self=<gui.filehandling.FileHandler object>, filename=u'C:\\Users\\Izzie\\Documents\\MyPaint\\Me- dwarf.jpg', doc=<gui.document.Document object>, export=False, **options={'quality': 90})
                    w, h = tiledsurface.N, tiledsurface.N # TODO: support for other sizes
                thumbnail_pixbuf = doc.model.save(filename, feedback_cb=self.gtk_main_tick, **options)
                self.lastsavefailed = False
  File "C:\Program Files\MyPaint\library.zip\lib\document.py", line 367, save(self=<lib.document.Document instance>, filename=u'C:\\Users\\Izzie\\Documents\\MyPaint\\Me- dwarf.jpg', **kwargs={'feedback_cb': <function gtk_main_tick>, 'quality': 90})
            try:
                save(filename, **kwargs)
            except gobject.GError, e:
  File "C:\Program Files\MyPaint\library.zip\lib\document.py", line 478, save_jpg(self=<lib.document.Document instance>, filename=u'C:\\Users\\Izzie\\Documents\\MyPaint\\Me- dwarf.jpg', quality=90, **kwargs={'feedback_cb': <function gtk_main_tick>})
                x, y, w, h = 0, 0, N, N # allow to save empty documents
            pixbuf = self.render_as_pixbuf(x, y, w, h, **kwargs)
            pixbuf.save(filename, 'jpeg', options={'quality':str(quality)})
  File "C:\Program Files\MyPaint\library.zip\lib\document.py", line 404, render_as_pixbuf(self=<lib.document.Document instance>, *args=(0, 0, 32640, 23552), **kwargs={'feedback_cb': <function gtk_main_tick>})
        def render_as_pixbuf(self, *args, **kwargs):
            return pixbufsurface.render_as_pixbuf(self, *args, **kwargs)
  File "C:\Program Files\MyPaint\library.zip\lib\pixbufsurface.py", line 104, render_as_pixbuf(surface=<lib.document.Document instance>, *rect=(0, 0, 32640, 23552), **kwargs={'feedback_cb': <function gtk_main_tick>})
        x, y, w, h, = rect
        s = Surface(x, y, w, h, alpha)
        tn = 0
  File "C:\Program Files\MyPaint\library.zip\lib\pixbufsurface.py", line 44, __init__(self=<lib.pixbufsurface.Surface instance>, x=0, y=0, w=32640, h=23552, alpha=False, data=None)
            self.epixbuf = gdk.Pixbuf(gdk.COLORSPACE_RGB, alpha, 8, self.ew, self.eh)
            dx = x-self.ex
RuntimeError: could not create GdkPixbuf object
```

**Comment by achadwick** [comment]
For 1.2, I only want to catch that RuntimeError and advise the user that saving as PNG would be a better idea.

But this bug should be kept open and the milestone bumped after that, given that we can do smarter saving (and may have to if we're saving colourspace info).

**Comment by achadwick** [comment]
Any new error dialog is going to require new strings. Marking for 1.2.0-alpha so we get it done before the string freeze.

**Comment by achadwick** [comment]
Also, an exception handler is pretty trivial: marking as bitesize...
