### ISSUE TITLE
Right click menu on brush icon: exception after deleting 'favorites' group

### ISSUE THREAD

**Issue by Flygohr** [mypaint/mypaint#641]
````python
Mypaint version: 1.2.0+git.f62444e.dirty
System information: Windows-8-6.2.9200
Traceback (most recent call last):
  File "C:\Program Files\MyPaint\share\mypaint\gui\brushselectionwindow.py", line 123, button_press_cb(self=<BrushList object at 0x8765168 (gui+brushselectionwindow+BrushList at 0x87d5c30)>, widget=<BrushList object at 0x8765168 (gui+brushselectionwindow+BrushList at 0x87d5c30)>, event=<void>)
            self.app.device_monitor.device_used(device)
            return pixbuflist.PixbufList.button_press_cb(self, widget, event)
  variables: {'self': ('local', <BrushList object at 0x8765168 (gui+brushselectionwindow+BrushList at 0x87d5c30)>), 'widget': ('local', <BrushList object at 0x8765168 (gui+brushselectionwindow+BrushList at 0x87d5c30)>), 'pixbuflist.PixbufList.button_press_cb': ('global', <unbound method PixbufList.button_press_cb>), 'event': ('local', <void at 0xe23bb40>)}
  File "C:\Program Files\MyPaint\share\mypaint\gui\pixbuflist.py", line 296, button_press_cb(self=<BrushList object at 0x8765168 (gui+brushselectionwindow+BrushList at 0x87d5c30)>, widget=<BrushList object at 0x8765168 (gui+brushselectionwindow+BrushList at 0x87d5c30)>, event=<void>)
                self.set_selected(item)
                self.item_popup(item)
            else:
  variables: {'self.item_popup': ('local', <MethodWithObservers gui.brushselectionwindow.BrushList.item_popup>), 'item': ('local', <ManagedBrush u'Foliage' p=None>)}
  File "C:\Program Files\MyPaint\share\mypaint\lib\observable.py", line 284, __call__(self=<MethodWithObservers gui.brushselectionwindow.BrushList.item_popup>, *args=(<ManagedBrush u'Foliage' p=None>,), **kwargs={})
                try:
                    observer(observed, *args, **kwargs)
                except BoundObserverMethod._ReferenceError:
  variables: {'args': ('local', (<ManagedBrush u'Foliage' p=None>,)), 'observed': ('local', <BrushList object at 0x8765168 (gui+brushselectionwindow+BrushList at 0x87d5c30)>), 'observer': ('local', <BoundObserverMethod gui.brushselectionwindow.BrushList._item_popup_cb>), 'kwargs': ('local', {})}
  File "C:\Program Files\MyPaint\share\mypaint\lib\observable.py", line 467, __call__(self=<BoundObserverMethod gui.brushselectionwindow.BrushList._item_popup_cb>, observed=<BrushList object at 0x8765168 (gui+brushselectionwindow+BrushList at 0x87d5c30)>, *args=(<ManagedBrush u'Foliage' p=None>,), **kwargs={})
                raise self._ReferenceError
            self._observer_func(observer, observed, *args, **kwargs)
            del observer
  variables: {'self._observer_func': ('local', <function _item_popup_cb at 0x0000000005ED5518>), 'observed': ('local', <BrushList object at 0x8765168 (gui+brushselectionwindow+BrushList at 0x87d5c30)>), 'kwargs': ('local', {}), 'observer': ('local', <BrushList object at 0x8765168 (gui+brushselectionwindow+BrushList at 0x87d5c30)>), 'args': ('local', (<ManagedBrush u'Foliage' p=None>,))}
  File "C:\Program Files\MyPaint\share\mypaint\gui\brushselectionwindow.py", line 166, _item_popup_cb(self=<BrushList object at 0x8765168 (gui+brushselectionwindow+BrushList at 0x87d5c30)>, self_=<BrushList object at 0x8765168 (gui+brushselectionwindow+BrushList at 0x87d5c30)>, brush=<ManagedBrush u'Foliage' p=None>)
            time = gtk.get_current_event_time()
            self.menu = BrushPopupMenu(self, brush)
            self.menu.show_all()
  File "C:\Program Files\MyPaint\share\mypaint\gui\brushselectionwindow.py", line 175, __init__(self=<BrushPopupMenu object at 0xe1b6090 (gui+brushselectionwindow+BrushPopupMenu at 0x5ba5790)>, bl=<BrushList object at 0x8765168 (gui+brushselectionwindow+BrushList at 0x87d5c30)>, brush=<ManagedBrush u'Foliage' p=None>)
            super(BrushPopupMenu, self).__init__()
            faves = bl.bm.groups[brushmanager.FAVORITES_BRUSH_GROUP]
            if brush not in faves:
  variables: {'brushmanager.FAVORITES_BRUSH_GROUP': ('global', u'favorites'), 'faves': (None, []), 'bl.bm.groups': ('local', {u'NIEGE': [<ManagedBrush u'NIEGE/pen' p=None>, <ManagedBrush u'NIEGE/airbrush' p=None>, <ManagedBrush u'NIEGE/brush' p=None>, <ManagedBrush u'NIEGE/water' p=None>, <ManagedBrush u'NIEGE/marker' p=None>, <ManagedBrush u'NIEGE/eraser' p=None>, <ManagedBrush u'NIEGE/binary' p=None>, <ManagedBrush u'NIEGE/ink_pen' p=None>, <ManagedBrush u'NIEGE/water_color' p=None>, <ManagedBrush u'NIEGE/water_9' p=None>, <ManagedBrush u'NIEGE/water_10' p=None>, <ManagedBrush u'NIEGE/oil_water' p=None>, <ManagedBrush u'NIEGE/pencil_2' p=None>, <ManagedBrush u'NIEGE/acrylic' p=None>, <ManagedBrush u'NIEGE/paper' p=None>, <ManagedBrush u'NIEGE/crayon' p=None>, <ManagedBrush u'NIEGE/blur' p=None>, <ManagedBrush u'NIEGE/pencil' p=None>], u'Favorite': [], u'experimental': [<ManagedBrush u'experimental/1pixel' p=None>, <ManagedBrush u'experimental/pixel_hardink' p=None>, <ManagedBrush u'experimental/pixelblocking' p=None>, <ManagedBrush u'experimental/basic' p=None>, <ManagedBrush u'experimental/subtle_pencil' p=None>, <ManagedBrush u'experimental/hard_sting' p=None>, <ManagedBrush u'experimental/glow' p=None>, <ManagedBrush u'experimental/soft' p=None>, <ManagedBrush u'experimental/track' p=None>, <ManagedBrush u'experimental/speed_blot' p=None>, <ManagedBrush u'experimental/fur' p=None>, <ManagedBrush u'experimental/soft_irregular' p=None>, <ManagedBrush u'experimental/irregular_ink' p=None>, <ManagedBrush u'experimental/bubble' p=None>, <ManagedBrush u'experimental/small_blot' p=None>, <ManagedBrush u'experimental/particules_3' p=None>, <ManagedBrush u'experimental/spaced-blot' p=None>, <ManagedBrush u'experimental/hard_blot' p=None>, <ManagedBrush u'experimental/sewing' p=None>, <ManagedBrush u'experimental/particules_eraser' p=None>, <ManagedBrush u'experimental/pick_and_drag' p=None>, <ManagedBrush u'experimental/leaves' p=None>, <ManagedBrush u'experimental/DNA_brush' p=None>], u'Anime CG': [<ManagedBrush u'custom_ink' p=None>, <ManagedBrush u'Anti/Water_Line' p=None>, <ManagedBrush u'rigger_1_custom' p=None>, <ManagedBrush u'rigger_2_custom' p=None>, <ManagedBrush u'Oil_Water_Custom' p=None>, <ManagedBrush u'Mix01_Custom' p=None>, <ManagedBrush u'Wet_Direction_Custom' p=None>, <ManagedBrush u'Round_BL_Custom' p=None>, <ManagedBrush u'classic_paint_custom' p=None>, <ManagedBrush u'smear_custom' p=None>, <ManagedBrush u'mixbrush_custom' p=None>, <ManagedBrush u'Wet_Round_Custom' p=None>, <ManagedBrush u'Foliage' p=None>], u'set#1': [<ManagedBrush u'ramon/B-pencil' p=None>, <ManagedBrush u'ramon/2B_pencil' p=None>, <ManagedBrush u'ramon/P._Shade' p=None>, <ManagedBrush u'ramon/Sketch_1' p=None>, <ManagedBrush u'ramon/Soft_Eraser' p=None>, <ManagedBrush u'ramon/Hard_Eraser' p=None>, <ManagedBrush u'ramon/Thin_Pen' p=None>, <ManagedBrush u'ramon/Pen' p=None>, <ManagedBrush u'ramon/PenBrush' p=None>, <ManagedBrush u'ramon/Marker' p=None>, <ManagedBrush u'ramon/Delayed_' p=None>, <ManagedBrush u'ramon/100%_Opaque' p=None>, <ManagedBrush u'ramon/Round' p=None>, <ManagedBrush u'ramon/Round_Bl' p=None>, <ManagedBrush u'ramon/BigAirbrush' p=None>, <ManagedBrush u'ramon/RS_blendOP' p=None>, <ManagedBrush u'ramon/wet_round' p=None>, <ManagedBrush u'ramon/Wet_Direction' p=None>, <ManagedBrush u'ramon/Classic_Paint' p=None>, <ManagedBrush u'ramon/Blur_Fast' p=None>, <ManagedBrush u'ramon/Smear' p=None>, <ManagedBrush u'ramon/Knife' p=None>, <ManagedBrush u'ramon/Grain' p=None>, <ManagedBrush u'ramon/Dirty_Noise' p=None>, <ManagedBrush u'ramon/Pastel_1' p=None>, <ManagedBrush u'ramon/Beamlight' p=None>, <ManagedBrush u'ramon/Glow_Airbrush' p=None>, <ManagedBrush u'ramon/Clouds' p=None>], u'set#2': [<ManagedBrush u'deevad/rough' p=None>, <ManagedBrush u'deevad/4H_pencil' p=None>, <ManagedBrush u'deevad/2B_pencil' p=None>, <ManagedBrush u'deevad/pen' p=None>, <ManagedBrush u'deevad/kneaded_eraser' p=None>, <ManagedBrush u'deevad/kneaded_eraser_large' p=None>, <ManagedBrush u'deevad/large_hard_eraser' p=None>, <ManagedBrush u'deevad/thin_hard_eraser' p=None>, <ManagedBrush u'deevad/basic_digital_brush' p=None>, <ManagedBrush u'deevad/basic_digital_brush_smudging' p=None>, <ManagedBrush u'deevad/basic_digital_knife' p=None>, <ManagedBrush u'deevad/basic_digital_knife_smudging' p=None>, <ManagedBrush u'deevad/detail_brush_large' p=None>, <ManagedBrush u'deevad/detail_brush_large_glazing' p=None>, <ManagedBrush u'deevad/detail_brush_thin' p=None>, <ManagedBrush u'deevad/detail_brush_thin_glazing' p=None>, <ManagedBrush u'deevad/rigger_brush' p=None>, <ManagedBrush u'deevad/rigger_brush_thin' p=None>, <ManagedBrush u'deevad/thin_watercolor' p=None>, <ManagedBrush u'deevad/large_watercolor_fringe' p=None>, <ManagedBrush u'deevad/watercolor_glazing' p=None>, <ManagedBrush u'deevad/watercolor_expressive' p=None>, <ManagedBrush u'deevad/only_water_fringe' p=None>, <ManagedBrush u'deevad/sponge_smudging' p=None>, <ManagedBrush u'deevad/ballpen' p=None>, <ManagedBrush u'deevad/pen-note' p=None>, <ManagedBrush u'deevad/soft-dip-pen' p=None>, <ManagedBrush u'deevad/liner' p=None>, <ManagedBrush u'deevad/brush' p=None>, <ManagedBrush u'deevad/fill' p=None>, <ManagedBrush u'deevad/spray' p=None>, <ManagedBrush u'deevad/spray2' p=None>, <ManagedBrush u'deevad/chalk' p=None>, <ManagedBrush u'deevad/grainy_blending' p=None>, <ManagedBrush u'deevad/blending' p=None>, <ManagedBrush u'deevad/airbrush' p=None>], u'set#3': [<ManagedBrush u'tanda/acrylic-03-only-water' p=None>, <ManagedBrush u'tanda/acrylic-03-paint' p=None>, <ManagedBrush u'tanda/acrylic-03-with-water' p=None>, <ManagedBrush u'tanda/acrylic-04-only-water' p=None>, <ManagedBrush u'tanda/acrylic-04-paint' p=None>, <ManagedBrush u'tanda/acrylic-04-with-water' p=None>, <ManagedBrush u'tanda/acrylic-05-only-water' p=None>, <ManagedBrush u'tanda/acrylic-05-paint' p=None>, <ManagedBrush u'tanda/acrylic-05-with-water' p=None>, <ManagedBrush u'tanda/charcoal-01' p=None>, <ManagedBrush u'tanda/charcoal-03' p=None>, <ManagedBrush u'tanda/charcoal-04' p=None>, <ManagedBrush u'tanda/charcoal-blur1' p=None>, <ManagedBrush u'tanda/marker-01' p=None>, <ManagedBrush u'tanda/marker-05' p=None>, <ManagedBrush u'tanda/oil-01-clean' p=None>, <ManagedBrush u'tanda/oil-01-paint' p=None>, <ManagedBrush u'tanda/oil-03-clean' p=None>, <ManagedBrush u'tanda/oil-03-paint' p=None>, <ManagedBrush u'tanda/oil-06-clean' p=None>, <ManagedBrush u'tanda/oil-06-paint' p=None>, <ManagedBrush u'tanda/oil-mop' p=None>, <ManagedBrush u'tanda/pencil-2b' p=None>, <ManagedBrush u'tanda/pencil-8b' p=None>, <ManagedBrush u'tanda/splatter-02' p=None>, <ManagedBrush u'tanda/splatter-04' p=None>, <ManagedBrush u'tanda/texture-03' p=None>, <ManagedBrush u'tanda/texture-06' p=None>, <ManagedBrush u'tanda/texture-12' p=None>, <ManagedBrush u'tanda/water-01' p=None>, <ManagedBrush u'tanda/water-02' p=None>, <ManagedBrush u'tanda/water-05' p=None>, <ManagedBrush u'tanda/water-06' p=None>, <ManagedBrush u'tanda/watercolor-02-paint' p=None>, <ManagedBrush u'tanda/watercolor-02-water' p=None>], u'deleted': [<ManagedBrush u'b011' p=None>, <ManagedBrush u'b012' p=None>, <ManagedBrush u'b013' p=None>, <ManagedBrush u'b014' p=None>, <ManagedBrush u'b015' p=None>, <ManagedBrush u'b001' p=None>, <ManagedBrush u'b000' p=None>, <ManagedBrush u'b002' p=None>, <ManagedBrush u'b001copy' p=None>, <ManagedBrush u'b003' p=None>, <ManagedBrush u'b004' p=None>, <ManagedBrush u'b005' p=None>, <ManagedBrush u'b006' p=None>, <ManagedBrush u'b007' p=None>, <ManagedBrush u'b008' p=None>, <ManagedBrush u'b009' p=None>, <ManagedBrush u'b010' p=None>, <ManagedBrush u'Oil_Water_Customcopy' p=None>], u'set#4': [<ManagedBrush u'kaerhon_v1/flat_bar_l' p=None>, <ManagedBrush u'kaerhon_v1/inkster_l' p=None>, <ManagedBrush u'kaerhon_v1/extreme_round_l' p=None>, <ManagedBrush u'kaerhon_v1/ink_slow_s' p=None>, <ManagedBrush u'kaerhon_v1/ink-slowline_s' p=None>, <ManagedBrush u'kaerhon_v1/smudge_ink(0.7)_sm' p=None>, <ManagedBrush u'kaerhon_v1/paint_radius_2_sm' p=None>, <ManagedBrush u'kaerhon_v1/Smear_sm' p=None>, <ManagedBrush u'kaerhon_v1/paint_sm' p=None>, <ManagedBrush u'kaerhon_v1/paint_barrr_sm' p=None>, <ManagedBrush u'kaerhon_v1/wet_paint_sm' p=None>, <ManagedBrush u'kaerhon_v1/Dirty_Transparent_sk' p=None>, <ManagedBrush u'kaerhon_v1/classic_sk' p=None>, <ManagedBrush u'kaerhon_v1/airsmudgeultimate_sk' p=None>, <ManagedBrush u'kaerhon_v1/Sketcher2_sk' p=None>, <ManagedBrush u'kaerhon_v1/airsmudge_a' p=None>, <ManagedBrush u'kaerhon_v1/airbruch_press_a' p=None>, <ManagedBrush u'kaerhon_v1/Airbrush_a' p=None>, <ManagedBrush u'kaerhon_v1/classicroundblock_static_c' p=None>, <ManagedBrush u'kaerhon_v1/fill_c' p=None>], u'Dirty': [<ManagedBrush u'Anti/ThinBrush' p=None>, <ManagedBrush u'Anti/Water_Line' p=None>, <ManagedBrush u'Anti/Dirty_Pencil' p=None>, <ManagedBrush u'Anti/Rough_Pencil' p=None>, <ManagedBrush u'Anti/Noisy_Ballpoint' p=None>, <ManagedBrush u'Anti/Silverpoint' p=None>, <ManagedBrush u'Anti/SoftFine' p=None>, <ManagedBrush u'Anti/FineSketch' p=None>, <ManagedBrush u'Anti/HairLine' p=None>, <ManagedBrush u'Anti/Bleeding_Ink' p=None>, <ManagedBrush u'Anti/Inker_01' p=None>, <ManagedBrush u'Anti/Inker_02' p=None>, <ManagedBrush u'Anti/Calligraphy_Sketch' p=None>, <ManagedBrush u'Anti/Solid_Eraser' p=None>, <ManagedBrush u'Anti/Calligraphy_Sketch_2' p=None>, <ManagedBrush u'Anti/Blocky_Eraser' p=None>, <ManagedBrush u'Anti/Smearaser' p=None>, <ManagedBrush u'Anti/PointiLine' p=None>, <ManagedBrush u'Anti/Rough_Coal' p=None>, <ManagedBrush u'Anti/Chalk_Chunks' p=None>, <ManagedBrush u'Anti/Nervous_Crosshatch' p=None>, <ManagedBrush u'Anti/Chosshatch_Layers' p=None>, <ManagedBrush u'Anti/PixlPointl' p=None>, <ManagedBrush u'Anti/Pointilism' p=None>, <ManagedBrush u'Anti/SlowPointilism' p=None>, <ManagedBrush u'Anti/Dirty_Brush' p=None>, <ManagedBrush u'Anti/Dirty_Knife' p=None>, <ManagedBrush u'Anti/Wet_Blops' p=None>, <ManagedBrush u'Anti/Dry_Bristles' p=None>, <ManagedBrush u'Anti/Hairy_Brush' p=None>, <ManagedBrush u'Anti/Blotchy_Airbrush_1' p=None>, <ManagedBrush u'Anti/Blotchy_Airbrush_2' p=None>, <ManagedBrush u'Anti/Blotchy_Airbrush_3' p=None>, <ManagedBrush u'Anti/Spit' p=None>, <ManagedBrush u'Anti/Noisy_Colorize' p=None>, <ManagedBrush u'Anti/Smudgy_Fingers' p=None>, <ManagedBrush u'Anti/Dry_Brush_Blender' p=None>, <ManagedBrush u'Anti/Pigment_Pusher' p=None>, <ManagedBrush u'Anti/Rough_Blender' p=None>, <ManagedBrush u'Anti/Crosshatch_Blender' p=None>, <ManagedBrush u'Anti/Censored' p=None>, <ManagedBrush u'Anti/FX_ZigZag' p=None>, <ManagedBrush u'Anti/FX_Crossline' p=None>, <ManagedBrush u'Anti/FX_Dashes' p=None>, <ManagedBrush u'Anti/FX_4_Liner' p=None>, <ManagedBrush u'Anti/FX_Wet_Line' p=None>, <ManagedBrush u'Anti/Wet_Crosshatch' p=None>, <ManagedBrush u'Anti/Water_dabs' p=None>], u'classic': [<ManagedBrush u'classic/pencil' p=None>, <ManagedBrush u'classic/charcoal' p=None>, <ManagedBrush u'classic/dry_brush' p=None>, <ManagedBrush u'classic/rounded' p=None>, <ManagedBrush u'classic/knife' p=None>, <ManagedBrush u'classic/smudge+paint' p=None>, <ManagedBrush u'classic/ink_eraser' p=None>, <ManagedBrush u'classic/blend+paint' p=None>, <ManagedBrush u'classic/modelling2' p=None>, <ManagedBrush u'classic/modelling' p=None>, <ManagedBrush u'classic/marker_fat' p=None>, <ManagedBrush u'classic/marker_small' p=None>, <ManagedBrush u'classic/kabura' p=None>, <ManagedBrush u'classic/pen' p=None>, <ManagedBrush u'classic/slow_ink' p=None>, <ManagedBrush u'classic/pointy_ink' p=None>, <ManagedBrush u'classic/brush' p=None>, <ManagedBrush u'classic/textured_ink' p=None>, <ManagedBrush u'classic/ink_blot' p=None>, <ManagedBrush u'classic/coarse_bulk_3' p=None>, <ManagedBrush u'classic/coarse_bulk_2' p=None>, <ManagedBrush u'classic/coarse_bulk_1' p=None>, <ManagedBrush u'classic/short_grass' p=None>, <ManagedBrush u'classic/long_grass' p=None>, <ManagedBrush u'classic/bulk' p=None>, <ManagedBrush u'classic/calligraphy' p=None>, <ManagedBrush u'classic/puantilism' p=None>, <ManagedBrush u'classic/puantilism2' p=None>, <ManagedBrush u'classic/impressionism' p=None>, <ManagedBrush u'classic/imp_details' p=None>, <ManagedBrush u'classic/imp_blending' p=None>, <ManagedBrush u'classic/wet_knife' p=None>, <ManagedBrush u'classic/blending_knife' p=None>, <ManagedBrush u'classic/smudge' p=None>, <ManagedBrush u'classic/blur' p=None>]})}
KeyError: u'favorites'
````

**Comment by achadwick** [comment]
Thanks for reporting. I think we should recreate the group in this case.

**Comment by achadwick** [comment]
Looking at the complexity of this pair of related changes (#641 and #654), I'm only going to fix them on master so that the new code can receive plenty of testing.
