### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 203: invalid start byte

### ISSUE THREAD

**Issue by ahloiscreamo** [mypaint/mypaint#722]
I am trying to reinstall mypaint after upgrading to fedora 24.
i have installed mypaint  git previously but since upgrading to f24 it cannot start,

output-

```
[azrulFTW@localhost ~]$ cd '/home/azrulFTW/mypaint' 
[azrulFTW@localhost mypaint]$ scons
Traceback (most recent call last):
  File "/usr/bin/scons", line 97, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3141, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3127, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3154, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 631, in _build_master
    ws = cls()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 624, in __init__
    self.add_entry(entry)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 680, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2122, in find_on_path
    path_item, entry, metadata, precedence=DEVELOP_DIST
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2521, in from_location
    py_version=py_version, platform=platform, **kw
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2838, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2486, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2654, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2013, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2008, in get_metadata
    metadata = f.read()
  File "/usr/lib64/python2.7/codecs.py", line 314, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 203: invalid start byte
[azrulFTW@localhost mypaint]$ 
```

**Comment by achadwick** [comment]
Please try this:

```sh
cd /tmp
mkdir testjunk.$$
cd testjunk.$$
touch SConstruct
scons
```

Expected output:

```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `.' is up to date.
scons: done building targets.
```

I don't think this is MyPaint's fault, since none of its code is mentioned in the backtrace, and it's early on in SCons. But you never know, it may be a result of something we do.

**Comment by ahloiscreamo** [comment]
Thanks for the output, but the command yields the same result.
It's okay i will ask some folk in Askfedora website.

**Comment by achadwick** [comment]
Nothing for us to do here, every SConscript is affected even blank ones. My guess: filesystem encoding or locale on @ahloiscreamo's deployment is not playing well with the new Fedora's SCons.

Another reason for MyPaint to migrate to plain ol' distutils, maybe! :smile:
