### ISSUE TITLE
Fullscreen: destroys/unparents canvas, no longer any active tdw

### ISSUE THREAD

**Issue by achadwick** [mypaint/mypaint#735]
#### Description

With GTK 3.21.5 from Debian testing/unstable pressing F11 to fullscreen MyPaint makes the canvas area disappear. Pressing a key in this state results in an assertion error about the active TDW being null.

Tested in: GNOME 3.21 (... masochist.)

Tested with: MyPaint master branch as of 512ddcecfe24051ebedf9561d9201ecb855eee4a.

#### Steps to reproduce

This is reproducible with either a fresh config or an existing one.

1. Start MyPaint
2. Press F11, mypaint goes full-screen. Canvas area disappears, widgets are drawn with the default theme colour.
3. Press a key such as space. The following assertion pops up from the keyboard handler:

#### Traceback

```python
Mypaint version: 1.3.0-alpha+git.1dfddfc
System information: Linux-4.6.0-1-amd64-x86_64-with-debian-stretch-sid
Using: Python 2.7.12, GTK 3.21.5, GdkPixbuf 2.34.0, Cairo 1.14.6, GLib 2.49.6
Traceback (most recent call last):
  File "/home/andrewc/Development/MyPaintProject/mypaint/gui/keyboard.py", line 215, _key_release_cb(self=<gui.keyboard.KeyboardManager instance>, widget=<drawwindow.DrawWindow object at 0x7fc522633aa0 (MyPaintDrawWindow at 0x27e8290)>, event=<Gdk.EventKey object at 0x7fc51046e158 (void at 0x2c8b5d0)>)
            # Fallthru handler: dispatch doc-specific stuff.
            return self._dispatch_fallthru_key_release_event(widget, event)
  variables: {'widget': ('local', <drawwindow.DrawWindow object at 0x7fc522633aa0 (MyPaintDrawWindow at 0x27e8290)>), 'event': ('local', <Gdk.EventKey object at 0x7fc51046e158 (void at 0x2c8b5d0)>), 'self._dispatch_fallthru_key_release_event': ('local', <bound method KeyboardManager._dispatch_fallthru_key_release_event of <gui.keyboard.KeyboardManager instance at 0x7fc51105e1b8>>)}
  File "/home/andrewc/Development/MyPaintProject/mypaint/gui/keyboard.py", line 235, _dispatch_fallthru_key_release_event(self=<gui.keyboard.KeyboardManager instance>, win=<drawwindow.DrawWindow object at 0x7fc522633aa0 (MyPaintDrawWindow at 0x27e8290)>, event=<Gdk.EventKey object at 0x7fc51046e158 (void at 0x2c8b5d0)>)
            # Fall-through behavior: handle via the active document.
            target_doc, target_tdw = self._get_active_doc()
            if target_doc is None:
  variables: {'self._get_active_doc': ('local', <bound method KeyboardManager._get_active_doc of <gui.keyboard.KeyboardManager instance at 0x7fc51105e1b8>>), 'target_doc': (None, []), 'target_tdw': (None, [])}
  File "/home/andrewc/Development/MyPaintProject/mypaint/gui/keyboard.py", line 220, _get_active_doc(self=<gui.keyboard.KeyboardManager instance>)
            # event dispatch.
            active_tdw = gui.tileddrawwidget.TiledDrawWidget.get_active_tdw()
            for doc in gui.document.Document.get_instances():
  variables: {'active_tdw': (None, []), 'gui.tileddrawwidget.TiledDrawWidget.get_active_tdw': ('global', <bound method GObjectMeta.get_active_tdw of <class 'gui.tileddrawwidget.TiledDrawWidget'>>)}
  File "/home/andrewc/Development/MyPaintProject/mypaint/gui/tileddrawwidget.py", line 73, get_active_tdw(kin=<class 'gui.tileddrawwidget.TiledDrawWidget'>)
            kin.__tdw_refs.extend(invis_refs)
            assert active_tdw is not None
            return active_tdw
  variables: {'active_tdw': ('local', None), 'None': ('builtin', None)}
AssertionError:  
```

**Comment by achadwick** [comment]
Fixes the assertion at least. If the extra pixel or so of border becomes a problem, we can poke it with some CSS.
