### ISSUE TITLE
a error programing has been detecting ... in full-screen mode

### ISSUE THREAD

**Issue by marecaca** [mypaint/mypaint#755]
I get the next error ; when enter in full-screen mode(via F11) the paper disappears and cannot paint; to push anything button show error reporting:

"a error programing has been detecting ... etc(gnome 3)"

#### Basic system details

MyPaint version: 1.2.0+gitexport.f62444e
Operating system: Debian GNU/Linux stretch/sid 64-bit
Desktop environment: GNOME 3.22.2

#### Steps to reproduce

1. Start MyPaint
2. F11 or full-screen mode
3. try to push any button

#### Backtraces or error messages

```
python
Mypaint version: 1.2.0+gitexport.f62444e
System information: Linux-4.2.0-1-amd64-x86_64-with-debian-stretch-sid
Traceback (most recent call last):
  File "/usr/share/mypaint/gui/keyboard.py", line 153, _key_press_cb(self=<gui.keyboard.KeyboardManager instance>, widget=<drawwindow.DrawWindow object at 0x7fa399811320 (MyPaintDrawWindow at 0x556059af2280)>, event=<Gdk.EventKey object at 0x7fa3908192b8 (void at 0x556059f2d8e0)>)
            # Otherwise, dispatch the event to the active doc.
            return self._dispatch_fallthru_key_press_event(widget, event)
  variables: {'self._dispatch_fallthru_key_press_event': ('local', <bound method KeyboardManager._dispatch_fallthru_key_press_event of <gui.keyboard.KeyboardManager instance at 0x7fa3998871b8>>), 'widget': ('local', <drawwindow.DrawWindow object at 0x7fa399811320 (MyPaintDrawWindow at 0x556059af2280)>), 'event': ('local', <Gdk.EventKey object at 0x7fa3908192b8 (void at 0x556059f2d8e0)>)}
  File "/usr/share/mypaint/gui/keyboard.py", line 230, _dispatch_fallthru_key_press_event(self=<gui.keyboard.KeyboardManager instance>, win=<drawwindow.DrawWindow object at 0x7fa399811320 (MyPaintDrawWindow at 0x556059af2280)>, event=<Gdk.EventKey object at 0x7fa3908192b8 (void at 0x556059f2d8e0)>)
            # Fall-through behavior: handle via the active document.
            target_doc, target_tdw = self._get_active_doc()
            if target_doc is None:
  variables: {'self._get_active_doc': ('local', <bound method KeyboardManager._get_active_doc of <gui.keyboard.KeyboardManager instance at 0x7fa3998871b8>>), 'target_doc': (None, []), 'target_tdw': (None, [])}
  File "/usr/share/mypaint/gui/keyboard.py", line 222, _get_active_doc(self=<gui.keyboard.KeyboardManager instance>)
            # event dispatch.
            active_tdw = gui.tileddrawwidget.TiledDrawWidget.get_active_tdw()
            for doc in gui.document.Document.get_instances():
  variables: {'active_tdw': (None, []), 'gui.tileddrawwidget.TiledDrawWidget.get_active_tdw': ('global', <bound method GObjectMeta.get_active_tdw of <class 'gui.tileddrawwidget.TiledDrawWidget'>>)}
  File "/usr/share/mypaint/gui/tileddrawwidget.py", line 75, get_active_tdw(kin=<class 'gui.tileddrawwidget.TiledDrawWidget'>)
            kin.__tdw_refs.extend(invis_refs)
            assert active_tdw is not None
            return active_tdw
  variables: {'active_tdw': ('local', None), 'None': ('builtin', None)}
AssertionError:
```

![mypaint-captura de pantalla de 2016-12-16 19-09-58](https://cloud.githubusercontent.com/assets/16688607/21273439/e366ca1c-c3c3-11e6-8bcf-3cfb81ed879e.png)

**Comment by achadwick** [comment]
Thank you for reporting, but this has already been reported: #735
