### ISSUE TITLE
Error when Saving on Windows 8.1

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#773]
#### Description of the problem

One of our users over on our Community Forums reported that they were getting an error every once in a while when they tried to save on Windows 8.1.

https://community.mypaint.org/t/error-saving-windows-8-1/597/2

#### Basic system details

MyPaint version:  w64 1.2.1+gitexport.bcf5a28d
Operating system: Windows 81.
Desktop environment: Windows Desktop

#### Steps to reproduce

User didn't provide steps to reproduce. Asked them and waiting for an answer.

#### Backtraces or error messages

```
Mypaint version: 1.2.1+gitexport.bcf5a28d
System information: Windows-8.1-6.3.9600-SP0
Using: Python 2.7.13, GTK 3.22.7, GdkPixbuf 2.36.4, Cairo 1.15.4, GLib 2.50.1
Traceback (most recent call last):
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/filehandling.py", line 665, save_cb(self=<gui.filehandling.FileHandler object>, action=<Gtk.Action object at 0x000000000dcbcc80 (GtkAction at 0x000000000df3d100)>)
            else:
                self.save_file(self.filename)
  variables: {'self.save_file': ('local', <bound method FileHandler.save_file of <gui.filehandling.FileHandler object at 0x000000000dcbdfd0>>), 'self.filename': ('local', u'D:/Galleries/) Xiwi/Sleepin/Sleeping color.ora')}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/drawwindow.py", line 84, wrapper(self=<gui.filehandling.FileHandler object>, *args=(u'D:/Galleries/) Xiwi/Sleepin/Sleeping color.ora',), **kwargs={})
            try:
                func(self, *args, **kwargs)
                # gtk main loop may be called in here...
  variables: {'self': ('local', <gui.filehandling.FileHandler object at 0x000000000dcbdfd0>), 'args': ('local', (u'D:/Galleries/) Xiwi/Sleepin/Sleeping color.ora',)), 'func': ('local', <function save_file at 0x000000000db7c500>), 'kwargs': ('local', {})}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/filehandling.py", line 436, save_file(self=<gui.filehandling.FileHandler object>, filename=u'D:/Galleries/) Xiwi/Sleepin/Sleeping color.ora', export=False, **options={})
                statusmsg=True,
                **options
            )
  variables: {'options': ('local', {})}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/filehandling.py", line 517, _save_doc_to_file(self=<gui.filehandling.FileHandler object>, filename=u'D:/Galleries/) Xiwi/Sleepin/Sleeping color.ora', doc=<gui.document.Document object>, export=False, statusmsg=True, **options={'save_srgb_chunks': True})
                    feedback_cb=self.gtk_main_tick,
                    **options
                )
  variables: {'options': ('local', {'save_srgb_chunks': True})}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/lib/document.py", line 1212, save(self=<Document nlayers=2 bbox=Rect(192, 256, 1536, 1088) paintonly=False>, filename=u'D:/Galleries/) Xiwi/Sleepin/Sleeping color.ora', **kwargs={'feedback_cb': <function gtk_main_tick>, 'save_srgb_chunks': True})
            try:
                result = save(filename, **kwargs)
            except GObject.GError as e:
  variables: {'kwargs': ('local', {'feedback_cb': <function gtk_main_tick at 0x000000000db7c320>, 'save_srgb_chunks': True}), 'save': ('local', <bound method Document.save_ora of <Document nlayers=2 bbox=Rect(192, 256, 1536, 1088) paintonly=False>>), 'result': ('local', None), 'filename': ('local', u'D:/Galleries/) Xiwi/Sleepin/Sleeping color.ora')}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/lib/fileutils.py", line 118, _wrapped_save_method(self=<Document nlayers=2 bbox=Rect(192, 256, 1536, 1088) paintonly=False>, filename=u'D:/Galleries/) Xiwi/Sleepin/Sleeping color.ora', *args=(), **kwds={'feedback_cb': <function gtk_main_tick>, 'save_srgb_chunks': True})
                    logger.error("cleanup: failed to remove temp path too")
                raise ex
            if not os.path.exists(temp_path):
  variables: {'ex': ('local', OSError("_MoveFileEx(u'c:/users/xiwang~1/appdata/local/temp/saveercsqhmypaint/.tmpsave.mergedimage.png', u'c:/users/xiwang~1/appdata/local/temp/saveercsqhmypaint/mergedimage.png')",))}
OSError: _MoveFileEx(u'c:/users/xiwang~1/appdata/local/temp/saveercsqhmypaint/.tmpsave.mergedimage.png', u'c:/users/xiwang~1/appdata/local/temp/saveercsqhmypaint/mergedimage.png')
```

**Comment by jplloyd** [comment]
System specs indicated a low-power machine with only 2GB of ram, while this file was fairly high-res with a lot of layers. Underlying cause could have been a lack of memory (Windows itself uses a fair bit) in combination with some file handling bug prior to the consistent use of context managers for those tasks. If this issue reappears for 2.0, we'll investigate it.
