### ISSUE TITLE
unable to run setup.py demo

### ISSUE THREAD

**Issue by bansd** [mypaint/mypaint#844]
#### I tried to install using git but getting following error:

via git:

````Package libmypaint-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libmypaint-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libmypaint-2.0' found
Traceback (most recent call last):
  File "setup.py", line 599, in <module>
    ext_modules=get_ext_modules(),
  File "setup.py", line 508, in get_ext_modules
    extra_compile_args=extra_compile_args,
  File "setup.py", line 449, in pkgconfig
    for conf_arg in subprocess.check_output(cmd).split():
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['pkg-config', '--libs', 'pygobject-3.0', 'glib-2.0', 'libpng', 'lcms2', 'gtk+-3.0', 'libmypaint-2.0']' returned non-zero exit status 1
````
I even tried downloading libmypaint  through homebrew. Not sure how can I fix this issue.
Thanks!

**Comment by briend** [comment]
It sounds like you need to build and install libmypaint from git first,
then build mypaint
https://github.com/mypaint/libmypaint/blob/master/README.md

**Comment by bansd** [comment]
I went through the steps listed for installing libmypaint, and I was not seeing any errors(all tests passed), but when I try to run 
````
$libmypaint
-bash: libmypaint: command not found
````
Now when I try to install I get this error:
````
$ python setup.py --help-commands
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    import tempfile
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
````
I am new to Python as well, so not sure how can I fix this?

**Comment by bansd** [comment]
Ok, so I tried searching solution for above problem and it worked, but now I am getting this error:
````
$ python setup.py --help-commands
Traceback (most recent call last):
  File "setup.py", line 599, in <module>
    ext_modules=get_ext_modules(),
  File "setup.py", line 468, in get_ext_modules
    import numpy
ImportError: No module named numpy
````
Any ideas?
Thanks in advance!

**Comment by briend** [comment]
You need to install python-bumpy and probably other things.
This doc should help:

https://github.com/mypaint/mypaint/blob/master/BUILDING.md

**Comment by achadwick** [comment]
You need to install numpy in order to build MyPaint. If you're using macports, it's called py27-numpy.

Docs here: https://github.com/mypaint/mypaint/blob/master/BUILDING.md#osx-macports (they may not be very good though)

We normally close user support tickets fairly swiftly, because this isn't really a good support forum.

However, since none of the regular devs are OSX people, I'm very interested in keeping those Mac docs up to date. Do you think you might be able to contribute corrections and patches based on your experiences?

We'd love a real OSX guru to step up and get some regular builds and testing together. Without any real community support, the Mac version is really lagging compared to the Linux and Windows platforms.

**Comment by bansd** [comment]
Sure, I would love to help with that. I tried everything listed in the doc you mentioned( https://github.com/mypaint/mypaint/blob/master/BUILDING.md#osx-macports) but nothing worked for now. But will keep on trying and will keep posted. :)

**Comment by briend** [comment]
I have a Sierra macOS machine now that I can play with.  I didn't have much luck with MacPorts and compiling libmypaint.  Failed on configure with gettext missing (but I definitely installed it).  I will try Fink and HomeBrew and see if that works better.

**Comment by briend** [comment]
Hmm, you know, I didn't try installing the deps and using build environment variables from this, maybe this can help:
https://github.com/macports/macports-ports/blob/master/graphics/MyPaint/Portfile

**Comment by blackwarthog** [comment]
You can install libmypaint with Homebrew (http://brewformulas.org/Libmypaint):

brew install libmypaint

**Comment by briend** [comment]
No luck yet.  I'm having the same issue as Brendan here: https://stackoverflow.com/questions/39893768/finding-dgettext-declaration-when-compiling-libmypaint-on-osx
I've tried exactly what he did but still having the same error.

**Comment by briend** [comment]
@blackwarthog  that installs a precompiled 1.3 I think. We're trying to compile the latest 2.x alpha from git.  Thank you though!

**Comment by briend** [comment]
![image](https://user-images.githubusercontent.com/6015639/29203411-73314dea-7e25-11e7-9384-d56be0d5bf56.png)


Ok I got libmypaint compiled and installed AND mypaint.  Woohoo.  Not *exactly* sure how but here are my steps I took:
fresh macOS 10.12.5.  I used homebrew.  I think I can get macports to work now... the critical thing I think is the gettext and linking with --force (truthfully I have no idea what that means), but it made it work.  I did *not* install the full xcode, just let homebrew download the small bits automatically.  I installed libmypaint  from src 1st just to get some of the dependencies but that didn't help much.  Make sure you install Xquartz (https://www.xquartz.org/)

#install homebrew
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install --build-from-source libmypaint
brew uninstall libmypaint
git clone https://github.com/mypaint/libmypaint
cd libmypaint/
brew install autoconf intltool automake libtool pkgconfig glib python gettext json-c
brew link gettext --force
./autogen.sh 
./configure
make
make check
sudo make install
cd ..
git clone https://github.com/mypaint/mypaint
cd mypaint/
brew install gtk+3 numpy scipy pygobject3 lcms2 librsvg swig libffi
brew link libffi --force
mkdir -p $HOME/Library/Python/2.7/lib/python/site-packages
echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> $HOME/Library/Python/2.7/lib/python/site-packages/homebrew.pth
export PKG_CONFIG_PATH=/usr/local/Frameworks/Python.framework/Versions/2.7/lib/pkgconfig/
export CFLAGS="-L/usr/local/include"
export ARCHFLAGS="-arch x86_64"
python setup.py build
python setup.py demo

**Comment by briend** [comment]
I'll reproduce this on a fresh build tomorrow.  This was condensed from like 1000 lines of shell

**Comment by briend** [comment]
I think we need to investigate how to get away from X11 and use native GTK for macOS, like GIMP does.
https://sites.google.com/site/httimchen/2011_imagesvn/build-gimp-on-mac
https://www.gtk.org/download/macos.php

**Comment by briend** [comment]
Oh, we need to edit autogen.sh and replace "python2" with "python" for homebrew and macports.  AFAIK we should make this change on master since it shouldn't break anything.

Here's macport.  I only installed xcode command line tools not the whole xcode:

sudo xcode-select --install
sudo port install autoconf automake intltool libtool pkgconfig glib
sudo port install python gettext json-c
sudo port install glib2
export LDFLAGS="-L/opt/local/lib"
git clone https://github.com/mypaint/libmypaint
cd libmypaint
./autogen.sh
./configure
make
make check
sudo make install

**Comment by briend** [comment]
`Copying MyPaint.egg-info to /var/folders/mp/gx458m3x0c5__tsxrgcczs880000gn/T/demo-br0eVO/lib/mypaint/MyPaint-1.3.0a0-py2.7.egg-info
running install_scripts
creating /var/folders/mp/gx458m3x0c5__tsxrgcczs880000gn/T/demo-br0eVO/bin
installing build/scripts-2.7/mypaint-ora-thumbnailer.py as mypaint-ora-thumbnailer
changing mode of /var/folders/mp/gx458m3x0c5__tsxrgcczs880000gn/T/demo-br0eVO/bin/mypaint-ora-thumbnailer to 755
installing build/scripts-2.7/mypaint.py as mypaint
changing mode of /var/folders/mp/gx458m3x0c5__tsxrgcczs880000gn/T/demo-br0eVO/bin/mypaint to 755
Demo: running ['/usr/bin/python', '/var/folders/mp/gx458m3x0c5__tsxrgcczs880000gn/T/demo-br0eVO/bin/mypaint', '-c', '/var/folders/mp/gx458m3x0c5__tsxrgcczs880000gn/T/demo-br0eVO/_config']...
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'/private/var/folders/mp/gx458m3x0c5__tsxrgcczs880000gn/T/demo-br0eVO'
Traceback (most recent call last):
  File "/var/folders/mp/gx458m3x0c5__tsxrgcczs880000gn/T/demo-br0eVO/bin/mypaint", line 446, in <module>
    = get_paths()
  File "/var/folders/mp/gx458m3x0c5__tsxrgcczs880000gn/T/demo-br0eVO/bin/mypaint", line 215, in get_paths
    from lib import fileutils
  File "/private/var/folders/mp/gx458m3x0c5__tsxrgcczs880000gn/T/demo-br0eVO/lib/mypaint/lib/fileutils.py", line 24, in <module>
    import lib.gichecks
  File "/private/var/folders/mp/gx458m3x0c5__tsxrgcczs880000gn/T/demo-br0eVO/lib/mypaint/lib/gichecks.py", line 18, in <module>
    import gi
ImportError: No module named gi
Demo: cleaning up '/var/folders/mp/gx458m3x0c5__tsxrgcczs880000gn/T/demo-br0eVO'...
Traceback (most recent call last):
  File "setup.py", line 599, in <module>
    ext_modules=get_ext_modules(),
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 200, in run
    subprocess.check_call(demo_cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '/var/folders/mp/gx458m3x0c5__tsxrgcczs880000gn/T/demo-br0eVO/bin/mypaint', '-c', '/var/folders/mp/gx458m3x0c5__tsxrgcczs880000gn/T/demo-br0eVO/_config']' returned non-zero exit status 1
`

**Comment by briend** [comment]
quick update, got it building with homebrew and python3 on Catalina 10.15.  The main this is I had to remove a couple linker flags for deprecated frameworks 'Carbon', 'CoreGraphics', 

setup.py:
+        print(linkflags)
+        del linkflags[2:4]
+        print(linkflags)

you should see this print out when running build:
['-framework', 'Cocoa', 'Carbon', 'CoreGraphics', '-Ofast']
['-framework', 'Cocoa', '-Ofast']

also removed:

'-D_POSIX_C_SOURCE=200809L',


MacOS might be nice if this gets merged and we can use pen input/ pressure on quartz:

https://gitlab.gnome.org/GNOME/gtk/issues/1551
