### ISSUE TITLE
Programming error on start (Windows, standalone).

### ISSUE THREAD

**Issue by Achaean** [mypaint/mypaint#856]
Windows x64 v.10.0.15063.
My Paint v.1.2.1-20170129a standalone. (This doesn't happens when mypaint is installed).

When starting it present a "programming error". You can choose to ignore it.

![screenshot_1](https://user-images.githubusercontent.com/3608053/29995501-3572b658-8ff3-11e7-9196-62181b139c67.png)
[GDB_OUTPUT.txt](https://github.com/mypaint/mypaint/files/1272156/GDB_OUTPUT.txt)

**Comment by achadwick** [comment]
Thanks for the GDB trace. Most likely to be this causing the error (you can fix it by deleting autosave backups so that the recovery dialog doesn't show, but you shouldn't have to do that):

```
Traceback (most recent call last):
  File "C:/Users/├ώ■±ήΎ≥ ╩∙≤ΪⁿΏΎΫΈΎ≥/Desktop/mypaint-w64-1.2.1-20170129a-standalone/mingw64/share/mypaint/gui/application.py", line 411, in _at_application_start
    autosave_recovery = gui.autorecover.Presenter(self)
  File "C:/Users/├ώ■±ήΎ≥ ╩∙≤ΪⁿΏΎΫΈΎ≥/Desktop/mypaint-w64-1.2.1-20170129a-standalone/mingw64/share/mypaint/gui/autorecover.py", line 50, in __init__
    builder.add_from_file(builder_xml)
```

Most likely to be another Unicode vs. Windows encoding screwup. I notice you're using a Greek alphabet user home / user name.

```c:\users\γιώργος κωστόπουλος\desktop\mypaint-w64-1.2.1-20170129a-standalone\mingw64\bin\../etc/gdbinit:5: Error in sourced command file:
```

Can you tell me some details about how your computer has been localized so that I can have a go at reproducing and fixing this bug?

**Comment by Achaean** [comment]
**Indeed!** :-)
Extracting the archive somewhere with no unicode on the path (eg. to C:\TEMP), solves the problem.
My locale is indeed el_GR (Greek).

Bye! :-)

![lang](https://user-images.githubusercontent.com/3608053/30002701-09c386c4-90b9-11e7-99bb-b362f738b835.png)
