### ISSUE TITLE
No break when changing pen tools

### ISSUE THREAD

**Issue by kelvinwop** [mypaint/mypaint#875]
####
I use a surface pro 3 and a two button pen. I have it set so that when I press down the 'eraser' button on the pen (lower button), it automatically switches to the tool in hotkey 1 (eraser) and erases. The problem comes when I let go of the eraser button. It creates a large mess of lines right under my pen.

![img_0903](https://user-images.githubusercontent.com/30770221/32305369-23ab0d2e-bf43-11e7-9ebe-c693a61d9b63.JPG)
![img_0904](https://user-images.githubusercontent.com/30770221/32305371-2468edb2-bf43-11e7-8dab-14930083ad80.JPG)
![img_0905](https://user-images.githubusercontent.com/30770221/32305372-25716b08-bf43-11e7-936c-955eb85d55a8.JPG)

#### Basic system details

MyPaint version: [1.3.0-alpha+git.aefccd44]
Operating system: [windows 10, default os on surface 3 pro]
Desktop environment: [windows I guess?]

#### Steps to reproduce

1. Start MyPaint
2. Use surface pro with pen
3. When pressing down on the pen eraser tool (doesn't erase by default), also select the hotkey with your eraser, thus binding that key to the eraser.
4. Using your pen normally (not with eraser button pressed down), draw some lines.
5. Erase some stuff (or none at all) by using the press the bound button method.
6. Let go of the eraser button
7. See lines where you erased and cry.

#### Backtraces or error messages

```
[n/a]
```

**Comment by achadwick** [comment]
I'm still surprised you've got so far with a surface 3, and that it's pressure-sensitive at all (still remembering the bad days of #484).

Can you expand on the detail a bit please? I'm having difficulty understanding what you've configured MyPaint or your drivers to do (hotkey means what?), and which order you do the (pen nib touches screen) (additional button pressed) (pen nib moved way from screen) (additional button released) events when it happens.

(Is there any order where it does *not* happen?)

(I don't have a Surface 3 myself. It might be hard to reproduce this. I can have a go with a pile of Linux, Win7, and random tablets though.)

**Comment by briend** [comment]
I have a feeling these weird lines that appear are actually delayed dabs that are catching up.  So when you release the button and eraser goes back to normal, the delayed marks are getting the new setting (non-eraser) and thus... it draws lines?

You could confirm this by repeating your test... do your erasing but then stop moving the stylus for a few seconds, THEN release the button to go back to normal mode.  I bet you won't have lines.

**Comment by kelvinwop** [comment]
For the erasing, when I hold down the additional button and press '1' (my eraser pen), then whenever I press that additional button, it uses the eraser pen.
But the problem comes when I'm done erasing. When I move the nib away from the screen, the stroke isn't broken or something and it creates an extra mark on the screen.

**Comment by kelvinwop** [comment]
[Video.zip](https://github.com/mypaint/mypaint/files/1438813/Video.zip)

**Comment by briend** [comment]
Oh I thought the "circle" your drew was part of the problem.  You're just talking about that tiny dot, or very short stroke.  Hmmm..

**Comment by kelvinwop** [comment]
Yeah, the strokes get really crazy when it's lagging or something. Sometimes the strokes cover like half the screen too, but I'm not really sure how that happens.

**Comment by briend** [comment]
Ok wait a second.  Do you have the eraser button configured somehow to send the "1" key when you press it?  If you open a notepad and press and hold the eraser button, does it send a stream of "1"s to the window? like "11111111111111111"?

**Comment by kelvinwop** [comment]
No, I configured it that way by pressing 1 when toggling the erase button. I guess mypaint recognizes the pen as a different pen when the erase button is held down which is why whenever I use the erase pen, I never have to switch to the erase tool using my keyboard.

**Comment by kelvinwop** [comment]
I managed to trigger an error with the first button on the stylus:

```python
Mypaint version: 1.2.1+gitexport.bcf5a28d
System information: Windows-8.1-6.3.9600-SP0
Using: Python 2.7.13, GTK 3.22.7, GdkPixbuf 2.36.4, Cairo 1.15.4, GLib 2.50.1
Traceback (most recent call last):
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/document.py", line 1547, context_cb(self=<gui.document.Document object>, action=<Gtk.Action object at 0x000000000d400690 (GtkAction at 0x000000000e098190)>)
                # restore brush
                bm.select_brush(context)
                if self.app.preferences['misc.context_restores_color']:
  variables: {'bm.select_brush': ('local', <bound method BrushManager.select_brush of <gui.brushmanager.BrushManager object at 0x000000000d41a910>>), 'context': ('local', <ManagedBrush u'context02' p=None>)}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/brushmanager.py", line 687, select_brush(self=<gui.brushmanager.BrushManager object>, brush=<ManagedBrush u'context02' p=deevad/pen>)
            brushinfo = brush.brushinfo
            if not self.is_in_brushlist(brush):
  variables: {'brush.brushinfo': ('local', <lib.brush.BrushInfo object at 0x000000000e590990>), 'brushinfo': (None, [])}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/brushmanager.py", line 969, get_brushinfo(self=<ManagedBrush u'context02' p=deevad/pen>)
        def get_brushinfo(self):
            self._ensure_settings_loaded()
            return self._brushinfo
  variables: {'self._ensure_settings_loaded': ('local', <bound method ManagedBrush._ensure_settings_loaded of <ManagedBrush u'context02' p=deevad/pen>>)}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/brushmanager.py", line 1211, _ensure_settings_loaded(self=<ManagedBrush u'context02' p=deevad/pen>)
                logger.debug("Loading %r...", self)
                self.load()
                assert self._settings_loaded
  variables: {'self.load': ('local', <bound method ManagedBrush.load of <ManagedBrush u'context02' p=deevad/pen>>)}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/brushmanager.py", line 1153, load(self=<ManagedBrush u'context02' p=deevad/pen>)
            self._load_preview()
            self._load_settings()
  variables: {'self._load_settings': ('local', <bound method ManagedBrush._load_settings of <ManagedBrush u'context02' p=deevad/pen>>)}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/brushmanager.py", line 1175, _load_settings(self=<ManagedBrush u'context02' p=deevad/pen>)
            try:
                self._brushinfo.load_from_string(brushinfo_str)
            except BrushInfo.ParseError, e:
  variables: {'self._brushinfo.load_from_string': ('local', <bound method BrushInfo.load_from_string of <lib.brush.BrushInfo object at 0x000000000e590990>>), 'brushinfo_str': ('local', '{\n    "comment": "MyPaint brush file", \n    "description": "A pen to draw and sketch", \n    "group": "", \n    "notes": "A brush preset part of the Brushkit v0.6 \\n created in october 2012 by David Revoy ( aka Deevad ) \\n source: http://www.davidrevoy.com/article142/ressource-mypaint-brushes \\n license: CC-Zero/Public-Domain", \n    "parent_brush_name": "deevad/pen", \n    "settings": {\n        "anti_aliasing": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_h": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_hsl_s": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_hsv_s": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_l": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_v": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "color_h": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "color_s": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "color_v": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "colorize": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "custom_input": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "custom_input_slowness": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "dabs_per_actual_radius": {\n            "base_value": 5.24, \n            "inputs": {}\n        }, \n        "dabs_per_basic_radius": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "dabs_per_second": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "direction_filter": {\n            "base_value": 2.0, \n            "inputs": {}\n        }, \n        "elliptical_dab_angle": {\n            "base_value": 178.09, \n            "inputs": {}\n        }, \n        "elliptical_dab_ratio": {\n            "base_value": 1.0, \n            "inputs": {}\n        }, \n        "eraser": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "hardness": {\n            "base_value": 1.0, \n            "inputs": {\n                "pressure": [\n                    [\n                        0.0, \n                        0.12\n                    ], \n                    [\n                        1.0, \n                        -0.18\n                    ]\n                ]\n            }\n        }, \n        "lock_alpha": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle_2": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle_2_asc": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle_adj": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle_asc": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_by_random": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_by_speed": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_by_speed_slowness": {\n            "base_value": 1.0, \n            "inputs": {}\n        }, \n        "offset_multiplier": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_x": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_y": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "opaque": {\n            "base_value": 0.29159999999935204, \n            "inputs": {}\n        }, \n        "opaque_linearize": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "opaque_multiply": {\n            "base_value": 0.0, \n            "inputs": {\n                "pressure": [\n                    [\n                        0.0, \n                        0.0\n                    ], \n                    [\n                        0.302469, \n                        0.104167\n                    ], \n                    [\n                        0.546296, \n                        0.333333\n                    ], \n                    [\n                        0.688272, \n                        0.729167\n                    ], \n                    [\n                        0.814815, \n                        0.927083\n                    ], \n                    [\n                        1.0, \n                        1.0\n                    ]\n                ]\n            }\n        }, \n        "pressure_gain_log": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "radius_by_random": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "radius_logarithmic": {\n            "base_value": 1.02, \n            "inputs": {\n                "pressure": [\n                    [\n                        0.0, \n                        -0.5\n                    ], \n                    [\n                        0.326923, \n                        -0.320312\n                    ], \n                    [\n                        0.717949, \n                        0.046875\n                    ], \n                    [\n                        1.0, \n                        0.75\n                    ]\n                ]\n            }\n        }, \n        "restore_color": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "slow_tracking": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "slow_tracking_per_dab": {\n            "base_value": 1.52, \n            "inputs": {}\n        }, \n        "smudge": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "smudge_length": {\n            "base_value": 0.5, \n            "inputs": {}\n        }, \n        "smudge_radius_log": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "snap_to_pixel": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "speed1_gamma": {\n            "base_value": 4.0, \n            "inputs": {}\n        }, \n        "speed1_slowness": {\n            "base_value": 0.04, \n            "inputs": {}\n        }, \n        "speed2_gamma": {\n            "base_value": 4.0, \n            "inputs": {}\n        }, \n        "speed2_slowness": {\n            "base_value": 0.8, \n            "inputs": {}\n        }, \n        "stroke_duration_logarithmic": {\n            "base_value": 4.0, \n            "inputs": {}\n        }, \n        "stroke_holdtime": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "stroke_threshold": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "tracking_noise": {\n            "base_value": 0.0, \n            "inputs": {}\n        }\n    }, \n    "version": 3\n}')}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/lib/brush.py", line 181, load_from_string(self=<lib.brush.BrushInfo object>, settings_str='{\n    "comment": "MyPaint brush file", \n    "des..."inputs": {}\n        }\n    }, \n    "version": 3\n}')
                # new json-based brush format
                self.from_json(settings_str)
            elif settings_str.startswith('#'):
  variables: {'self.from_json': ('local', <bound method BrushInfo.from_json of <lib.brush.BrushInfo object at 0x000000000e590990>>), 'settings_str': ('local', '{\n    "comment": "MyPaint brush file", \n    "description": "A pen to draw and sketch", \n    "group": "", \n    "notes": "A brush preset part of the Brushkit v0.6 \\n created in october 2012 by David Revoy ( aka Deevad ) \\n source: http://www.davidrevoy.com/article142/ressource-mypaint-brushes \\n license: CC-Zero/Public-Domain", \n    "parent_brush_name": "deevad/pen", \n    "settings": {\n        "anti_aliasing": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_h": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_hsl_s": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_hsv_s": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_l": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "change_color_v": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "color_h": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "color_s": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "color_v": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "colorize": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "custom_input": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "custom_input_slowness": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "dabs_per_actual_radius": {\n            "base_value": 5.24, \n            "inputs": {}\n        }, \n        "dabs_per_basic_radius": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "dabs_per_second": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "direction_filter": {\n            "base_value": 2.0, \n            "inputs": {}\n        }, \n        "elliptical_dab_angle": {\n            "base_value": 178.09, \n            "inputs": {}\n        }, \n        "elliptical_dab_ratio": {\n            "base_value": 1.0, \n            "inputs": {}\n        }, \n        "eraser": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "hardness": {\n            "base_value": 1.0, \n            "inputs": {\n                "pressure": [\n                    [\n                        0.0, \n                        0.12\n                    ], \n                    [\n                        1.0, \n                        -0.18\n                    ]\n                ]\n            }\n        }, \n        "lock_alpha": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle_2": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle_2_asc": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle_adj": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_angle_asc": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_by_random": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_by_speed": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_by_speed_slowness": {\n            "base_value": 1.0, \n            "inputs": {}\n        }, \n        "offset_multiplier": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_x": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "offset_y": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "opaque": {\n            "base_value": 0.29159999999935204, \n            "inputs": {}\n        }, \n        "opaque_linearize": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "opaque_multiply": {\n            "base_value": 0.0, \n            "inputs": {\n                "pressure": [\n                    [\n                        0.0, \n                        0.0\n                    ], \n                    [\n                        0.302469, \n                        0.104167\n                    ], \n                    [\n                        0.546296, \n                        0.333333\n                    ], \n                    [\n                        0.688272, \n                        0.729167\n                    ], \n                    [\n                        0.814815, \n                        0.927083\n                    ], \n                    [\n                        1.0, \n                        1.0\n                    ]\n                ]\n            }\n        }, \n        "pressure_gain_log": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "radius_by_random": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "radius_logarithmic": {\n            "base_value": 1.02, \n            "inputs": {\n                "pressure": [\n                    [\n                        0.0, \n                        -0.5\n                    ], \n                    [\n                        0.326923, \n                        -0.320312\n                    ], \n                    [\n                        0.717949, \n                        0.046875\n                    ], \n                    [\n                        1.0, \n                        0.75\n                    ]\n                ]\n            }\n        }, \n        "restore_color": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "slow_tracking": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "slow_tracking_per_dab": {\n            "base_value": 1.52, \n            "inputs": {}\n        }, \n        "smudge": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "smudge_length": {\n            "base_value": 0.5, \n            "inputs": {}\n        }, \n        "smudge_radius_log": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "snap_to_pixel": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "speed1_gamma": {\n            "base_value": 4.0, \n            "inputs": {}\n        }, \n        "speed1_slowness": {\n            "base_value": 0.04, \n            "inputs": {}\n        }, \n        "speed2_gamma": {\n            "base_value": 4.0, \n            "inputs": {}\n        }, \n        "speed2_slowness": {\n            "base_value": 0.8, \n            "inputs": {}\n        }, \n        "stroke_duration_logarithmic": {\n            "base_value": 4.0, \n            "inputs": {}\n        }, \n        "stroke_holdtime": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "stroke_threshold": {\n            "base_value": 0.0, \n            "inputs": {}\n        }, \n        "tracking_noise": {\n            "base_value": 0.0, \n            "inputs": {}\n        }\n    }, \n    "version": 3\n}')}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/lib/brush.py", line 165, from_json(self=<lib.brush.BrushInfo object>, json_string='{\n    "comment": "MyPaint brush file", \n    "des..."inputs": {}\n        }\n    }, \n    "version": 3\n}')
                if k not in self.settings:
                    print 'ignoring unknown brush setting %r' % k
                    continue
  variables: {'k': ('local', u'offset_angle_2')}
IOError: [Errno 9] Bad file descriptor
```

**Comment by kelvinwop** [comment]
I was trying to figure out how to stop the crazy jagged lines of error #177 and #879 but then this happened

**Comment by kelvinwop** [comment]
current version: 1.2.1+gitexport.bcf5a28d

(Python 2.7.13, GTK 3.22.7, GdkPixbuf 2.36.4, Cairo 1.15.4, GLib 2.50.1), win64 windows 7
