### ISSUE TITLE
Autosave: RuntimeError: writer object's internal state is invalid (no file)

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/mypaint#904]
#### Description of the problem

Error popped up after I opened up MyPaint. Looks to be related to the Autosave feature since the error dosen't seem to pop up when I turn the feature off. I did clear the config folder and the cache folder to make sure it just wasn't a corrupt file. Dosen't crash the program but will pop up everytime I stop for an extended period of time. Fix for now is to turn off Autosave.

#### Basic system details

MyPaint version: 1.3.0-alpha+git.acb10b6b
Operating system: Antergos  (Arch Based)
Desktop environment: Gnome Shell

#### Steps to reproduce

1. Start MyPaint
2. Draw on screen and wait a minute
3. Error pops up

#### Backtraces or error messages

```python
Mypaint version: 1.3.0-alpha+git.acb10b6b
System information: Linux-4.15.6-1-ARCH-x86_64-with-glibc2.2.5
Using: Python 2.7.14, GTK 3.22.28, GdkPixbuf 2.36.10, Cairo 1.15.10, GLib 2.54.0
Traceback (most recent call last):
  File "/usr/lib/mypaint/lib/idletask.py", line 84, _process(self=<lib.idletask.Processor object>)
                func, args, kwargs = self._queue[0]
                func_done = bool(func(*args, **kwargs))
                if not func_done:
  variables: {'bool': ('builtin', <type 'bool'>), 'args': ('local', ()), 'func_done': (None, []), 'func': ('local', <lib.tiledsurface.PNGFileUpdateTask object at 0x7f1b0b30a690>), 'kwargs': ('local', {})}
  File "/usr/lib/mypaint/lib/tiledsurface.py", line 1386, __call__(self=<lib.tiledsurface.PNGFileUpdateTask object>, *args=(), **kwargs={})
            except Exception:
                self._png_writer.close()
                self._png_writer = None
  variables: {'self._png_writer.close': ('local', <bound method ProgressivePNGWriter.close of <lib.mypaintlib.ProgressivePNGWriter; proxy of <Swig Object of type 'ProgressivePNGWriter *' at 0x7f1b0b2f39f0> >>)}
  File "/usr/lib/mypaint/lib/mypaintlib.py", line 830, close(self=<lib.mypaintlib.ProgressivePNGWriter; proxy of <...ype 'ProgressivePNGWriter *' at 0x7f1b0b2f39f0> >)
        def close(self):
            return _mypaintlib.ProgressivePNGWriter_close(self)
        __swig_destroy__ = _mypaintlib.delete_ProgressivePNGWriter
  variables: {'_mypaintlib.ProgressivePNGWriter_close': ('global', <built-in function ProgressivePNGWriter_close>), 'self': ('local', <lib.mypaintlib.ProgressivePNGWriter; proxy of <Swig Object of type 'ProgressivePNGWriter *' at 0x7f1b0b2f39f0> >)}
RuntimeError: writer object's internal state is invalid (no file)
```

**Comment by briend** [comment]
Dup of #893?

**Comment by achadwick** [comment]
Replicated here as of master at 0a1ac9136c1a38c862e989f5722cebee38b237cb.

**Comment by achadwick** [comment]
Bisecting: this was introduced in acb10b6bc162b3d14cb51aeaf99e62fe816fa034. Looks like the revert (which wasn't really a revert) got something wrong. Investigating.

```
$ git bisect bad
acb10b6bc162b3d14cb51aeaf99e62fe816fa034 is the first bad commit
commit acb10b6bc162b3d14cb51aeaf99e62fe816fa034
Author: Andrew Chadwick <a.t.chadwick@gmail.com>
Date:   Wed Feb 28 18:45:03 2018 +0000

    fastpng: revert filename passing to fix builds.
    
    Debian testing/unstable, Python 2: ✔build ✔nosetests ✔test
    Debian testing/unstable, Python 3: ✔build ✔nosetests-subset
    Ubuntu trusty, Python 2: ✔build ✔nosetests ✔test
    Ubuntu trusty, Python 3: ✔build ✔nosetests-subset
    Windows 7 MSYS2, Python 2: ✔build ✔nosetests ✔test
    Windows 7 MSYS2, Python 3: ✔build ✔nosetests-subset

:040000 040000 785b4368f0901fab7b4a273dbe178d72c96f198e 4b0d2038eb5a30b1984d60e0300c6e8f9280a828 M	lib
$ git bisect log
git bisect start
# bad: [0a1ac9136c1a38c862e989f5722cebee38b237cb] More fixups for g_filename_to_utf8().
git bisect bad 0a1ac9136c1a38c862e989f5722cebee38b237cb
# good: [5eebb8dd788019f3265759ea6dfc22b00b2dd210] Rework rendering: extract ops, tighter tile loop.
git bisect good 5eebb8dd788019f3265759ea6dfc22b00b2dd210
# bad: [a57771e005b675b2d74f9e4ed10460aa1d059336] CODEQUAL: lint; fix imports, copyrights, typos…
git bisect bad a57771e005b675b2d74f9e4ed10460aa1d059336
# good: [dfdb69e1afe0f0b9557ae845c4e8d161083c308c] New commands: Refactor Layer Group (tiles/pixels)
git bisect good dfdb69e1afe0f0b9557ae845c4e8d161083c308c
# good: [83ac8f8545a2508fc05c9a10b4982bb2b5066cd0] Py3 prep: several import fixes.
git bisect good 83ac8f8545a2508fc05c9a10b4982bb2b5066cd0
# good: [9e34a54146053d27d604890106ffb75eac85be50] Swig: we have to pass filenames to C++ now, and it sucks.
git bisect good 9e34a54146053d27d604890106ffb75eac85be50
# bad: [acb10b6bc162b3d14cb51aeaf99e62fe816fa034] fastpng: revert filename passing to fix builds.
git bisect bad acb10b6bc162b3d14cb51aeaf99e62fe816fa034
# first bad commit: [acb10b6bc162b3d14cb51aeaf99e62fe816fa034] fastpng: revert filename passing to fix builds.
```

**Comment by achadwick** [comment]
Okay, fix and test case commited. Sorry about that ☺

Just spotted another regression with flood_fill, also fixed.
