### ISSUE TITLE
Error message on startup: A programming error has been detected (KeyError: 'colorize')

### ISSUE THREAD

**Issue by festerman** [mypaint/mypaint#907]
#### Description

As the title sez. Appears anything that has to do with menus etc does this. Drawing works, but can't get rid of the error dialog: clicking on Ignore just "re"-pops the dialog. Leaving it up, in the background, drawing works.

#### Steps to reproduce

Start mypaint ...

#### Traceback

```python
Mypaint version: 1.3.0-alpha+git.32091849
System information: Linux-4.15.6-1-ARCH-x86_64-with-glibc2.2.5
Using: Python 2.7.14, GTK 3.22.28, GdkPixbuf 2.36.10, Cairo 1.15.10, GLib 2.54.0
Traceback (most recent call last):
  File "/usr/lib/mypaint/gui/tileddrawwidget.py", line 227, enter_notify_cb(self=<tileddrawwidget.TiledDrawWidget object at 0x7f89c45783c0 (TiledDrawWidget at 0x55ad87d49130)>, widget=<tileddrawwidget.TiledDrawWidget object at 0x7f89c45783c0 (TiledDrawWidget at 0x55ad87d49130)>, event=<Gdk.EventCrossing object at 0x7f89beab2520 (void at 0x55ad8875ea00)>)
            # Ensure the cursor reflects layer-locking changes etc.
            self.renderer.update_cursor()
  variables: {'self.renderer.update_cursor': ('local', <bound method CanvasRenderer.update_cursor of <tileddrawwidget.CanvasRenderer object at 0x7f89c4578410 (gui+tileddrawwidget+CanvasRenderer at 0x55ad87d7a0f0)>>)}
  File "/usr/lib/mypaint/gui/tileddrawwidget.py", line 601, update_cursor(self=<tileddrawwidget.CanvasRenderer object at 0x7f89...ileddrawwidget+CanvasRenderer at 0x55ad87d7a0f0)>)
            else:
                radius, style = self._get_cursor_info()
                c = cursor.get_brush_cursor(radius, style, self.app.preferences)
  variables: {'self._get_cursor_info': ('local', <bound method CanvasRenderer._get_cursor_info of <tileddrawwidget.CanvasRenderer object at 0x7f89c4578410 (gui+tileddrawwidget+CanvasRenderer at 0x55ad87d7a0f0)>>), 'style': (None, []), 'radius': (None, [])}
  File "/usr/lib/mypaint/gui/tileddrawwidget.py", line 628, _get_cursor_info(self=<tileddrawwidget.CanvasRenderer object at 0x7f89...ileddrawwidget+CanvasRenderer at 0x55ad87d7a0f0)>)
                style = cursor.BRUSH_CURSOR_STYLE_LOCK_ALPHA
            elif b.is_colorize():
                style = cursor.BRUSH_CURSOR_STYLE_COLORIZE
  variables: {'b.is_colorize': ('local', <bound method BrushInfo.is_colorize of <lib.brush.BrushInfo object at 0x7f89c72ba910>>)}
  File "/usr/lib/mypaint/lib/brush.py", line 561, is_colorize(self=<lib.brush.BrushInfo object>)
        def is_colorize(self):
            return self.has_large_base_value("colorize")
  variables: {'self.has_large_base_value': ('local', <bound method BrushInfo.has_large_base_value of <lib.brush.BrushInfo object at 0x7f89c72ba910>>)}
  File "/usr/lib/mypaint/lib/brush.py", line 502, has_large_base_value(self=<lib.brush.BrushInfo object>, cname='colorize', threshold=0.9)
        def has_large_base_value(self, cname, threshold=0.9):
            return self.get_base_value(cname) > threshold
  variables: {'threshold': ('local', 0.9), 'cname': ('local', 'colorize'), 'self.get_base_value': ('local', <bound method BrushInfo.get_base_value of <lib.brush.BrushInfo object at 0x7f89c72ba910>>)}
  File "/usr/lib/mypaint/lib/brush.py", line 441, get_base_value(self=<lib.brush.BrushInfo object>, cname='colorize')
        def get_base_value(self, cname):
            return self.settings[cname][0]
  variables: {'cname': ('local', 'colorize'), 'self.settings': ('local', {'tracking_noise': [0.0, {}], 'speed2_gamma': [4.0, {}], 'speed2_slowness': [0.800000011920929, {}], 'stroke_holdtime': [0.0, {}], 'stroke_duration_logarithmic': [4.0, {}], 'slow_tracking': [0.0, {}], 'change_color_v': [0.0, {}], 'elliptical_dab_angle': [90.0, {}], 'offset_multiplier': [0.0, {}], 'offset_angle_asc': [0.0, {}], 'change_color_l': [0.0, {}], 'offset_by_speed_slowness': [1.0, {}], 'stroke_threshold': [0.0, {}], 'slow_tracking_per_dab': [0.0, {}], 'offset_angle_adj': [0.0, {}], 'dabs_per_basic_radius': [0.0, {}], 'opaque': [1.0, {}], 'offset_angle': [0.0, {}], 'opaque_multiply': [0.0, {'pressure': [(0.0, 0.0), (1.0, 1.0)]}], 'elliptical_dab_ratio': [1.0, {}], 'lock_alpha': [0.0, {}], 'offset_x': [0.0, {}], 'offset_y': [0.0, {}], 'offset_angle_2_asc': [0.0, {}], 'restore_color': [0.0, {}], 'gridmap_scale': [0.0, {}], 'speed1_gamma': [4.0, {}], 'eraser': [0.0, {}], 'color_h': [0.0, {}], 'custom_input_slowness': [0.0, {}], 'smudge_radius_log': [0.0, {}], 'speed1_slowness': [0.03999999910593033, {}], 'smudge': [0.0, {}], 'custom_input': [0.0, {}], 'gridmap_scale_y': [1.0, {}], 'gridmap_scale_x': [1.0, {}], 'radius_by_random': [0.0, {}], 'dabs_per_second': [0.0, {}], 'color_v': [0.0, {}], 'color_s': [0.0, {}], 'hardness': [0.800000011920929, {}], 'opaque_linearize': [0.8999999761581421, {}], 'smudge_length': [0.5, {}], 'radius_logarithmic': [2.0, {}], 'direction_filter': [2.0, {}], 'offset_angle_2': [0.0, {}], 'change_color_hsv_s': [0.0, {}], 'offset_by_speed': [0.0, {}], 'change_color_h': [0.0, {}], 'dabs_per_actual_radius': [2.0, {}], 'offset_by_random': [0.0, {}], 'change_color_hsl_s': [0.0, {}], 'anti_aliasing': [1.0, {}]})}
KeyError: 'colorize'
```

**Comment by odysseywestra** [comment]
I recently switched the dependencies for the AUR packages to depend on the python 3. Could you do a full reinstall of it and it's dependencies and see if you can reproduce the issue? I did so we can test out what needs to be done. If this continues to be a problem, I will switch the dependencies back to python 2 libraries.

**Comment by achadwick** [comment]
@festerman 
I tried to reproduce this on latest Debian, latest git, and Python 2, and I failed. We kinda need better steps to reproduce than a bare "start MyPaint" :sweat_smile: 

Are you able to reproduce it starting from `python setup.py demo`? Demo mode uses a throwaway clean config and a throwaway install down in `/tmp`. Knowing this would be useful, since it might be brush dependent.

If you _can_ reproduce it in demo mode, are you able to `git bisect` for a bit and see where this came from? There has been a lot of code churn recently as the Py3 support goes in.

FYI, brush colourize mode is on <kbd>Shift+E</kbd> now, if you need to find steps-to-reproduce that start from `python setup.py demo`.


Python3 support is new, and it's incomplete. A differential with that would be useful for us too (although when you find other bugs, please report them as different issues, ahem).

**Comment by achadwick** [comment]
@festerman 
Are you able to reproduce this one with a clean config, as described above?

**Comment by achadwick** [comment]
@festerman Please respond. This one needs more info for us to diagnose properly.

We need to know if a new Arch Py3 build fixes it (a ton of bugfixes went in around that point), if you can. If you're building from source, telling us whether it's still broken in "demo mode" is useful too.

**Comment by festerman** [comment]
Sorry for the slow answer, been off doing other stuff (work ... )

Pulled the latest, and no errors (yet). So this can be closed, I guess!

/festerman

**Comment by achadwick** [comment]
@festerman 
Okay, no problem. Feel free to open a new one referencing this issue as `#907` if it comes back, and one of us will take a deeper look.
