### ISSUE TITLE
Build fails using MSYS2 since libmypaint-2.0 is not available.

### ISSUE THREAD

**Issue by JornVernee** [mypaint/mypaint#912]
Following the instructions in `BUILDING.md`:
```
pacman -S mingw-w64-x86_64-libmypaint
```
With MSYS2 this installs libmypaint version 1.3.0-3:
```
$ pacman -Ss libmypaint
mingw32/mingw-w64-i686-libmypaint 1.3.0-3
    Brush engine used by MyPaint (mingw-w64)
mingw64/mingw-w64-x86_64-libmypaint 1.3.0-3 [installed]
    Brush engine used by MyPaint (mingw-w64)
```

And it looks like there is no version 2.0 available. But the build script does seem to require it:
```
PS J:\Projects\mypaint> python setup.py build
Package libmypaint-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libmypaint-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libmypaint-2.0' found
Traceback (most recent call last):
  File "setup.py", line 603, in <module>
    ext_modules=get_ext_modules(),
  File "setup.py", line 512, in get_ext_modules
    extra_compile_args=extra_compile_args,
  File "setup.py", line 451, in pkgconfig
    universal_newlines=True,
  File "J:\msys64\mingw64\lib\python2.7/subprocess.py", line 220, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['pkg-config', '--libs', 'pygobject-3.0', 'glib-2.0', 'libpng', 'lcms2', 'gtk+-3.0', 'libmypaint-2.0']' returned non-zero exit status 1
```

Is this right?

`pkg-config --list-all` does list `libmypaint`, but not `libmypaint-2.0`. Any suggestions for a workaround?

Thanks!

**Comment by odysseywestra** [comment]
You need to build and install libmypaint from source first, then you can build the latest mypaint version from source.

**Comment by odysseywestra** [comment]
Actually all you need to do is install `libmypaint-git` and 'mypaint-git` packages. I don't know why we don't have those in the build instructions... We'll have to update them.

**Comment by JornVernee** [comment]
The build instructions points to the pre-built MSYS2 package, so I wanted to use those (nice and easy).

There is no `libmypaint-git` MSYS2  package as far as I can see.

I also tried to build libmypaint from source, but no luck so far.

**Comment by odysseywestra** [comment]
Oh, okay. I'll have to load my windows lapotop and look at it later on today(at work).

In the meantime, you can grab the PKGBUILD for libmypaint-git here: https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-libmypaint-git/PKGBUILD

Just grab it with wget in MSYS2 and run it with makepkg. Once the package is made, you should be able to install with pacman. Here instructions with using pacman: https://wiki.archlinux.org/index.php/pacman

**Comment by odysseywestra** [comment]
Oh, you can also use the [msys2-build.sh script](https://github.com/mypaint/mypaint/blob/master/windows/msys2-build.sh) too. This script is designed to be called by AppVeyor or Tea-CI. However it's clean enough to run from an interactive shell. It expects to be called with MSYSTEM="MINGW{64,32}", i.e. from an MSYS2 "native" shell.

**Comment by briend** [comment]
Or even just run https://github.com/mypaint/mypaint/blob/master/windows/install-msys2-deps.sh
Which just calls the msys2-build.sh to install the deps.   libmypaint-git definitely exists in MSYS2, maybe you need to update the package cache or there is a typo?

**Comment by JornVernee** [comment]
I'm gonna try to reinstall msys2, I'm missing the mingw shell login script. Gonna see if I can't find `libmypaint-git` when I have things et up again.

**Comment by briend** [comment]
did you try a few updates by running pacman -Syu a few times?

**Comment by JornVernee** [comment]
Yeah, that didn't change anything. Now that I think about it, the installation might just have been borked, as it survived multiple windows re-installations/hardware switches.

**Comment by JornVernee** [comment]
>  libmypaint-git definitely exists in MSYS2

Maybe I'm checking it wrong then. Not sure how I should update the package cache if  `pacman -Syu` doesn't do it (I can't seem to find how to do it through google.) This is what I see:
```
Jorn@Jorn-PC MINGW64 ~/linux-projects/mypaint
$ pacman -Ss libmypaint
mingw32/mingw-w64-i686-libmypaint 1.3.0-3
    Brush engine used by MyPaint (mingw-w64)
mingw64/mingw-w64-x86_64-libmypaint 1.3.0-3
    Brush engine used by MyPaint (mingw-w64)

Jorn@Jorn-PC MINGW64 ~/linux-projects/mypaint
$
```

After re-installing, this is what I see when I run `install-msys2-deps.sh` (for the 2nd time) trough the mingw64 terminal (i.e. it doesn't work still :( ):
```
Jorn@Jorn-PC MINGW64 ~/linux-projects/mypaint
$ windows/install-msys2-deps.sh
+++ About to install build deps for MyPaint

This script does the following on your behalf. Please read through the
list and press Return if you're happy. You will be able to uninstall
everything that gets installed with "pacman" afterwards. Only the files
in your MSYS2 installation will be affected.

This helper script needs your approval to...

1. Download and install Open Source software from the MSYS2 repositories:
   - all the runtime dependencies needed by MyPaint
   - all the necessary developer tools needed to build MyPaint
2. Download, build, and install Open Source software from GitHub:
   - libmypaint (MyPaint's C brush engine)

+++ Press Return to accept these changes, or Ctrl+C to quit now

+++ Updating pacman cache, and installing dependencies
:: Synchronising package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
Removing potential package conflicts...
error: target not found: mingw-w64-x86_64-mypaint-git
error: target not found: mingw-w64-x86_64-mypaint
error: target not found: mingw-w64-x86_64-libmypaint-git
error: target not found: mingw-w64-x86_64-libmypaint
Installing pre-built dependencies for MyPaint
:: There are 17 members in group mingw-w64-x86_64-toolchain:
:: Repository mingw64
   1) mingw-w64-x86_64-binutils  2) mingw-w64-x86_64-crt-git  3) mingw-w64-x86_64-gcc
   4) mingw-w64-x86_64-gcc-ada  5) mingw-w64-x86_64-gcc-fortran  6) mingw-w64-x86_64-gcc-libgfortran
   7) mingw-w64-x86_64-gcc-libs  8) mingw-w64-x86_64-gcc-objc  9) mingw-w64-x86_64-gdb
   10) mingw-w64-x86_64-headers-git  11) mingw-w64-x86_64-libmangle-git
   12) mingw-w64-x86_64-libwinpthread-git  13) mingw-w64-x86_64-make  14) mingw-w64-x86_64-pkg-config
   15) mingw-w64-x86_64-tools-git  16) mingw-w64-x86_64-winpthreads-git
   17) mingw-w64-x86_64-winstorecompat-git

Enter a selection (default=all):
warning: mingw-w64-x86_64-binutils-2.30-2 is up to date -- skipping
warning: mingw-w64-x86_64-crt-git-6.0.0.5125.b491fac6-1 is up to date -- skipping
warning: mingw-w64-x86_64-gcc-7.3.0-1 is up to date -- skipping
warning: mingw-w64-x86_64-gcc-ada-7.3.0-1 is up to date -- skipping
warning: mingw-w64-x86_64-gcc-fortran-7.3.0-1 is up to date -- skipping
warning: mingw-w64-x86_64-gcc-libgfortran-7.3.0-1 is up to date -- skipping
warning: mingw-w64-x86_64-gcc-libs-7.3.0-1 is up to date -- skipping
warning: mingw-w64-x86_64-gcc-objc-7.3.0-1 is up to date -- skipping
warning: mingw-w64-x86_64-gdb-8.0.1-4 is up to date -- skipping
warning: mingw-w64-x86_64-headers-git-6.0.0.5125.b491fac6-1 is up to date -- skipping
warning: mingw-w64-x86_64-libmangle-git-6.0.0.5079.3b7a42fd-1 is up to date -- skipping
warning: mingw-w64-x86_64-libwinpthread-git-6.0.0.5098.2464b7e6-1 is up to date -- skipping
warning: mingw-w64-x86_64-make-4.2.1-2 is up to date -- skipping
warning: mingw-w64-x86_64-pkg-config-0.29.2-1 is up to date -- skipping
warning: mingw-w64-x86_64-tools-git-6.0.0.5111.3bc5ab74-1 is up to date -- skipping
warning: mingw-w64-x86_64-winpthreads-git-6.0.0.5098.2464b7e6-1 is up to date -- skipping
warning: mingw-w64-x86_64-winstorecompat-git-5.0.0.4760.d3089b5-1 is up to date -- skipping
warning: mingw-w64-x86_64-pkg-config-0.29.2-1 is up to date -- skipping
warning: mingw-w64-x86_64-glib2-2.54.3-1 is up to date -- skipping
warning: mingw-w64-x86_64-gtk3-3.22.28-1 is up to date -- skipping
warning: mingw-w64-x86_64-json-c-0.13_20171207-2 is up to date -- skipping
warning: mingw-w64-x86_64-lcms2-2.8-1 is up to date -- skipping
warning: mingw-w64-x86_64-python2-cairo-1.16.3-1 is up to date -- skipping
warning: mingw-w64-x86_64-pygobject-devel-3.28.1-1 is up to date -- skipping
warning: mingw-w64-x86_64-python2-gobject-3.28.1-1 is up to date -- skipping
warning: mingw-w64-x86_64-python2-numpy-1.13.0-1 is up to date -- skipping
warning: mingw-w64-x86_64-hicolor-icon-theme-0.15-2 is up to date -- skipping
warning: mingw-w64-x86_64-librsvg-2.40.20-1 is up to date -- skipping
warning: mingw-w64-x86_64-gobject-introspection-1.54.1-4 is up to date -- skipping
warning: mingw-w64-x86_64-python2-nose-1.3.7-6 is up to date -- skipping
warning: mingw-w64-x86_64-python2-setuptools-36.6.0-1 is up to date -- skipping
warning: mingw-w64-x86_64-swig-3.0.12-1 is up to date -- skipping
warning: mingw-w64-x86_64-gsettings-desktop-schemas-3.24.1-1 is up to date -- skipping
:: There are 55 members in group base-devel:
:: Repository msys
   1) asciidoc  2) autoconf  3) autoconf2.13  4) autogen  5) automake-wrapper  6) automake1.10
   7) automake1.11  8) automake1.12  9) automake1.13  10) automake1.14  11) automake1.15  12) automake1.6
   13) automake1.7  14) automake1.8  15) automake1.9  16) bison  17) diffstat  18) diffutils
   19) dos2unix  20) file  21) flex  22) gawk  23) gdb  24) gettext  25) gettext-devel  26) gperf
   27) grep  28) groff  29) help2man  30) intltool  31) lemon  32) libtool  33) libunrar
   34) libunrar-devel  35) m4  36) make  37) man-db  38) pacman  39) pactoys-git  40) patch
   41) patchutils  42) perl  43) pkg-config  44) pkgfile  45) quilt  46) rcs  47) scons  48) sed
   49) swig  50) texinfo  51) texinfo-tex  52) ttyrec  53) unrar  54) wget  55) xmlto

Enter a selection (default=all):
warning: asciidoc-8.6.9-4 is up to date -- skipping
warning: autoconf-2.69-3 is up to date -- skipping
warning: autoconf2.13-2.13-2 is up to date -- skipping
warning: autogen-5.18.12-2 is up to date -- skipping
warning: automake-wrapper-10-1 is up to date -- skipping
warning: automake1.10-1.10.3-3 is up to date -- skipping
warning: automake1.11-1.11.6-3 is up to date -- skipping
warning: automake1.12-1.12.6-3 is up to date -- skipping
warning: automake1.13-1.13.4-4 is up to date -- skipping
warning: automake1.14-1.14.1-3 is up to date -- skipping
warning: automake1.15-1.15.1-1 is up to date -- skipping
warning: automake1.6-1.6.3-2 is up to date -- skipping
warning: automake1.7-1.7.9-2 is up to date -- skipping
warning: automake1.8-1.8.5-3 is up to date -- skipping
warning: automake1.9-1.9.6-2 is up to date -- skipping
warning: bison-3.0.4-1 is up to date -- skipping
warning: diffstat-1.61-1 is up to date -- skipping
warning: diffutils-3.5-1 is up to date -- skipping
warning: dos2unix-7.4.0-1 is up to date -- skipping
warning: file-5.32-1 is up to date -- skipping
warning: flex-2.6.4-1 is up to date -- skipping
warning: gawk-4.2.0-1 is up to date -- skipping
warning: gdb-7.11.1-1 is up to date -- skipping
warning: gettext-0.19.8.1-1 is up to date -- skipping
warning: gettext-devel-0.19.8.1-1 is up to date -- skipping
warning: gperf-3.1-1 is up to date -- skipping
warning: grep-3.0-1 is up to date -- skipping
warning: groff-1.22.3-1 is up to date -- skipping
warning: help2man-1.47.5-1 is up to date -- skipping
warning: intltool-0.51.0-2 is up to date -- skipping
warning: lemon-3.8.7.0-1 is up to date -- skipping
warning: libtool-2.4.6-2 is up to date -- skipping
warning: libunrar-5.5.3-1 is up to date -- skipping
warning: libunrar-devel-5.5.3-1 is up to date -- skipping
warning: m4-1.4.18-1 is up to date -- skipping
warning: make-4.2.1-1 is up to date -- skipping
warning: man-db-2.7.6-3 is up to date -- skipping
warning: pacman-5.0.1-5 is up to date -- skipping
warning: pactoys-git-r2.07ca37f-1 is up to date -- skipping
warning: patch-2.7.6-1 is up to date -- skipping
warning: patchutils-0.3.4-1 is up to date -- skipping
warning: perl-5.24.1-4 is up to date -- skipping
warning: pkg-config-0.29.2-1 is up to date -- skipping
warning: pkgfile-17-1 is up to date -- skipping
warning: quilt-0.65-2 is up to date -- skipping
warning: rcs-5.9.4-2 is up to date -- skipping
warning: scons-2.5.1-1 is up to date -- skipping
warning: sed-4.4-2 is up to date -- skipping
warning: swig-3.0.12-1 is up to date -- skipping
warning: texinfo-6.3-1 is up to date -- skipping
warning: texinfo-tex-6.3-1 is up to date -- skipping
warning: ttyrec-1.0.8-1 is up to date -- skipping
warning: unrar-5.5.3-1 is up to date -- skipping
warning: wget-1.19.4-1 is up to date -- skipping
warning: xmlto-0.0.28-1 is up to date -- skipping
warning: git-2.16.2-1 is up to date -- skipping
 there is nothing to do
Installing pre-built dependencies for Styrene + its install
warning: mingw-w64-x86_64-nsis-3.01-1 is up to date -- skipping
warning: mingw-w64-x86_64-gcc-7.3.0-1 is up to date -- skipping
warning: mingw-w64-x86_64-binutils-2.30-2 is up to date -- skipping
warning: mingw-w64-x86_64-python3-3.6.4-2 is up to date -- skipping
warning: mingw-w64-x86_64-python3-pip-9.0.1-3 is up to date -- skipping
warning: zip-3.0-1 is up to date -- skipping
 there is nothing to do
Dependencies installed.
Updating /tmp/src/mingw...
/tmp/src/mingw ~/linux-projects/mypaint
Already up to date.
~/linux-projects/mypaint
Updated /tmp/src/mingw
/tmp/src/mingw/mingw-w64-libmypaint-git ~/linux-projects/mypaint
Building in /tmp/src/mingw/mingw-w64-libmypaint-git for mingw64 ...
==> Making package: mingw-w64-libmypaint-git 1.3.0.85.g40d9077-1 (27 Mar 2018 19:57:57)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating libmypaint git repo...
Fetching origin
==> Validating source files with sha256sums...
    libmypaint ... Skipped
==> Extracting sources...
  -> Creating working copy of libmypaint git repo...
Switched to a new branch 'makepkg'
==> Starting prepare()...

I am testing that you have the tools required to build
libmypaint from git. This test is not foolproof.

Looks like Win32, you will need libtool 2.2 or newer.

checking for libtool >= 2.2 ... yes (version 2.4.6)
checking for autoconf >= 2.62 ... yes (version 2.69)
checking for automake >= 1.13 ... yes (version 1.13.4)
checking for intltool >= 0.40.1 ... yes (version 0.51.0)
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4macros'.
libtoolize: linking file 'm4macros/libtool.m4'
libtoolize: linking file 'm4macros/ltoptions.m4'
libtoolize: linking file 'm4macros/ltsugar.m4'
libtoolize: linking file 'm4macros/ltversion.m4'
libtoolize: linking file 'm4macros/lt~obsolete.m4'
Checked mypaint-brush-settings-gen.h: up to date, not rewritten
Checked brushsettings-gen.h: up to date, not rewritten
configure.ac:60: installing './missing'
Makefile.am: installing './depcomp'
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
configure: loading site script /etc/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for x86_64-w64-mingw32-gcc... J:\msys64\mingw64\bin\clang.exe
checking whether the C compiler works... no
configure: error: in `/tmp/src/mingw/mingw-w64-libmypaint-git/src/build-x86_64-w64-mingw32':
configure: error: C compiler cannot create executables
See `config.log' for more details
==> ERROR: A failure occurred in build().
    Aborting...
+++ Refreshing loaders.cache to solve missing SVG icons
+++ All done!

Dependencies installed for MSYSTEM=MINGW64.
You should now be able to run the following commands to build and
test MyPaint from within this folder.

    python setup.py build
    python setup.py nosetests
    python setup.py test
    python setup.py clean --all

    python setup.py demo

+++ Happy developing!

Jorn@Jorn-PC MINGW64 ~/linux-projects/mypaint
$
```

**Comment by briend** [comment]
Sorry, I apparently don't know how PKGBUILD and pacman work!  I can't search and find libmypaint-git either.  However, that's not the problem-- the build script is able to (magically) find libmypaint-git and download it.  It's just failing to build it.  It looks like your setup is trying to use clang instead of gcc:

> 
> checking for x86_64-w64-mingw32-gcc... J:\msys64\mingw64\bin\clang.exe
> checking whether the C compiler works... no

So, try to switch to gcc.  I'm not sure how but I'd start by just removing clang and installing gcc and seeing if that helps.  On my system my output looks like:

> checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for x86_64-w64-mingw32-gcc... x86_64-w64-mingw32-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
and so on.

**Comment by odysseywestra** [comment]
The errors saying can't find packages is part of the script. It just making
sure it has a clean environment to build and install.

**Comment by briend** [comment]
Yeah, we should make that quiet :-).  I still don't know why you can't search for libmypaint-git but it is clearly in the repository.  Is it because it is some kind of alias?

**Comment by JornVernee** [comment]
> checking for x86_64-w64-mingw32-gcc... J:\msys64\mingw64\bin\clang.exe
D'oh. It looks like it's picking up my `CC` windows environment variable.

Looks like using:
```
export CC=/mingw64/bin/gcc.exe
```
fixes that problem.

---

I tried running `python setup.py build` and ran into pretty much the same problem with `clang++`. So also need `export CXX=/mingw64/bin/g++.exe`

---

Running `python setup.py build` is also working now. Not sure if there's any more steps? That seems to be it for the instructions in `BUILDING.md`, but no .exe is generated, and running `python mypaint.py` fails with:

```
Jorn@Jorn-PC MINGW64 ~/linux-projects/mypaint
$ python mypaint.py
INFO: mypaint: Installation layout: not installed, testing from within the source tree
INFO: lib.i18n: Windows: LANG='en_GB.UTF-8'
INFO: lib.i18n: Windows: LANGUAGE='en_GB:nl_NL'
INFO: lib.i18n: Value of LANGUAGE after cleanup: 'en_GB:C:nl_NL'
WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
INFO: mypaint: Trying platform-specific fallback hacks to find bindtextdomain funcs.
INFO: mypaint: Windows: found working bindtextdomain funcs in 'libintl-8.dll' (ctypes)
Traceback (most recent call last):
  File "mypaint.py", line 461, in <module>
    main.main(datapath, iconspath, old_confpath, version=version)
  File "gui/main.py", line 97, in main
    from gui import application
  File "gui/application.py", line 48, in <module>
    import lib.document
  File "lib/document.py", line 28, in <module>
    from lib.fileutils import safename
  File "lib/fileutils.py", line 26, in <module>
    import lib.helpers
  File "lib/helpers.py", line 26, in <module>
    from . import mypaintlib
  File "lib/mypaintlib.py", line 17, in <module>
    _mypaintlib = swig_import_helper()
  File "lib/mypaintlib.py", line 16, in swig_import_helper
    return importlib.import_module('_mypaintlib')
  File "J:/msys64/mingw64/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _mypaintlib
```

Maybe I'm still doing something wrong? Sorry for dragging this out :/

**Comment by briend** [comment]
Read more about the setup.py:
python setup.py --help-commands
Some might only work on unix (I don't think managed_install works on MSYS2)
Basically you should should try
python setup.py demo
and see if mypaint launches and works.

for windows, to generate the installer and the standalone/portable "application" you'll want to run
msys2-build.sh bundle
and then look in the "out" folder for the bundles, if all goes well

**Comment by JornVernee** [comment]
`python setup.py demo` works fine (as long as I set CC and CXX before running). As well as using `msys2-build.sh bundle`. Thanks for all the help :). I seem to be up and running now.

**Comment by odysseywestra** [comment]
Your welcome. Glad we could be of help. Just as a reminder next time you help, feel free to post it up on our [community forums](https://community.mypaint.org). That would be a better place for user support. We like to keep this place more for bugs with MyPaint itself. ^^'

**Comment by JornVernee** [comment]
Sorry, will do next time. In my defence, I thought I had found a bug in either the build script or the build instructions.
