### ISSUE TITLE
Py3: ValueError invalid tree path '0' (in New Layer Group)

### ISSUE THREAD

**Issue by zakimano** [mypaint/mypaint#913]
#### Description of the problem

When creating a new layer (not sure if related), mypaint gave me this error.

#### Basic system details

```
Kernel: 4.15.13-1-MANJARO x86_64 bits: 64
Desktop: Gnome 3.26.2 
Distro: Manjaro Linux 17.1.7 Hakoila 
System: LENOVO 80NJ ideapad 305-15IBD

CPU: Intel Core i5-5200U
Graphics: Intel HD Graphics 5500 / AMD R5 M330
RAM: 4 GiB
```

#### Steps to reproduce

I do not know the exact cause of this error, what I did is best described as:

1. Start MyPaint (load up previously saved drawing from .ora file)
2. Draw
3. Create a few layers
4. Save
5. Close MyPaint
6. Repeat 1-5 steps in random order.

Do note that this error showed up when, after drawing for a while, I tried to create a new layer.

#### Backtraces or error messages

```python
Mypaint version: 1.3.0-alpha+git.b'e1c2a9f8\n'
System information: Linux-4.15.13-1-MANJARO-x86_64-with-arch-Manjaro-Linux
Using: Python 3.6.4, GTK 3.22.28, GdkPixbuf 2.36.10, Cairo 1.15.10, GLib 2.54.0
Traceback (most recent call last):
  File "/usr/lib/mypaint/gui/document.py", line 1393, new_layer_cb(self=<gui.document.Document object>, action=<Gtk.Action object at 0x7f46da0ed120 (GtkAction at 0x559eeadf5920)>)
            self.model.add_layer(path, layer_class=layer_class, **layer_kwds)
            self.layerblink_state.activate(action)
  variables: {'self.model.add_layer': ('local', <bound method Document.add_layer of <Document nlayers=5 bbox=Rect(-384, 0, 1920, 1216) paintonly=False>>), 'path': ('local', (0,)), 'layer_class': ('local', <class 'lib.layer.group.LayerStack'>), 'layer_kwds': ('local', {})}
  File "/usr/lib/mypaint/lib/document.py", line 1243, add_layer(self=<Document nlayers=5 bbox=Rect(-384, 0, 1920, 1216) paintonly=False>, path=(0,), layer_class=<class 'lib.layer.group.LayerStack'>, **kwds={})
            )
            self.do(cmd)
  variables: {'self.do': ('local', <bound method Document.do of <Document nlayers=5 bbox=Rect(-384, 0, 1920, 1216) paintonly=False>>), 'cmd': ('local', <Add Group>)}
  File "/usr/lib/mypaint/lib/document.py", line 1118, do(self=<Document nlayers=5 bbox=Rect(-384, 0, 1920, 1216) paintonly=False>, cmd=<Add Group>)
            self.sync_pending_changes()
            self.command_stack.do(cmd)
  variables: {'self.command_stack.do': ('local', <bound method CommandStack.do of <CommandStack undo_len=30 redo_len=0>>), 'cmd': ('local', <Add Group>)}
  File "/usr/lib/mypaint/lib/command.py", line 69, do(self=<CommandStack undo_len=30 redo_len=0>, command=<Add Group>)
            self._discard_redo()
            command.redo()
            self.undo_stack.append(command)
  variables: {'command.redo': ('local', <bound method AddLayer.redo of <Add Group>>)}
  File "/usr/lib/mypaint/lib/command.py", line 913, redo(self=<Add Group>)
            self._prev_currentlayer_path = layers.get_current_path()
            layers.deepinsert(self._insert_path, self._layer)
            assert self._layer.name is not None
  variables: {'layers.deepinsert': ('local', <bound method RootLayerStack.deepinsert of <RootLayerStack len=5 'Root'>>), 'self._insert_path': ('local', (0,)), 'self._layer': ('local', <LayerStack len=0>)}
  File "/usr/lib/mypaint/lib/layer/tree.py", line 1702, deepinsert(self=<RootLayerStack len=5 'Root'>, path=(0,), layer=<LayerStack len=0>)
                else:
                    stack.insert(idx, layer)
                    layer.name = self.get_unique_name(layer)
  variables: {'stack.insert': ('local', <bound method LayerStack.insert of <RootLayerStack len=5 'Root'>>), 'idx': ('local', 0), 'layer': ('local', <LayerStack len=0>)}
  File "/usr/lib/mypaint/lib/layer/group.py", line 333, insert(self=<RootLayerStack len=5 'Root'>, index=0, layer=<LayerStack len=0>)
            self._layers.insert(index, layer)
            self._notify_adopt(layer, index)
            self._content_changed(*layer.get_full_redraw_bbox())
  variables: {'self._notify_adopt': ('local', <bound method LayerStack._notify_adopt of <RootLayerStack len=5 'Root'>>), 'layer': ('local', <LayerStack len=0>), 'index': ('local', 0)}
  File "/usr/lib/mypaint/lib/layer/group.py", line 254, _notify_adopt(self=<RootLayerStack len=5 'Root'>, adoptee=<LayerStack len=0>, newindex=0)
            if root is not None:
                root._notify_layer_inserted(self, adoptee, newindex)
            # Recursively adopt all descendents of the adoptee after
  variables: {'root._notify_layer_inserted': ('local', <bound method RootLayerStack._notify_layer_inserted of <RootLayerStack len=5 'Root'>>), 'self': ('local', <RootLayerStack len=5 'Root'>), 'adoptee': ('local', <LayerStack len=0>), 'newindex': ('local', 0)}
  File "/usr/lib/mypaint/lib/layer/tree.py", line 2582, _notify_layer_inserted(self=<RootLayerStack len=5 'Root'>, parent=<RootLayerStack len=5 'Root'>, newchild=<LayerStack len=0>, newindex=0)
            assert len(path) > 0
            self.layer_inserted(path)
  variables: {'self.layer_inserted': ('local', <_MethodWithObservers lib.layer.tree.RootLayerStack.layer_inserted>), 'path': ('local', (0,))}
  File "/usr/lib/mypaint/lib/observable.py", line 289, __call__(self=<_MethodWithObservers lib.layer.tree.RootLayerStack.layer_inserted>, *args=((0,),), **kwargs={})
                    try:
                        observer(observed, *args, **kwargs)
                    except _BoundObserverMethod._ReferenceError:
  variables: {'observer': ('local', <_BoundObserverMethod gui.layers.RootStackTreeModelWrapper._layer_inserted_cb>), 'observed': (None, []), 'args': ('local', ((0,),)), 'kwargs': ('local', {})}
  File "/usr/lib/mypaint/lib/observable.py", line 474, __call__(self=<_BoundObserverMethod gui.layers.RootStackTreeModelWrapper._layer_inserted_cb>, observed=<RootLayerStack len=5 'Root'>, *args=((0,),), **kwargs={})
                raise self._ReferenceError
            self._observer_func(observer, observed, *args, **kwargs)
            del observer
  variables: {'self._observer_func': ('local', <function RootStackTreeModelWrapper._layer_inserted_cb at 0x7f46dd273ae8>), 'observer': ('local', <RootStackTreeModelWrapper n=5>), 'observed': ('local', <RootLayerStack len=5 'Root'>), 'args': ('local', ((0,),)), 'kwargs': ('local', {})}
  File "/usr/lib/mypaint/gui/layers.py", line 105, _layer_inserted_cb(self=<RootStackTreeModelWrapper n=5>, root=<RootLayerStack len=5 'Root'>, path=(0,))
            self.invalidate_iters()
            it = self.get_iter(path)
            self.row_inserted(Gtk.TreePath(path), it)
  variables: {'it': (None, []), 'self.get_iter': ('local', <bound method TreeModel.get_iter of <RootStackTreeModelWrapper n=5>>), 'path': ('local', (0,))}
  File "/usr/lib/python3.6/site-packages/gi/overrides/Gtk.py", line 839, get_iter(self=<RootStackTreeModelWrapper n=5>, path=<Gtk.TreePath object at 0x7f46d9b627c8 (GtkTreePath at 0x7f46a4001450)>)
            if not success:
                raise ValueError("invalid tree path '%s'" % path)
            return aiter
  variables: {'ValueError': ('builtin', <class 'ValueError'>), 'path': ('local', <Gtk.TreePath object at 0x7f46d9b627c8 (GtkTreePath at 0x7f46a4001450)>)}
ValueError: invalid tree path '0'
```

**Comment by achadwick** [comment]
Aha, reproduced. Quite easy, really!  

1. Start MyPaint with `python3 setup.py demo`.
2. Open the Layers panel with the <kbd>L</kbd> key or _Layer → Layers Panel_
3. Create a layer group with <kbd>Ctrl+G</kbd> or _Layer → New Layer Group_

Obs1: Yes, it's Python3-specific. It cannot be reproduced with Python2. This is more than a little strange, given how these interfaces are supposed to work.

**Comment by achadwick** [comment]
Alrighty. That should be fixed as of that commit. Thanks for the report, and especial thanks for including the backtrace! :mag:

**Comment by zakimano** [comment]
Thanks for the quick fix, and sorry that I couldn't help more - I wasn't online at the time.

Yes, I can confirm that I had the layers panel open, though I don't remember creating a new layer group - but it is entirely possible that I did, I was tired when this happened.
The layers tree had a few layers at the root point, and no child layers whatsoever.

Thanks again, and have a good one! ^^
