### ISSUE TITLE
Edit in External App function is glitched?

### ISSUE THREAD

**Issue by AtsusaKaneytza** [mypaint/mypaint#920]
[Note that I did attempt a search on the issue tracker before choosing to report this issue, and didn't find anything]

#### Description of the problem

MyPaint has no option for me to update the list of softwares I can use to make external edits (a feature I distinctly remember existing in previous versions.)
Trying to proceed with external editing option with the "unnamed" software results in an error prompt.
Other art softwares that I have that _should_ be in the list are: Krita, Medibang Paint Pro, and FireAlpaca.

#### Basic system details

MyPaint version: 1.2.1+gitexport.bcf5a28 (happens in both 32 and 64-bit versions.)
Operating system: Windows 10, 64-bit
![image](https://user-images.githubusercontent.com/8382492/38473306-bf240c2e-3b53-11e8-8215-2bb91af5085a.png)
![image](https://user-images.githubusercontent.com/8382492/38473316-0ba5d578-3b54-11e8-893a-1a833cf20d1a.png)

Steps to reproduce: **See screenshots posted.**

#### Backtraces or error messages

Here's the bug details from the error message window.
```python
Mypaint version: 1.2.1+gitexport.bcf5a28d
System information: Windows-10-10.0.16299-SP0
Using: Python 2.7.13, GTK 3.22.7, GdkPixbuf 2.36.4, Cairo 1.15.4, GLib 2.50.1
Traceback (most recent call last):
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/document.py", line 2049, begin_external_layer_edit_cb(self=<gui.document.Document object>, action=<Gtk.Action object at 0x000000000fb4bfa0 (GtkAction at 0x000000000febb190)>)
            """Callback: edit the current layer in an external app"""
            self._begin_external_layer_edit()
  variables: {'self._begin_external_layer_edit': ('local', <bound method Document._begin_external_layer_edit of <gui.document.Document object at 0x000000000fdf7850>>)}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/document.py", line 2053, _begin_external_layer_edit(self=<gui.document.Document object>)
            layer = self.model.layer_stack.current
            self._layer_edit_manager.begin(layer)
  variables: {'layer': ('local', <PaintingLayer u'Layer 1'>), 'self._layer_edit_manager.begin': ('local', <bound method LayerEditManager.begin of <gui.externalapp.LayerEditManager object at 0x000000000fe04c10>>)}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/externalapp.py", line 247, begin(self=<gui.externalapp.LayerEditManager object>, layer=<PaintingLayer u'Layer 1'>)
            else:
                self._begin_file_edit_using_gio(file_path, layer)
            self._begin_file_monitoring_using_gio(file_path, layer)
  variables: {'layer': ('local', <PaintingLayer u'Layer 1'>), 'file_path': ('local', u'C:\\Users\\LexW610\\AppData\\Local\\Microsoft\\Windows\\INetCache/mypaint/doc.cj9rgo/edits/c0aee798-4885-4af8-856b-6cbf961e25ca.png'), 'self._begin_file_edit_using_gio': ('local', <bound method LayerEditManager._begin_file_edit_using_gio of <gui.externalapp.LayerEditManager object at 0x000000000fe04c10>>)}
  File "C:/Program Files/mypaint-w64/mingw64/share/mypaint/gui/externalapp.py", line 296, _begin_file_edit_using_gio(self=<gui.externalapp.LayerEditManager object>, file_path=u'C:\\Users\\LexW610\\AppData\\Local\\Microsoft\...o/edits/c0aee798-4885-4af8-856b-6cbf961e25ca.png', layer=<PaintingLayer u'Layer 1'>)
            )
            launched_app = appinfo.launch([file], launch_ctx)
            if not launched_app:
  variables: {'launch_ctx': ('local', <Gdk.AppLaunchContext object at 0x000000001d61f8c0 (GdkAppLaunchContext at 0x0000000012852d90)>), 'launched_app': (None, []), 'appinfo.launch': ('local', gi.FunctionInfo(launch)), 'file': ('local', <__gi__.GLocalFile object at 0x00000000130d86e0 (GLocalFile at 0x000000001f62ada0)>)}
Error: g-io-error-quark: Application registry did not specify a shell\open\command (0)
```

**Comment by calwas** [comment]
It turns out this bug was indirectly addressed in closed issue #531 

Specifically, when running on Windows, [externalapp.py](https://github.com/mypaint/mypaint/blob/master/gui/externalapp.py#L278) no longer calls `_begin_file_edit_using_gio` (which causes the problem in this issue), but instead calls `_begin_file_edit_using_startfile`.

FYI: The [GLib issue](https://gitlab.gnome.org/GNOME/glib/-/issues/1104) that prompted this change still exists.
