### ISSUE TITLE
Windows 64 AppVeyor builds stopped working after 324

### ISSUE THREAD

**Issue by teleportingtortoise** [mypaint/mypaint#932]
Builds after that refuse to start and throw an error. Here's the log from the debugger.

```
Running python2.exe...
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix u'C:/Program Files/mypaint-git-w64/mingw64'
INFO: lib.i18n: Windows: LANG='en_US'
INFO: lib.i18n: Windows: LANGUAGE='en_US'
INFO: lib.i18n: Value of LANGUAGE after cleanup: 'en_US:C'
WARNING: mypaint: No bindtextdomain builtins found in module 'locale'.
INFO: mypaint: Trying platform-specific fallback hacks to find bindtextdomain funcs.
INFO: mypaint: Windows: found working bindtextdomain funcs in 'libintl-8.dll' (ctypes)
Traceback (most recent call last):
  File "mingw64/bin/mypaint", line 471, in <module>
    main.main(datapath, iconspath, old_confpath, version=version)
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/gui/main.py", line 97, in main
    from gui import application
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/gui/application.py", line 48, in <module>
    import lib.document
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/lib/document.py", line 28, in <module>
    from lib.fileutils import safename
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/lib/fileutils.py", line 26, in <module>
    import lib.helpers
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/lib/helpers.py", line 26, in <module>
    from . import mypaintlib
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/lib/mypaintlib.py", line 17, in <module>
    _mypaintlib = swig_import_helper()
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/mypaint/lib/mypaintlib.py", line 16, in swig_import_helper
    return importlib.import_module('_mypaintlib')
  File "C:/Program Files/mypaint-git-w64/mingw64/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _mypaintlib
python2.exe exited with status 1.
Press return to close this window.
```

Running Windows 10 x64 latest update.

Thank you for your time and sorry if this is a duplicate. I looked around but the only ticket I found with this error was old and closed.

**Comment by briend** [comment]
This was my bad.  The latest Alpha should work if you check right now.  Well, a couple things-- you should be looking through the history and NOT downloading "pull request" builds unless you really want to try some wizbang feature.  On the other hand, I shouldn't be spamming the builds with these builds that don't work.  It's Pull Request 853 that is broken, so just avoid that one.

So, I'm going to refrain from any more commits on 853 until I can figure out what's wrong with that particular branch. Sorry about that!

**Comment by briend** [comment]
Actually, I think #902 is baaaaack

**Comment by briend** [comment]
Yes please make a new bug for the other issue.  Although, if you are using 324 that is another pull request with perspective mode, so make sure you note what version you are using.  Build 275 seems to be the latest version of the official master branch, and it seems to work.

**Comment by briend** [comment]
The newest build 333 and onward *should* be fixed now.  I tested 333 for sure.
