### ISSUE TITLE
Alpine Linux: `mypaint` fails to build `_mypaintlib` due to an `openmp/libgomp`-related bug

### ISSUE THREAD

**Issue by finnoleary** [mypaint/mypaint#945]
#### Description of the problem

`mypaint` fails to build `_mypaintlib` due to an `openmp`-related bug on Alpine Linux. 

#### Basic system details

MyPaint version: git HEAD (e474dd2766bb90dc169d1977dd5f9257e3e03019)
Operating system: Alpine Linux 3.8.1
Desktop environment: Not relevant

#### Steps to reproduce

```
git pull <mypaint repo>
python3 setup.py demo
```

#### Backtraces or error messages

```
[...]
running install_scripts
creating /tmp/demo-cho1mmp8/bin
installing build/scripts-3.6/mypaint.py as mypaint
changing mode of /tmp/demo-cho1mmp8/bin/mypaint to 755
installing build/scripts-3.6/mypaint-ora-thumbnailer.py as mypaint-ora-thumbnailer
changing mode of /tmp/demo-cho1mmp8/bin/mypaint-ora-thumbnailer to 755
Demo: running ['/usr/bin/python3', '/tmp/demo-cho1mmp8/bin/mypaint', '-c', '/tmp/demo-cho1mmp8/_config']...
INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix '/tmp/demo-cho1mmp8'
Traceback (most recent call last):
  File "/tmp/demo-cho1mmp8/lib/mypaint/lib/mypaintlib.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: Error relocating /usr/lib/libgomp.so.1: __cxa_finalize: initial-exec TLS resolves to dynamic definition in /usr/lib/libgomp.so.1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/demo-cho1mmp8/bin/mypaint", line 452, in <module>
    = get_paths()
  File "/tmp/demo-cho1mmp8/bin/mypaint", line 225, in get_paths
    from lib import fileutils
  File "/tmp/demo-cho1mmp8/lib/mypaint/lib/fileutils.py", line 26, in <module>
    import lib.helpers
  File "/tmp/demo-cho1mmp8/lib/mypaint/lib/helpers.py", line 26, in <module>
    from . import mypaintlib
  File "/tmp/demo-cho1mmp8/lib/mypaint/lib/mypaintlib.py", line 17, in <module>
    _mypaintlib = swig_import_helper()
  File "/tmp/demo-cho1mmp8/lib/mypaint/lib/mypaintlib.py", line 16, in swig_import_helper
    return importlib.import_module('_mypaintlib')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_mypaintlib'
Demo: cleaning up '/tmp/demo-cho1mmp8'...
Traceback (most recent call last):
  File "setup.py", line 603, in <module>
    ext_modules=get_ext_modules(),
  File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 200, in run
    subprocess.check_call(demo_cmd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/tmp/demo-cho1mmp8/bin/mypaint', '-c', '/tmp/demo-cho1mmp8/_config']' returned non-zero exit status 1.
$ 
```

### ""Fix""

Because `libgomp` is a dependency of `openmp`, this problem is fixed by commenting out [these lines](https://github.com/mypaint/mypaint/blob/e474dd2766bb90dc169d1977dd5f9257e3e03019/setup.py#L484) in `setup.py`:
```
     if sys.platform != "darwin":
        extra_link_args.append("-fopenmp")
        extra_compile_args.append("-fopenmp")
```

**Comment by jplloyd** [comment]
It seems that a lot of projects have had problems with using openmp on musl. Even if this linked correctly, it would probably have been prone to crash (#927). I'm not blaming musl for this, but am unsure if we can do anything about it. The current "solution" for a lot of cases is to just disable openmp for the relevant projects.

If nobody can find and fix the underlying problem, I propose we add a `--disable-openmp` option to the build_ext subcommand, so that those who cannot use openmp will have that option "out of the box". We already have `--enable-openmp=no` in [libmypaint.](/mypaint/libmypaint/) after all.

**Comment by jplloyd** [comment]
Added the option to disable compiling with openmp here: d8e73645f207c0a2ed710616d7ab1b3aac95ed05

Closing this now, but if there are any musl experts who want to look into if there's something we can do on our end to support running on musl-based openmp, that would be appreciated.
