### ISSUE TITLE
Can't set default background

### ISSUE THREAD

**Issue by teleportingtortoise** [mypaint/mypaint#960]
#### Description of the problem

I noticed that MyPaint changed my default background to a canvas texture after a recent update so I tried to change it, but MyPaint will not let me save a default background now and produces an error. I have tried clearing the settings located in `.config` and the data in `.local` but this seemed to make no difference. The error is the same for both texture and solid color backgrounds.

#### Basic system details

MyPaint version: 2.0.0-alpha+git.9736b174
Operating system: Archlinux
Desktop environment: Awesome 4.0.225.gd6412b96-1

#### Steps to reproduce

1. Start MyPaint
2. Change background layer
3. Try to save it as default

#### Backtraces or error messages

```python
Mypaint version: 2.0.0-alpha+git.9736b174
System information: Linux-4.20.5-arch1-1-ARCH-x86_64-with-arch
Using: Python 3.7.2, GTK 3.24.4, GdkPixbuf 2.38.0, Cairo 1.16.0, GLib 2.58.2
Traceback (most recent call last):
  File "/usr/lib/mypaint/gui/backgroundwindow.py", line 114, _response_cb(self=<backgroundwindow.BackgroundWindow object at 0x7...groundwindow+BackgroundWindow at 0x55b08bd3ab20)>, dialog=<backgroundwindow.BackgroundWindow object at 0x7...groundwindow+BackgroundWindow at 0x55b08bd3ab20)>, response=1, *args=())
            if response == RESPONSE_SAVE_AS_DEFAULT:
                self._save_as_default_cb()
            elif response == Gtk.ResponseType.ACCEPT:
  variables: {'self._save_as_default_cb': ('local', <bound method BackgroundWindow._save_as_default_cb of <backgroundwindow.BackgroundWindow object at 0x7ff3cc2493f0 (gui+backgroundwindow+BackgroundWindow at 0x55b08bd3ab20)>>)}
  File "/usr/lib/mypaint/gui/backgroundwindow.py", line 137, _save_as_default_cb(self=<backgroundwindow.BackgroundWindow object at 0x7...groundwindow+BackgroundWindow at 0x55b08bd3ab20)>)
            )
            lib.pixbuf.save(pixbuf, path, 'png')
            self.hide()
  variables: {'lib.pixbuf.save': ('global', <function save at 0x7ff3e10bed08>), 'pixbuf': ('local', <GdkPixbuf.Pixbuf object at 0x7ff3cc25ed38 (GdkPixbuf at 0x55b08d2598c0)>), 'path': ('local', '/home/[user]/.local/share/mypaint/backgrounds/mrmamurk/mamurk_e_1.png')}
  File "/usr/lib/mypaint/lib/pixbuf.py", line 63, save(pixbuf=<GdkPixbuf.Pixbuf object at 0x7ff3cc25ed38 (GdkPixbuf at 0x55b08d2598c0)>, filename='/home/[user]/.local/share/mypaint/backgrounds/mrmamurk/mamurk_e_1.png', type='png', **kwargs={})
        """
        with open(filename, 'wb') as fp:
            try:
  variables: {'open': ('builtin', <built-in function open>), 'filename': ('local', '/home/[user]/.local/share/mypaint/backgrounds/mrmamurk/mamurk_e_1.png'), 'fp': (None, [])}
FileNotFoundError: [Errno 2] No such file or directory: '/home/[user]/.local/share/mypaint/backgrounds/mrmamurk/mamurk_e_1.png'
```

**Comment by briend** [comment]
Sorry about that, should be fixed.  We'll have new appimages up soon

**Comment by teleportingtortoise** [comment]
Thank you!
