### ISSUE TITLE
'BrushInfo' has no attribute 'ParseError' and a problem in Dieterle v4 brush set

### ISSUE THREAD

**Issue by magv** [mypaint/mypaint#967]
Hi, folks. I've just tried the v2.0.0-alpha.5 appimage on Ubuntu 18.04, and once I've selected one of the excellent brushes from the bundled Dieterle v4 set, every time I hit `B` to bring up the brush menu, I get this error (in a second or so):
```python
Mypaint version: 2.0.0-alpha+git.ce3d35d
System information: Linux-4.15.0-45-generic-x86_64-with-debian-buster-sid
Using: Python 2.7.5, GTK 3.22.30, GdkPixbuf 2.36.12, Cairo 1.15.12, GLib 2.56.1
Traceback (most recent call last):
  File "/tmp/.mount_mypainHtLFex/usr/lib/mypaint/gui/pixbuflist.py", line 137, motion_notify_cb(self=<pixbuflist.PixbufList object at 0x7facf40571e0 (PixbufList at 0x26ba450)>, widget=<pixbuflist.PixbufList object at 0x7facf40571e0 (PixbufList at 0x26ba450)>, event=<Gdk.EventMotion object at 0x7faceedeab50 (void at 0x6125460)>)
                    item = self.itemlist[i]
                    item_name = self.namefunc(item)
                    # Tooltip changing has to happen over two motion-notifys
  variables: {'item_name': (None, []), 'item': ('local', <ManagedBrush u'Dieterle/Fountain_SF#1' p=None>), 'self.namefunc': ('local', <function managedbrush_namefunc at 0x7facf5c198c0>)}
  File "/tmp/.mount_mypainHtLFex/usr/lib/mypaint/gui/brushselectionwindow.py", line 49, managedbrush_namefunc(managedbrush=<ManagedBrush u'Dieterle/Fountain_SF#1' p=None>)
        template = "{name}"
        if managedbrush.description:
            template = "{name}\n{description}"
  File "/tmp/.mount_mypainHtLFex/usr/lib/mypaint/gui/brushmanager.py", line 1197, description(self=<ManagedBrush u'Dieterle/Fountain_SF#1' p=None>)
            """
            return self.brushinfo.get_string_property("description")
  File "/tmp/.mount_mypainHtLFex/usr/lib/mypaint/gui/brushmanager.py", line 1226, get_brushinfo(self=<ManagedBrush u'Dieterle/Fountain_SF#1' p=None>)
        def get_brushinfo(self):
            self._ensure_settings_loaded()
            return self._brushinfo
  variables: {'self._ensure_settings_loaded': ('local', <bound method ManagedBrush._ensure_settings_loaded of <ManagedBrush u'Dieterle/Fountain_SF#1' p=None>>)}
  File "/tmp/.mount_mypainHtLFex/usr/lib/mypaint/gui/brushmanager.py", line 1477, _ensure_settings_loaded(self=<ManagedBrush u'Dieterle/Fountain_SF#1' p=None>)
                logger.debug("Loading %r...", self)
                self.load()
                assert self._settings_loaded
  variables: {'self.load': ('local', <bound method ManagedBrush.load of <ManagedBrush u'Dieterle/Fountain_SF#1' p=None>>)}
  File "/tmp/.mount_mypainHtLFex/usr/lib/mypaint/gui/brushmanager.py", line 1418, load(self=<ManagedBrush u'Dieterle/Fountain_SF#1' p=None>)
            self._load_preview()
            self._load_settings()
  variables: {'self._load_settings': ('local', <bound method ManagedBrush._load_settings of <ManagedBrush u'Dieterle/Fountain_SF#1' p=None>>)}
  File "/tmp/.mount_mypainHtLFex/usr/lib/mypaint/gui/brushmanager.py", line 1442, _load_settings(self=<ManagedBrush u'Dieterle/Fountain_SF#1' p=None>)
                self._brushinfo.load_from_string(brushinfo_str)
            except BrushInfo.ParseError as e:
                logger.warning('Failed to load brush %r: %s', filename, e)
AttributeError: type object 'BrushInfo' has no attribute 'ParseError'
```

I'm guessing the `BrushInfo.ParseError` part should instead be `ParseError`, which should be imported from `lib.brush` just like `BrushInfo` is. When I make this fix, the error changes to this:

```python
Exception while analyzing the exception.
Traceback (most recent call last):
  File ".../usr/lib/mypaint/gui/pixbuflist.py", line 137, in motion_notify_cb
    item_name = self.namefunc(item)
  File ".../usr/lib/mypaint/gui/brushselectionwindow.py", line 49, in managedbrush_namefunc
    if managedbrush.description:
  File ".../usr/lib/mypaint/gui/brushmanager.py", line 1197, in description
    return self.brushinfo.get_string_property("description")
  File ".../usr/lib/mypaint/gui/brushmanager.py", line 1226, in get_brushinfo
    self._ensure_settings_loaded()
  File ".../usr/lib/mypaint/gui/brushmanager.py", line 1477, in _ensure_settings_loaded
    self.load()
  File ".../usr/lib/mypaint/gui/brushmanager.py", line 1418, in load
    self._load_settings()
  File ".../usr/lib/mypaint/gui/brushmanager.py", line 1441, in _load_settings
    self._brushinfo.load_from_string(brushinfo_str)
  File ".../usr/lib/mypaint/lib/brush.py", line 334, in load_from_string
    self.from_json(settings_str)
  File ".../usr/lib/mypaint/lib/brush.py", line 297, in from_json
    brush_def = json.loads(json_string)
  File ".../usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File ".../usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File ".../usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name enclosed in double quotes: line 150 column 13 (char 3927)
```

Now this looks like a problem in the brush set itself (I'll open an issue on https://github.com/briend/Brushes/ separately), but it would have been useful to know in which particular file the problem lies.

**Comment by briend** [comment]
Whoops, I was manually cleaning out some old cruft last night and must have mangled those brushes.  Sorry about that!  Thanks for the patches and catching that latent bug too!
