### ISSUE TITLE
TypeError when importing brush package containing readme under Python 3

### ISSUE THREAD

**Issue by SpotlightKid** [mypaint/mypaint#989]
#### Description of the problem

When importing a brush Zip package via "Import brushes" containing a `readme.txt` file, the following python exception occurs when MyPaint wants to display the readme:

    TypeError: Must be string, not bytes

#### Basic system details

MyPaint version: 2.0.0-alpha+git.55af8eac (AUR package `mypaint-git`)
Operating system: Manjaro Linux
Desktop environment: Xfce4

#### Steps to reproduce

1. Click on Brushes Icon
2. Select "Import Brushes" from popup menu
3. Select brush zip file (e.g. [Concept Design](https://github.com/mypaint/mypaint/wiki/Brush-Packages#concept-design-c_d) brushes containing a `readme.txt` file, and confirm.

#### Suggested Solution

Add the following two lines to `brushmanager.py`after line 601:

                if isinstance(readme, bytes):
                    readme = readme.decode("utf-8", errors='ignore')

#### Backtraces or error messages

```python
Mypaint version: 2.0.0-alpha+git.55af8eac
System information: Linux-4.19.28-1-MANJARO-x86_64-with-arch-Manjaro-Linux
Using: Python 3.7.2, GTK 3.24.5, GdkPixbuf 2.38.1, Cairo 1.16.0, GLib 2.58.2
Traceback (most recent call last):
  File "/usr/lib/mypaint/gui/drawwindow.py", line 702, import_brush_pack_cb(self=<drawwindow.DrawWindow object at 0x7f3d256b8090 (MyPaintDrawWindow at 0x55706b398260)>, *junk=(<Gtk.MenuItem object at 0x7f3d1d5e1438 (GtkMenuItem at 0x55706bf33a30)>,))
                return
            imported = self.app.brushmanager.import_brushpack(filename, self)
            logger.info("Imported brush groups %r", imported)
  variables: {'imported': (None, []), 'self.app.brushmanager.import_brushpack': ('local', <bound method BrushManager.import_brushpack of <gui.brushmanager.BrushManager object at 0x7f3d24726780>>), 'filename': ('local', '/home/chris/Downloads/Concept Design.zip'), 'self': ('local', <drawwindow.DrawWindow object at 0x7f3d256b8090 (MyPaintDrawWindow at 0x55706b398260)>)}
  File "/usr/lib/mypaint/gui/brushmanager.py", line 652, import_brushpack(self=<gui.brushmanager.BrushManager object>, path='/home/chris/Downloads/Concept Design.zip', window=<drawwindow.DrawWindow object at 0x7f3d256b8090 (MyPaintDrawWindow at 0x55706b398260)>)
                    answer = dialogs.confirm_brushpack_import(
                        basename(path), window, readme,
                    )
  variables: {'basename': ('global', <function basename at 0x7f3d35d1cf28>), 'path': ('local', '/home/chris/Downloads/Concept Design.zip'), 'window': ('local', <drawwindow.DrawWindow object at 0x7f3d256b8090 (MyPaintDrawWindow at 0x55706b398260)>), 'readme': ('local', b'\r\n================================================\r\nMyPaint 0.9.0 (or later) BrushPackage release                                                          \r\n*****  "Concept Design (C_D)"  *****                           \r\n                                               \r\nwww.ramonmiranda.com \r\nmirandagraphic@gmail.com                                           \r\n================================================\r\nA briefs words...\r\n-----------------\r\n"Concept Design" idea comes from conceptual design, where Markers and inks are very useful. I thought that it would be fun to have something similar inside mypaint so i made them.in this set we have 16 brushes with specific functions to improve the workflows and productivity.\r\nso please, feel free to change order, mix with other sets or whatever you want.\r\n\r\nInstall notes\r\n-------------\r\nWhen install popup menu appears, select "OK" to install and then select the "Rename all" option if you want to have an independent set, or "Replace all" if you want to remove the older brushes.\r\n\r\nLicense\r\n-------\r\nCopyright 2011 Ramon Miranda\r\n\r\nExcept where otherwise noted, these brushes are licensed under a Creative Commons Attribution 3.0 Unported License. See http://creativecommons.org/licenses/by/3.0/ for details.\r\n\r\nAs an exception to this and to the extent possible under law, Ramon Miranda has waived all copyright and related or neighboring rights to the raw brush settings (those files ending with ".myb"). See http://creativecommons.org/publicdomain/zero/1.0/ for details.                                                 ================================================\r\n\r\n')}
  File "/usr/lib/mypaint/gui/dialogs.py", line 342, confirm_brushpack_import(packname='Concept Design.zip', window=<drawwindow.DrawWindow object at 0x7f3d256b8090 (MyPaintDrawWindow at 0x55706b398260)>, readme=b'\r\n==========================================...========================================\r\n\r\n')
            tv.set_wrap_mode(Gtk.WrapMode.WORD_CHAR)
            tv.get_buffer().set_text(readme)
            tv.set_editable(False)
  variables: {'tv.get_buffer': ('local', gi.FunctionInfo(get_buffer)), 'set_text': (None, []), 'readme': ('local', b'\r\n================================================\r\nMyPaint 0.9.0 (or later) BrushPackage release                                                          \r\n*****  "Concept Design (C_D)"  *****                           \r\n                                               \r\nwww.ramonmiranda.com \r\nmirandagraphic@gmail.com                                           \r\n================================================\r\nA briefs words...\r\n-----------------\r\n"Concept Design" idea comes from conceptual design, where Markers and inks are very useful. I thought that it would be fun to have something similar inside mypaint so i made them.in this set we have 16 brushes with specific functions to improve the workflows and productivity.\r\nso please, feel free to change order, mix with other sets or whatever you want.\r\n\r\nInstall notes\r\n-------------\r\nWhen install popup menu appears, select "OK" to install and then select the "Rename all" option if you want to have an independent set, or "Replace all" if you want to remove the older brushes.\r\n\r\nLicense\r\n-------\r\nCopyright 2011 Ramon Miranda\r\n\r\nExcept where otherwise noted, these brushes are licensed under a Creative Commons Attribution 3.0 Unported License. See http://creativecommons.org/licenses/by/3.0/ for details.\r\n\r\nAs an exception to this and to the extent possible under law, Ramon Miranda has waived all copyright and related or neighboring rights to the raw brush settings (those files ending with ".myb"). See http://creativecommons.org/publicdomain/zero/1.0/ for details.                                                 ================================================\r\n\r\n')}
  File "/usr/lib/python3.7/site-packages/gi/overrides/Gtk.py", line 760, set_text(self=<Gtk.TextBuffer object at 0x7f3d1d4faab0 (GtkTextBuffer at 0x55706dda92e0)>, text=b'\r\n==========================================...========================================\r\n\r\n', length=-1)
        def set_text(self, text, length=-1):
            Gtk.TextBuffer.set_text(self, text, length)
  variables: {'Gtk.TextBuffer.set_text': ('global', gi.FunctionInfo(set_text)), 'self': ('local', <Gtk.TextBuffer object at 0x7f3d1d4faab0 (GtkTextBuffer at 0x55706dda92e0)>), 'text': ('local', b'\r\n================================================\r\nMyPaint 0.9.0 (or later) BrushPackage release                                                          \r\n*****  "Concept Design (C_D)"  *****                           \r\n                                               \r\nwww.ramonmiranda.com \r\nmirandagraphic@gmail.com                                           \r\n================================================\r\nA briefs words...\r\n-----------------\r\n"Concept Design" idea comes from conceptual design, where Markers and inks are very useful. I thought that it would be fun to have something similar inside mypaint so i made them.in this set we have 16 brushes with specific functions to improve the workflows and productivity.\r\nso please, feel free to change order, mix with other sets or whatever you want.\r\n\r\nInstall notes\r\n-------------\r\nWhen install popup menu appears, select "OK" to install and then select the "Rename all" option if you want to have an independent set, or "Replace all" if you want to remove the older brushes.\r\n\r\nLicense\r\n-------\r\nCopyright 2011 Ramon Miranda\r\n\r\nExcept where otherwise noted, these brushes are licensed under a Creative Commons Attribution 3.0 Unported License. See http://creativecommons.org/licenses/by/3.0/ for details.\r\n\r\nAs an exception to this and to the extent possible under law, Ramon Miranda has waived all copyright and related or neighboring rights to the raw brush settings (those files ending with ".myb"). See http://creativecommons.org/publicdomain/zero/1.0/ for details.                                                 ================================================\r\n\r\n'), 'length': ('local', -1)}
TypeError: Must be string, not bytes
```

**Comment by jplloyd** [comment]
Sorry about the delay on this, thanks for reporting and locating the problem!
Fixed in 29ace1a27749acc6c10800ac59eda865072f55d7
